objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting to Start</fullName>
                    <default>true</default>
                    <label>Waiting to Start</label>
                </value>
                <value>
                    <fullName>Ready for Match Step</fullName>
                </value>
                <value>
                    <fullName>Ready for Order Linking</fullName>
                </value>
                <value>
                    <fullName>Processing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Table__c</fullName>
        <label>Source Table</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SSVSyncOrdersServiceTest.cls
@isTest
private class SSVSyncOrdersServiceTest {

    @isTest static void testLinkSingleOrder() {

		Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
		testSSV1.Source_Table__c = 'Salesforce Account';
		insert testSSV1;

		// query created record
		List<Source_System_View__c> records = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id});

		// link record
		SSVSyncOrdersService testSyncService = new SSVSyncOrdersService(new SSVBatchSelectorBuilder());
		
		Test.startTest();
		
		testSyncService.linkOrders(records);

        Test.stopTest();
        
        // query (hopefully) updated record
        List<Source_System_View__c> updatedRecords = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id});
        
        system.assertEquals(SSVSelector.PROCESSING_STATUS_COMPLETE, updatedRecords[0].Processing_Status__c);
    }
}