objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateCaseClass_Test.cls
/**
	Test Class: CreateCaseClass_Test for CreateCaseClass
**/

@isTest
private class CreateCaseClass_Test 
{
	public static testMethod void testCreateCaseClass() 
	{
		
		PrepareData.populateCustomSettings();
		
        // given
        Account testAccount = new Account(
            Name = 'test account'
        );
        database.insert(testAccount);
        
        // given
        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            firstName = 'paul',
            lastname = 'hemmings'
        );
        database.insert(testContact);
        
        //given
		RH_Order__c rhOrder = new RH_Order__c(
            Account_sold_to__c = testAccount.id,
            Contact_sold_to__c = testContact.id,
            Name ='ORDER 123'
        );
		database.insert(rhOrder);
		
		ApexPages.currentPage().getParameters().put('orderId', rhOrder.Id);
		ApexPages.StandardController controller=new ApexPages.StandardController(rhOrder);
		CreateCaseClass c = new CreateCaseClass(controller);
		
		c.initRecordTypes();
		c.CreateCase();
		c.cancelCreateCase();  
	}
}