objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Est_Delivery_Date__c</fullName>
        <label>Est. Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Customer_Delivery_Date__c</fullName>
        <description>New standardized field to utilize pick values.  Deleting previous Expected Delivery Date field, which was open text &amp; subject to interpretation. LALO 022110</description>
        <label>Expected Customer Delivery Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-2 days</fullName>
                </value>
                <value>
                    <fullName>3-7 days</fullName>
                </value>
                <value>
                    <fullName>7-10 days</fullName>
                </value>
                <value>
                    <fullName>1-2 weeks</fullName>
                </value>
                <value>
                    <fullName>2-3 Weeks</fullName>
                </value>
                <value>
                    <fullName>3-4 Weeks</fullName>
                </value>
                <value>
                    <fullName>4-6 Weeks</fullName>
                </value>
                <value>
                    <fullName>45-60 days</fullName>
                </value>
                <value>
                    <fullName>120-150 days</fullName>
                </value>
                <value>
                    <fullName>Est. to Ship TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fulfillment_Method__c</fullName>
        <inlineHelpText>Choose a method for each line item.</inlineHelpText>
        <label>Fulfillment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COM/COL</fullName>
                    <color>#990000</color>
                    <label>COM/COL</label>
                </value>
                <value>
                    <fullName>Contract Inventory</fullName>
                    <color>#CC0000</color>
                    <label>Contract Inventory</label>
                </value>
                <value>
                    <fullName>Contract SPO</fullName>
                    <color>#FF0000</color>
                    <label>Contract SPO</label>
                </value>
                <value>
                    <fullName>Custom</fullName>
                    <color>#993300</color>
                    <label>Custom</label>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                    <color>#FF6666</color>
                    <label>Drop Ship</label>
                </value>
                <value>
                    <fullName>Retail Inventory</fullName>
                    <color>#333333</color>
                    <default>true</default>
                    <label>Retail Inventory</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SKU_del__c</fullName>
        <description>The SKU of the specific item ordered.</description>
        <label>SKU</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncedQuoteId__c</fullName>
        <formula>Opportunity.SyncedQuote.Id</formula>
        <label>SyncedQuoteId</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>BDL_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>person the quote was prepared on behalf of</description>
        <inlineHelpText>person the quote was prepared on behalf of</inlineHelpText>
        <label>BDL Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To_Last_Name__c</fullName>
        <label>Bill To Last Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country Shipping to</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>Offshore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Handling_Fees_Y_N__c</fullName>
        <description>if any of the line items in this quote require Handling Fees, select Yes.</description>
        <inlineHelpText>if any of the line items in this quote require Handling Fees, select Yes.</inlineHelpText>
        <label>Handling Fees? (Y/N)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <formula>Opportunity.PO__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>this is populated from the Opportunity</inlineHelpText>
        <label>PO #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quoted_On__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>date the quote was provided to the client</inlineHelpText>
        <label>Quoted On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Range_for_Handling_Fees__c</fullName>
        <inlineHelpText>Geographical range for furniture delivery</inlineHelpText>
        <label>*Delivery Rate Table</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>HI/AK</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>E - Exempt</fullName>
                </value>
                <value>
                    <fullName>G - GST Only</fullName>
                </value>
                <value>
                    <fullName>N - Non Taxable</fullName>
                </value>
                <value>
                    <fullName>P - PST Only</fullName>
                </value>
                <value>
                    <fullName>R - Resale</fullName>
                    <default>true</default>
                    <label>R - Resale</label>
                </value>
                <value>
                    <fullName>T - Standard Tax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <inlineHelpText>Leave blank for Tax Exempt quotes.</inlineHelpText>
        <label>Tax Rate</label>
        <precision>5</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>All Users but Admin</description>
        <label>Standard</label>
    </recordTypes>
    <recordTypes>
        <fullName>US</fullName>
        <active>false</active>
        <description>US Only Record Type for Quotes Created Prior to 6/26/2014</description>
        <label>US (Old Model)</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Est_Delivery_Date__c</fullName>
        <label>Est. Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Customer_Delivery_Date__c</fullName>
        <label>Expected Customer Delivery Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-2 days</fullName>
                </value>
                <value>
                    <fullName>3-7 days</fullName>
                </value>
                <value>
                    <fullName>1-2 weeks</fullName>
                </value>
                <value>
                    <fullName>2-3 Weeks</fullName>
                </value>
                <value>
                    <fullName>3-4 Weeks</fullName>
                </value>
                <value>
                    <fullName>4-6 Weeks</fullName>
                </value>
                <value>
                    <fullName>60-90 days</fullName>
                </value>
                <value>
                    <fullName>45-60 days</fullName>
                </value>
                <value>
                    <fullName>120-150 days</fullName>
                </value>
                <value>
                    <fullName>Est. to Ship TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fulfillment_Method__c</fullName>
        <label>Fulfillment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COM/COL</fullName>
                </value>
                <value>
                    <fullName>Contract Inventory</fullName>
                </value>
                <value>
                    <fullName>Contract SPO</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
                <value>
                    <fullName>Retail Inventory</fullName>
                    <default>true</default>
                    <label>Retail Inventory</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityLineItemId__c</fullName>
        <formula>OpportunityLineItem.Id</formula>
        <label>OpportunityLineItemId</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestSyncOLI_QLI.cls
@isTest
private class TestSyncOLI_QLI {
/*
    static testMethod void SyncOLIQLI() {
        List<QuoteLineItem> 		lstQLI = new List<QuoteLineItem>();
        List<OpportunityLineItem> 	lstOLI = new List<OpportunityLineItem>();
        List<Quote> 				lstQ = new List<Quote>();
        List<Opportunity> 			lstO = new List<Opportunity>();
        Date						todays = Date.today();
        
        // Account
        Account a = new Account();
        a.Name = 'Test Acc';
        a.Industry = 'Commercial';
        a.Segment__c = 'Architect';
        a.Member_Since__c = (Date.today()).addMonths(-4);
        insert a;
        
        // Contact
        
        Contact c = new Contact();
        c.Email = 'none@none.tcom';
        c.LastName = 'Test Contact';
        c.AccountId = a.id;
        insert c;
        
        // Opportunity
        
        Opportunity o = new Opportunity();
        o.Name = 'Opp Name';
        o.CurrencyIsoCode = 'USD';
        o.CloseDate = Date.today();
        o.AccountId = a.id;
        o.StageName = 'Project Inquiry';
        o.LeadSource = 'Web';
        //o.Ops_Contact__c = UserInfo.getUserId();
        o.PO__c = '222';
        o.Project__c = 'Test Proj';
        o.Price_Bid_Contact__c = c.Id;
       	insert o;
       	
       	Pricebook2 pb = [select Id from Pricebook2 where IsStandard = true];
       	PricebookEntry PBE=[select id,product2Id,Pricebook2Id from PricebookEntry WHERE isActive = true AND CurrencyIsoCode = 'USD' and Pricebook2Id = :pb.Id limit 1 ];
       	//PricebookEntry PBE=[select id,product2Id,Pricebook2Id from PricebookEntry WHERE isActive = true AND CurrencyIsoCode = 'USD' limit 1 ];
       	
       	system.debug('*****TestSyncOLI_QLI SyncOLIQLI PBE.Id = ' + PBE.Id + ' PBE.Product2Id = ' + PBE.Product2Id + ' PBE.Pricebook2Id = ' + PBE.Pricebook2Id);
       	 
       	OpportunityLineItem oli = new OpportunityLineItem();
       	oli.PricebookEntryId = PBE.id;
       	oli.Quantity = 100;
       	oli.Fulfillment_Method__c = 'Core Inventory - AC';
       	oli.Expected_Customer_Delivery_Date__c = '3-7 days';
       	oli.Est_Delivery_Date__c = todays;
       	oli.Notes__c = 'This is a fantastic product.';
       	oli.OpportunityId = o.id;
       	oli.UnitPrice = 11;
       	oli.SKU_del__c = PBE.Product2Id;
       	insert oli;
       	
       	lstOLI = [SELECT Fulfillment_Method__c, Est_Delivery_Date__c,  Expected_Customer_Delivery_Date__c, Notes__c FROM OpportunityLineItem WHERE Id = : oli.Id];
       	system.debug('lstOLI -  '+lstOLI);
       	
       	Quote q = new Quote();
       	q.name = 'TestQ';
       	q.Quoted_On__c = Date.today();
       	q.ExpirationDate = (Date.today()).addMonths(1);
       	q.Country__c = 'US';
       	q.Range_for_Handling_Fees__c = 'Yes';
       	q.Tax_Rate__c = 11;
       	q.Handling_Fees_Y_N__c = 'Yes';
       	q.ContactId = c.id;
       	q.Bill_To_Last_Name__c = 'Bunny';
       	q.BillingName = 'Test Contact';
       	q.ShippingName = 'Test Acc';
       	q.BDL_Name__c = UserInfo.getUserId();
       	q.OpportunityId = o.Id;
       	q.Pricebook2Id = oli.PricebookEntry.Pricebook2Id;
       	q.Tax_Code__c = 'T - Standard Tax';
       	q.RecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
       	
       	insert q;
       	
       	QuoteLineItem q1 = new QuoteLineItem();
       	q1.QuoteId = q.Id;
       	q1.PricebookEntryId = oli.PricebookEntryId;
       
       	q1.UnitPrice = oli.UnitPrice;
       	q1.Quantity = oli.Quantity;
       	q1.Fulfillment_Method__c = oli.Fulfillment_Method__c;
		q1.Delivery_Date__c = oli.Delivery_Date__c;
		q1.Notes__c = oli.Notes__c;
		q1.Quantity = oli.Quantity;
		q1.UnitPrice = oli.UnitPrice;
       	
       	insert q1;
		
       	List<QuoteLineItem> qliList = new List<QuoteLineItem>();
       	qliList = [select Id, Quantity, UnitPrice, OpportunityLineItemId__c, Fulfillment_Method__c, Delivery_Date__c, Expected_Customer_Delivery_Date__c, Est_Delivery_Date__c, Notes__c from QuoteLineItem where Id = : q1.Id];
       	
       	system.debug('*****TestSyncOLI_QLI qliList 1 = ' + qliList);
       	
       	System.assertEquals(oli.Fulfillment_Method__c, qliList[0].Fulfillment_Method__c);
		System.assertEquals(oli.Delivery_Date__c, qliList[0].Delivery_Date__c);
		System.assertEquals(oli.Notes__c, qliList[0].Notes__c);
       	
		oli.Fulfillment_Method__c = 'Contract Inventory';
		oli.Delivery_Date__c = '2 weeks';
		oli.Notes__c = 'Different notes';
		oli.Quantity = oli.Quantity + 1;
		oli.UnitPrice = oli.UnitPrice + 1;
		update oli;
		
		qliList = [select Id, Quantity, UnitPrice, OpportunityLineItemId__c, Fulfillment_Method__c, Delivery_Date__c, Expected_Customer_Delivery_Date__c, Est_Delivery_Date__c, Notes__c from QuoteLineItem where Id = : q1.Id];
		
		system.debug('*****TestSyncOLI_QLI qliList 2 = ' + qliList);
		
       	System.assertNotEquals(oli.Fulfillment_Method__c, qliList[0].Fulfillment_Method__c);
       	System.assertNotEquals(oli.Delivery_Date__c, qliList[0].Delivery_Date__c);
		System.assertNotEquals(oli.Notes__c, qliList[0].Notes__c);
		System.assertNotEquals(oli.Quantity, qliList[0].Quantity);
		System.assertNotEquals(oli.UnitPrice, qliList[0].UnitPrice);
       	
       	// Now synchronize the quote with the opportunity and verify that custom fields in the line items are synchronized
       	OpportunityLineItemService.resetOLItoQLIinProcess();
       	QuoteLineItemService.resetQLItoOLIinProcess();
       	o.SyncedQuoteId = q.Id;
       	update o;
       	
       	qliList = [select Id, Quantity, UnitPrice, OpportunityLineItemId__c, Fulfillment_Method__c, Delivery_Date__c, Expected_Customer_Delivery_Date__c, Est_Delivery_Date__c, Notes__c from QuoteLineItem where Id = : q1.Id];
		system.debug('*****TestSyncOLI_QLI qliList 3 = ' + qliList);
       	
       	List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
       	oliList = [select PricebookEntryId, PricebookEntry.Pricebook2Id, Quantity, UnitPrice, Fulfillment_Method__c, Delivery_Date__c, Est_Delivery_Date__c,  Expected_Customer_Delivery_Date__c, Notes__c, SyncedQuoteId__c from OpportunityLineItem where OpportunityId = :o.Id limit 1];
       	
       	system.debug('*****TestSyncOLI_QLI oliList 4 = ' + oliList);
       	
       	System.assertEquals(oliList[0].Fulfillment_Method__c, qliList[0].Fulfillment_Method__c);
       	System.assertEquals(oliList[0].Delivery_Date__c, qliList[0].Delivery_Date__c);
		System.assertEquals(oliList[0].Notes__c, qliList[0].Notes__c);
		System.assertEquals(oliList[0].Quantity, qliList[0].Quantity);
		System.assertEquals(oliList[0].UnitPrice, qliList[0].UnitPrice);
		
		qliList[0].Fulfillment_Method__c = 'Custom';
		qliList[0].Delivery_Date__c = '3 weeks';
		qliList[0].Notes__c = 'Blah blah';
		qliList[0].Quantity = qliList[0].Quantity + 1;
		qliList[0].UnitPrice = qliList[0].UnitPrice + 1;
		
		OpportunityLineItemService.resetOLItoQLIinProcess();
       	QuoteLineItemService.resetQLItoOLIinProcess();
		update qliList[0];
		
		oliList = [select PricebookEntryId, PricebookEntry.Pricebook2Id, Quantity, UnitPrice, Fulfillment_Method__c, Delivery_Date__c, Est_Delivery_Date__c,  Expected_Customer_Delivery_Date__c, Notes__c, SyncedQuoteId__c from OpportunityLineItem where OpportunityId = :o.Id limit 1];
		
		system.debug('*****TestSyncOLI_QLI oliList 5 = ' + oliList);
		
		System.assertEquals(oliList[0].Fulfillment_Method__c, qliList[0].Fulfillment_Method__c);
       	System.assertEquals(oliList[0].Delivery_Date__c, qliList[0].Delivery_Date__c);
		System.assertEquals(oliList[0].Notes__c, qliList[0].Notes__c);
		System.assertEquals(oliList[0].Quantity, qliList[0].Quantity);
		System.assertEquals(oliList[0].UnitPrice, qliList[0].UnitPrice);
		
		oliList[0].Fulfillment_Method__c = 'COM/COL';
		oliList[0].Delivery_Date__c = '4 weeks';
		oliList[0].Notes__c = 'JJJJJJ';
		oliList[0].Quantity = oliList[0].Quantity + 1;
		oliList[0].UnitPrice = oliList[0].UnitPrice + 1;
		
		OpportunityLineItemService.resetOLItoQLIinProcess();
       	QuoteLineItemService.resetQLItoOLIinProcess();
		update oliList[0];
		
		qliList = [select Id, Quantity, UnitPrice, OpportunityLineItemId__c, Fulfillment_Method__c, Delivery_Date__c, Expected_Customer_Delivery_Date__c, Est_Delivery_Date__c, Notes__c from QuoteLineItem where Id = : q1.Id];
		
		system.debug('*****TestSyncOLI_QLI qliList 6 = ' + qliList);
		
		System.assertEquals(oliList[0].Fulfillment_Method__c, qliList[0].Fulfillment_Method__c);
       	System.assertEquals(oliList[0].Delivery_Date__c, qliList[0].Delivery_Date__c);
		System.assertEquals(oliList[0].Notes__c, qliList[0].Notes__c);
		System.assertEquals(oliList[0].Quantity, qliList[0].Quantity);
		System.assertEquals(oliList[0].UnitPrice, qliList[0].UnitPrice);
    }
*/
}