objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Total_Lifetime_Value__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand.</description>
        <inlineHelpText>Lifetime revenue for this contact (where the contact was the Billing name on the order)</inlineHelpText>
        <label>Total Lifetime Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Impact_On_Account_Lifetime_Value__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand. No known use for this field.</description>
        <label>Last Impact On Account Lifetime Value</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Impact_On_Contact_Lifetime_Value__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand. No known use for this field.</description>
        <label>Last Impact On Contact Lifetime Value</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Open- Order lines are open to be fulfilled
Closed- All items have either shipped or cancelled
Cancelled - No items have shipped - all cancelled
Held- Order placed on hold. Will not ship.
Suspended/Error - Issues preventing CW processing and accepting</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <description>Including shipping, handling, and tax</description>
        <inlineHelpText>Order total sums all ship tos.</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RollUps.cls
/**
 * @description Container for roll up operations
 * @author John Rogers
 * @date 02-11-2016
 */
public class RollUps {

    /**
     * @description Lazy roll up
     *     Roll up type: Sum
     *     Child type: RH_Order
     *     Parent type: Contact
     *     Lookup field: Contact_Sold_To
     *     Child field: Total_Order_Amount
     *     Parent field: Total_Business_Contact_Lifetime_Value
     *     Exclude all children orders that have Status = 'Cancelled'
     * @author John Rogers, Traction on Demand
     * @date 2016-02-09
     */
    public class ContactLifetimeValueRollUp extends LazyRollUp {

        public ContactLifetimeValueRollUp() {
            ruType = RollUp.RollUpType.SUM;
            lastImpactOnRollUpField = RH_Order__c.Last_Impact_On_Contact_Lifetime_Value__c;
            lookupField = RH_Order__c.Contact_Sold_To__c;
            childField = RH_Order__c.Total_Order_Amount__c;
            parentField = Contact.Total_Lifetime_Value__c;
            rollUpCriteriaClause = 'Total_Order_Amount__c != null AND Status__c != \'Cancelled\'';
        }

        /**
         * @description Returns true if the given child record fits the roll up criteria
         * @author John Rogers, Traction on Demand
         * @date   2016-02-09
         * @param  obj : The record
         * @return True if the child record fits the roll up criteria
         */
        public override Boolean fitsRollUpCriteria(SObject obj) {
            RH_Order__c order = (RH_Order__c) obj;
            return (order.Total_Order_Amount__c != null &&
                order.Status__c != 'Cancelled');
        }
    }

    /**
     * @description Lazy roll up
     *      Roll up type: Sum
     *      Child type: RH_Order
     *      Parent type: Account
     *      Lookup field: Account_Sold_To__c
     *      Child field: Total_Order_Amount
     *      Parent field: Total_Company_Lifetime_Value
     *      Exclude all children orders that have Status = 'Cancelled'
     * @author John Rogers, Traction on Demand
     * @date 2016-02-09
     */
    public class AccountLifetimeValueRollUp extends LazyRollUp {

        public AccountLifetimeValueRollUp() {
            ruType = RollUp.RollUpType.SUM;
            lastImpactOnRollUpField = RH_Order__c.Last_Impact_On_Account_Lifetime_Value__c;
            lookupField = RH_Order__c.Account_Sold_To__c;
            childField = RH_Order__c.Total_Order_Amount__c;
            parentField = Account.Total_Company_Lifetime_Value__c;
            rollUpCriteriaClause = 'Total_Order_Amount__c != null AND Status__c != \'Cancelled\'';
        }

        /**
         * @description Returns true if the given child record fits the roll up criteria
         * @author John Rogers, Traction on Demand
         * @date   2016-02-09
         * @param  obj : The record
         * @return True if the child record fits the roll up criteria
         */
        public override Boolean fitsRollUpCriteria(SObject obj) {
            RH_Order__c order = (RH_Order__c) obj;
            return (order.Total_Order_Amount__c != null &&
                order.Status__c != 'Cancelled');
        }
    }

}