objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>All Users but Admin</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Clone__c.object
<CustomObject>
    <description>A clone of a corresponding Quote record. For use in portals.</description>
    <fields>
        <fullName>Card_Billing_City__c</fullName>
        <label>Card Billing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Billing_Country__c</fullName>
        <label>Card Billing Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Billing_Postal_Code__c</fullName>
        <label>Card Billing Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Billing_State__c</fullName>
        <label>Card Billing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Billing_Street__c</fullName>
        <label>Card Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Expiration_Month__c</fullName>
        <label>Card Expiration Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Expiration_Year__c</fullName>
        <label>Card Expiration Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <description>The name of the credit card holder as it appears on the credit card.</description>
        <inlineHelpText>The name of the credit card holder as it appears on the credit card.</inlineHelpText>
        <label>Card Holder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Source_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Record</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Clones</relationshipLabel>
        <relationshipName>Quote_Clones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <label>RH Quote</label>
    <nameField>
        <label>RH Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RH Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestCopyCardInfoToOpportunity.cls
/**********************************************************/
/*                                                        */
/*  This Class tests the CopyCardInfoToOpportunity        */
/*  Trigger that copies the credit card info from a       */
/*  Quote Clone object to an Opportunity.                 */
/*                                                        */
/**********************************************************/

@isTest
private class TestCopyCardInfoToOpportunity {

    static testMethod void testCopyCardInfoToOpportunity() {
        
        // Populate Custom Settings
        PrepareData.populateCustomSettings();
        
        // Create an Account
        Account a = PrepareData.createAccount();
        insert a;
        
        // Create a Contact
        Contact c = PrepareData.createContact(a.Id);
        insert c;
        
        // Create an Opportunity
        Opportunity o = PrepareData.createOpportunity(a.Id);
        insert o;
        
        // Get a User
        User u = [SELECT Id FROM User WHERE IsActive = true AND UserType = 'Standard' LIMIT 1];
        
        // Create a Quote
        Quote q = PrepareData.createQuote(u.Id, c.Id, o.Id, u.Id, 'Standard');
        insert q;
        
        // Get the Quote Clone Object that was created
        Quote_Clone__c qc = [SELECT Card_Billing_City__c, Card_Billing_Country__c, Card_Billing_Postal_Code__c,
				Card_Billing_State__c, Card_Billing_Street__c, Card_Expiration_Month__c,
				Card_Expiration_Year__c, Card_Holder_Name__c, Card_Number__c FROM Quote_Clone__c WHERE Source_Record__c = :q.Id LIMIT 1];
		
		// Update the Quote Clone Object
		qc.Card_Billing_City__c = 'Denver';
		qc.Card_Billing_Country__c = 'USA';
		qc.Card_Billing_Postal_Code__c = '80237';
		qc.Card_Billing_State__c = 'CO';
		qc.Card_Billing_Street__c = '6565 Main Street';
		qc.Card_Expiration_Month__c = '03';
		qc.Card_Expiration_Year__c = '3014';
		qc.Card_Holder_Name__c = 'Pat Anderson';
		qc.Card_Number__c = '4111111111111111';
		qc.Submitted__c = true;
		update qc;
		
		// Reselect the Opportunity fields
		Opportunity theOpportunity = [SELECT Card_Billing_City__c, Card_Billing_Country__c, 
			Card_Billing_Postal_Code__c, Card_Billing_State__c, Card_Billing_Street__c,
			Card_Expiration_Month__c, Card_Expiration_Year__c, Card_Holder_Name__c,
			Card_Number__c FROM Opportunity WHERE Id = :o.Id LIMIT 1];
		
		// Assert that the Opportunity was updated correctly
		System.assertEquals('Denver', theOpportunity.Card_Billing_City__c);
		System.assertEquals('USA', theOpportunity.Card_Billing_Country__c);
		System.assertEquals('80237', theOpportunity.Card_Billing_Postal_Code__c);
		System.assertEquals('CO', theOpportunity.Card_Billing_State__c);
		System.assertEquals('6565 Main Street', theOpportunity.Card_Billing_Street__c);
		System.assertEquals('03', theOpportunity.Card_Expiration_Month__c);
		System.assertEquals('3014', theOpportunity.Card_Expiration_Year__c);
		System.assertEquals('Pat Anderson', theOpportunity.Card_Holder_Name__c);
		System.assertEquals('4111111111111111', theOpportunity.Card_Number__c);	
    }
}