objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_SSV_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field mapping for order to ssv records.</description>
    <label>Order SSV Field Mapping</label>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AuditLog__c</fullName>
        <description>Logs the change to the customer number for this order</description>
        <label>AuditLog</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Order.</description>
        <label>Customer Address Sold To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_to_Company__c</fullName>
        <label>Sold To Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Customer_Number__c</fullName>
        <description>CW Sold to Cust Number</description>
        <label>Sold To Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_View_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV process has run to determine whether this Order should be linked to an existing SSV or if a new SSV needs to be created.</description>
        <label>Source System View Sold To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Ship To should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Ship Tos are linked to the incorrect Business or Person Account record.</description>
        <label>Account Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <formula>Order__r.Account_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CW_Customer_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW Customer Ship To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Ship Tos (CW Customer Ship To)</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Ship To.</description>
        <label>Customer Address Ship To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer_Number__c</fullName>
        <label>Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AuditLog__c</fullName>
        <label>AuditLog</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RH_Orders.cls
/**
 * @description Domain class for RH_Order__c object. 
 *  Handles all functionality for its respective object,
 *  deferring complex implementations to helper classes.
 * @author John Rogers, Traction on Demand
 * @date 17-02-2016
 */
public class RH_Orders extends SObjectDomain {

	private @testVisible List<Order_SSV_Field_Mapping__c> orderMapSettings {
		get {
			if(orderMapSettings == null) {
				orderMapSettings = Order_SSV_Field_Mapping__c.getAll().values();
			}

			return orderMapSettings;
		} private set;
	}    

    public RH_Orders() {
        super();
    }

    public override void handleBeforeInsert() {
		if (!UserHelper.isIntegrationUser()) {
	        setLookups(records);
	        linkToExistingContact(records);
		}        
    }

    public override void handleBeforeUpdate(Map<Id, SObject> oldRecordMap) {
    	if (!UserHelper.isIntegrationUser()) {
	        handleSSVChanges(oldRecordMap);
		}        

    }

    public override void handleAfterUpdate(Map<Id, SObject> oldRecordMap) {
    	if (!UserHelper.isIntegrationUser()) {
    		// update ship-to
        	recordsToUpdate((List<SObject>) updateShipToChildren(oldRecordMap));
        	// handle creating SSV if one not already created
        	handleSSVCreation(oldRecordMap);
    	}
    }

    public override void handleAfterInsert() {
		if (!UserHelper.isIntegrationUser()) {
    		handleSSVCreation(null);
		}
    }
    
    /*
     * Link to any contacts that we know already exist
     * Company first (via trade-id)
     */
    
    private @testvisible void linkToExistingContact(List<RH_Order__c> orders) {
    	
    	// return if empty
    	if (orders == null || orders.size() < 1) {
    		system.debug('empty orders');
    		return;
    	}
    	    	    	
    	// build up a set of trade IDs
    	system.debug('build up a set of trade IDs');
    	Set<String> tradeIds = new Set<String>();
    	for(RH_Order__c triggerOrder : orders) {
    		if (triggerOrder.Trade_ID__c != null) {
    			tradeIds.add(triggerOrder.Trade_ID__c);
    		}
    	}
    	
    	// query all the accounts with those trade ids
    	system.debug('query all the accounts with those trade ids');
		List<Account> accounts = [
            SELECT ID, X12_Digit_Member__c, Name 
            FROM Account
            WHERE X12_Digit_Member__c IN :tradeIds
        ];    	
    	
    	// create a map based on trade ID
    	system.debug('create a map based on trade ID');
        Map<String, Account> existing = new Map<String, Account>();
        MapUtils.mapByField(existing, accounts, Account.X12_Digit_Member__c);   	
        
        // assign existing accounts to order matching on trade ID.  
        system.debug('loop through orders, linking to matching account by trade-id');  	
		for(RH_Order__c orderRecord : orders) {
			if (orderRecord.Trade_ID__c != null) {
				system.debug('order has a trade ID');
				if (existing.containsKey(orderRecord.Trade_ID__c)) {
					system.debug('account with that trade id is found');
					orderRecord.Account_Sold_To__c = existing.get(orderRecord.Trade_ID__c).ID;
			
			//source for this order value is CW, order values should not be updated programatically 		
			//		orderRecord.Sold_to_Company__c = existing.get(orderRecord.Trade_ID__c).Name;	
			
				} else {
					system.debug('no matching account - remove the trade id from the order');
				//should not overwrite value provided from CW
				//	orderRecord.Trade_ID__c = null; 
				}				
			} 
		}
		        
    }
    
    /**
     * Spawn SSV records when a new order is created/updated
     * An SSV is spawned if:
     * 1. This is an insert and the sold to customer number is already populated.
     * 2. This is an update adn the sold to customer number is being populated for the FIRST time (and no existing SSV is already attached to the order)
     */
     
    private @testvisible void handleSSVCreation(Map<Id, SObject> oldRecordMap) {
    	
    	Reporter.log('Checkpoint - Order SSV Creation Start: ' +  Datetime.now().getTime());
    	
		// handle records    	
		for(RH_Order__c orderRecord : (List<RH_Order__c>) records) {
			if (oldRecordMap == null) {
				if (orderRecord.Sold_To_Customer_Number__c != null) {
					Source_System_View__c newSSV = SSVLoader.createSSV(orderRecord, orderMapSettings); 
					// add the SSV
					system.debug('creating an ssv for record with id ' + orderRecord.Id + ' and customer number ' + orderRecord.Sold_To_Customer_Number__c);
					recordsToInsert.add(newSSV);
				}
			} else {
				RH_Order__c existingRecord = (RH_Order__c) oldRecordMap.get(orderRecord.Id);
				if (orderRecord.Sold_To_Customer_Number__c != null  && orderRecord.Source_System_View_Sold_To__c == null && (existingRecord == null || existingRecord.Sold_To_Customer_Number__c == null)) {
					Source_System_View__c newSSV = SSVLoader.createSSV(orderRecord, orderMapSettings);
					// add the SSV					
					system.debug('creating an ssv for record with id ' + orderRecord.Id + ' and customer number ' + orderRecord.Sold_To_Customer_Number__c);
					recordsToInsert.add(newSSV);					
				}				
			}
		}
		
		Reporter.log('Checkpoint - Order SSV Creation Stop: ' +  Datetime.now().getTime());
    } 
    

    /**
     * @description Handles updates to the Sold_To_Customer_Number__c and Source_System_View_Sold_To__c fields
     * @author John Rogers, Traction on Demand
     * @date 2016-02-19
     * @param oldRecordMap : The records prior to update
     */
    private void handleSSVChanges(Map<Id, SObject> oldRecordMap) {
        // If related ssv changes update lookups
        List<RH_Order__c> ssvChanged = new List<RH_Order__c>();
        for (RH_Order__c order : (List<RH_Order__c>) records) {
            RH_Order__c oldOrder = (RH_Order__c) oldRecordMap.get(order.Id);
            if (oldOrder.Sold_To_Customer_Number__c != order.Sold_To_Customer_Number__c) {
            	order.AuditLog__c += (oldOrder.Sold_To_Customer_Number__c + '->');
                ssvChanged.add(order);
            }
        }
        if (!ssvChanged.isEmpty()) {
        	Reporter.log('updated records contain changes to Sold_To_Customer_Number__c: ' + ssvChanged.size());
	        setLookups(ssvChanged);
        }
    }

    /**
     * @description Given a list of orders, sets the Source_System_View_Sold_To__c lookup to
     *              the SSV record SSV.EXT_Source_System_Customer_ID__c = order.Sold_To_Customer_Number__c 
     *              or if Sold_To_Customer_Number__c is null and Source_System_View_Sold_To__c is not,
     *              sets Source_System_View_Sold_To__c by SSV record SSV.Id = order.Source_System_View_Sold_To__c
     * @author John Rogers, Traction on Demand
     * @date        2016-02-18
     * @param       orders : orders to set the lookups on
     */
    private void setLookups(List<RH_Order__c> orders) {
        
        Set<String> custNums = new Set<String>();
        for (RH_Order__c order : orders) {
            if (!String.isBlank(order.Sold_To_Customer_Number__c)) {
                custNums.add(order.Sold_To_Customer_Number__c);
            }
        }

        if (custNums.isEmpty()) {
            return;
        }

        List<Source_System_View__c> ssvs = [
            SELECT EXT_Source_System_Customer_ID__c, 
                    Account__c, 
                    Contact__c, 
                    Customer_Address__c
            FROM Source_System_View__c
            WHERE EXT_Source_System_Customer_ID__c IN :custNums
        ];

        setOrderLookupsFromSSV(orders, ssvs);
    }

    /**
     *  @description Given a list of orders with Sold To customer numbers:
     *               Sets the order lookups to SSV, Account, Contact, and Address
     *               equal to the corresponding Customer Number SSV values
     *  @author      Ernesto Valdes, Traction on Demand.
     *  @date        2016-02-23
     *  @param       orders        The orders to link using customer number
     *  @param       custNumToSSV  The source sytem view records from which to get lookup values
     */
     
    public static void setOrderLookupsFromSSV(List<RH_Order__c> orders, 
                                        List<Source_System_View__c> ssvs) {
                                        	
        Map<String, Source_System_View__c> custNumToSSV = new Map<String, Source_System_View__c>();
        MapUtils.mapByField(custNumToSSV, ssvs, Source_System_View__c.EXT_Source_System_Customer_ID__c);

        for (RH_Order__c order : orders) {
        	if (custNumToSSV.containsKey(order.Sold_To_Customer_Number__c)) {
	            Source_System_View__c ssv = custNumToSSV.get(order.Sold_To_Customer_Number__c);	
	            if (order.Source_System_View_Sold_To__c != ssv.Id ||
	                order.Account_Sold_To__c != ssv.Account__c ||
	                order.Contact_Sold_To__c != ssv.Contact__c ||
	                order.Customer_Address_Sold_To__c != ssv.Customer_Address__c) {
	                	
				    order.Source_System_View_Sold_To__c = ssv.Id;
				    order.Account_Sold_To__c = ssv.Account__c;
				    order.Contact_Sold_To__c = ssv.Contact__c;
				    order.Customer_Address_Sold_To__c = ssv.Customer_Address__c;
	            }
        	}
        }
    }

    /**
     * @description Called within after update context will copy lookup field values to 
     *              children Ship_To__c records with Ship_To_Customer_Number__c = '0'
     * @author John Rogers, Traction on Demand
     * @date 2016-02-18
     * @param  oldRecordMap : The records prior to update
     * @return Children records to update
     */
     
    private List<Ship_To__c> updateShipToChildren(Map<Id, SObject> oldRecordMap) {
    	
        // If various lookups have changed, pass changes down to children
        
        List<RH_Order__c> changedOrders = new List<RH_Order__c>();
        for (RH_Order__c order : (List<RH_Order__c>) records) {
        	if (oldRecordMap.containsKey(order.Id)) {
	            RH_Order__c oldOrder = (RH_Order__c) oldRecordMap.get(order.Id);
	            if (oldOrder.Source_System_View_Sold_To__c != order.Source_System_View_Sold_To__c ||
	                    oldOrder.Account_Sold_To__c != order.Account_Sold_To__c ||
	                    oldOrder.Contact_Sold_To__c != order.Contact_Sold_To__c ||
	                    oldOrder.Customer_Address_Sold_To__c != order.Customer_Address_Sold_To__c) {
	                changedOrders.add(order);
	            }
        	}
        }

        if (changedOrders.isEmpty()) {
            return new List<Ship_To__c>();
        }

        return setShipToLookupsFromOrder(changedOrders);
    }

    /**
     *  @description For a given list of orders, gets the Ship_To__c records that
     *               share the same customer as the order, and update these Ship_To__c records
     *               to match the order's Account/Contact/CustomerAddress lookups
     *  @author      Ernesto Valdes, Traction on Demand.
     *  @date        2016-02-24
     *  @param       orders        The orders for which to set Ship_To__c lookups
     *  @return                    The updated Ship_To__c records
     */
     
    public static List<Ship_To__c> setShipToLookupsFromOrder(List<RH_Order__c> orders) {

        List<Ship_To__c> toUpdate = new List<Ship_To__c>();

        // Get map of orders to their shipTo children
        Map<Id, List<SObject>> orderToShipTos = MapUtils.mapByIdFieldToList([
            SELECT Order__c, CW_Customer_Ship_To__c, Account_Ship_To__c, 
                    Contact_Ship_To__c, Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Ship_To_Customer_Number__c = '0' AND
                Order__c IN :orders
        ], Ship_To__c.Order__c);

        // Copy order info over to shipTo children
        for (RH_Order__c order : orders) {

            if (orderToShipTos.containsKey(order.Id)) {
                for (Ship_To__c shipTo : (List<Ship_To__c>) orderToShipTos.get(order.Id)) {

                    if (shipTo.CW_Customer_Ship_To__c != order.Source_System_View_Sold_To__c ||
		                shipTo.Account_Ship_To__c != order.Account_Sold_To__c ||
		                shipTo.Contact_Ship_To__c != order.Contact_Sold_To__c ||
		                shipTo.Customer_Address_Ship_To__c != order.Customer_Address_Sold_To__c) {
                    	
				        shipTo.CW_Customer_Ship_To__c = order.Source_System_View_Sold_To__c;
				        shipTo.Account_Ship_To__c = order.Account_Sold_To__c; 
				        shipTo.Contact_Ship_To__c = order.Contact_Sold_To__c;
				        shipTo.Customer_Address_Ship_To__c = order.Customer_Address_Sold_To__c;                        
                        toUpdate.add(shipTo);
                    }
                }
            }
        }
        return toUpdate;
    }

}