objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Design_Atelier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>DA_Opportunity_Number__c</fullName>
        <label>DA Opportunity Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DA_Opportunity__c</fullName>
        <label>DA Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Design Atelier Quotes</relationshipLabel>
        <relationshipName>Design_Atelier_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EXT_Oppty_Quote_Number__c</fullName>
        <externalId>true</externalId>
        <label>EXT Oppty Quote Number</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Subtotal__c</fullName>
        <label>Order Subtotal</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Id__c</fullName>
        <externalId>true</externalId>
        <label>Quote Id</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Design Atelier Quote</label>
    <nameField>
        <label>Design Atelier Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Design Atelier Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Opportunity_DAQuoteCtrlExt_Test.cls
/*Test class for controller*/

@isTest(SeeAllData = true)
	
public with sharing class Opportunity_DAQuoteCtrlExt_Test  {

	static testMethod void Opportunity_DAQuoteCtrlExt_UnitTest() {
  		
  		Account testDAAccount = new Account();
	 	Contact testDAContact = new Contact();
	 	Opportunity testDAOppty = new Opportunity();
	 	Opportunity testDAOppty2 = new Opportunity();
  		
  		testDAAccount = PrepareData.createAccount();
	 	insert testDAAccount;
	 	testDAContact = PrepareData.createContact(testDAAccount.Id);
	 	insert testDAContact;
	 	testDAOppty = PrepareData.createOpportunity(testDAAccount.Id);
	 	insert testDAOppty;
	 	testDAOppty2 = PrepareData.createOpportunity(testDAAccount.Id);
	 	insert testDAOppty2;
  		
  		//Create a new instance of standard controller
 		ApexPages.StandardController sc = new ApexPages.standardController(testDAOppty);
 		Opportunity_DAQuoteCtrlExt controller = new Opportunity_DAQuoteCtrlExt(sc);
 		
 		Design_Atelier_Quote__c daq = new Design_Atelier_Quote__c();
 		Design_Atelier_Quote__c daq2 = new Design_Atelier_Quote__c();
 		
 		List<Opportunity_DAQuoteCtrlExt.DesignAtelierQuoteWrapper> testdaQuoteWrapperList = new List<Opportunity_DAQuoteCtrlExt.DesignAtelierQuoteWrapper>();
	  	
	  	daq.name='DATestQuoteName';
	  	daq.Quote_Id__c = 'DATestQuoteId';
	  	daq.Forecast__c = TRUE;
	  	daq.Order_Subtotal__c = 123.00;
	  	daq.EXT_Oppty_Quote_Number__c = 'DATestEXTOpptyQuoteNumber';
	  	daq.DA_Opportunity__c = testDAOppty.Id;
	  	daq.DA_Opportunity_Number__c = 'DATestOpptyNumber';
	  	
	  	insert daq;
	  	
	  	daq2.name='DATestQuoteName';
	  	daq2.Quote_Id__c = 'DATestQuoteId';
	  	daq2.Forecast__c = TRUE;
	  	daq2.Order_Subtotal__c = 123.00;
	  	daq2.EXT_Oppty_Quote_Number__c = 'DATestEXTOpptyQuoteNumber';
	  	daq2.DA_Opportunity__c = testDAOppty2.Id;
	  	daq2.DA_Opportunity_Number__c = 'DATestOpptyNumber';
	
		insert daq2;
		
	  	test.startTest();
	  	testdaQuoteWrapperList = controller.daQuoteWrapperList;
	  	test.stopTest();	
    } 
}