objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <fields>
        <fullName>Value_Text__c</fullName>
        <label>Value - Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

objects/FieldIdLookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>lookup values for custom Field API names and field Id&apos;s. Used for creating pre-populated values for buttons</description>
    <fields>
        <fullName>FieldId__c</fullName>
        <description>Salesforce Field Id</description>
        <label>FieldId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Field Id Lookup</label>
</CustomObject>

objects/Gallery_Furniture__c.object
<CustomObject>
    <description>Represents furniture located in a Gallery.</description>
    <fields>
        <fullName>Gallery_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gallery Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Name</field>
                <operation>startsWith</operation>
                <value>Gallery</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>0,1,2,3,4,5,6,7,8,9</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Gallery Furniture</relationshipLabel>
        <relationshipName>Gallery_Furniture</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gallery_Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gallery Associate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Gallery_Furniture</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HDL_Checklist__c</fullName>
        <label>HDL Checklist #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Piece__c</fullName>
        <label>Piece #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Gallery Furniture</relationshipLabel>
        <relationshipName>Gallery_Furniture</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Register__c</fullName>
        <label>Register #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Date__c</fullName>
        <label>Sold Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_2__c</fullName>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_3__c</fullName>
        <label>Sold To Address 3</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Alternate_Phone__c</fullName>
        <label>Sold To Alternate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_To_City__c</fullName>
        <label>Sold To City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Email__c</fullName>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_To_First_Name__c</fullName>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Last_Name__c</fullName>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Phone__c</fullName>
        <label>Sold To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_To_Postal_Code__c</fullName>
        <label>Sold To Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_State_Province__c</fullName>
        <label>Sold To State/Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Pieces__c</fullName>
        <label>Total Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Gallery Furniture</label>
    <nameField>
        <displayFormat>GF-{00000000}</displayFormat>
        <label>Gallery Furniture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gallery Furniture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CW_Item_Description__c</fullName>
        <description>upload from ipim. field map: CW Item Description. 121311LALO</description>
        <label>CW Item Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECommerce_Display_Name__c</fullName>
        <label>ECommerce Display Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Image_URL__c</fullName>
        <description>the url where the image of the product resides</description>
        <label>Product Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>STSSku__c</fullName>
        <description>ipim field map; RH Retail SKU. 032111LALO</description>
        <label>STSSku</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/RH_Brand__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping table - maps the value in the Source Code field of the Order (contains the 2 character Division code) to the Restoration Hardware brand to use for things like the Billing Summary email.</description>
    <label>RH Brand</label>
</CustomObject>

classes/GalleryFurnitureCtlExt.cls
public with sharing class GalleryFurnitureCtlExt {
	
	/*
	 *	Gallery Furniture controller extension - methods to support the gallery Furniture Status Form.
	 *
	 */
	
	ApexPages.StandardController stdController;
	
	public Gallery_Furniture__c rhFurniture {get; set;}
	public RH_Brand__c rhBrand {get; set;}
	public String productImageURL {get; set;}
	public String productDescription {get; set;}
	public String clientName {get; set;}
	public String clientStreetAddress {get; set;}
	public String productCode {get; set;}
	public Boolean validUPC {get; set;}
	public Boolean fatalError {get; set;}
	
	private String galleryFurnitureId;
	private String productId;
	private String accountId;
	private String retURL;
	
	// Constructor
	public GalleryFurnitureCtlExt(ApexPages.StandardController stdController) {
		
		fatalError = false;
		
		galleryFurnitureId = ApexPages.currentPage().getParameters().get('galleryFurnitureId');
		productId = ApexPages.currentPage().getParameters().get('productId');
		accountId = ApexPages.currentPage().getParameters().get('accountId');
		retURL = ApexPages.currentPage().getParameters().get('retURL');
		
	}
	
	// Get all the data for the Furniture Status Form
	public PageReference initFurnitureStatusForm() {
		
		rhFurniture = new Gallery_Furniture__c();
		
		if (String.isNotBlank(galleryFurnitureId)) {
			
			rhFurniture = [select Id, Name, Gallery_Account__c, Gallery_Associate__c, Product__c, 
					Register__c, Sold__c, Sold_To_Address_1__c, Sold_To_Address_2__c, Sold_To_Address_3__c, 
					Sold_To_Alternate_Phone__c, Sold_To_City__c, Sold_To_Email__c, Sold_To_First_Name__c, 
					Sold_To_Last_Name__c, Sold_To_Phone__c, Sold_To_Postal_Code__c, Sold_To_State_Province__c, 
					Sold_Date__c, Transaction__c, UPC__c, HDL_Checklist__c, Piece__c, Total_Pieces__c, 
					Product__r.Name, Product__r.UPC__c, Product__r.CW_Item_Description__c, 
					Product__r.ECommerce_Display_Name__c, Product__r.Product_Image_URL__c, Product__r.STSSku__c, 
					Gallery_Associate__r.Name, Gallery_Associate__r.Gallery__c, 
					Gallery_Account__r.Name, Gallery_Account__r.Gallery__c 
					from Gallery_Furniture__c where Id = :galleryFurnitureId];
			
			// Verify we have a valid UPC number
			validUPC = false;
			if (String.isNotBlank(rhFurniture.UPC__c)) {
				productCode = rhFurniture.UPC__c;
			} else {
				productcode = rhFurniture.Product__r.UPC__c;
			}
			if (String.isNotBlank(productCode) && productCode.isNumeric() &&  productCode.length() == 12) {
				validUPC = true;
			}
			
			// Verify required information (required for Furniture Status Form but not required for page layout)
			if (validUPC) {
				
				rhBrand = RH_Brand__c.getInstance('999');
				
				productImageURL = rhFurniture.Product__r.Product_Image_URL__c;
				if (String.isBlank(productImageURL)) {
					productImageURL = Application_Settings__c.getInstance('ProductImageNotAvailableURL').Value_Text__c;
				}
				
				productDescription = rhFurniture.Product__r.ECommerce_Display_Name__c;
				if (String.isBlank(productDescription) || productDescription == 'PRODUCT NOT AVAILABLE') {
					productDescription = rhFurniture.Product__r.CW_Item_Description__c;
					if (String.isBlank(productDescription)) {
						productDescription = ' ';
					}
				}
				
				clientName = '';
				if (String.isNotBlank(rhFurniture.Sold_To_First_Name__c)) {
					clientName += rhFurniture.Sold_To_First_Name__c + ' ';
				}
				if (String.isNotBlank(rhFurniture.Sold_To_Last_Name__c)) {
					clientName += rhFurniture.Sold_To_Last_Name__c;
				}
				if (String.isBlank(clientName)) {
					clientName = ' ';
				}
				
				clientStreetAddress = '';
				if (String.isNotBlank(rhFurniture.Sold_To_Address_1__c)) {
					clientStreetAddress += rhFurniture.Sold_To_Address_1__c + ', ';
				}
				if (String.isNotBlank(rhFurniture.Sold_To_Address_2__c)) {
					clientStreetAddress += rhFurniture.Sold_To_Address_2__c + ', ';
				}
				if (String.isNotBlank(rhFurniture.Sold_To_Address_3__c)) {
					clientStreetAddress += rhFurniture.Sold_To_Address_3__c + ', ';
				}
				if (String.isBlank(clientStreetAddress)) {
					clientStreetAddress = ' ';
				} else {
					clientStreetAddress = clientStreetAddress.removeEnd(', ');
				}
				
			} else {
				fatalError = true;
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Gallery Furniture field UPC must not be blank and UPC must be a valid 12 digit UPC number.'));
			}
				
		} else {
			
			fatalError = true;
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Invalid Gallery Furniture Id.'));
			
		}
		
		return null;
	}
	
	// Get data to pre-populate new Gallery Furniture record
	public PageReference initGalleryFurniture() {
		PageReference pr = null;
		Product2 rhProduct = new Product2();
		List<Account> accList = new List<Account>();
		User rhUser = new User();
		Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Account.getRecordTypeInfosByName();
		
		try {
			rhUser = [select Id, Name, Gallery__c from User where Id = :UserInfo.getUserId()];
			
			if (String.isNotBlank(accountId)) {
				accList = [select Id, Name from Account where Id = :accountId];
			} else {
				if (String.isNotBlank(rhUser.Gallery__c)) {
					accList = [select Id, Name from Account where Name = :rhUser.Gallery__c and RecordTypeId = :rtMap.get('Internal').getRecordTypeId() limit 1];
				}
			}
			
			if (String.isNotBlank(productId)) {
				rhProduct = [select Id, Name, UPC__c from Product2 where Id = :productId];
			}
			
			// Take the user to the create new Gallery Furniture page
			FieldIdLookup__c fieldId;
			String encodedName;
			Schema.DescribeSObjectResult r = Gallery_Furniture__c.sObjectType.getDescribe();
			String grKeyPrefix = r.getKeyPrefix();
			String pageURL = '/' + grKeyPrefix + '/e?retURL=' + retURL;
			if (rhProduct.Id != null) {
				if (String.isNotBlank(rhProduct.UPC__c)) {
					fieldId = FieldIdLookup__c.getInstance('Gallery_Furniture.UPC');
					encodedName = EncodingUtil.urlEncode(rhProduct.UPC__c,'UTF-8');
					pageURL += '&' + fieldId.FieldId__c + '=' + encodedName;
				}
				fieldId = FieldIdLookup__c.getInstance('Gallery_Furniture.Product');
				encodedName = EncodingUtil.urlEncode(rhProduct.Name,'UTF-8');
				pageURL += '&CF' + fieldId.FieldId__c + '=' + encodedName + '&CF' + fieldId.FieldId__c + '_lkid=' + rhProduct.Id;
			}
			if (!accList.isEmpty()) {
				fieldId = FieldIdLookup__c.getInstance('Gallery_Furniture.Gallery_Account');
				encodedName = EncodingUtil.urlEncode(accList[0].Name,'UTF-8');
				pageURL += '&CF' + fieldId.FieldId__c + '=' + encodedName + '&CF' + fieldId.FieldId__c + '_lkid=' + accList[0].Id;
			}
			if (String.isNotBlank(rhUser.Gallery__c)) {
				fieldId = FieldIdLookup__c.getInstance('Gallery_Furniture.Gallery_Associate');
				encodedName = EncodingUtil.urlEncode(rhUser.Name,'UTF-8');
				pageURL += '&CF' + fieldId.FieldId__c + '=' + encodedName + '&CF' + fieldId.FieldId__c + '_lkid=' + rhUser.Id;
			}
			
			pr = new PageReference(pageURL);
			
		} catch(Exception e) {
			fatalError = true;
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Exception while reading User, Account, or Product data: ' + e.getMessage()));
		}
		
		return pr;
	}
}