objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <description>CW Sold to Country</description>
        <label>Sold To Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>New_Ship_to_Country__c</fullName>
        <label>New Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Stewardship_Request__c.object
<CustomObject>
    <description>These requests are created by users to indicate that a related record needs to be reviewed by the stewardship team.</description>
    <fields>
        <fullName>Source_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The order from which this request was created.</description>
        <inlineHelpText>The order from which this request was created.</inlineHelpText>
        <label>Source Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipName>Stewardship_Review_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ship to from which this request was created.</description>
        <inlineHelpText>The ship to from which this request was created.</inlineHelpText>
        <label>Source Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipName>Stewardship_Review_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System_View__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for stewardship requests associated with Source System View records that fail to spawn correctly</description>
        <label>Source System View</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipName>Stewardship_Review_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stewardship Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Stewardship Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardship Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReporterTest.cls
/**
 *  ReporterTest.cls
 *  @description Verifies that APEX error reporting functionality
 *               works as expected
 *  @author Ernesto Valdes, Salesforce + Traction On Demand
 */
@isTest
private class ReporterTest {

	private class TestException extends Exception {}

	@isTest static void testReporting() {

		// Assert default starting state
		system.assertEquals(false, Reporter.logging);
		system.assertEquals(1, Reporter.logCount);

		// Verify start logging
		Reporter.startLogging();
		system.assertEquals(true, Reporter.logging);

		// Verify debug
		Reporter.log('test debug');
		system.assertEquals(2, Reporter.logCount);

		// Verify error message from text
		Reporter.report('test error message');
		system.assertEquals(3, Reporter.logCount);
		system.assertEquals(1, Reporter.logs.size());

		// Verify error message from exception
		Reporter.report(new TestException('test error exception'));
		system.assertEquals(4, Reporter.logCount);
		system.assertEquals(2, Reporter.logs.size());

		// Verify error message from database save result
		List<Account> testSObject = new List<Account>{new Account(FirstName='Test SObject')};
		Reporter.report(Database.insert(testSObject, false));
		system.assertEquals(5, Reporter.logCount);
		system.assertEquals(3, Reporter.logs.size());

		// Verify stop logging
		Reporter.stopLogging();
		system.assertEquals(false, Reporter.logging);

		// Verify logs created
		Reporter.createErrorLogs();
		List<Error_Log__c> testLogs = [SELECT Id FROM Error_Log__c];
		system.assertNotEquals(true, testLogs.isEmpty());
		system.assertEquals(3, testLogs.size());
	}

	@isTest static void testIntegrationReporting() {
		Source_System_View__c ssv = TestDataFactory.createSSV(true);
		SSVCustomer ssvCust = new SSVCustomer(ssv);
		ssvCust.ssvCleansedList.add(new SSVCleansed(ssv));
		List<Account> testSObject = new List<Account>{new Account(FirstName='Test SObject')};

		Reporter.startLogging();
		Reporter.integrationReport(
			new List<SSVCustomer> {ssvCust},
			testSObject,
			Database.insert(testSObject, false)
		);
		Reporter.createErrorLogs();
		List<Error_Log__c> testLogs = [SELECT Id FROM Error_Log__c];
		List<Stewardship_Request__c> reqs = [SELECT Id FROM Stewardship_Request__c];
		system.assert(!testLogs.isEmpty());
		system.assert(!reqs.isEmpty());
	}

	@isTest static void testIntegrationReporting_invalidLists() {
		Source_System_View__c ssv = TestDataFactory.createSSV(true);
		SSVCustomer ssvCust = new SSVCustomer(ssv);
		ssvCust.ssvCleansedList.add(new SSVCleansed(ssv));
		List<Account> testSObject = new List<Account>{
			TestDataFactory.createAccount(false)
		};

		Reporter.startLogging();
		Reporter.integrationReport(
			new List<SSVCustomer> {ssvCust, ssvCust}, // List is of wrong length
 			testSObject,
			Database.insert(testSObject, false)
		);
		Reporter.createErrorLogs();
		List<Error_Log__c> testLogs = [SELECT Message__c FROM Error_Log__c];
		System.assertEquals(0, testLogs.size());
		//System.assertEquals(Reporter.INVALID_CALL_ERROR, testLogs[0].Message__c);
	}

	@isTest static void testIntegrationReporting_invalidLists_2() {
		List<Account> accs = new List<Account>{
			new Account(FirstName='Test SObject')
		};

		Reporter.startLogging();
		List<Database.SaveResult> results = Database.insert(accs, false);
		accs.add(new Account());
		Reporter.integrationReport(
 			accs,
			results // List lengths do not match
		);
		Reporter.createErrorLogs();
		List<Error_Log__c> testLogs = [SELECT Message__c FROM Error_Log__c];
		System.assertEquals(1, testLogs.size());
		System.assertEquals(Reporter.INVALID_CALL_ERROR, testLogs[0].Message__c);
	}

	@isTest static void testReporting_invalidLists() {
		List<Account> accs = new List<Account>{
			new Account(FirstName='Test SObject')
		};

		Reporter.startLogging();
		List<Database.SaveResult> results = Database.insert(accs, false);
		accs.add(new Account());
		Reporter.report(
 			accs,
			results // List lengths do not match
		);
		Reporter.createErrorLogs();
		List<Error_Log__c> testLogs = [SELECT Message__c FROM Error_Log__c];
		System.assertEquals(1, testLogs.size());
		System.assertEquals(Reporter.INVALID_CALL_ERROR, testLogs[0].Message__c);
	}

	@isTest static void testDMLErrorReport_delete() {
		List<Source_System_View__c> ssvs = TestDataFactory.createSSV(1, true);
		Reporter.startLogging();
		Reporter.report(ssvs, Database.delete(ssvs, false));
		Reporter.createErrorLogs();
		List<Error_Log__c> testLogs = [SELECT Message__c FROM Error_Log__c];
		System.assertEquals(0, testLogs.size());
	}

	@isTest static void testDMLErrorReport_ssv() {
		List<Source_System_View__c> ssvs = TestDataFactory.createSSV(1, false);
		ssvs[0].Country__c = 'Entering more than 80 characters to break validation rule. Entering more than 80 characters to break validation rule.';
		Reporter.startLogging();
		Reporter.integrationReport(ssvs, Database.insert(ssvs, false));
		Reporter.createErrorLogs();
		Stewardship_Request__c req = [SELECT Source_System_View__c FROM Stewardship_Request__c];
		System.assertEquals(req.Source_System_View__c, ssvs[0].Id);
	}

	@isTest static void testDMLErrorReport_order() {
		List<RH_Order__c> os = TestDataFactory.createRhOrders(1, false);
		os[0].Sold_To_Country__c = 'Entering more than 80 characters to break validation rule. Entering more than 80 characters to break validation rule.';
		Reporter.startLogging();
		Reporter.integrationReport(os, Database.insert(os, false));
		Reporter.createErrorLogs();
		Stewardship_Request__c req = [SELECT Source_Order__c FROM Stewardship_Request__c];
		System.assertEquals(req.Source_Order__c, os[0].Id);
	}

	@isTest static void testDMLErrorReport_ship_to() {
		List<Ship_To__c> shts = TestDataFactory.createShipTos(1, false);
		shts[0].New_Ship_to_Country__c = 'Entering more than 80 characters to break validation rule. Entering more than 80 characters to break validation rule.';
		Reporter.startLogging();
		Reporter.integrationReport(shts, Database.insert(shts, false));
		Reporter.createErrorLogs();
		Stewardship_Request__c req = [SELECT Source_Ship_To__c FROM Stewardship_Request__c];
		System.assertEquals(req.Source_Ship_To__c, shts[0].Id);
	}
}