objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company_Account_SSV_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field mapping for account to ssv records. (Non person accounts)</description>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>Source Field mapping to SSV Field</description>
        <inlineHelpText>This contains the API field name of the relevant field from Account object</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company Account SSV Field Mapping</label>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Principal_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Membership_Number_Sequence_Reference__c.object
<CustomObject>
    <description>This table is present to generate a unique membership number for any new Trade or Contract customers. A table is used for this process vs a custom setting in order to reduce the risk of locking with the creation on new trade/ contract customers. A trigger references this table, inserts a row, obtains the next autonumber sequence and then deletes the row in order to minimize storage requirements.</description>
    <fields>
        <fullName>X12_Digit_Member__c</fullName>
        <description>Membership #&apos;s with 12 digits for Member Card Bar Code</description>
        <displayFormat>{YYYY}{MM}{000000}</displayFormat>
        <label>12 Digit Member</label>
        <type>AutoNumber</type>
    </fields>
    <label>Membership Number Sequence Reference</label>
    <nameField>
        <label>Membership Number Sequence Reference Nam</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Number Sequence References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Person_Account_SSV_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field mapping for account to ssv records. (Person Accounts)</description>
    <fields>
        <fullName>Source_Field__c</fullName>
        <inlineHelpText>This contains the API field name of the relevant field from Account object</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Person Account SSV Field Mapping</label>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Table__c</fullName>
        <label>Source Table</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Accounts.cls
/**
 * Customer Reconciliation Process
 * Accounts trigger - Upsert SSV records
 * @author Zi Zhang, Traction on Demand
 * @date   2016-02-27
 */
public class Accounts extends SObjectDomain {

    public static final Map<String, Schema.RecordTypeInfo> ACCOUNT_RECORD_TYPES = Schema.SObjectType.Account.getRecordTypeInfosByName();
    
    public static final Id CONTRACT_RECORD_TYPE_ID = ACCOUNT_RECORD_TYPES.get('Contract').getRecordTypeId();

    public static final Id TRADE_RECORD_TYPE_ID = ACCOUNT_RECORD_TYPES.get('Trade').getRecordTypeId();
            
    // Static variable to store children before thier parent is deleted by merge
    private static Contacts childrenContacts = new Contacts();

    private @testVisible List<Company_Account_SSV_Field_Mapping__c> companyMapSettings {
        get {
            if(companyMapSettings == null) {
                companyMapSettings = Company_Account_SSV_Field_Mapping__c.getAll().values();
            }

            return companyMapSettings;
        } private set;
    }

    private @testVisible List<Person_Account_SSV_Field_Mapping__c> personMapSettings {
        get {
            if(personMapSettings == null) {
                personMapSettings = Person_Account_SSV_Field_Mapping__c.getAll().values();
            }

            return personMapSettings;
        } private set;
    }

    private @testVisible Map<String, Source_System_View__c> relatedSSVByAccount {
        get {
            if(relatedSSVByAccount == null) {
                relatedSSVByAccount = new Map<String, Source_System_View__c>();

                List<Source_System_View__c> relatedSSVs = [SELECT Id, Account__c 
                                                            FROM Source_System_View__c 
                                                            WHERE Account__c IN :records AND 
                                                                (Source_Table__c = 'Salesforce Account' OR Source_Table__c = 'Salesforce Person Account')];
                MapUtils.mapByField(relatedSSVByAccount, relatedSSVs, Source_System_View__c.Account__c);
            }

            return relatedSSVByAccount;
        } private set;
    }

    private @testVisible Map<String, Customer_Address__c> relatedContactCustomerAddress {
        get {
            if(relatedContactCustomerAddress == null) {
                Set<Id> contactIds = new Set<Id>();
                relatedContactCustomerAddress = new Map<String, Customer_Address__c>();

                for(Account rec : (List<Account>) records) {
                    if(String.isNotEmpty(rec.PersonContactId)) {
                        contactIds.add(rec.PersonContactId);
                    }
                }

                List<Customer_Address__c> customerAddresses = [SELECT Id, Address__c, Contact__c 
                                                               FROM Customer_Address__c 
                                                               WHERE Contact__c IN :contactIds 
                                                                        AND Is_Principal_Address__c = true];

                MapUtils.mapByField(relatedContactCustomerAddress, customerAddresses, Customer_Address__c.Contact__c);
            }

            return relatedContactCustomerAddress;
        } private set;
    }

    /**
     * Given a list of accounts, set the X12_Digit_Member__c field if the account
     * is of the correct record type and has no current X12_Digit_Member__c
     * @author John Rogers, Traction on Demand
     * @date        2016-03-15
     * @param       accs : The accounts 
     */
    public static void setMemberNumbers(List<Account> accs) {
        
        System.debug('processing accs: ' + accs);
        List<Account> needsMemberNumber = new List<Account>();
            
        for (Account a : accs) {                            
            if ((a.RecordTypeId == CONTRACT_RECORD_TYPE_ID || a.RecordTypeId == TRADE_RECORD_TYPE_ID) && String.isBlank(a.X12_Digit_Member__c)) {
                needsMemberNumber.add(a);
            }           
        }
        
        System.debug('setting mem num on accs: ' + needsMemberNumber.size());
        
        if (needsMemberNumber.isEmpty()) {
            return;
        }

        // Create Membership_Number_Sequence_Reference__c records to get member numbers
        List<Membership_Number_Sequence_Reference__c> memNums = new List<Membership_Number_Sequence_Reference__c>();
                
        for (Account a : needsMemberNumber) {
            memNums.add(new Membership_Number_Sequence_Reference__c());
        }
        insert memNums;
        
        // Get the member numbers
        memNums = [SELECT X12_Digit_Member__c FROM Membership_Number_Sequence_Reference__c WHERE Id IN :memNums];
        System.debug('created mem numbers: ' + memNums);

        // Assign the member numbers
        for (Integer i = 0; i < memNums.size(); i++) {                       
            needsMemberNumber[i].X12_Digit_Member__c = memNums[i].X12_Digit_Member__c;
        }
            
        // Delete the used member numbers
        delete memNums;
    
    }

    public override void handleBeforeInsert() {
        setMemberNumbers((List<Account>) records);
    }

    public override void handleBeforeUpdate(Map<Id, SObject> oldRecordMap) {
        setMemberNumbers((List<Account>) records);
    }

    /**
     * Before delete for deleted Accounts which includes losers during a merge
     * Trigger will remove all child SSVs related to Accounts being deleted
     * @author Zi Zhang, Traction on Demand
     * @date   2016-02-29
     */
    public override void handleBeforeDelete() {
        deleteSSVs();
    }

    /**
     * Merges don't fire delete triggers when children records are
     * deleted/updated. This method performs the required logic on the children.
     * @author John Rogers, Traction on Demand
     * @date        2016-03-08
     */
    public override void handleBeforeMergeDelete() {
        // Collect the contacts that will be deleted
        childrenContacts.records = [
            SELECT Id 
            FROM Contact 
            WHERE AccountId IN :records AND Account.IsPersonAccount = true
        ];
        // TODO-jdr TODO-zz does beforeDelete() also need to be called?
        childrenContacts.handleBeforeMergeDelete();
    }
    /*
    public override void handleAfterDelete() {
       // for MDM2-78
       Set<Id> masters = new Set<Id>();    
       for(Account a:(List<Account>)records){
           if(a.MasterRecordId != null){
              masters.add(a.MasterRecordId);
           }
       }
       if(!masters.isEmpty()){
			List<SObject> recordsToUpdate = new List<SObject>();
			OrderService.processRollups(recordsToUpdate, masters);
			for(SObject record : recordsToUpdate) {
				this.recordsToUpdateMap.put(record.id, record);
			}
       }
    }   */     

    /**
     * After Update for Accounts: Upsert SSV records
     * @author Zi Zhang, Traction on Demand
     * @date   2016-02-27
     */
    public override void handleAfterUpdate(Map<Id, SObject> oldMap) {
        updateSSVs(oldMap);
    }

    /**
     * After Insert for Accounts: Upsert SSV records
     * @author Zi Zhang, Traction on Demand
     * @date   2016-02-27
     */
    public override void handleAfterInsert() {
        createSSVs();
    }

    /**
     * Create new SSV records on insert of Accounts
     * @author Zi Zhang, Traction on Demand
     * @date   2016-02-29
     */
    @testVisible
    private void createSSVs() {
        if (!UserHelper.isIntegrationUser()) {
            for(Account acc : (List<Account>) records) {
                if(acc.IsPersonAccount) {
                    recordsToInsert.add(SSVLoader.createSSV(acc, personMapSettings, relatedContactCustomerAddress.get(acc.PersonContactId)));
                   // CusContactInfoAndCusAddress.CusContactInfoAndCusAddress(acc,true);
                    
                } else {
                    recordsToInsert.add(SSVLoader.createSSV(acc, companyMapSettings, null));
                }
            }
        }
    }

    /**
     * Create new SSV records on insert of Accounts
     * @author Zi Zhang, Traction on Demand
     * @date   2016-02-29
     */
    @testVisible
    private void updateSSVs(Map<Id, SObject> oldMap) {
        if (!UserHelper.isIntegrationUser()) {
            for(Account acc : (List<Account>) records) {
                if(acc.IsPersonAccount && keyFieldsUpdated(acc, oldMap, personMapSettings) || keyFieldsCustomPersonAccount(acc, oldMap)) {
                    // todo-zz put if else into method maybe?
                    if(relatedSSVByAccount.get(acc.Id) != null) {
                        SSVLoader.updateSSV(acc, relatedSSVByAccount.get(acc.Id), personMapSettings, relatedContactCustomerAddress.get(acc.PersonContactId));
                        recordToUpdate(relatedSSVByAccount.get(acc.Id));
                    } else {
                        recordsToInsert.add(SSVLoader.createSSV(acc, personMapSettings, relatedContactCustomerAddress.get(acc.PersonContactId)));
                    }
                } else if(!acc.IsPersonAccount && keyFieldsUpdated(acc, oldMap, companyMapSettings) || keyFieldsCustomCompanyAccount(acc, oldMap)) {
                    if(relatedSSVByAccount.get(acc.Id) != null) {
                        SSVLoader.updateSSV(acc, relatedSSVByAccount.get(acc.Id), companyMapSettings, null);
                        recordToUpdate(relatedSSVByAccount.get(acc.Id));
                    } else {
                        recordsToInsert.add(SSVLoader.createSSV(acc, companyMapSettings, null));
                    }
                }
            }
        }
    }

    /**
     * Create new SSV records on insert of Accounts
     * @author Zi Zhang, Traction on Demand
     * @date   2016-02-29
     */
    @testVisible
    private void deleteSSVs() {
        if (!UserHelper.isIntegrationUser()) {
            recordsToDelete.addAll((List<SObject>) relatedSSVByAccount.values());
        }
    }

    /**
     * Returns true if any key fields have been changed.
     * @author Zi Zhang, Traction on Demand
     * @date   2016-02-29
     */
    @testVisible
    private Boolean keyFieldsUpdated(SObject obj, Map<Id, SObject> oldMap, List<SObject> mapSettings) {
        if(oldMap == null || mapSettings == null) {
            return false;
        }

        for(SObject mapField : mapSettings) {
            String fieldName = (String) mapField.get('Source_Field__c');
            // Ignore LastModifiedDate field mapping. Trigger should not fire when this field changes
            if(fieldName == 'LastModifiedDate') {
                continue;
            }

            if(FieldMapper.hasSObjectField(fieldName, obj)) {
                if(obj.get(fieldName) != oldMap.get(obj.Id).get(fieldName)) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * Key fields updated for company account not included in the custom setting
     * @author Zi Zhang, Traction on Demand
     * @date   2016-03-02
     */
    private Boolean keyFieldsCustomCompanyAccount(SObject obj, Map<Id, SObject> oldMap) {
        if(FieldMapper.hasSObjectField('BillingStreet', obj)) {
            if(obj.get('BillingStreet') != oldMap.get(obj.Id).get('BillingStreet')) {
                return true;
            } 
        }
        
        return false;
    }

    /**
     * Key fields updated for person account not included in the custom setting
     * @author Zi Zhang, Traction on Demand
     * @date   2016-03-02
     */
    private Boolean keyFieldsCustomPersonAccount(SObject obj, Map<Id, SObject> oldMap) {
        if(FieldMapper.hasSObjectField('PersonMailingStreet', obj)) {
            if(obj.get('PersonMailingStreet') != oldMap.get(obj.Id).get('PersonMailingStreet')) {
                return true;
            }
        }

        return false;
    }
}