objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Queue_Type__c</fullName>
        <label>Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accommodations</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Delivering on Delight</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
                <value>
                    <fullName>Final Mile Delivery Notification</fullName>
                </value>
                <value>
                    <fullName>Order Inquiries</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Reorders</fullName>
                </value>
                <value>
                    <fullName>Replacement Parts</fullName>
                </value>
                <value>
                    <fullName>Delight HQ</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_to_City__c</fullName>
        <label>Alternate City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Country__c</fullName>
        <label>Alternate Country</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Day_Phone__c</fullName>
        <label>Alternate Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Send_to_First_Name__c</fullName>
        <label>Alternate First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Last_Name__c</fullName>
        <label>Alternate Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_State__c</fullName>
        <label>Alternate State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Zip__c</fullName>
        <label>Alternate Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Accommodations</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Accommodations</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testMyTasks_CSC.cls
/*
 *  Methods to test MyTasks_CSC.cls and TaskTrigger.trigger
 *
 */
 
@isTest(SeeAllData=true)
private class testMyTasks_CSC {
    
    static testMethod void mtTest1() {
        
        // Initialize test date
        String orderNumber = 'mtT1O1';
        RH_Order__c order = PrepareData.createOrder(orderNumber);
        insert order;
        
        List<Case> cList = new List<Case>();
        cList.add(new Case(
            OwnerId = UserInfo.getUserId(),
            Request_Category__c = 'Gift Card',
           // Queue_Type__c = 'Accommodations',
            Send_to_First_Name__c = 'Bob',
            Send_to_Last_Name__c = 'Jones',
            Send_to_City__c = 'Santa Cruz',
            Send_to_State__c = 'CA',
            Send_to_Zip__c = '94500',
            Send_to_Country__c = 'USA',
            Send_to_Day_Phone__c = '555-555-5555',
            RH_Order_Number__c = order.Id)
        );
        insert cList;
        
        List<Task> tList = new List<Task>();
        Map<String, Schema.RecordTypeInfo> tRtMap = Schema.SObjectType.Task.getRecordTypeInfosByName();
        Task t1 = PrepareData.createTask(System.today().addDays(30), 'Not Started', 'Test Task', cList[0].Id, tRtMap.get('Standard').getRecordTypeId());
        t1.Contact_Type__c = 'Sold To';
        tList.add(t1);
        t1 = PrepareData.createTask(System.today().addDays(30), 'Not Started', 'Test Task', cList[0].Id, tRtMap.get('Standard').getRecordTypeId());
        t1.Contact_Type__c = 'Ship To 1';
        tList.add(t1);
        t1 = PrepareData.createTask(System.today().addDays(30), 'Not Started', 'Test Task', cList[0].Id, tRtMap.get('Standard').getRecordTypeId());
        t1.Contact_Type__c = 'Send To';
        tList.add(t1);
        t1 = PrepareData.createTask(System.today().addDays(30), 'Not Started', 'Test Task', cList[0].Id, tRtMap.get('Standard').getRecordTypeId());
        tList.add(t1);
        t1 = PrepareData.createTask(System.today().addDays(30), 'Not Started', 'Test Task', cList[0].Id, tRtMap.get('Standard').getRecordTypeId());
        tList.add(t1);
        
        insert tList;
        
        ApexPages.StandardController std = new ApexPages.StandardController(tList[0]);
        MyTasks_CSC ctl = new MyTasks_CSC(std);
        
        String disp = ctl.getdisplaySelected();
        system.assertEquals('All Open', disp);
        List<Task> tctlList;
        tctlList = ctl.gettaskList();
        ctl.setdisplaySelected('Overdue');
        tctlList = ctl.gettaskList();
        ctl.setdisplaySelected('Due Today');
        tctlList = ctl.gettaskList();
        ctl.setdisplaySelected('Tomorrow');
        tctlList = ctl.gettaskList();
        ctl.setdisplaySelected('Next 7 Days');
        tctlList = ctl.gettaskList();
        ctl.setdisplaySelected('This Month');
        tctlList = ctl.gettaskList();
        ctl.setdisplaySelected('All Completed');
        tctlList = ctl.gettaskList();
    }
    
     static testMethod void lacTest(){
        
        //Create test Account and insert
        Account testAccount = PrepareData.createAccount();
        insert testAccount;
        
        // Create test Contact and insert
        Contact testContact = PrepareData.createContact(testAccount.Id);
        insert testContact;
        
        // Create test Log A Call Task and insert
        
        Id testUser = UserInfo.getUserId();
        Id testRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('CSC InMoment Survey').getRecordTypeId();
        
        Task testLogACallTask = new Task(WhatId = testAccount.Id, WhoId = testContact.Id, InMoment_Interaction_Type__c = 'Inbound Call', InMoment_Who__c = 'Customer', InMoment_Reason__c = 'Gallery Inquiry', Status = 'Not Started', Priority = 'Medium', RecordTypeId = testRecordTypeId);
        
        insert testLogACallTask;
        // Validate
        
        testLogACallTask = [Select Id, InMoment_Survey_Status__c from Task where Id = : testLogACallTask.Id];
        System.assertEquals(testLogACallTask.InMoment_Survey_Status__c, 'Sent');
    }  
}