objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Issue__c</fullName>
        <label>Issue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Bath Hardware</fullName>
                </value>
                <value>
                    <fullName>Cabinet Hardware</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Consolidation</fullName>
                </value>
                <value>
                    <fullName>Freight Forwarding</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Lighting</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Damaged</fullName>
                </value>
                <value>
                    <fullName>Defective</fullName>
                </value>
                <value>
                    <fullName>Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Short Shipped</fullName>
                </value>
                <value>
                    <fullName>Textiles</fullName>
                </value>
                <value>
                    <fullName>WISMO</fullName>
                </value>
                <value>
                    <fullName>Wrong Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <businessProcess>Contract</businessProcess>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_Sharing_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Issue Sharing Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <label>Issue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Issue_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Delivery Provider</fullName>
                </value>
                <value>
                    <fullName>Assembled Incorrectly</fullName>
                </value>
                <value>
                    <fullName>Assembly - Components Misaligned/ Non-Functioning Hardware</fullName>
                </value>
                <value>
                    <fullName>Billing Issue</fullName>
                </value>
                <value>
                    <fullName>Blemishes</fullName>
                </value>
                <value>
                    <fullName>Bowing/ Warping</fullName>
                </value>
                <value>
                    <fullName>Broken Part</fullName>
                </value>
                <value>
                    <fullName>Bubbling/ Lifting</fullName>
                </value>
                <value>
                    <fullName>Bugs/ Vermin</fullName>
                </value>
                <value>
                    <fullName>Burning Smell</fullName>
                </value>
                <value>
                    <fullName>Cannot Contact HDL</fullName>
                </value>
                <value>
                    <fullName>Color Clash</fullName>
                </value>
                <value>
                    <fullName>Color Slightly off</fullName>
                </value>
                <value>
                    <fullName>Cracks/ Splits</fullName>
                </value>
                <value>
                    <fullName>Creases</fullName>
                </value>
                <value>
                    <fullName>Crushed Corner</fullName>
                </value>
                <value>
                    <fullName>CSC Service Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Preference - Product As Expected</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>Delivery Service Issue</fullName>
                </value>
                <value>
                    <fullName>Dings/ Dents/ Gouges</fullName>
                </value>
                <value>
                    <fullName>Dirt</fullName>
                </value>
                <value>
                    <fullName>Dirtied Home</fullName>
                </value>
                <value>
                    <fullName>Distressing</fullName>
                </value>
                <value>
                    <fullName>Does Not Fit</fullName>
                </value>
                <value>
                    <fullName>Does Not Turn On</fullName>
                </value>
                <value>
                    <fullName>Doors Do Not Open or Close Properly</fullName>
                </value>
                <value>
                    <fullName>Drawers Do Not Open or Close Properly</fullName>
                </value>
                <value>
                    <fullName>Duplicate Order</fullName>
                </value>
                <value>
                    <fullName>Element Does Not Align</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Number__c</fullName>
        <formula>CW_SKU_ID__r.Vendor_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Number</label>
        <type>Text</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISSUE-{0}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IssueService.cls
public without sharing class IssueService {
	
	public static void processIssueSharing(List<Issue__c> Issues, boolean isInsert){
		
		List<Issue__c> VendorIssues = new List<Issue__c>();
		Set<String> Vendors = new Set<String>();
		Map<String, String> VendorPublicGroupIdMap = new Map<String, String>();
		List<Issue__Share> IssueShares  = new List<Issue__Share>();
		
		
		
		for(Issue__c issue: Issues){
			
			System.debug('Is Insert: ' + isInsert + ' Issue Sharing Update: ' + issue.Issue_Sharing_Update__c);
			
			if(isInsert || !isInsert && issue.Issue_Sharing_Update__c){
				if(!String.isBlank(issue.Vendor_Number__c)){
					VendorIssues.add(issue);	
					Vendors.add(issue.Vendor_Number__c);
				
					System.debug('Vendor Issues: ' + VendorIssues);
					System.debug('Vendors:' + Vendors);
				}
			}
		}
		 
		for(Account a: [Select PublicGroupId__c, Vendor_Number__c from Account where Vendor_Number__c in :Vendors limit 1]){
			VendorPublicGroupIdMap.put(a.Vendor_Number__c, a.PublicGroupId__c);       	
		}
		            
		for(Issue__c issue :VendorIssues){  
				Issue__Share SupplierShare = new Issue__Share();          
			    SupplierShare.ParentId = issue.Id;
			    SupplierShare.UserOrGroupId = VendorPublicGroupIdMap.get(issue.Vendor_Number__c);
			    SupplierShare.AccessLevel = 'Read';  
			    SupplierShare.RowCause = Schema.Issue__Share.RowCause.Supplier_Access__c;
			    IssueShares.add(SupplierShare);
		}
		        
		if(!IssueShares.isEmpty()){
			Database.SaveResult[] issueShareInsertResult = Database.insert(IssueShares,false);
			for (Database.SaveResult sr : issueShareInsertResult) {
				if (sr.isSuccess()) {
			    	System.debug('Successfully inserted Share Record.Share ID: ' + sr.getId());
			    	System.debug('Sharing Record: ' + sr);
			    }else{
			   		// Operation failed, so get all errors                
			        for(Database.Error err : sr.getErrors()) {
			        	System.debug('The following error has occurred.');                    
			            System.debug(err.getStatusCode() + ': ' + err.getMessage());
			            System.debug('Issue fields that affected this error: ' + err.getFields());
			        }
		        }  
		    }  
		}
	}
	
	// Set the Status field on related Contract Cases to In Progress
	// - after insert
	public static void contractCaseStatus(List<Issue__c> newList) {
		Set<Id> cIds = new Set<Id>();
		
		for (Issue__c i :newList) {
			if (i.Case__c != null) {
				cIds.add(i.Case__c);
			}
		}
		
		if (!cIds.isEmpty()) {
			Map<String, Schema.RecordTypeInfo> caseRtByNameMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
			List<Case> caseList = new List<Case>();
			List<Case> caseUpList = new List<Case>();
			caseList = [select Id, Status from Case where Id in :cIds and RecordTypeId = :caseRtByNameMap.get('Contract').getRecordTypeId()];
			
			for (Case c :caseList) {
				if (c.Status == 'New') {
					c.Status = 'In Progress';
					caseUpList.add(c);
				}
			}
			
			if (!caseUpList.isEmpty()) {
				update caseUpList;
			}
		}
	}
}