objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand.

This field will be used as a primary match for Demand Tools duplicate matching/ stewardship review</description>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Information__c.object
<CustomObject>
    <description>This table contains one record per contact point. A contact point is defined as a method for contacting the customer (examples include: Email, Phone, Social Handles).</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipName>Contact_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <label>Contact Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <description>For phone contact information</description>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_to_Customer_Number__c</fullName>
        <description>CW Sold to Cust Number</description>
        <label>Sold To Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_View_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV process has run to determine whether this Order should be linked to an existing SSV or if a new SSV needs to be created.</description>
        <label>Source System View Sold To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Ship To should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Ship Tos are linked to the incorrect Business or Person Account record.</description>
        <label>Account Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <formula>Order__r.Account_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CW_Customer_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW Customer Ship To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Ship Tos (CW Customer Ship To)</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer_Number__c</fullName>
        <label>Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <description>This field specifies the match type to be processed by Salesforce duplicate match</description>
        <label>Match Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_View_CW_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System View CW Company</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Table__c</fullName>
        <label>Source Table</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerManager__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>runMDMTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>runMDMTriggers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>runTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>runTriggers</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerManager</label>
</CustomObject>

classes/SSVSyncServiceTest.cls
/**
 *  SSVSyncServiceTest.cls
 *  @description Apex Unit tests for source system view sync scheduler
 *  @author Ernesto Valdes, Traction On Demand
 */
@isTest
private class SSVSyncServiceTest {

    static String TEST_CUSTOMER_NUMBER = 'TESTNUMBER';

    @testSetup static void initExistingData() {
    	
    	PrepareData.populateCustomSettings();
    	
    	TestDataFactory.turnMdmFeatureFlagsOn();    	

        // create a new order
        RH_Order__c testOrder = TestDataFactory.createRhOrder(false);
        testOrder.Sold_To_Customer_Number__c = TEST_CUSTOMER_NUMBER;
        insert testOrder;

        // create ship to record under order
        Ship_To__c shipToSoldTo = TestDataFactory.createShipTo(false);
        shipToSoldTo.Ship_To_Customer_Number__c = '0';
        shipToSoldTo.Order__c = testOrder.Id;

        Ship_To__c shipToOther = TestDataFactory.createShipTo(false);
        shipToOther.Ship_To_Customer_Number__c = TEST_CUSTOMER_NUMBER;
        shipToOther.Order__c = testOrder.Id;

        insert new List<Ship_To__c>{shipToSoldTo, shipToOther};
    }

    @isTest static void testSyncToExistingDuplicateCompany() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Source_Table__c = 'Salesforce Account';
        insert testSSV1;

        // query created record
        List<Source_System_View__c> records = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id});

        // sync record
        SSVSyncService testSyncService = new SSVSyncService(records);
        testSyncService.sync(testSyncService.records);

        // create duplicate ssv record
        Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
        testSSV2.Source_Table__c = 'Salesforce Account';
        insert testSSV2;

        // set duplicate set id on ssv records
        testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        update new List<Source_System_View__c>{testSSV1,testSSV2};

        // sync duplicate record
        Test.startTest();
        //Reporter.startLogging();
        
        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        //Reporter.stopLogging();
        Test.stopTest();

        // verify that records were consolidated and spawned the same account
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        testSSV2 = SSVSelector.getSSVsById(new Set<Id>{testSSV2.Id})[0];
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV2.Account__c);
        system.assertEquals(testSSV1.Account__c, testSSV2.Account__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(false, testSpawnedAccount.IsPersonAccount);
        //system.assertEquals('TESTDUPLICATESET', testSpawnedAccount.Duplicate_Set_ID__c);
    }

    @isTest static void testSyncNewDuplicateCompanies() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Source_Table__c = 'Salesforce Account';
        insert testSSV1;

        // create duplicate ssv record
        Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
        testSSV2.Source_Table__c = 'Salesforce Account';
        insert testSSV2;

        // set duplicate set id on ssv records
        testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        update new List<Source_System_View__c>{testSSV1,testSSV2};

        // sync duplicate record
        Test.startTest();
        Reporter.startLogging();
        
        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        Reporter.stopLogging();
        Test.stopTest();

        // verify that records were consolidated and spawned the same account
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        testSSV2 = SSVSelector.getSSVsById(new Set<Id>{testSSV2.Id})[0];
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV2.Account__c);
        system.assertEquals(testSSV1.Account__c, testSSV2.Account__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(false, testSpawnedAccount.IsPersonAccount);
        system.assertEquals('TESTDUPLICATESET', testSpawnedAccount.Duplicate_Set_ID__c);

    }

    @isTest static void testSyncNewDuplicateContacts() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Source_Table__c = 'CW Customer';
        testSSV1.EXT_Source_System_Customer_ID__c = '1000';
        insert testSSV1;

        // create duplicate ssv record
        Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
        testSSV2.Source_Table__c = 'CW Customer';
        testSSV2.EXT_Source_System_Customer_ID__c = '1001';
        insert testSSV2;

        // set duplicate set id on ssv records
        testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATESET1';
        testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATESET1';
        update new List<Source_System_View__c>{testSSV1,testSSV2};

        // query created duplicate record
        List<Source_System_View__c> records = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id, testSSV2.Id});

        // query parent ssv records
        List<Source_System_View__c> parentRecords = SSVSelector.getSSVsById(
            new Set<Id>{records[0].Source_System_View_CW_Company__c, records[1].Source_System_View_CW_Company__c}
        );

        // set duplicate set id on parent ssv records
        parentRecords[0].Duplicate_Set_ID__c = 'TESTDUPLICATESET2';
        parentRecords[1].Duplicate_Set_ID__c = 'TESTDUPLICATESET2';
        update parentRecords;

        // sync duplicate record
        Test.startTest();
        //Reporter.startLogging();
        
        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        //Reporter.stopLogging();
        Test.stopTest();

        // verify that records were consolidated and spawned the same account and contact
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        testSSV2 = SSVSelector.getSSVsById(new Set<Id>{testSSV2.Id})[0];
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV2.Account__c);
        system.assertNotEquals(null, testSSV1.Contact__c);
        system.assertNotEquals(null, testSSV2.Contact__c);
        system.assertEquals(testSSV1.Account__c, testSSV2.Account__c);
        system.assertEquals(testSSV1.Contact__c, testSSV2.Contact__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(false, testSpawnedAccount.IsPersonAccount);
        system.assertEquals('TESTDUPLICATESET2', testSpawnedAccount.Duplicate_Set_ID__c);

        verifyContactInformation(testSSV1, 2);
        verifyAddress(testSSV1, 1);
    }

    @isTest static void testSyncToExistingDuplicateContact() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Source_Table__c = 'CW Customer';
        testSSV1.EXT_Source_System_Customer_ID__c = 'testSTEDC1000';
        insert testSSV1;

        // query created record
        List<Source_System_View__c> records1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id});

        // query parent ssv record
        List<Source_System_View__c> parentRecords1 = SSVSelector.getSSVsById(
            new Set<Id>{records1[0].Source_System_View_CW_Company__c}
        );

        // sync record and parent record
        records1.addAll(parentRecords1);
        SSVSyncService testSyncService = new SSVSyncService(records1);
        testSyncService.sync(testSyncService.records);

        // create duplicate ssv record
        Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
        testSSV2.Source_Table__c = 'CW Customer';
        testSSV2.EXT_Source_System_Customer_ID__c = 'testSTEDC1001';
        insert testSSV2;

        // set duplicate set id on ssv records
        testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATESET1';
        testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATESET1';
        update new List<Source_System_View__c>{testSSV1,testSSV2};

        // query created duplicate records
        List<Source_System_View__c> records2 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id, testSSV2.Id});

        // query created parent ssv records
        List<Source_System_View__c> parentRecords2 = SSVSelector.getSSVsById(
            new Set<Id>{records2[0].Source_System_View_CW_Company__c, records2[1].Source_System_View_CW_Company__c}
        );

        // set duplicate set id on parent ssv records
        parentRecords2[0].Duplicate_Set_ID__c = 'TESTDUPLICATESET2';
        parentRecords2[1].Duplicate_Set_ID__c = 'TESTDUPLICATESET2';
        update parentRecords2;

        // sync duplicate record
        Test.startTest();
        //Reporter.startLogging();
        
        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        //Reporter.stopLogging();
        Test.stopTest();

        // verify that records were consolidated and spawned the same account and contact
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        testSSV2 = SSVSelector.getSSVsById(new Set<Id>{testSSV2.Id})[0];
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV2.Account__c);
        system.assertNotEquals(null, testSSV1.Contact__c);
        system.assertNotEquals(null, testSSV2.Contact__c);
        system.assertEquals(testSSV1.Account__c, testSSV2.Account__c);
        system.assertEquals(testSSV1.Contact__c, testSSV2.Contact__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(false, testSpawnedAccount.IsPersonAccount);
        //system.assertEquals('TESTDUPLICATESET2', testSpawnedAccount.Duplicate_Set_ID__c);

        verifyContactInformation(testSSV1, 2);
        verifyAddress(testSSV1, 1);
    }

    @isTest static void testSyncToExistingDuplicatePerson() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Company_Name__c = null;
        insert testSSV1;

        // query created record
        List<Source_System_View__c> records = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id});

        // sync record
        SSVSyncService testSyncService = new SSVSyncService(records);
        testSyncService.sync(testSyncService.records);

        // create duplicate ssv record
        Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
        testSSV2.Company_Name__c = null;
        insert testSSV2;

        // set duplicate set id on ssv records
        testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        update new List<Source_System_View__c>{testSSV1,testSSV2};

        // sync duplicate record
        Test.startTest();
        //Reporter.startLogging();
        
        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        //Reporter.stopLogging();
        Test.stopTest();

        // verify that records were consolidated and spawned the same account
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        testSSV2 = SSVSelector.getSSVsById(new Set<Id>{testSSV2.Id})[0];
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV2.Account__c);
        system.assertEquals(testSSV1.Account__c, testSSV2.Account__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(true, testSpawnedAccount.IsPersonAccount);
        //system.assertEquals('TESTDUPLICATESET', testSpawnedAccount.Duplicate_Set_ID__c);

        verifyAddress(testSSV1, 1);
    }

    @isTest static void testSyncNewDuplicatePersons() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Company_Name__c = null;
        insert testSSV1;

        // create duplicate ssv record
        Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
        testSSV2.Company_Name__c = null;
        insert testSSV2;

        // set duplicate set id on ssv records
        testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATESET';
        update new List<Source_System_View__c>{testSSV1,testSSV2};

        // sync duplicate record
        Test.startTest();
        //Reporter.startLogging();
        
        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        //Reporter.stopLogging();
        Test.stopTest();

        // verify that records were consolidated and spawned the same account
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        testSSV2 = SSVSelector.getSSVsById(new Set<Id>{testSSV2.Id})[0];
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV2.Account__c);
        system.assertEquals(testSSV1.Account__c, testSSV2.Account__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(true, testSpawnedAccount.IsPersonAccount);
        system.assertEquals('TESTDUPLICATESET', testSpawnedAccount.Duplicate_Set_ID__c);

        verifyAddress(testSSV1, 1);
    }

    @isTest static void testSyncUniquePerson() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Company_Name__c = null;
        testSSV1.EXT_Source_System_Customer_ID__c = 'testSUP' + TEST_CUSTOMER_NUMBER + '1';
        insert testSSV1;

        // sync ssv record
        Test.startTest();
        //Reporter.startLogging();
    
		User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;

		TriggerManager__c triggerManager = new TriggerManager__c(SetupOwnerId = u.Id, runTriggers__c=true, runMDMTriggers__c=true);
		insert triggerManager;
		
        System.runAs(u) {      
        	SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));
        }
        
        //Reporter.stopLogging();
        Test.stopTest();

        // Get record
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(true, testSpawnedAccount.IsPersonAccount);
        system.assertNotEquals(null, testSSV1.Contact__c);
        system.assertNotEquals(null, testSSV1.Account__c);
        //system.assertNotEquals(null, testSSV1.Customer_Address__c);

        verifyContactInformation(testSSV1, 2);
        verifyAddress(testSSV1, 1);
        //verifyOrderLink(testSSV1);
    }

    @isTest static void testSyncUniqueContact() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Source_Table__c = 'CW Customer';
        testSSV1.EXT_Source_System_Customer_ID__c = 'testSUC' + TEST_CUSTOMER_NUMBER + '1';
        insert testSSV1;

        // sync ssv record and parent
        Test.startTest();
        //Reporter.startLogging();

        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        //SSVSyncService testSyncService = new SSVSyncService(SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id}));
        //testSyncService.sync(testSyncService.records);
        
        //Reporter.stopLogging();
        Test.stopTest();

        // verify that records spawned an account and contact
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        system.assertNotEquals(null, testSSV1.Contact__c);
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV1.Customer_Address__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c, Phone
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(false, testSpawnedAccount.IsPersonAccount);
        system.assertEquals('+1.(555)-555-0001', testSpawnedAccount.Phone);

        verifyContactInformation(testSSV1, 2);
        verifyAddress(testSSV1, 1);
        // verifyOrderLink(testSSV1);

    }

    @isTest static void testSyncUniqueContactZeroPhoneNumber() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Source_Table__c = 'CW Customer';
        testSSV1.Day_Phone__c = '0';
        testSSV1.EXT_Source_System_Customer_ID__c = 'testSUCZPN' + TEST_CUSTOMER_NUMBER + '1';
        insert testSSV1;

        // sync ssv record and parent
        Test.startTest();
        Reporter.startLogging();

        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));

        //SSVSyncService testSyncService = new SSVSyncService(SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id}));
        //testSyncService.sync(testSyncService.records);
        
        Reporter.stopLogging();
        Test.stopTest();

        // verify that records spawned an account and contact
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        system.assertNotEquals(null, testSSV1.Contact__c);
        system.assertNotEquals(null, testSSV1.Account__c);
        system.assertNotEquals(null, testSSV1.Customer_Address__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c, Phone
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(false, testSpawnedAccount.IsPersonAccount);
        system.assertEquals(null, testSpawnedAccount.Phone);

        verifyContactInformation(testSSV1, 1);
        verifyAddress(testSSV1, 1);
        // verifyOrderLink(testSSV1);

    }

    @isTest static void testSyncUniqueContactNoName() {

        // create new ssv record
        Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
        testSSV1.Last_Name__c = null;
        testSSV1.First_Name__c = null;
        testSSV1.Source_Table__c = 'CW Customer';
        testSSV1.EXT_Source_System_Customer_ID__c = 'testSUCNN' + TEST_CUSTOMER_NUMBER + '1';
        insert testSSV1;
    
        // sync ssv record and parent
        Test.startTest();
        //Reporter.startLogging();

        SSVSyncService.enqueueBatchSync(false, Datetime.now().addMinutes(1));
        
        //Reporter.stopLogging();
        Test.stopTest();

        // verify that records spawned an account but no contact (due to missing last name)
        testSSV1 = SSVSelector.getSSVsById(new Set<Id>{testSSV1.Id})[0];
        system.assertEquals('Contact', testSSV1.Match_Type__c);
        system.assertEquals(null, testSSV1.Contact__c);
        system.assertEquals(null, testSSV1.Customer_Address__c);
        system.assertNotEquals(null, testSSV1.Account__c);

        // Query created account and verify mappings
        Account testSpawnedAccount = [
            SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
            FROM Account
            WHERE Id = :testSSV1.Account__c
        ];
        system.assertEquals(false, testSpawnedAccount.IsPersonAccount);

        // verifyOrderLink(testSSV1);

    }
    
    private static void verifyAddress(Source_System_View__c ssv, Integer verifyCount) {

        // Verify address information was created
        List<Customer_Address__c> testCustomerAddresses = [
            SELECT Id, Address__c
            FROM Customer_Address__c
            WHERE Contact__c = :ssv.Contact__c
        ];
        system.assertNotEquals(true, testCustomerAddresses.isEmpty(), 'No customer address was created.');
        system.assertEquals(verifyCount, testCustomerAddresses.size());

        // Verify address was created
        List<Address__c> testAddress = [
            SELECT Id
            FROM Address__c
            WHERE Id = :testCustomerAddresses[0].Address__c
        ];
        system.assertNotEquals(true, testAddress.isEmpty(), 'No address was created.');
        system.assertEquals(verifyCount, testAddress.size());
    }

    private static void verifyContactInformation(Source_System_View__c ssv, Integer verifyCount) {

        // Verify contact information was created
        List<Contact_Information__c> testContactInfos = [
            SELECT Id, Is_Primary__c
            FROM Contact_Information__c
            WHERE Contact__c = :ssv.Contact__c
        ];

        system.assertNotEquals(true, testContactInfos.isEmpty(), 'No contact information was created.');
        system.assertEquals(verifyCount, testContactInfos.size());
/*
        for (Contact_Information__c ci : testContactInfos) {
            system.assertEquals(true, ci.Is_Primary__c);
        }
*/     
    }

    private static void verifyOrderLink(Source_System_View__c ssv) {

        RH_Order__c testOrder = [
            SELECT Source_System_View_Sold_To__c, Account_Sold_To__c, Contact_Sold_To__c
            FROM RH_Order__c
            WHERE Source_System_View_Sold_To__c = :ssv.Id
        ];
        system.assertEquals(ssv.Contact__c, testOrder.Contact_Sold_To__c);
        system.assertEquals(ssv.Account__c, testOrder.Account_Sold_To__c);

        List<Ship_To__c> testShipTo = [
            SELECT CW_Customer_Ship_To__c, Account_Ship_To__c, Contact_Ship_To__c
            FROM Ship_To__c
            WHERE CW_Customer_Ship_To__c = :ssv.Id
        ];
        system.assertNotEquals(true, testShipTo.isEmpty());
        for (Ship_To__c st : testShipTo) {
            system.assertEquals(ssv.Contact__c, st.Contact_Ship_To__c);
            system.assertEquals(ssv.Account__c, st.Account_Ship_To__c);
        }
    }
}