objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <inlineHelpText>For United States, enter US. 
For Canada, enter CA. 
Leave blank for all other countries.</inlineHelpText>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residence</fullName>
                </value>
                <value>
                    <fullName>Vacation Home</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Address__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manually populated as primary address for a customer.</description>
        <label>Is Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Principal_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AddressExtension.cls
public with sharing class AddressExtension {
	
	public Id addressContactId {get; private set;}
	public Address__c address {get; private set;}
	public Customer_Address__c customerAddress {get; private set;}
	
	public String errorMessage {get; private set;} 
	public Boolean hasErrors { get { return String.isNotBlank(this.errorMessage); } set; } 	
	
	public List<Customer_Address__c> contactCustomerAddresses {get; private set;}
    
    /* 
     * Constructors
     */
     
    public AddressExtension(Contact contact) {
    	this.initializeExtension(contact);
    }
    
    public AddressExtension(ApexPages.StandardController sc) {
    	 this.initializeExtension((Address__c) sc.getRecord());
    }
    
    /*
     * Initialize extension for editing an existing address
     */
    
    public void initializeExtension(Address__c existingAddress) {
    	this.address = this.getAddressRecord(existingAddress.Id).get(0);
    	this.errorMessage = '';
    	this.contactCustomerAddresses = getAddressContactRecords(this.address.Id);
    	
    	if (this.contactCustomerAddresses != null && this.contactCustomerAddresses.size() > 0) {
    		// default to first in list
			this.customerAddress = this.contactCustomerAddresses[0];
			this.addressContactId = this.customerAddress.Contact__c;    		
    	}
    }

    /*
     * Initialize extension for adding an address to a contact
     */
         
    public void initializeExtension(Contact contact) {
    	this.address = new Address__c();
    	this.customerAddress = new Customer_Address__c();
    	this.errorMessage = '';
    	
    	this.addressContactId = contact.Id;
    	this.contactCustomerAddresses = getContactAddressRecords(this.addressContactId);    	
    }
    
    /*
     * Buttons
     */
    
    public PageReference saveAndAddMore() {
        return insertNewAddress(true);
    }
        
    public PageReference insertNewAddress() { 
    	return this.insertNewAddress(false);  
    }
    
    public PageReference addressCancelAddNew() {
        PageReference pr = new PageReference('/' + this.addressContactId);
        pr.setRedirect(true);
        return pr;
    }  

	public PageReference updateExistingAddress() {
		return this.updateExistingAddress(false);
	}       
	
	public PageReference updateAndMore() {
		return this.updateExistingAddress(true);
	}
	
    public PageReference addressCancelUpdateExisting() {
    	String retURL = ApexPages.currentPage().getParameters().get('retURL');
        PageReference pr = new PageReference(retURL);
        pr.setRedirect(true);
        return pr;
    }  	
    
    /*
     * Insert a new address 
     */
	
    
    public PageReference insertNewAddress(Boolean stayOnPage) {   	
		return this.insertNewAddress(stayOnPage, this.address, this.customerAddress, this.addressContactId);    		
    }    
    
    private @testVisible PageReference insertNewAddress(Boolean stayOnPage, Address__c newAddress, Customer_Address__c customerAddress, Id contactId) {
    	
		this.errorMessage = null;
		PageReference pr = null;
		                
    	try {     	
			// insert the address
			database.insert(newAddress);
			// insert the customer address
			customerAddress.Address__c = newAddress.Id;	
			customerAddress.Contact__c = contactId;    	
			database.insert(customerAddress);		
     	} catch(DMLException e) {
            errorMessage = e.getMessage();
        }    	

        if (!this.hasErrors && !stayOnPage) {
	 		pr = new PageReference('/' + this.addressContactId);
			pr.setRedirect(true);        	
        } else {
    		this.address = new Address__c();
    		this.customerAddress = new Customer_Address__c();         	
        }        
        
        return pr;		
    }   
    
    /* 
     * Update an existing address
     */
    
    public PageReference updateExistingAddress(Boolean stayOnPage) {
		return this.updateExistingAddress(stayOnPage, this.address, this.contactCustomerAddresses);   		
    }
    
    private @testVisible PageReference updateExistingAddress(Boolean stayOnPage, Address__c updatedAddress, List<Customer_Address__c> contactAddresses) {
    	
    	this.errorMessage = null;
    	PageReference pr = null;
    	
    	try {
    		    	    	    	
			// update the address    		
			database.update(updatedAddress);		
			// update the related customer addresses
			if (contactAddresses != null && contactAddresses.size() > 0) {
				database.update(contactAddresses);
			}   
		 		   			    		
    	} catch(DMLException e) {
            errorMessage = e.getMessage();
        }  
        
        if (!this.hasErrors && !stayOnPage) {
	        pr = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
			pr.setRedirect(true);        	
        }        
        
    	return pr; 
    }
    
    
   /*
    * Get list of all addresses associated with this contact for the page
    */
    
    private @testVisible List<Customer_Address__c> getContactAddressRecords(Id contactId) {
    	return [
    		SELECT 	Is_Inactive__c, Is_Principal_Address__c, Address_Type__c, Address__c, 
    				Address__r.Name, Address__r.Address_1__c, Address__r.Address_2__c, Address__r.City__c, Address__r.State__c, Address__r.Zip__c, Address__r.Country__c, Address__r.Country_Code__c     
    		FROM Customer_Address__c 
    		WHERE Contact__c =:contactId
    	];    	
    }
    
    /*
     * Get all the contacts this address record is associated with.
     * Includes those contact mailing details for comparison
     * If the customer address is set to primary, the details should always match
     */
    
    private @testVisible List<Customer_Address__c> getAddressContactRecords(Id addressId) {
    	return [
    		SELECT 	Is_Inactive__c, 
		    		Is_Principal_Address__c, 
		    		Address_Type__c,  
    		
    				Contact__c,     		
    				Contact__r.FirstName, 
    				Contact__r.LastName,   
    				
                    Contact__r.MailingStreet,
	                Contact__r.MailingCity,
	                Contact__r.MailingCountry,
	                Contact__r.MailingState,
	                Contact__r.MailingPostalCode,   
	                Contact__r.AccountId,
	                Contact__r.Account.IsPersonAccount,         
	            
	            	Address__c,
	                Address__r.Address_1__c,
	                Address__r.City__c,
	                Address__r.Country_Code__c,
	                Address__r.State__c,
	                Address__r.Zip__c
	                
    		FROM Customer_Address__c 
    		WHERE Address__c =:addressId
    	];    	
    }
    
    /* 
     * Get the details for the address being edited
     */
    
    private @testVisible List<Address__c> getAddressRecord(Id addressId) {
    	return [
    		SELECT 	Name, Address_1__c, Address_2__c, City__c, State__c, Zip__c, Country__c, Country_Code__c        
    		FROM Address__c 
    		WHERE Id =:addressId
    	];    	
    	
    }    
    
    
    
}