objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Order.</description>
        <label>Customer Address Sold To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System_View_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV process has run to determine whether this Order should be linked to an existing SSV or if a new SSV needs to be created.</description>
        <label>Source System View Sold To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Ship To should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Ship Tos are linked to the incorrect Business or Person Account record.</description>
        <label>Account Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <formula>Order__r.Account_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CW_Customer_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW Customer Ship To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Ship Tos (CW Customer Ship To)</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Ship To.</description>
        <label>Customer Address Ship To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer_Number__c</fullName>
        <label>Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Ship_TosTest.cls
@isTest
private class Ship_TosTest {

    static String CUST_ID = '123456789';
    static Integer NUM_SHIP_TOS = 10;

    static User nonIntegrationUser {
        get {
            if (nonIntegrationUser == null) {
                nonIntegrationUser = TestDataFactory.createUser();
                nonIntegrationUser.Single_View_of_Customer_Process_User__c = false;
            }
            return nonIntegrationUser;
        } set;
    }

    @testSetup
    static void setup() {
    	
    	PrepareData.populateCustomSettings();
    	
    	TestDataFactory.turnMdmFeatureFlagsOn();    	    	
        Account a = TestDataFactory.createAccount(true);
        Contact c = TestDataFactory.createContact(true);
        Customer_Address__c ca = TestDataFactory.createCustomerAddress(true);
        Source_System_View__c ssv = TestDataFactory.createSSV(false);
        ssv.EXT_Source_System_Customer_ID__c = CUST_ID;
        ssv.Account__c = a.Id;
        ssv.Contact__c = c.Id;
        ssv.Customer_Address__c = ca.Id;
        insert ssv;

        a = TestDataFactory.createAccount(true);
        c = TestDataFactory.createContact(true);
        ca = TestDataFactory.createCustomerAddress(true);
        RH_Order__c order = TestDataFactory.createRhOrder(false);
        order.Account_Sold_To__c = a.Id;
        order.Contact_Sold_To__c = c.Id;
        order.Customer_Address_Sold_To__c = ca.Id;
        insert order;
    }
    
    // Test setting CW_Customer_Ship_To__c & other lookups by non-zero Ship_To_Customer_Number__c on insert
    @isTest
    static void test_setSsvLookup_insert_non_zero() {
        RH_Order__c order = [
            SELECT Account_Sold_To__c,
                Contact_Sold_To__c,
                Customer_Address_Sold_To__c
            FROM RH_Order__c
        ];

        Source_System_View__c ssv = [
            SELECT Account__c,
                Contact__c,
                Customer_Address__c
            FROM Source_System_View__c
            WHERE EXT_Source_System_Customer_ID__c = :CUST_ID
        ];

        // Create children
        System.debug('creating shipTos');
        List<Ship_To__c> shipTos = TestDataFactory.createShipTos(NUM_SHIP_TOS, false);
        for (Ship_To__c shipTo : shipTos) {
            shipTo.Order__c = order.Id;
            shipTo.Ship_To_Customer_Number__c = CUST_ID;
        }

        System.runAs(nonIntegrationUser) { 
            insert shipTos;
        }
        System.debug('created shipTos');

        // Assert insert is mirrored to SSV
        List<Ship_To__c> children = [
            SELECT CW_Customer_Ship_To__c,
                Account_Ship_To__c, 
                Contact_Ship_To__c, 
                Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Id IN :shipTos
        ];
        for (Ship_To__c child : children) {
            System.assertEquals(ssv.Id, child.CW_Customer_Ship_To__c);
            System.assertEquals(ssv.Account__c, child.Account_Ship_To__c);
            System.assertEquals(ssv.Contact__c, child.Contact_Ship_To__c);
            System.assertEquals(ssv.Customer_Address__c, child.Customer_Address_Ship_To__c);
        }
    }

    // Test setting CW_Customer_Ship_To__c & other lookups by non-zero Ship_To_Customer_Number__c on update
    @isTest
    static void test_setSsvLookup_update_non_zero() {
        RH_Order__c order = [
            SELECT Account_Sold_To__c,
                Contact_Sold_To__c,
                Customer_Address_Sold_To__c
            FROM RH_Order__c
        ];

        Source_System_View__c ssv = [
            SELECT Account__c,
                Contact__c,
                Customer_Address__c
            FROM Source_System_View__c
            WHERE EXT_Source_System_Customer_ID__c = :CUST_ID
        ];

        // Create children
        System.debug('creating shipTos');
        List<Ship_To__c> shipTos = TestDataFactory.createShipTos(NUM_SHIP_TOS, false);
        for (Ship_To__c shipTo : shipTos) {
            shipTo.Order__c = order.Id;
        }

        System.runAs(nonIntegrationUser) { 
            insert shipTos;
        }
        System.debug('created shipTos');

        // Assert update is not mirrored to SSV
        List<Ship_To__c> children = [
            SELECT CW_Customer_Ship_To__c,
                Account_Ship_To__c, 
                Contact_Ship_To__c, 
                Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Id IN :shipTos
        ];
        for (Ship_To__c child : children) {
            System.assertNotEquals(ssv.Id, child.CW_Customer_Ship_To__c);
            System.assertNotEquals(ssv.Account__c, child.Account_Ship_To__c);
            System.assertNotEquals(ssv.Contact__c, child.Contact_Ship_To__c);
            System.assertNotEquals(ssv.Customer_Address__c, child.Customer_Address_Ship_To__c);
        }

        for (Ship_To__c shipTo : shipTos) {
            shipTo.Ship_To_Customer_Number__c = CUST_ID;
        }

        System.runAs(nonIntegrationUser) { 
            update shipTos;
        }

        // Assert update is mirrored to SSV
        children = [
            SELECT CW_Customer_Ship_To__c,
                Account_Ship_To__c, 
                Contact_Ship_To__c, 
                Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Id IN :shipTos
        ];
        for (Ship_To__c child : children) {
            System.assertEquals(ssv.Id, child.CW_Customer_Ship_To__c);
            System.assertEquals(ssv.Account__c, child.Account_Ship_To__c);
            System.assertEquals(ssv.Contact__c, child.Contact_Ship_To__c);
            System.assertEquals(ssv.Customer_Address__c, child.Customer_Address_Ship_To__c);
        }
    }

    // Test setting CW_Customer_Ship_To__c & other lookups by zero Ship_To_Customer_Number__c on insert
    @isTest
    static void test_setSsvLookup_insert_zero() {
        RH_Order__c order = [
            SELECT Source_System_View_Sold_To__c, 
                Account_Sold_To__c,
                Contact_Sold_To__c,
                Customer_Address_Sold_To__c
            FROM RH_Order__c
        ];

        Source_System_View__c ssv = [
            SELECT Account__c,
                Contact__c,
                Customer_Address__c
            FROM Source_System_View__c
            WHERE EXT_Source_System_Customer_ID__c = :CUST_ID
        ];

        // Create children
        System.debug('creating shipTos');
        List<Ship_To__c> shipTos = TestDataFactory.createShipTos(NUM_SHIP_TOS, false);
        for (Ship_To__c shipTo : shipTos) {
            shipTo.Order__c = order.Id;
            shipTo.Ship_To_Customer_Number__c = '0';
        }

        System.runAs(nonIntegrationUser) { 
            insert shipTos;
        }
        System.debug('created shipTos');

        // Assert update is mirrored to order
        List<Ship_To__c> children = [
            SELECT CW_Customer_Ship_To__c,
                Account_Ship_To__c, 
                Contact_Ship_To__c, 
                Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Id IN :shipTos
        ];
        for (Ship_To__c child : children) {
            System.assertEquals(order.Source_System_View_Sold_To__c, child.CW_Customer_Ship_To__c);
            System.assertEquals(order.Account_Sold_To__c, child.Account_Ship_To__c);
            System.assertEquals(order.Contact_Sold_To__c, child.Contact_Ship_To__c);
            System.assertEquals(order.Customer_Address_Sold_To__c, child.Customer_Address_Ship_To__c);
        }
    }

    // Test setting CW_Customer_Ship_To__c & other lookups by zero Ship_To_Customer_Number__c on update
    @isTest
    static void test_setSsvLookup_update_zero() {
        RH_Order__c order = [
            SELECT Source_System_View_Sold_To__c,
                Account_Sold_To__c,
                Contact_Sold_To__c,
                Customer_Address_Sold_To__c
            FROM RH_Order__c
        ];

        Source_System_View__c ssv = [
            SELECT Account__c,
                Contact__c,
                Customer_Address__c
            FROM Source_System_View__c
            WHERE EXT_Source_System_Customer_ID__c = :CUST_ID
        ];

        // Create children
        System.debug('creating shipTos');
        List<Ship_To__c> shipTos = TestDataFactory.createShipTos(NUM_SHIP_TOS, false);
        for (Ship_To__c shipTo : shipTos) {
            shipTo.Order__c = order.Id;
        }

        System.runAs(nonIntegrationUser) { 
            insert shipTos;
        }
        System.debug('created shipTos');

        // Assert update is not mirrored to order
        List<Ship_To__c> children = [
            SELECT CW_Customer_Ship_To__c,
                Account_Ship_To__c, 
                Contact_Ship_To__c, 
                Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Id IN :shipTos
        ];
        for (Ship_To__c child : children) {
            System.assertNotEquals(order.Account_Sold_To__c, child.Account_Ship_To__c);
            System.assertNotEquals(order.Contact_Sold_To__c, child.Contact_Ship_To__c);
            System.assertNotEquals(order.Customer_Address_Sold_To__c, child.Customer_Address_Ship_To__c);
        }

        for (Ship_To__c shipTo : shipTos) {
            shipTo.Ship_To_Customer_Number__c = '0';
        }

        System.runAs(nonIntegrationUser) { 
            update shipTos;
        }

        // Assert update is mirrored to order
        children = [
            SELECT CW_Customer_Ship_To__c,
                Account_Ship_To__c, 
                Contact_Ship_To__c, 
                Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Id IN :shipTos
        ];
        for (Ship_To__c child : children) {
            System.assertEquals(order.Source_System_View_Sold_To__c, child.CW_Customer_Ship_To__c);
            System.assertEquals(order.Account_Sold_To__c, child.Account_Ship_To__c);
            System.assertEquals(order.Contact_Sold_To__c, child.Contact_Ship_To__c);
            System.assertEquals(order.Customer_Address_Sold_To__c, child.Customer_Address_Ship_To__c);
        }
    }
}