objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key_Hash__c</fullName>
        <externalId>true</externalId>
        <label>Address Match Key Hash</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key__c</fullName>
        <label>Address Match Key</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Phone_Extension__c</fullName>
        <inlineHelpText>Enter the extension for the primary phone number, if any.  Enter only dial numbers (exclude &quot;x&quot; or &quot;ext&quot;</inlineHelpText>
        <label>Phone Extension</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Information__c.object
<CustomObject>
    <description>This table contains one record per contact point. A contact point is defined as a method for contacting the customer (examples include: Email, Phone, Social Handles).</description>
    <fields>
        <fullName>Contact_Information_Match_Key_Hash__c</fullName>
        <description>This is a hashed version of the Contact Information Match Key (Contact ID + Contact Info Medium + (Email or Phone)</description>
        <externalId>true</externalId>
        <label>Contact Information Match Key Hash</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Information_Match_Key__c</fullName>
        <label>Contact Information Match Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Information_Medium__c</fullName>
        <label>Contact Information Medium</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipName>Contact_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines whether or not this Contact Information record is Active</description>
        <label>Is Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Extension__c</fullName>
        <label>Phone Extension</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <label>Contact Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>For email contact information</description>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <description>For phone contact information</description>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residence</fullName>
                </value>
                <value>
                    <fullName>Vacation Home</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Address__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manually populated as primary address for a customer.</description>
        <label>Is Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Principal_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CusContactInfoAndCusAddress.cls
/* Helper class which is called 
   to insert Customer Contact information and customerAddress Automatically
   when a person Account is inserted manually*/    



public class CusContactInfoAndCusAddress {
    
  public static Contact_Information__c primaryPhone, primaryEmail;
    
    public static List<Contact_Information__c> contactInfos {
        get {
            if (contactInfos == null) contactInfos = new List<Contact_Information__c>();
            return contactInfos;
        }
        set;
    }
    
    public static set<Address__c> AddrSet=new Set<Address__c>();
    
        private static Map<String, Schema.RecordTypeInfo> contactInfoRecordTypes {
        get {
            if (contactInfoRecordTypes == null) {
                contactInfoRecordTypes = Schema.SObjectType.Contact_Information__c.getRecordTypeInfosByName();
            }
            return contactInfoRecordTypes;
        }
        set;
    }
    
        public static  void CusContactInfoAndCusAddress(Account acc,Boolean isPrimary) {
        	
        	List<Account> accList=[Select Id,PersonContactId,PersonMailingStreet,BillingCity,PersonMailingCity,PersonMailingPostalCode,PersonMailingState,PersonMailingCountry
        						   from Account where Id=:acc.Id];
        	
        	String phone=acc.Phone;
		
			Contact_Information__c newContactInfo;
			
        
        	if (acc.PersonEmail != null) {
            // Check if primary email exists
            if (primaryEmail == null) {
                newContactInfo = createEmailContactInformation(acc.PersonContactId	
                , acc.PersonEmail, true);
                primaryEmail = newContactInfo;
            } else {
                newContactInfo = createEmailContactInformation(acc.PersonContactId	
                , acc.PersonEmail, isPrimary);     
            }

            if (newContactInfo != null) {
                contactInfos.add(newContactInfo);
                system.debug('Size of contact Info is' + contactInfos.size() );
            }
        }
        // Check for Phone information
        
        if(acc.Phone!=null){
      if (primaryPhone == null) {
				// then make current phone primary
				newContactInfo = createPhoneContactInformation(acc,acc.PersonContactId, phone, true);
				primaryPhone = newContactInfo;
			} else {
				newContactInfo = createPhoneContactInformation(acc,acc.PersonContactId, phone, isPrimary);
			}
			
			if (newContactInfo != null) {
				contactInfos.add(newContactInfo);
			}
			if(contactInfos.size()>0){
			insert contactInfos;
			
			}
        
      //return  newContactInfo;
      }
      
     // Billing information is not null
      IF(acc.PersonMailingStreet!=null){
    	createAddress(accList[0].PersonContactId,accList[0].PersonMailingStreet, accList[0].PersonMailingCity,accList[0].PersonMailingPostalCode,accList[0].PersonMailingState,accList[0].PersonMailingCountry);
      }
      
  }
    
    public static Contact_Information__c createEmailContactInformation( Id contactId,
                                                                    String email, 
                                                                    Boolean isPrimary) {
                                                                        
            Contact_Information__c newContactInformation = new Contact_Information__c(
                Contact__c = contactId,
                Is_Primary__c = isPrimary,
                 Contact_Information_Medium__c = 'Email',
                Name = email,
                Email__c = email
            );

        // Set record type
        newContactInformation.RecordTypeId = contactInfoRecordTypes.get('Email').getRecordTypeId();

        // Set contact information match keys
        newContactInformation.Contact_Information_Match_Key__c = 
            SSVCleaner.buildContactInfoMatchKey(newContactInformation);
        newContactInformation.Contact_Information_Match_Key_Hash__c = 
            SSVCleaner.encodeHash(newContactInformation.Contact_Information_Match_Key__c);
            
            return newContactInformation;                                                           
                                                                        
          }
          
          //Method for creating PhoneContactInformation...
          
        public static Contact_Information__c createPhoneContactInformation(	Account acc,Id contactId,
																	String phone,
																	Boolean isPrimary) {
				String PhExtension=null;														
				if(acc.Phone_Extension__c!=null){
				PhExtension=acc.Phone_Extension__c;
					}
		// Build contact information record
		Contact_Information__c newContactInformation_Phone = new Contact_Information__c(
				Contact__c = contactId,
				Is_Primary__c = isPrimary,
				Name = phone,
				Phone_Extension__c=PhExtension,
				Contact_Information_Medium__c = 'Phone',
				Phone__c = phone
				
			);
		// Set record type
		newContactInformation_Phone.RecordTypeId = contactInfoRecordTypes.get('Phone').getRecordTypeId();
		// Set contact information match keys
		newContactInformation_Phone.Contact_Information_Match_Key__c = 
			SSVCleaner.buildContactInfoMatchKey(newContactInformation_Phone);
		newContactInformation_Phone.Contact_Information_Match_Key_Hash__c = 
			SSVCleaner.encodeHash(newContactInformation_Phone.Contact_Information_Match_Key__c);

		return newContactInformation_Phone;
	}   
	
	// Method for creating customer Address
	
	
	public static Address__c createAddress(Id PersonContactId,String Address1,String City,String Zip, String State,String country) {
	
	Id ContactId=PersonContactId;
	
	// check for address matchkey exists in the address table... else... if it already exists... associate with customer address
			List<Address__c> AddInsertList=new List<Address__c>();
			List<Address__c> NewAddrInsertList=new List<Address__c>();
			List<String> addressFields = new List<String>();
		if (address1 != null) addressFields.add(address1.trim());
		if (city != null) addressFields.add(city.trim());
		if (state != null) addressFields.add(state.trim());
		if (zip != null) addressFields.add(zip.trim());
		if (country!= null) addressFields.add(country.trim());

		String addressMatchKey = String.join(addressFields, '');
		addressMatchKey = addressMatchKey.toUpperCase().replaceAll('[+-. ()]', '');
		
		List<Address__c> AddressList=new List<Address__c>(/*[Select Address_Match_Key__c from Address__c]*/);
		
		Set<String> AddressMatchKeySet=new Set<String>();
		
		for(Address__C addr:AddressList){
			
			AddressMatchKeySet.add(addr.Address_Match_Key__c);
			AddrSet.add(addr);
			
		}
		
		if(!AddressMatchKeySet.contains(addressMatchKey)){
			/*pick the existing address */
			/* pass the address to be added to customer address*/
			// CreateCusAddress(AddrSet);
			
			for(Address__C addr:AddrSet){
				CreateCusAddress(ContactId,Addr);
				
			}
		}


		else {
			/*call method to create addresses*/
			Address__c newAddr= new Address__c(
			Address_1__c=Address1,
			Address_2__c='',
			City__c=City,
			Zip__c=Zip,
			State__c=State,
			Country__c=country
			);
			/*add this to a different list*/		
		newAddr.Address_Match_Key__c = SSVCleaner.buildAddressMatchKey(newAddr);
		newAddr.Address_Match_Key_Hash__c = SSVCleaner.encodeHash(newAddr.Address_Match_Key__c);
			
			
			if(newAddr!=null){
				AddInsertList.add(newAddr);
				
			}
			
			insert AddInsertList;
			
			// Iterate over the inserted address list
			if(AddInsertList.size()>0){
			for(Address__c addr:AddInsertList){
				/*Pass this method to customer address*/
				CusAddressForNewAddresses(ContactId,addr);
			}
				
			}
		}
// Build address
		return null;
	}
	
	
	public static void CreateCusAddress(Id contactId,Address__c addr){
		
		List<Customer_Address__c> CusAddrList=new List<Customer_Address__c>();
		
		Customer_Address__c CusAddr=new Customer_Address__c(
			Contact__c = contactId,
			Address__c = addr.Id,
			Is_Principal_Address__c =true,
			Is_Inactive__c = false,
			Address_Type__c = 'Residence'
		);
		
		if(CusAddr!=null){
		CusAddrList.add(CusAddr);
			
		}
		
		insert CusAddrList;
}
	
	// Create CusAddressForNewAddresses
	
	public static void CusAddressForNewAddresses(Id ContactId,Address__c addr){
		List<Customer_Address__c> CusNewAddressList=new List<Customer_Address__c>();
		Customer_Address__c CusAddr=new Customer_Address__c(Contact__c = contactId,
			Address__c = addr.Id,
			Is_Principal_Address__c =true,
			Is_Inactive__c = false,
			Address_Type__c = 'Residence');
			
			if(CusAddr!=null){
			CusNewAddressList.add(CusAddr);
			 }
			 insert CusNewAddressList;
		}
}