objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand.

This field will be used as a primary match for Demand Tools duplicate matching/ stewardship review</description>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unauthorized_Contact_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this field if the Contact is no longer an approved Contact on this Account</inlineHelpText>
        <label>Unauthorized Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Add field history tracking</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Add field history tracking</description>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SSVCustomerTest.cls
@isTest
public with sharing class SSVCustomerTest {
    
    public static testMethod void testCreateAccountContact() {
    	
		RecordType tradeAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Trade' and SObjectType = 'Account'];
		RecordType contractAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Contract' and SObjectType = 'Account'];
		RecordType unclassifiedAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Unclassified Business Account' and SObjectType = 'Account'];
		
		Source_System_View__c ssv = new Source_System_View__c(
			First_Name__c = 'paul',
			Last_Name__c = 'hemmings',
			Address_1__c = null,
			City__c = '',
			State__c = '',
			Zip__c = '',
			Country__c = '',
			Email__c = '',
			Duplicate_Set_ID__c = ''	
		); 
		
		Account account = new Account(
			Name = 'test Account'
		);
		
		database.insert(ssv);
		database.insert(account);
		
		Map<String, Contact> testContacts = new Map<String, Contact>();
		testContacts.put('Trade', SSVCustomer.createContactAtAccount(ssv, account.Id, tradeAccountRecordType.Id));
		testContacts.put('Contract', SSVCustomer.createContactAtAccount(ssv, account.Id, contractAccountRecordType.Id));
		testContacts.put('Unclassified Business Account', SSVCustomer.createContactAtAccount(ssv, account.Id, unclassifiedAccountRecordType.Id));
		
		
		System.assertEquals(true, testContacts.get('Trade').Unauthorized_Contact_Checkbox__c);
		System.assertEquals(true, testContacts.get('Contract').Unauthorized_Contact_Checkbox__c);	
		System.assertEquals(false, testContacts.get('Unclassified Business Account').Unauthorized_Contact_Checkbox__c);							
	}
	
}