objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact_Address__c.object
<CustomObject>
    <label>Contact Address</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Contact Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Sold To</label>
        <referenceTo>Contact_Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <description>CW Sold to Address Line 1</description>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address_2__c</fullName>
        <description>CW Sold to Address Line 2</description>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_City__c</fullName>
        <description>CW Sold to City</description>
        <label>Sold To City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Company__c</fullName>
        <label>Sold To Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <description>CW Sold to Country</description>
        <label>Sold To Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Customer_Number__c</fullName>
        <description>CW Sold to Cust Number</description>
        <label>Sold To Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <description>CW Sold to Daytime Phone</description>
        <label>Sold To Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <description>CW Sold to State</description>
        <label>Sold To State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <description>CW Sold to Zip</description>
        <label>Sold To Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactAddressMergeServiceTest.cls
@isTest
public with sharing class ContactAddressMergeServiceTest {
    
	public static testMethod void testGettingPersonAccountAndContactRecordTypes() {
		
		system.assertNotEquals(null, ContactAddressMergeService.getRecordTypeByName(ContactAddressMergeService.ACCOUNTS_RECORD_TYPE_NAMES, 'RH End Customer'));
		
		
	}
	
	public static testMethod void testCreatingOrderPersonAccount() {
				
    	PrepareData.populateCustomSettings();
    	
    	// GIVEN - an ssv user
    	
		User su = TestDataFactory.createUser();
        su.Single_View_of_Customer_Process_User__c = true;   
        		
		// given (a test order)
		
		List<Rh_Order__c> testOrders = new List<Rh_Order__c>();
		testOrders.add(new Rh_Order__c(
			CONTACT_SOLD_TO__C = null,
			SOLD_TO_ADDRESS_1__C = 'address 1',
			SOLD_TO_ADDRESS_2__C = 'address 2',
			SOLD_TO_CITY__C = 'city',
			SOLD_TO_STATE__C = 'CA',
			SOLD_TO_ZIP__C = '94949',	
			SOLD_TO_COUNTRY__C = 'US',	
			SOLD_TO_CUSTOMER_NUMBER__C = '1111111',
			SOLD_TO_DAY_PHONE__C = '9191231234',
			SOLD_TO_EMAIL__C = 'paul@paul.com',
			SOLD_TO_FIRST_NAME__C = 'paul',
			SOLD_TO_LAST_NAME__C = 'hemmings'		
		));
		testOrders.add(new Rh_Order__c(
			CONTACT_SOLD_TO__C = null,
			Sold_to_Company__c = 'pauls test company',			
			SOLD_TO_ADDRESS_1__C = 'address 1',
			SOLD_TO_ADDRESS_2__C = 'address 2',
			SOLD_TO_CITY__C = 'city',
			SOLD_TO_STATE__C = 'CA',
			SOLD_TO_ZIP__C = '94949',	
			SOLD_TO_COUNTRY__C = 'US',	
			SOLD_TO_CUSTOMER_NUMBER__C = '1111111',
			SOLD_TO_DAY_PHONE__C = '9191231234',
			SOLD_TO_EMAIL__C = 'paul@paul.com',
			SOLD_TO_FIRST_NAME__C = 'paul',
			SOLD_TO_LAST_NAME__C = 'hemmings'		
		));		
		System.runAs(su) {
			database.insert(testOrders);
		}
						
		// when (create customer for order)
		
		database.update(ContactAddressMergeService.buildCustomerForOrders(testOrders));
		
		// then (get the processed orders)
		
		List<Rh_Order__c> processedOrders = [SELECT ID, CONTACT_SOLD_TO__C, ACCOUNT_SOLD_TO__C FROM Rh_Order__c];	
		List<Account> spawnedAccounts = [SELECT ID FROM Account];
		List<Contact> spawnedContacts = [SELECT ID FROM Contact];
		List<Contact_Address__c> spawnedContactAddresses = [SELECT ID FROM Contact_Address__c];
			
		// then (test order now has link to account and contact)

		system.assertNotEquals(null, spawnedAccounts);
		system.assertNotEquals(null, spawnedContacts);
		// system.assertNotEquals(null, spawnedContactAddresses);
		
		system.assertEquals(2, spawnedAccounts.size());
		system.assertEquals(2, spawnedContacts.size());
		// system.assertEquals(2, spawnedContactAddresses.size());
		
		for (Rh_Order__c processedOrder : processedOrders) {
			system.assertNotEquals(null, processedOrder.ACCOUNT_SOLD_TO__C);
			system.assertNotEquals(null, processedOrder.CONTACT_SOLD_TO__C);
			// system.assertNotEquals(null, processedOrder.ADDRESS_SOLD_TO__C);
		}		
	}
    
}