objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <label>Application Settings</label>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CaseLineToOrderLineMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting contains field mappings for Case Line Item and Order Line Item</description>
    <label>CaseLineToOrderLineMapping</label>
</CustomObject>

objects/CasetoOrderFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CasetoOrderFieldMapping</label>
</CustomObject>

objects/Delayed_Order_Rule__c.object
<CustomObject>
    <label>Delayed Order Rule</label>
    <nameField>
        <displayFormat>DOR-{0}</displayFormat>
        <label>Delayed Order Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delayed Order Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Groups</label>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Ship_To__c</fullName>
        <label>Ship To Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <description>to view hidden fields</description>
        <label>Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>All Users but Admin</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Brand__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping table - maps the value in the Source Code field of the Order (contains the 2 character Division code) to the Restoration Hardware brand to use for things like the Billing Summary email.</description>
    <label>RH Brand</label>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestPrepareData.cls
/************************************************/
/*                                              */
/*  This test class is designed to provide      */
/*  coverage to the PrepareData class in        */
/*  order to enable smooth migration.           */
/*                                              */
/************************************************/

@isTest(SeeAllData=true)
private class TestPrepareData {

    static testMethod void testPrepareData() {
        
		// Test custom setting data creation in memory
		List<Application_Settings__c> appSettings = PrepareData.createApplicationSettings(); 
        List<Groups__c> grpSettings = PrepareData.createGroups();
        List<RH_Brand__c> rhbList = PrepareData.createRHBrand();
		List<CasetoOrderFieldMapping__c> ctoList = PrepareData.createCaseToOrderMappingList();
		List<CaseLineToOrderLineMapping__c> cliTOoliList = PrepareData.createCaseLineToOrderLineMappingList();
		
		// Test the getPortalProfile method
		PrepareData.getPortalProfile();
		
		// Create an Account
		Account a = PrepareData.createAccount();
		insert a;
		
		// Create a Contact
		Contact c = PrepareData.createContact(a.Id);
		insert c;
		
		// Get the Standard Pricebook
		Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name = 'Standard Price Book' LIMIT 1];
		
		// Create an Opportunity
		Opportunity o = PrepareData.createOpportunity(a.Id);
		o.Pricebook2Id = pb.Id;
		insert o;
		OpportunityContactRole ocr = PrepareData.createContactRole(c.Id, o.Id, 'Other');
		
		// Get a BDL User
		User bDLUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
		OpportunityTeamMember otm = PrepareData.createOpportunityTeamMember(o.Id, bDLUser.Id);
		
		// Get a Prepared By User
		User preparedByUser = [SELECT Id FROM User WHERE IsActive = true AND Id != :bDLUser.Id LIMIT 1];
		
		// Create a Quote
		Quote quote = PrepareData.createQuote(bDLUser.Id, c.Id, o.Id, preparedByUser.Id, 'Admin');
		
		// Get two Pricebook Entry Records
		List<PricebookEntry> pBEList = new List<PricebookEntry>([SELECT Id FROM PricebookEntry WHERE Pricebook2Id = :pb.Id LIMIT 2]);
		OpportunityLineItem oli = PrepareData.createOLI(10, o.Id, 1000, pBEList[0].Id, 2);
		
		// Create two Quote Line Items
		QuoteLineItem qli1 = PrepareData.createQLI(quote.Id, 1000, pBEList[0].Id, 1);
		
		// Execute the other methods of PrepareData
		PrepareData.createGenericRHData();
		Case rhCase = PrepareData.createCase('Standard');
		insert rhCase;
		Case_Line_Items__c rhCLI = PrepareData.createCaseLineItem(rhCase);
		Attachment att = PrepareData.createAttachment(rhCase.Id);
		PrepareData.productClass pc = PrepareData.createProduct('DDDD', 10, 'DDDD', 10);
		Task tsk = PrepareData.createTask(system.today(), 'Open', 'Subject', c.Id, c.Id);
		Delayed_Order_Rule__c dor = PrepareData.rcDelayedOrderRule('Standard');
		RH_Order__c rhOrder = PrepareData.createOrder('WWW');
		insert rhOrder;
		Ship_To__c rhShipTo = PrepareData.createShipTo(rhOrder.Id, '1');
		insert rhShipTo;
		Order_Line_Items__c rhOrderLine = PrepareData.createOrderLine(rhOrder.Id, rhShipTo.Id, '1', pc.p.Id);
    }
}