objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Manual_Reservation__c.object
<CustomObject>
    <description>Stores data from the Manual Reservation screen in CW.</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Early_Delivery_Date__c</fullName>
        <label>Early Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Subject_Brand__c</fullName>
        <label>Email Subject Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RH</fullName>
                </value>
                <value>
                    <fullName>RH Baby &amp; Child</fullName>
                </value>
                <value>
                    <fullName>RH Contract</fullName>
                </value>
                <value>
                    <fullName>RH Teen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_To_Address__c</fullName>
        <label>Email To Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Late_Delivery_Date__c</fullName>
        <label>Late Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Lines__c</fullName>
        <label>Order Lines</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Manual Reservations</relationshipLabel>
        <relationshipName>Manual_Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Manual Reservations</relationshipLabel>
        <relationshipName>Manual_Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Manual Reservation</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Manual Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CW_External_Id__c</fullName>
        <description>Commercial Ware External Id</description>
        <externalId>true</externalId>
        <label>CW External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMMSSku__c</fullName>
        <description>ipim field map: CWLINK, where field is concatenation of fields Item#,  Color Code, Size Code.  032111LALO</description>
        <externalId>true</externalId>
        <label>DMMSSku</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STSSku__c</fullName>
        <description>ipim field map; RH Retail SKU. 032111LALO</description>
        <label>STSSku</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sku_Status__c</fullName>
        <description>ipim field map: Sku Status, where A=Active, D=Discontinued, 
N - Non-selling; P – Part ; Q –  Quality Hold;  S – Swatch.  032111LALO</description>
        <label>Sku Status</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testManualReservation_PreviewCtlExt.cls
@isTest
private class testManualReservation_PreviewCtlExt {
	
	/*
	 *	Test methods for ManualReservation_PreviewCtlExt.cls and ManualReservation.cls.
	 *
	 */
	
	// Create Manual Reservation test data
	@testSetup static void mrTestData() {
		
		PrepareData.populateCustomSettings();
		
		Account acc = PrepareData.createAccount();
		insert acc;
		
		Contact con = PrepareData.createContact(acc.Id);
		insert con;
		
		Opportunity opp = PrepareData.createOpportunity(acc.Id);
		opp.Ops_Contact__c = UserInfo.getUserId();
		insert opp;
		
		List<RH_Order__c> orderList = new List<RH_Order__c>();
		orderList.add(PrepareData.createOrder('mrOrderW'));
		orderList[0].Order_Type_Code__c = 'W';
		
		orderList.add(PrepareData.createOrder('mrOrderE'));
		orderList[1].Order_Type_Code__c = 'W';
		orderList[1].Sold_to_Email__c = '';
		
		orderList.add(PrepareData.createOrder('mrOrderZ'));
		orderList[2].Order_Type_Code__c = 'Z';
		orderList[2].Opportunity__c = opp.Id;
		insert orderList;
    	
    	List<Ship_To__c> shipToList = new List<Ship_To__c>();
    	for (Integer i=0; i<orderList.size(); i++) {
    		shipToList.add(PrepareData.createShipTo(orderList[i].Id, '1'));
    	}
        insert shipToList;
        
        Product2 product = new Product2(
        	Name = '23580079PN',
        	CW_External_Id__c = '23580079PN',
        	Sku_Status__c = 'A',
        	STSSku__c = '23580080',
        	DMMSSku__c = '23580079PN'
        );
        insert product;
        
        List<Order_Line_Items__c> oliList = new List<Order_Line_Items__c>();
		oliList.add(PrepareData.createOrderLine(orderList[0].Id, shipToList[0].Id, '1', product.Id));
		oliList.add(PrepareData.createOrderLine(orderList[1].Id, shipToList[1].Id, '1', product.Id));
		oliList.add(PrepareData.createOrderLine(orderList[2].Id, shipToList[2].Id, '1', product.Id));
        insert oliList;
        
        List<Manual_Reservation__c> mrList = new List<Manual_Reservation__c>();
        mrList.add(new Manual_Reservation__c(
        	Company__c = '100',
        	Order_Number__c = orderList[0].Id,
        	Ship_To__c = shipToList[0].Id,
        	Early_Delivery_Date__c = system.today().addDays(30),
        	Late_Delivery_Date__c = system.today().addDays(35),
        	Email_Subject_Brand__c = 'RH',
    		Email_To_Address__c = orderList[0].Sold_to_Email__c,
    		Order_Lines__c = '["' + orderList[0].Name + '-' + shipToList[0].Name + '-' + oliList[0].Name + '"]')
    	);
    	insert mrList;
	}
	
	// Test with valid parameters and a non-Contract order
	static testMethod void mrPreviewTest1() {
		
		List<Manual_Reservation__c> mrList = new List<Manual_Reservation__c>();
        mrList = [select Id, Order_Number__c from Manual_Reservation__c where Order_Number__r.Name = 'mrOrderW'];
        
        system.assertEquals(1, mrList.size());
        
        // Now test the controller extension
    	ApexPages.StandardController std = new ApexPages.StandardController(mrList[0]);
    	ApexPages.currentPage().getParameters().put('mrId', mrList[0].Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + mrList[0].Id);
		ManualReservation_PreviewCtlExt ctl = new ManualReservation_PreviewCtlExt(std);
		
		ctl.sendNotification();
		ctl.cancelMRPreview();
	}
	
	// Test with invalid parameters and a non-Contract order
	static testMethod void mrPreviewTest2() {
		
		List<Manual_Reservation__c> mrList = new List<Manual_Reservation__c>();
        mrList = [select Id, Order_Number__c from Manual_Reservation__c where Order_Number__r.Name = 'mrOrderW'];
        
        system.assertEquals(1, mrList.size());
        
        // Now test the controller extension
    	ApexPages.StandardController std = new ApexPages.StandardController(mrList[0]);
    	ApexPages.currentPage().getParameters().put('mrId', mrList[0].Id);
		ManualReservation_PreviewCtlExt ctl = new ManualReservation_PreviewCtlExt(std);
		
		ctl.cancelMRPreview();
	}
}