objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_Type__c</fullName>
        <label>Issue Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Contract_Issue__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Attitude</fullName>
                </value>
                <value>
                    <fullName>Balance Due</fullName>
                </value>
                <value>
                    <fullName>Carton Damage</fullName>
                </value>
                <value>
                    <fullName>Color/ Finish</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Contamination</fullName>
                </value>
                <value>
                    <fullName>Credit Due</fullName>
                </value>
                <value>
                    <fullName>CSC Service Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Preference (Product As Expected)</fullName>
                </value>
                <value>
                    <fullName>Customer Specific Requirements</fullName>
                </value>
                <value>
                    <fullName>Customer Unavailable</fullName>
                </value>
                <value>
                    <fullName>Customs</fullName>
                </value>
                <value>
                    <fullName>Damage</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>Delivery Service Issue</fullName>
                </value>
                <value>
                    <fullName>Drayage</fullName>
                </value>
                <value>
                    <fullName>Fabric</fullName>
                </value>
                <value>
                    <fullName>Fabrics/ Leather/ Fur</fullName>
                </value>
                <value>
                    <fullName>Finish</fullName>
                </value>
                <value>
                    <fullName>Frame</fullName>
                </value>
                <value>
                    <fullName>Function</fullName>
                </value>
                <value>
                    <fullName>Gallery Service Issue</fullName>
                </value>
                <value>
                    <fullName>Grouped/ Not</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Incorrect</fullName>
                </value>
                <value>
                    <fullName>Invoice Missing</fullName>
                </value>
                <value>
                    <fullName>Lack of Knowledge</fullName>
                </value>
                <value>
                    <fullName>Lack of Response</fullName>
                </value>
                <value>
                    <fullName>Late/ Cx V Promise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <label>Issue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Issue_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Delivery Provider</fullName>
                </value>
                <value>
                    <fullName>Assembled Incorrectly</fullName>
                </value>
                <value>
                    <fullName>Assembly - Components Misaligned/ Non-Functioning Hardware</fullName>
                </value>
                <value>
                    <fullName>Billing Issue</fullName>
                </value>
                <value>
                    <fullName>Blemishes</fullName>
                </value>
                <value>
                    <fullName>Bowing/ Warping</fullName>
                </value>
                <value>
                    <fullName>Broken Part</fullName>
                </value>
                <value>
                    <fullName>Bubbling/ Lifting</fullName>
                </value>
                <value>
                    <fullName>Bugs/ Vermin</fullName>
                </value>
                <value>
                    <fullName>Burning Smell</fullName>
                </value>
                <value>
                    <fullName>Cannot Contact HDL</fullName>
                </value>
                <value>
                    <fullName>Color Clash</fullName>
                </value>
                <value>
                    <fullName>Color Slightly off</fullName>
                </value>
                <value>
                    <fullName>Cracks/ Splits</fullName>
                </value>
                <value>
                    <fullName>Creases</fullName>
                </value>
                <value>
                    <fullName>Crushed Corner</fullName>
                </value>
                <value>
                    <fullName>CSC Service Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Preference - Product As Expected</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>Delivery Service Issue</fullName>
                </value>
                <value>
                    <fullName>Dings/ Dents/ Gouges</fullName>
                </value>
                <value>
                    <fullName>Dirt</fullName>
                </value>
                <value>
                    <fullName>Dirtied Home</fullName>
                </value>
                <value>
                    <fullName>Distressing</fullName>
                </value>
                <value>
                    <fullName>Does Not Fit</fullName>
                </value>
                <value>
                    <fullName>Does Not Turn On</fullName>
                </value>
                <value>
                    <fullName>Doors Do Not Open or Close Properly</fullName>
                </value>
                <value>
                    <fullName>Drawers Do Not Open or Close Properly</fullName>
                </value>
                <value>
                    <fullName>Duplicate Order</fullName>
                </value>
                <value>
                    <fullName>Element Does Not Align</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Notes__c</fullName>
        <label>Issue Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vendor_Number__c</fullName>
        <formula>CW_SKU_ID__r.Vendor_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_Product_Type_is_the_SKU__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bath Furniture</fullName>
                </value>
                <value>
                    <fullName>Bath Water Supply</fullName>
                </value>
                <value>
                    <fullName>Bed/ Crib/ Toddler Bed /Bunk Bed</fullName>
                </value>
                <value>
                    <fullName>Casegoods/ Shelving</fullName>
                </value>
                <value>
                    <fullName>Cushion/ Pillows</fullName>
                </value>
                <value>
                    <fullName>Décor - Wall Decor/ Frames/ Lit Decor/ Holiday</fullName>
                </value>
                <value>
                    <fullName>Fire Pits/ Fire Bowls/ Heaters</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Jewelry</fullName>
                </value>
                <value>
                    <fullName>Kitchenware/ Tableware</fullName>
                </value>
                <value>
                    <fullName>Lighting</fullName>
                </value>
                <value>
                    <fullName>Mirrors</fullName>
                </value>
                <value>
                    <fullName>Plumbing Fixtures/ Bath Water Supply</fullName>
                </value>
                <value>
                    <fullName>Rugs</fullName>
                </value>
                <value>
                    <fullName>Seating</fullName>
                </value>
                <value>
                    <fullName>Sinks/ Basins</fullName>
                </value>
                <value>
                    <fullName>Tables/ Desks</fullName>
                </value>
                <value>
                    <fullName>Textiles</fullName>
                </value>
                <value>
                    <fullName>Umbrellas/ Shade</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Where_is_the_Problem__c</fullName>
        <label>Problem Location</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>What_Product_Type_is_the_SKU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arm(s)</fullName>
                </value>
                <value>
                    <fullName>Back</fullName>
                </value>
                <value>
                    <fullName>Backing</fullName>
                </value>
                <value>
                    <fullName>Base/ Pedestal</fullName>
                </value>
                <value>
                    <fullName>Binding</fullName>
                </value>
                <value>
                    <fullName>Bottom</fullName>
                </value>
                <value>
                    <fullName>Bowl</fullName>
                </value>
                <value>
                    <fullName>Bulb Holder</fullName>
                </value>
                <value>
                    <fullName>Bulbs</fullName>
                </value>
                <value>
                    <fullName>Burner</fullName>
                </value>
                <value>
                    <fullName>Cabinet Doors</fullName>
                </value>
                <value>
                    <fullName>Cabinet Drawers</fullName>
                </value>
                <value>
                    <fullName>Canopy</fullName>
                </value>
                <value>
                    <fullName>Casters/ Wheels</fullName>
                </value>
                <value>
                    <fullName>Chain</fullName>
                </value>
                <value>
                    <fullName>Clasp</fullName>
                </value>
                <value>
                    <fullName>Cord</fullName>
                </value>
                <value>
                    <fullName>Crystals</fullName>
                </value>
                <value>
                    <fullName>Cushion</fullName>
                </value>
                <value>
                    <fullName>Door(s)</fullName>
                </value>
                <value>
                    <fullName>Drain</fullName>
                </value>
                <value>
                    <fullName>Drawer(s)</fullName>
                </value>
                <value>
                    <fullName>Drawer Pulls</fullName>
                </value>
                <value>
                    <fullName>Electrical - Bulb Holder</fullName>
                </value>
                <value>
                    <fullName>Electrical - Cords</fullName>
                </value>
                <value>
                    <fullName>Electrical - Plug</fullName>
                </value>
                <value>
                    <fullName>Electrical - Switch</fullName>
                </value>
                <value>
                    <fullName>Embellishments/ Attachments</fullName>
                </value>
                <value>
                    <fullName>Faucet</fullName>
                </value>
                <value>
                    <fullName>Fill/ Foam/ Batting/ Feathers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISSUE-{0}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Vendor_Number__c</fullName>
        <description>ipim field map: Vendor Number (up to 9999), where PRIMARY ONLY. If more than one vendor per product, there is no systematic way to indicate this.. 032111LALO</description>
        <label>Vendor Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/IssueServiceTest.cls
@isTest
private class IssueServiceTest {

    static testMethod void createIssueAndShare() {	
	 
	    // Create vendors public group
	    Group vendorGroup = new Group(Name = 'Vendor Partner Users');
	    insert vendorGroup;
	    
	    // Create test Account and insert
	    Account testAccount = new Account(Name='Partner Account');
		testAccount.Vendor_Number__c = '1234';
		insert testAccount;
		
		testAccount.isPartner = true;
		update testAccount;
		
		// Create test Product and insert
		PrepareData.productClass testProductClass = PrepareData.createProduct('59030274COCO', 25.00, 'testProd', 25.00);
		
		System.debug('Product: ' + testProductClass.p);
		
		Product2 testProduct = testProductClass.p;
		
		testProduct.Vendor_Number__c = '1234'; 
		update testProduct;
		
		// Create test Issue and insert
		Issue__c testIssue = new Issue__c(
										CW_SKU_ID__c = testProduct.Id, 
										What_Product_Type_is_the_SKU__c = 'Bath Water Supply', 
										Where_is_the_Problem__c = 'Faucet', 
										Issue_Type__c = 'Contamination', 
										Other_Notes__c = 'tesht');
		insert testIssue;
		
		testIssue = [Select Vendor_Number__c from Issue__c where Id = :testIssue.Id];
		
		testAccount = [Select Id, Name, PublicGroupId__c, isPartner from Account where Id= :testAccount.Id];
		Group testGroup = [Select Name from Group where Id = :testAccount.PublicGroupId__c];
		List<Issue__Share> issueShare = [SELECT ParentId from Issue__Share where UserOrGroupId = :testAccount.PublicGroupId__c limit 1];
				
		
		System.assertEquals('VEND-' + testAccount.Name + '-' + testAccount.Id, testGroup.name);
		System.assertEquals(testAccount.isPartner, true);
		System.assertEquals(testIssue.Id, issueShare[0].ParentId);
    }
}