objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Order.</description>
        <label>Customer Address Sold To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country_Code__c</fullName>
        <description>CW Sold to Country Code</description>
        <label>Sold To Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Customer_Number__c</fullName>
        <description>CW Sold to Cust Number</description>
        <label>Sold To Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_View_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV process has run to determine whether this Order should be linked to an existing SSV or if a new SSV needs to be created.</description>
        <label>Source System View Sold To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Ship To should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Ship Tos are linked to the incorrect Business or Person Account record.</description>
        <label>Account Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <formula>Order__r.Account_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CW_Customer_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW Customer Ship To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Ship Tos (CW Customer Ship To)</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Ship To.</description>
        <label>Customer Address Ship To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer_Number__c</fullName>
        <label>Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerManager__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>runMDMTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>runMDMTriggers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>runTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>runTriggers</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerManager</label>
</CustomObject>

classes/RH_OrdersTest.cls
@isTest
private class RH_OrdersTest {
	
    static String SSV_ID = '1234567';

    @testSetup
    static void setup() {
    	
    	PrepareData.populateCustomSettings();
    	
    	TestDataFactory.turnMdmFeatureFlagsOn();
        Account a = TestDataFactory.createAccount(true);
        Contact c = TestDataFactory.createContact(true);
        Customer_Address__c ca = TestDataFactory.createCustomerAddress(true);
        Source_System_View__c ssv = TestDataFactory.createSSV(false);
        ssv.EXT_Source_System_Customer_ID__c = SSV_ID;
        ssv.Account__c = a.Id;
        ssv.Contact__c = c.Id;
        ssv.Customer_Address__c = ca.Id;
        insert ssv;
    }  

    @isTest
    static void testSsvCreatingFromOrder() {

		// GIVEN (test User)    	
		
		User u = TestDataFactory.createUser();
        
		TriggerManager__c triggerManager = new TriggerManager__c(SetupOwnerId = u.Id, runTriggers__c=true, runMDMTriggers__c=true);
		insert triggerManager;
		
		// GIVEN (test trade account)
		
		List<Account> testAccounts = new List<Account>();
		testAccounts.add(new Account (
			NAME = 'test-account'
		));
		u.Single_View_of_Customer_Process_User__c = true;
		System.runAs(u) {
			database.insert(testAccounts);
		}
		
		// GIVEN (trade id from new account)
		
		String tradeId = [SELECT X12_Digit_Member__c FROM Account WHERE ID = :testAccounts.get(0).Id].X12_Digit_Member__c;
		system.assertNotEquals(NULL, tradeId);
		
    	// GIVEN (test order)
    	
    	List<SObject> testOrders = new List<SObject>();
    	testOrders.add(new RH_Order__c(
    		Sold_to_Customer_Number__c = 'this-is-a-test-record',
    		Sold_to_Country_Code__c = 'USA',
    		Trade_ID__c = tradeId
    	));
    	
    	// GIVEN (domain handler)
    	
    	RH_Orders domainOrders = new RH_Orders();
    	domainOrders.records.addAll(testOrders);
    	
    	// WHEN (call link to existing contact)
    	
    	domainOrders.linkToExistingContact((List<Rh_Order__c>)testOrders);
 
	    	
    	// THEN (account associated with order)
    	
    	System.assertNotEquals(null, testAccounts.get(0).Id);
    	System.assertEquals(testAccounts.get(0).Id, ((RH_Order__c)testOrders.get(0)).Account_Sold_To__c, 'order account not set');
    	
    	// WHEN (after insert trigger run)
    	
		domainOrders.handleSSVCreation(null);
        
        // THEN ssv generated
    	
    	System.assertEquals(1, domainOrders.recordsToInsert.size());
    	System.assertEquals('this-is-a-test-record', ((Source_System_View__c)domainOrders.recordsToInsert[0]).Name);    	
    	System.assertEquals(testAccounts.get(0).Id, ((Source_System_View__c)domainOrders.recordsToInsert[0]).Account__c);
    	System.assertEquals('US', ((Source_System_View__c)domainOrders.recordsToInsert[0]).Country_Code__c);
    }
	
    // Test setting Source_System_View_Sold_To__c by Sold_To_Customer_Number__c
    @isTest
    static void test_setSsvLookup_custNum_insert() {
    	
		User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;

		TriggerManager__c triggerManager = new TriggerManager__c(SetupOwnerId = u.Id, runTriggers__c=true, runMDMTriggers__c=true);
		insert triggerManager;
		
        System.runAs(u) {    
	        Source_System_View__c ssv = [
	            SELECT Account__c,
	                Contact__c,
	                Customer_Address__c
	            FROM Source_System_View__c
	            WHERE EXT_Source_System_Customer_ID__c = :SSV_ID
	        ];
	
	        RH_Order__c order = TestDataFactory.createRhOrder(false);
	        order.Sold_To_Customer_Number__c = SSV_ID;
	        insert order;
	
	        order = [
	            SELECT Source_System_View_Sold_To__c,
	                Account_Sold_To__c,
	                Contact_Sold_To__c,
	                Customer_Address_Sold_To__c
	            FROM RH_Order__c
	            WHERE Id = :order.Id
	        ];
	        System.assertEquals(ssv.Id, order.Source_System_View_Sold_To__c);
	        System.assertEquals(ssv.Account__c, order.Account_Sold_To__c);
	        System.assertEquals(ssv.Contact__c, order.Contact_Sold_To__c);
	        System.assertEquals(ssv.Customer_Address__C, order.Customer_Address_Sold_To__c);
        }
    }

    // Test setting Source_System_View_Sold_To__c by Sold_To_Customer_Number__c
    @isTest
    static void test_setSsvLookup_custNum_update() {
    	
		User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;

		TriggerManager__c triggerManager = new TriggerManager__c(SetupOwnerId = u.Id, runTriggers__c=true, runMDMTriggers__c=true);
		insert triggerManager;
		
        System.runAs(u) {     	
	        Source_System_View__c ssv = [
	            SELECT Account__c,
	                Contact__c,
	                Customer_Address__c
	            FROM Source_System_View__c
	            WHERE EXT_Source_System_Customer_ID__c = :SSV_ID
	        ];
	
	        RH_Order__c order = TestDataFactory.createRhOrder(false);
	        insert order;
	
	        order = [
	            SELECT Source_System_View_Sold_To__c,
	                Account_Sold_To__c,
	                Contact_Sold_To__c,
	                Customer_Address_Sold_To__c
	            FROM RH_Order__c
	            WHERE Id = :order.Id
	        ];
	        System.assertNotEquals(ssv.Id, order.Source_System_View_Sold_To__c);
	        System.assertNotEquals(ssv.Account__c, order.Account_Sold_To__c);
	        System.assertNotEquals(ssv.Contact__c, order.Contact_Sold_To__c);
	        System.assertNotEquals(ssv.Customer_Address__C, order.Customer_Address_Sold_To__c);
	
	        order.Sold_To_Customer_Number__c = SSV_ID;
	        update order;
	
	        order = [
	            SELECT Source_System_View_Sold_To__c,
	                Account_Sold_To__c,
	                Contact_Sold_To__c,
	                Customer_Address_Sold_To__c
	            FROM RH_Order__c
	            WHERE Id = :order.Id
	        ];
	        System.assertEquals(ssv.Id, order.Source_System_View_Sold_To__c);
	        System.assertEquals(ssv.Account__c, order.Account_Sold_To__c);
	        System.assertEquals(ssv.Contact__c, order.Contact_Sold_To__c);
	        System.assertEquals(ssv.Customer_Address__C, order.Customer_Address_Sold_To__c);
        }
    }

    // Test mirroring of lookup fields on children
    @isTest
    static void test_mirror_lookups_children() {
    	
    	User u = TestDataFactory.createUser();
		u.Single_View_of_Customer_Process_User__c = false;

        System.runAs(u) {    	   	
	        // Update lookup on order
	        Source_System_View__c ssv = [
	            SELECT Account__c,
	                Contact__c,
	                Customer_Address__c
	            FROM Source_System_View__c
	            WHERE EXT_Source_System_Customer_ID__c = :SSV_ID
	        ];
	        RH_Order__c order = TestDataFactory.createRhOrder(false);
	        order.Sold_To_Customer_Number__c = SSV_ID;
	        insert order;
	
	        Ship_To__c child = TestDataFactory.createShipTo(false);
	        child.Order__c = order.Id;
	        child.Ship_To_Customer_Number__c = '0';
	        insert child;
	
	        // Assert lookups are mirrored
	        child = [
	            SELECT CW_Customer_Ship_To__c, 
	                Account_Ship_To__c, 
	                Contact_Ship_To__c, 
	                Customer_Address_Ship_To__c
	            FROM Ship_To__c
	            WHERE Id = :child.Id
	        ];
	        System.assertEquals(ssv.Id, child.CW_Customer_Ship_To__c);
	        System.assertEquals(ssv.Account__c, child.Account_Ship_To__c);
	        System.assertEquals(ssv.Contact__c, child.Contact_Ship_To__c);
	        System.assertEquals(ssv.Customer_Address__c, child.Customer_Address_Ship_To__c);
	
	        order.Source_System_View_Sold_To__c = null;
	        order.Account_Sold_To__c = null;
	        order.Contact_Sold_To__c = null;
	        order.Customer_Address_Sold_To__c = null;
	        update order;
	        child = [
	            SELECT CW_Customer_Ship_To__c, 
	                Account_Ship_To__c, 
	                Contact_Ship_To__c, 
	                Customer_Address_Ship_To__c
	            FROM Ship_To__c
	            WHERE Id = :child.Id
	        ];
	        System.assertEquals(null, child.CW_Customer_Ship_To__c);
	        System.assertEquals(null, child.Account_Ship_To__c);
	        System.assertEquals(null, child.Contact_Ship_To__c);
	        System.assertEquals(null, child.Customer_Address_Ship_To__c);
        }
    }

    // Test non-mirroring of lookup fields on children because Ship_To_Customer_Number__c != 0
    @isTest
    static void test_not_mirror_lookups_children() {
    	
		User u = TestDataFactory.createUser();
		u.Single_View_of_Customer_Process_User__c = true;

        System.runAs(u) {    	
	        // Update lookup on order
	        Source_System_View__c ssv = [
	            SELECT Account__c,
	                Contact__c,
	                Customer_Address__c
	            FROM Source_System_View__c
	            WHERE EXT_Source_System_Customer_ID__c = :SSV_ID
	        ];
	        RH_Order__c order = TestDataFactory.createRhOrder(false);
	        order.Sold_To_Customer_Number__c = SSV_ID;
	        insert order;
	
	        Ship_To__c child = TestDataFactory.createShipTo(false);
	        child.Order__c = order.Id;
	        child.Ship_To_Customer_Number__c = '1';
	        insert child;
	
	        // Assert lookups are not mirrored
	        child = [
	            SELECT CW_Customer_Ship_To__c, 
	                Account_Ship_To__c, 
	                Contact_Ship_To__c, 
	                Customer_Address_Ship_To__c
	            FROM Ship_To__c
	            WHERE Id = :child.Id
	        ];
	        System.assertNotEquals(ssv.Id, child.CW_Customer_Ship_To__c);
	        System.assertNotEquals(ssv.Account__c, child.Account_Ship_To__c);
	        System.assertNotEquals(ssv.Contact__c, child.Contact_Ship_To__c);
	        System.assertNotEquals(ssv.Customer_Address__c, child.Customer_Address_Ship_To__c);
        }
    }

    // Test bulk updates
    @isTest
    static void test_mirror_ssv_lookup_children_bulk() {
        Integer numOrders = 40;
        Integer numChildrenEach = 5;

        System.debug('creating orders');
        List<RH_Order__c> orders = TestDataFactory.createRhOrders(numOrders, false);
        insert orders;
        System.debug('created orders');

        Source_System_View__c ssv = [
            SELECT Account__c,
                Contact__c,
                Customer_Address__c
            FROM Source_System_View__c
            WHERE EXT_Source_System_Customer_ID__c = :SSV_ID
        ];

        // Create children
        System.debug('creating shipTos');
        List<Ship_To__c> shipTos = TestDataFactory.createShipTos(numOrders * numChildrenEach, false);
        Integer count = 0;
        for (RH_Order__c order : orders) {
            for (Integer i = 0; i < numChildrenEach; i++) {
                shipTos[count].Order__c = order.Id;
                shipTos[count].Ship_To_Customer_Number__c = '0';
                count++;
            }
            order.Sold_To_Customer_Number__c = SSV_ID;
        }

        User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;

        System.runAs(u) {
            Reporter.startLogging();
            Reporter.log('Queries Before:' + Limits.getQueries());
            insert shipTos;
            Reporter.log('Queries After:' + Limits.getQueries());
            Reporter.stopLogging();
        }
        System.debug('created shipTos');

        // Update lookup on orders
        Test.startTest();
            System.debug('updating orders');
            update orders;
            System.debug('updated orders');
        Test.stopTest();

        // Assert update is mirrored
        List<Ship_To__c> children = [
            SELECT CW_Customer_Ship_To__c, Account_Ship_To__c, Contact_Ship_To__c, Customer_Address_Ship_To__c
            FROM Ship_To__c
            WHERE Id IN :shipTos
        ];
        for (Ship_To__c child : children) {
            // System.assertEquals(ssv.Id, child.CW_Customer_Ship_To__c);
            // System.assertEquals(ssv.Account__c, child.Account_Ship_To__c);
            // System.assertEquals(ssv.Contact__c, child.Contact_Ship_To__c);
            // System.assertEquals(ssv.Customer_Address__C, child.Customer_Address_Ship_To__c);
        }
    }
}