objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <fields>
        <fullName>Value_Text__c</fullName>
        <label>Value - Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Attribution__c.object
<CustomObject>
    <fields>
        <fullName>Associate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associate Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Attributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attribution_ID__c</fullName>
        <label>Associate User ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribution_Percent__c</fullName>
        <label>Attribution Percent</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Sales Attributions</relationshipLabel>
        <relationshipName>Sales_Attributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Associate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Attribution</label>
    <nameField>
        <displayFormat>SA-{0000000000}</displayFormat>
        <label>Sales Attribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Attributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SalesAttributionServiceTest.cls
@isTest
public with sharing class SalesAttributionServiceTest {
    
	static testMethod void createSalesAttribution() {	
	    
	    // Create and insert test Account 
	    Account testAccount = PrepareData.createAccount();
		insert testAccount;
		
		// Create test Contact and insert
		User testUser = TestDataFactory.createUser();
		testUser.Username = 'wsxnji@wsxnji.com';
		
		insert testUser;
		
		// Create test Order and insert
		RH_Order__c testOrder = PrepareData.createOrder('741741741');
		insert testOrder;
		
		// Populate custom setting
		
		insert new Application_Settings__c(Name='CCD System Hold Codes', Value_Text__c='AT,AU,AV,AW,UT,UU,UV,UW');
		
		// Create Sales Attribution and insert
		Sales_Attribution__c testSalesAttribution = new Sales_Attribution__c(Order__c = testOrder.Id, Attribution_ID__c = 'wsxnji', Primary_Associate__c = true, Attribution_Percent__c = 100.00); 
		insert testSalesAttribution;
		
		// Validate
		testSalesAttribution = [Select Id, Associate_Name__c from Sales_Attribution__c where Id = : testSalesAttribution.Id];
		System.assertEquals(testSalesAttribution.Associate_Name__c, testUser.Id);
    }    
}