objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <inlineHelpText>For United States, enter US. 
For Canada, enter CA. 
Leave blank for all other countries.</inlineHelpText>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact_Information__c.object
<CustomObject>
    <description>This table contains one record per contact point. A contact point is defined as a method for contacting the customer (examples include: Email, Phone, Social Handles).</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipName>Contact_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <label>Contact Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>For email contact information</description>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Address__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Feature_Flags__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>MDM_Address_Feature__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MDM Address Feature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MDM_Merge_feature__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MDM Merge feature</label>
        <type>Checkbox</type>
    </fields>
    <label>Feature Flags</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Role__c.object
<CustomObject>
    <description>This table contains mappings of contacts related to an order</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Sold To Account on the Order.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Roles (Account)</relationshipLabel>
        <relationshipName>Order_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Record Linkage for Order Contact Role</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Order_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Role__c</fullName>
        <label>Order Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliated Person</fullName>
                </value>
                <value>
                    <fullName>RH Designer</fullName>
                </value>
                <value>
                    <fullName>External Designer</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Sold To</fullName>
                </value>
                <value>
                    <fullName>Partial Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipName>Order_Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For data model build out: how viable is the design with ship to and order populated</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Roles</relationshipLabel>
        <relationshipName>Order_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Role</label>
    <nameField>
        <displayFormat>OR-{0000000}</displayFormat>
        <label>Order Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Add field history tracking</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Add field history tracking</description>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
/**
 *  TestDataFactory.cls
 *  @description Utility class for APEX unit tests to create necessary data
 *  @author Ernesto Valdes, Traction On Demand
 */
@isTest
public with sharing class TestDataFactory {
	
	public static void turnMdmFeatureFlagsOn() {
		Feature_Flags__c customSetting = new Feature_Flags__c(
			MDM_Address_Feature__c = true,
			MDM_Merge_feature__c = true
		);
		database.insert(customSetting);					
	}

	public static User createUser() {
		return (User) TestDataFactoryHelper.createSObject(User.getSObjectType());
	}

	public static Contact_Information__c createContactInformation(Boolean doInsert) {
		return createContactInformations(1, doInsert)[0];
	}

	public static List<Contact_Information__c> createContactInformations(Integer howMany, Boolean doInsert) {
		List<Contact_Information__c> contactInformations = (List<Contact_Information__c>) 
				TestDataFactoryHelper.createSObjects(Contact_Information__c.getSObjectType(), howMany);

		if (doInsert) {
			insert contactInformations;
		}

		return contactInformations;
	}

	public static Ship_To__c createShipTo(Boolean doInsert) {
		return createShipTos(1, doInsert)[0];
	}

	public static List<Ship_To__c> createShipTos(Integer howMany, Boolean doInsert) {
		List<Ship_To__c> shipTos = (List<Ship_To__c>) 
			TestDataFactoryHelper.createSObjects(Ship_To__c.getSObjectType(), howMany);

		if (doInsert) {
			insert shipTos;
		}

		return shipTos;
	}

	public static Address__c createAddress(Boolean doInsert) {
		return createAddresses(1, doInsert)[0];
	}

	public static List<Address__c> createAddresses(Integer howMany, Boolean doInsert) {
		List<Address__c> addrs = (List<Address__c>) 
			TestDataFactoryHelper.createSObjects(Address__c.getSObjectType(), howMany);

		if (doInsert) {
			insert addrs;
		}

		return addrs;
	}

	public static Customer_Address__c createCustomerAddress(Boolean doInsert) {
		return createCustomerAddresses(1, doInsert)[0];
	}

	public static Customer_Address__c createCustomerAddress(Boolean doInsert, Boolean createParents) {
		return createCustomerAddresses(1, doInsert, createParents)[0];
	}

	public static List<Customer_Address__c> createCustomerAddresses(Integer howMany, Boolean doInsert) {
		return createCustomerAddresses(howMany, doInsert, true);
	}

	public static List<Customer_Address__c> createCustomerAddresses(Integer howMany, Boolean doInsert, Boolean createParents) {
		// Account c = createAccount(true); // removed in favor of contact lookup, data model change Feb 18th
		Contact c;
		Address__c a;
		if (createParents) {
			c = createContact(true);
			a = createAddress(true);
		}
		List<Customer_Address__c> customerAddresses = (List<Customer_Address__c>) 
				TestDataFactoryHelper.createSObjects(Customer_Address__c.getSObjectType(), howMany);

		for (Customer_Address__c ca : customerAddresses) {
			if (createParents) {
				ca.Address__c = a.Id;
				ca.Contact__c = c.Id;
			}
		}

		if (doInsert) {
			insert customerAddresses;
		}

		return customerAddresses;
	}

	public static Account createPersonAccount(Boolean doInsert) {
		return createPersonAccounts(1, doInsert)[0];
	}

	public static List<Account> createPersonAccounts(Integer howMany, Boolean doInsert) {
		RecordType personAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'RH End Customer' and SObjectType = 'Account'];
		List<Account> accs = new List<Account>();
		for (Integer i = 0; i < howMany; i++) {
			accs.add(
				new Account(
					LastName = 'test ' + i,
					RecordType = personAccountRecordType
				)
			);
		}

		if (doInsert) {
			insert accs;
		}
		return accs;
	}

	public static Account createAccount(Boolean doInsert) {
		return createAccount(1, doInsert)[0];
	}

	public static List<Account> createAccount(Integer howMany, Boolean doInsert) {
		List<Account> createdRecords = new List<Account>();
		for (Integer i = 0; i < howMany; i++) {
			createdRecords.add(
				new Account(
					Name = 'Test Account ' + i
				));
		}

		if (doInsert) insert createdRecords;

		return createdRecords;
	}

	public static Contact createContact(Boolean doInsert) {
		return createContacts(1, doInsert)[0];
	}

	public static List<Contact> createContacts(Integer howMany, Boolean doInsert) {
		List<Contact> contacts = TestDataFactoryHelper.createSObjects(Contact.getSObjectType(), howMany);

		if (doInsert) {
			insert contacts;
		} 

		return contacts;
	}

	public static Order_Role__c createOrderRole(Boolean doInsert) {
		return createOrderRoles(1, doInsert)[0];
	}

	public static List<Order_Role__c> createOrderRoles(Integer howMany, Boolean doInsert) {
		Account a = createAccount(true);
		List<RH_Order__c> orders = createRhOrders(howMany, true);

		List<Order_Role__c> orderRoles = TestDataFactoryHelper.createSObjects(Order_Role__c.getSObjectType(), howMany);
		Integer i = 0;
		for (Order_Role__c orderRole : orderRoles) {
			orderRole.Account__c = a.Id;
			orderRole.Order__c = orders[i++].Id;
		}

		if (doInsert) {
			insert orderRoles;
		} 

		return orderRoles;
	}

	public static RH_Order__c createRhOrder(Boolean doInsert) {
		return createRhOrders(1, doInsert)[0];
	}

	public static List<RH_Order__c> createRhOrders(Integer howMany, Boolean doInsert) {
		List<RH_Order__c> rhOrders = TestDataFactoryHelper.createSObjects(RH_Order__c.getSObjectType(), howMany);

		if (doInsert) {
			insert rhOrders;
		} 

		return rhOrders;
	}

	public static Case createCase(Boolean doInsert) {
		return createCases(1, doInsert)[0];
	}

	public static List<Case> createCases(Integer howMany, Boolean doInsert) {
		List<Case> cases = TestDataFactoryHelper.createSObjects(Case.getSObjectType(), howMany);

		if (doInsert) {
			insert cases;
		} 

		return cases;
	}

	public static Source_System_View__c createSSV(Boolean doInsert) {
		return createSSV(1, doInsert)[0];
	}

	static Integer uniqueSSVId = 1;
	public static List<Source_System_View__c> createSSV(Integer howMany, Boolean doInsert) {

		List<Source_System_View__c> createdRecords = new List<Source_System_View__c>();
		for (Integer i = 1; i <= howMany; i++) {
			createdRecords.add(
				new Source_System_View__c(
					EXT_Source_System_Customer_ID__c = String.valueOf(uniqueSSVId),
					Day_Phone__c = '+1.(555)-555-' + padLeft(i, 4),
					Email__c = 'test' + i + '+email@domain.test.com',
					Company_Name__c = 'Test Company' + i,
					First_Name__c = 'TestFirst' + i,
					Last_Name__c = 'TestLast' + i,
					Address_1__c = padLeft(i, 4) + ' Test St ',
					Address_2__c = ' Apt 456A',
					City__c = 'San Francisco',
					State__c = ' CA ',
					Zip__c = '12345 ',
					Country__c = 'US',
					Country_Code__c = 'US'
				));
			uniqueSSVId++;
		}

		if (doInsert) insert createdRecords;

		return createdRecords;
	}

	/**
	 *  @description Converts a given integer to string, and pads the string
	 *               up to the given number of characters with leading zeroes
	 *  @author 	 Ernesto Valdes, Traction on Demand.
	 *  @date        2016-01-26
	 *  @param       i             The given integer to convert and pad
	 *  @param       pad           The size of the returned string, leading zeroes are added if needed
	 *  @return                    The padded string
	 */
	public static String padLeft(Integer i, Integer pad) {

		// Convert int to string, empty string if int is null
		String iString = (i != null) ? String.valueOf(i) : '';

		while ((pad - iString.length()) > 0) {

			// Add zero to left of string
			iString = '0' + iString;
		}

		return iString;
	}
}