objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Total_Lifetime_Value__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand.</description>
        <inlineHelpText>Lifetime revenue for this contact (where the contact was the Billing name on the order)</inlineHelpText>
        <label>Total Lifetime Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Open- Order lines are open to be fulfilled
Closed- All items have either shipped or cancelled
Cancelled - No items have shipped - all cancelled
Held- Order placed on hold. Will not ship.
Suspended/Error - Issues preventing CW processing and accepting</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <description>Including shipping, handling, and tax</description>
        <inlineHelpText>Order total sums all ship tos.</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testMDMOrderRollup.cls
@isTest
private class testMDMOrderRollup {

    static Account p;
    static Account ba;
    static Contact baCon;
    static Account personAccount;
    static RH_Order__c o;
    static RH_Order__c o2;
    static RH_Order__c oBusiness;

    static void setup(){
        
        PrepareData.populateCustomSettings();
        
        p = TestDataFactory.createPersonAccount(true);
        o = TestDataFactory.createRhOrder(false);
        o.Account_Sold_To__c = p.Id;
        personAccount = [select Id, PersonContactId, IsPersonAccount from Account where Id = :p.Id];
        o.Contact_Sold_To__c = personAccount.PersonContactId;
        o.Total_Order_Amount__c = 200.0;
        o.Status__c = 'Closed';
        insert o;            
    }
    
    static void setupBusinessAccount(){
        
        PrepareData.populateCustomSettings();
        
        ba = TestDataFactory.createAccount(true);
        baCon = TestDataFactory.createContacts(1, false)[0];
        baCon.AccountId = ba.Id;
        insert baCon;
        //
        oBusiness = TestDataFactory.createRhOrder(false);
        oBusiness.Account_Sold_To__c = ba.Id;
        oBusiness.Contact_Sold_To__c = baCon.Id;
        oBusiness.Total_Order_Amount__c = 200.0;
        oBusiness.Status__c = 'Closed';
        insert oBusiness;            
    }

    static testMethod void testOrderRollups() {
        
        Test.startTest();
        setup();
        o.Total_Order_Amount__c = 300.0;
        update o;             
        Test.stopTest();
       
        Account aPostRollup = [SELECT Id, PersonContactId, PersonContact.Total_Lifetime_Value__c from Account WHERE Id = :p.Id];
        System.AssertEquals(aPostRollup.PersonContact.Total_Lifetime_Value__c, 300.0);
         
    }

    static testMethod void testOrderRollupsCompany() {
        
        Test.startTest();
        setupBusinessAccount();   
        oBusiness.Total_Order_Amount__c = 900.0;
        update oBusiness;             
        Test.stopTest();
        
        Account aPostRollup = [SELECT Id, Total_Company_Lifetime_Value__c from Account WHERE Id = :ba.Id];
        System.AssertEquals(aPostRollup.Total_Company_Lifetime_Value__c, 900.0);
         
    }
        
    static testMethod void testOrderRollupsDelete() {
        
        Test.startTest();
        setup();   
        o2 = TestDataFactory.createRhOrder(false);
        o2.Account_Sold_To__c = p.Id;
        o2.Contact_Sold_To__c = personAccount.PersonContactId;
        o2.Total_Order_Amount__c = 500.0;
        o2.Status__c = 'Closed';
        insert o2;
        delete o2;                     
        Test.stopTest();
        
        Account aPostRollup = [SELECT Id, PersonContact.Total_Lifetime_Value__c from Account WHERE Id = :p.Id];
        System.AssertEquals(aPostRollup.PersonContact.Total_Lifetime_Value__c, 200.0);
        
    }  
    
    static testMethod void testOrderRollupsUndelete() {
        
        Test.startTest();
        setup();   
        o2 = TestDataFactory.createRhOrder(false);
        o2.Account_Sold_To__c = p.Id;
        o2.Contact_Sold_To__c = personAccount.PersonContactId;
        o2.Total_Order_Amount__c = 500.0;
        o2.Status__c = 'Closed';
        insert o2;
        delete o2;
        undelete o2;                     
        Test.stopTest();
        
        Account aPostRollup = [SELECT Id, PersonContact.Total_Lifetime_Value__c from Account WHERE Id = :p.Id];
        System.AssertEquals(aPostRollup.PersonContact.Total_Lifetime_Value__c, 700.0);
        
    }       
        
}