objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand.

This field will be used as a primary match for Demand Tools duplicate matching/ stewardship review</description>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Information__c.object
<CustomObject>
    <description>This table contains one record per contact point. A contact point is defined as a method for contacting the customer (examples include: Email, Phone, Social Handles).</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipName>Contact_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <label>Contact Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <description>This field specifies the match type to be processed by Salesforce duplicate match</description>
        <label>Match Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_View_CW_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System View CW Company</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Table__c</fullName>
        <label>Source Table</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SSVCreatorTest.cls
/**
 *  SSVCreatorTest.cls
 *  @description Apex Unit tests for data spawn
 *  @author Ernesto Valdes, Traction On Demand
 */
@isTest
private class SSVCreatorTest {
	
    @testSetup
    static void setup() {
    	TestDataFactory.turnMdmFeatureFlagsOn();
    }	

	/**
	 *  @description Tests data creation for a single unique company account
	 *  @author 	 Ernesto Valdes, Traction on Demand.
	 *  @date        2016-02-10
	 */
	@isTest static void testCreateUniqueCompany() {

		// Given
		// Create a unique source system view record for a company
		List<Source_System_View__c> testSSVList = TestDataFactory.createSSV(1, false);
		testSSVList[0].Source_Table__c = 'Salesforce Account';
		insert testSSVList;

		// Query the created object and all necessary fields using field selector
		testSSVList = SSVSelector.getSSVsById(new Map<Id, Source_System_View__c>(testSSVList).keySet());

		Test.startTest();

		// When
		// Call SSVCreator to spawn data from single given source system view record
		SSVCreator testSSVCreator = new SSVCreator(testSSVList);
		testSSVCreator.syncToCustomers().spawnData();

		Test.stopTest();

		// Then
		// Query source system view record and verify that it was linked to a created account
		Source_System_View__c testSSV = [
			SELECT Account__c, Contact__c
			FROM Source_System_View__c
			WHERE Id = :testSSVList[0].Id
		];
		system.assertNotEquals(null, testSSV.Account__c);
		system.assertEquals(null, testSSV.Contact__c);

		// Query created account and verify mappings
		Account testSpawnedAccount = [
			SELECT Id
			FROM Account
			WHERE Id = :testSSV.Account__c
		];
	}

	/**
	 *  @description Tests data creation for a single unique contact
	 *  @author 	 Ernesto Valdes, Traction on Demand.
	 *  @date        2016-02-10
	 */
	@isTest static void testCreateUniqueContactNewCompany() {

		// Given
		// Create a unique source system view record for a contact
		List<Source_System_View__c> testSSVList = TestDataFactory.createSSV(1, false);
		testSSVList[0].Source_Table__c = 'CW Customer';
		insert testSSVList;

		// Query the created object and all necessary fields using field selector
		testSSVList = SSVSelector.getSSVsById(new Map<Id, Source_System_View__c>(testSSVList).keySet());

		// Verify that record was linked to a created parent company record
		system.assertNotEquals(null, testSSVList[0].Source_System_View_CW_Company__c);

		// Verify that parent record is a company record
		List<Source_System_View__c> testParentSSVList = SSVSelector.getSSVsById(new Set<Id>{testSSVList[0].Source_System_View_CW_Company__c});
		system.assertEquals('Company', testParentSSVList[0].Match_Type__c);
		testSSVList.addAll(testParentSSVList);
		
		Test.startTest();
		//Reporter.startLogging();

		// When
		// Call SSVCreator to spawn data from single given source system view record
		SSVCreator testSSVCreator = new SSVCreator(testSSVList);
		testSSVCreator.syncToCustomers().spawnData();
		
		//Reporter.stopLogging();
		Test.stopTest();

		// Then
		// Query source system view record and verify that it was linked to a created account and contact
		Source_System_View__c testSSV = [
			SELECT Account__c, Contact__c, Source_System_View_CW_Company__c, Source_System_View_CW_Company__r.Account__c
			FROM Source_System_View__c
			WHERE Id = :testSSVList[0].Id
		];
		system.assertNotEquals(null, testSSV.Contact__c);
		system.assertNotEquals(null, testSSV.Source_System_View_CW_Company__c);
		system.assertNotEquals(null, testSSV.Account__c);
		system.assertEquals(testSSV.Source_System_View_CW_Company__r.Account__c, testSSV.Account__c);

		// Query created account and verify mappings
		Account testSpawnedAccount = [
			SELECT Id
			FROM Account
			WHERE Id = :testSSV.Account__c
		];

		// Query created contact and verify mappings
		Contact testSpawnedContact = [
			SELECT Id
			FROM Contact
			WHERE Id = :testSSV.Contact__c
		];
		
		// Verify contact information was created
		List<Contact_Information__c> testContactInfos = [
			SELECT Id
			FROM Contact_Information__c
			WHERE Contact__c = :testSpawnedContact.Id
		];
		system.assertNotEquals(true, testContactInfos.isEmpty(), 'No contact information was created.');
		system.assertEquals(2, testContactInfos.size());

		// Verify address information was created
		List<Customer_Address__c> testCustomerAddresses = [
			SELECT Id, Address__c
			FROM Customer_Address__c
			WHERE Contact__c = :testSpawnedContact.Id
		];
		system.assertNotEquals(true, testCustomerAddresses.isEmpty(), 'No customer address was created.');
		system.assertEquals(1, testCustomerAddresses.size());

		// Verify address was created
		List<Address__c> testAddress = [
			SELECT Id
			FROM Address__c
			WHERE Id = :testCustomerAddresses[0].Address__c
		];
		system.assertNotEquals(true, testAddress.isEmpty(), 'No address was created.');
		system.assertEquals(1, testAddress.size());
	}

	/**
	 *  @description Tests data creation for a single unique contact
	 *  @author 	 Ernesto Valdes, Traction on Demand.
	 *  @date        2016-02-10
	 */
	@isTest static void testCreateUniqueContactExistingCompany() {

		// Given

		// CREATE EXISTING COMPANY
		// Create a source system view record for an existing company
		List<Source_System_View__c> testSSVList = TestDataFactory.createSSV(1, false);
		testSSVList[0].Source_Table__c = 'Salesforce Account';
		testSSVList[0].Duplicate_Set_ID__c = 'TESTDUPLICATEID';
		insert testSSVList;

		// Query the created object and all necessary fields using field selector
		testSSVList = SSVSelector.getSSVsById(new Map<Id, Source_System_View__c>(testSSVList).keySet());

		// Call SSVCreator to spawn data from single given source system view record
		SSVCreator testSSVCreator = new SSVCreator(testSSVList);
		testSSVCreator.syncToCustomers().spawnData();

		// Query source system view record and verify that it was linked to a created account
		Source_System_View__c testExistingSSV = [
			SELECT Account__c, Contact__c
			FROM Source_System_View__c
			WHERE Id = :testSSVList[0].Id
		];
		system.assertNotEquals(null, testExistingSSV.Account__c);
		system.assertEquals(null, testExistingSSV.Contact__c);
		Id existingAccountId = testExistingSSV.Account__c;

		// CREATE NEW CONTACT FOR EXISTING COMPANY
		// Create a unique source system view record for a contact
		testSSVList = TestDataFactory.createSSV(1, false);
		testSSVList[0].Source_Table__c = 'CW Customer';
		insert testSSVList;

		// Query the created object and all necessary fields using field selector
		testSSVList = SSVSelector.getSSVsById(new Map<Id, Source_System_View__c>(testSSVList).keySet());

		// Verify that record was linked to a created parent company record
		system.assertNotEquals(null, testSSVList[0].Source_System_View_CW_Company__c);

		// Verify that parent record is a company record
		// set its duplicate id and link to an existing company
		List<Source_System_View__c> testParentSSVList = SSVSelector.getSSVsById(new Set<Id>{testSSVList[0].Source_System_View_CW_Company__c});
		system.assertEquals('Company', testParentSSVList[0].Match_Type__c);
		testParentSSVList[0].Duplicate_Set_ID__c = 'TESTDUPLICATEID';
		testParentSSVList[0].Account__c = existingAccountId;
		update testParentSSVList;

		Test.startTest();

		// When
		// Call SSVCreator to spawn data from single given source system view record
		testSSVCreator = new SSVCreator(testSSVList);
		testSSVCreator.syncToCustomers().spawnData();

		Test.stopTest();

		// Then
		// Query source system view record and verify that it was linked to an existing account and new contact
		Source_System_View__c testSSV = [
			SELECT Account__c, Contact__c, Duplicate_Set_ID__c,
					Source_System_View_CW_Company__c, Source_System_View_CW_Company__r.Account__c
			FROM Source_System_View__c
			WHERE Id = :testSSVList[0].Id
		];
		system.assertNotEquals(null, testSSV.Contact__c);
		system.assertNotEquals(null, testSSV.Source_System_View_CW_Company__c);
		system.assertNotEquals(null, testSSV.Account__c);
		system.assertEquals(testSSV.Source_System_View_CW_Company__r.Account__c, testSSV.Account__c);
		system.assertEquals(existingAccountId, testSSV.Account__c);

		// Query created account and verify mappings
		Account testSpawnedAccount = [
			SELECT Id, Duplicate_Set_ID__c
			FROM Account
			WHERE Id = :testSSV.Account__c
		];
		system.assertEquals('TESTDUPLICATEID', testSpawnedAccount.Duplicate_Set_ID__c);

		// Query created contact and verify mappings
		Contact testSpawnedContact = [
			SELECT Id
			FROM Contact
			WHERE Id = :testSSV.Contact__c
		];
		
		// Verify contact information was created
		List<Contact_Information__c> testContactInfos = [
			SELECT Id
			FROM Contact_Information__c
			WHERE Contact__c = :testSpawnedContact.Id
		];
		system.assertNotEquals(true, testContactInfos.isEmpty(), 'No contact information was created.');
		system.assertEquals(2, testContactInfos.size());

		// Verify address information was created
		List<Customer_Address__c> testCustomerAddresses = [
			SELECT Id, Address__c
			FROM Customer_Address__c
			WHERE Contact__c = :testSpawnedContact.Id
		];
		system.assertNotEquals(true, testCustomerAddresses.isEmpty(), 'No customer address was created.');
		system.assertEquals(1, testCustomerAddresses.size());

		// Verify address was created
		List<Address__c> testAddress = [
			SELECT Id
			FROM Address__c
			WHERE Id = :testCustomerAddresses[0].Address__c
		];
		system.assertNotEquals(true, testAddress.isEmpty(), 'No address was created.');
		system.assertEquals(1, testAddress.size());
		
	}

	/**
	 *  @description Tests data creation for a single unique person account
	 *  @author 	 Ernesto Valdes, Traction on Demand.
	 *  @date        2016-02-10
	 */
	@isTest static void testCreateUniquePerson() {

		// Given
		// Create a unique source system view record for a company
		List<Source_System_View__c> testSSVList = TestDataFactory.createSSV(1, false);
		testSSVList[0].Company_Name__c = null;
		testSSVList[0].Address_2__c = null;
		insert testSSVList;

		// Query the created object and all necessary fields using field selector
		testSSVList = SSVSelector.getSSVsById(new Map<Id, Source_System_View__c>(testSSVList).keySet());

		Test.startTest();

		// When
		// Call SSVCreator to spawn data from single given source system view record
		SSVCreator testSSVCreator = new SSVCreator(testSSVList);
		testSSVCreator.syncToCustomers().spawnData();

		Test.stopTest();

		// Then
		// Query source system view record and verify that it was linked to a created account
		Source_System_View__c testSSV = [
			SELECT Account__c, Contact__c
			FROM Source_System_View__c
			WHERE Id = :testSSVList[0].Id
		];
		system.assertNotEquals(null, testSSV.Account__c);
		system.assertNotEquals(null, testSSV.Contact__c);

		// Query created account and verify mappings
		Account testSpawnedAccount = [
			SELECT Id, IsPersonAccount, BillingStreet
			FROM Account
			WHERE Id = :testSSV.Account__c
		];
		system.assertEquals(true, testSpawnedAccount.IsPersonAccount);
		System.debug(LoggingLevel.ERROR, 'BillingStreet: ' + testSpawnedAccount.BillingStreet);

		// Verify address information was created
		List<Customer_Address__c> testCustomerAddresses = [
			SELECT Id, Address__c
			FROM Customer_Address__c
			WHERE Contact__c = :testSSV.Contact__c
		];
		system.assertNotEquals(true, testCustomerAddresses.isEmpty(), 'No customer address was created.');
		system.assertEquals(1, testCustomerAddresses.size());

		// Verify address was created
		List<Address__c> testAddress = [
			SELECT Id
			FROM Address__c
			WHERE Id = :testCustomerAddresses[0].Address__c
		];
		system.assertNotEquals(true, testAddress.isEmpty(), 'No address was created.');
		system.assertEquals(1, testAddress.size());
	}

	/**
	 *  @description Tests data creation for a single duplicate company account
	 *  @author 	 Ernesto Valdes, Traction on Demand.
	 *  @date        2016-02-10
	 */
	@isTest static void testCreateDuplicateCompany() {

		// Given
		// Create duplicate source system view records for a company
		Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
		Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
		testSSV1.Source_Table__c = 'Salesforce Account';
		testSSV2.Source_Table__c = 'Salesforce Account';
		testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATEID';
		testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATEID';
		List<Source_System_View__c> testSSVList = new List<Source_System_View__c>{testSSV1, testSSV2};
		insert testSSVList;

		// Query the created object and all necessary fields using field selector
		testSSVList = SSVSelector.getSSVsById(new Map<Id, Source_System_View__c>(testSSVList).keySet());

		// Create a consolidated grouping of duplicate records
		List<SSVConsolidated> consolidatedRecords = new List<SSVConsolidated>();
		SSVConsolidated consolidatedRecord = new SSVConsolidated(new SSVCleansed(testSSVList[0]));
		consolidatedRecord.addSSV(new SSVCleansed(testSSVList[1]));
		consolidatedRecords.add(consolidatedRecord);

		Test.startTest();
		
		// When
		// Call SSVCreator to spawn data from single given source system view record
		SSVCreator testSSVCreator = new SSVCreator(consolidatedRecords);
		testSSVCreator.syncToCustomers().spawnData();

		Test.stopTest();

		// Then
		// Query source system view records and verify that they were linked to a created account
		testSSVList = [
			SELECT Account__c, Contact__c
			FROM Source_System_View__c
			WHERE Id IN :testSSVList
		];
		system.assertEquals(2, testSSVList.size());
		system.assertNotEquals(null, testSSVList[0].Account__c);
		system.assertEquals(null, testSSVList[0].Contact__c);
		system.assertNotEquals(null, testSSVList[1].Account__c);
		system.assertEquals(null, testSSVList[1].Contact__c);
		system.assertEquals(testSSVList[0].Account__c, testSSVList[1].Account__c);
		system.assertEquals(testSSVList[0].Contact__c, testSSVList[1].Contact__c);

		// Query created account and verify mappings
		Account testSpawnedAccount = [
			SELECT Id, Duplicate_Set_ID__c
			FROM Account
			WHERE Id = :testSSVList[0].Account__c
		];
		system.assertEquals('TESTDUPLICATEID', testSpawnedAccount.Duplicate_Set_ID__c);
	}

	/**
	 *  @description Tests data creation for a single Duplicate person account
	 *  @author 	 Ernesto Valdes, Traction on Demand.
	 *  @date        2016-02-10
	 */
	@isTest static void testCreateDuplicatePerson() {

		// Given
		// Create duplicate source system view records for a person
		Source_System_View__c testSSV1 = TestDataFactory.createSSV(1, false)[0];
		Source_System_View__c testSSV2 = TestDataFactory.createSSV(1, false)[0];
		testSSV1.Duplicate_Set_ID__c = 'TESTDUPLICATEID';
		testSSV2.Duplicate_Set_ID__c = 'TESTDUPLICATEID';
		testSSV1.Company_Name__c = null;
		testSSV2.Company_Name__c = null;
		List<Source_System_View__c> testSSVList = new List<Source_System_View__c>{testSSV1, testSSV2};
		insert testSSVList;

		// Query the created object and all necessary fields using field selector
		testSSVList = SSVSelector.getSSVsById(new Map<Id, Source_System_View__c>(testSSVList).keySet());

		// Create a consolidated grouping of duplicate records
		List<SSVConsolidated> consolidatedRecords = new List<SSVConsolidated>();
		SSVConsolidated consolidatedRecord = new SSVConsolidated(new SSVCleansed(testSSVList[0]));
		consolidatedRecord.addSSV(new SSVCleansed(testSSVList[1]));
		consolidatedRecords.add(consolidatedRecord);

		Test.startTest();
		Reporter.startLogging();
		
		// When
		// Call SSVCreator to spawn data from single given source system view record
		SSVCreator testSSVCreator = new SSVCreator(consolidatedRecords);
		testSSVCreator.syncToCustomers().spawnData();

		Reporter.stopLogging();
		Test.stopTest();

		// Then
		// Query source system view records and verify that they were linked to a created account
		testSSVList = [
			SELECT Account__c, Contact__c
			FROM Source_System_View__c
			WHERE Id IN :testSSVList
		];
		system.assertEquals(2, testSSVList.size());
		system.assertNotEquals(null, testSSVList[0].Account__c);
		system.assertNotEquals(null, testSSVList[0].Contact__c);
		system.assertNotEquals(null, testSSVList[1].Account__c);
		system.assertNotEquals(null, testSSVList[1].Contact__c);
		system.assertEquals(testSSVList[0].Account__c, testSSVList[1].Account__c);
		system.assertEquals(testSSVList[0].Contact__c, testSSVList[1].Contact__c);

		// Query created account and verify mappings
		Account testSpawnedAccount = [
			SELECT Id, IsPersonAccount, Duplicate_Set_ID__c
			FROM Account
			WHERE Id = :testSSVList[0].Account__c
		];
		system.assertEquals(true, testSpawnedAccount.IsPersonAccount);
		system.assertEquals('TESTDUPLICATEID', testSpawnedAccount.Duplicate_Set_ID__c);

		// Verify address information was created
		List<Customer_Address__c> testCustomerAddresses = [
			SELECT Id, Address__c
			FROM Customer_Address__c
			WHERE Contact__c = :testSSVList[0].Contact__c
		];
		system.assertNotEquals(true, testCustomerAddresses.isEmpty(), 'No customer address was created.');
		system.assertEquals(1, testCustomerAddresses.size());

		// Verify address was created
		List<Address__c> testAddress = [
			SELECT Id
			FROM Address__c
			WHERE Id = :testCustomerAddresses[0].Address__c
		];
		system.assertNotEquals(true, testAddress.isEmpty(), 'No address was created.');
		system.assertEquals(1, testAddress.size());
	}
}