objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <fields>
        <fullName>Value_Text__c</fullName>
        <label>Value - Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

objects/Company_Account_SSV_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field mapping for account to ssv records. (Non person accounts)</description>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>Source Field mapping to SSV Field</description>
        <inlineHelpText>This contains the API field name of the relevant field from Account object</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SSV field that will be mapped to Account field</description>
        <inlineHelpText>This contains the API field name of the relevant field from Source System View object.</inlineHelpText>
        <label>Target Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company Account SSV Field Mapping</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Alternate_Email__c</fullName>
        <description>If customer has two email addresses, list secondary here.</description>
        <label>Alternate Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phone_Extension__c</fullName>
        <inlineHelpText>Enter the extension for the primary phone number, if any.  Enter only dial numbers (exclude &quot;x&quot; or &quot;ext&quot;</inlineHelpText>
        <label>Phone Extension</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Information__c.object
<CustomObject>
    <description>This table contains one record per contact point. A contact point is defined as a method for contacting the customer (examples include: Email, Phone, Social Handles).</description>
    <fields>
        <fullName>Contact_Information_Medium__c</fullName>
        <label>Contact Information Medium</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Extension__c</fullName>
        <label>Phone Extension</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <label>Contact Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>For email contact information</description>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>Fax</fullName>
        <active>true</active>
        <description>For fax contact information</description>
        <label>Fax</label>
    </recordTypes>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <description>For phone contact information</description>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_SSV_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field mapping for contact to ssv records. (B2B Contacts)</description>
    <fields>
        <fullName>Source_Field__c</fullName>
        <inlineHelpText>This contains the API field name of the relevant field from Contact object</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <inlineHelpText>This contains the API field name of the relevant field from Source System View object</inlineHelpText>
        <label>Target Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contact SSV Field Mapping</label>
</CustomObject>

objects/Order_Role__c.object
<CustomObject>
    <description>This table contains mappings of contacts related to an order</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Sold To Account on the Order.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Roles (Account)</relationshipLabel>
        <relationshipName>Order_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Record Linkage for Order Contact Role</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Order_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Role__c</fullName>
        <label>Order Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliated Person</fullName>
                </value>
                <value>
                    <fullName>RH Designer</fullName>
                </value>
                <value>
                    <fullName>External Designer</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Sold To</fullName>
                </value>
                <value>
                    <fullName>Partial Ship To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Role</label>
    <nameField>
        <displayFormat>OR-{0000000}</displayFormat>
        <label>Order Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_View_CW_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System View CW Company</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Table__c</fullName>
        <label>Source Table</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactsTest.cls
/**
 * Test class for contact triggers
 * @author Zi Zhang + John Rogers, Traction on Demand
 * @date   2016-02-27
 */
@isTest
public class ContactsTest {

	static {
		TestDataFactory.turnMdmFeatureFlagsOn();
	}
		
    private static Id companyAccountRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contract').getRecordTypeId();
    static Account testAccount;
    static Contact masterContact, mergeContact, testContact;
    static RH_Order__c testOrder;
    static Order_Role__c testOrderRole;

    // Test creation of no CI records due to integration user running
    static testMethod void test_createContactInformationRecords_integration() {
        User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = true;
        System.runAs(u) {
            Contact c = TestDataFactory.createContact(false);
            c.Email = 'test@test.com';
            c.Alternate_Email__c = 'test2@test.com';
            c.Phone = '456';
            c.Phone_Extension__c = 789;
            c.MobilePhone = '101112';
            c.Fax = '123';
            insert c;

            List<Contact_Information__c> cis = [
                SELECT Is_Primary__c,
                    Contact_Information_Medium__c, 
                    Email__c,
                    RecordTypeId
                FROM Contact_Information__c 
                WHERE Contact__c = :c.Id
            ];

            System.assertEquals(0, cis.size());
        }
    }

    // Test creation of related CI records on insert
    static testMethod void test_createContactInformationRecords_all() {
        User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;
        System.runAs(u) {
            Contact c = TestDataFactory.createContact(false);
            c.Email = 'test@test.com';
            c.Alternate_Email__c = 'test2@test.com';
            c.Phone = '456';
            c.Phone_Extension__c = 789;
            c.MobilePhone = '101112';
            c.Fax = '123';
            insert c;

            List<Contact_Information__c> cis = [
                SELECT Is_Primary__c,
                    Contact_Information_Medium__c, 
                    Email__c,
                    RecordTypeId
                FROM Contact_Information__c 
                WHERE Contact__c = :c.Id
            ];

            System.assertEquals(0, cis.size());
        }
    }

    // Test creation of no CI records on insert
    static testMethod void test_createContactInformationRecords_none() {
        User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;
        System.runAs(u) {
            Contact c = TestDataFactory.createContact(false);
            c.Email = null;
            c.Alternate_Email__c = null;
            c.Phone = null;
            c.Phone_Extension__c = null;
            c.MobilePhone = null;
            c.Fax = null;
            insert c;

            List<Contact_Information__c> cis = [
                SELECT Is_Primary__c,
                    Contact_Information_Medium__c, 
                    Email__c,
                    RecordTypeId
                FROM Contact_Information__c 
                WHERE Contact__c = :c.Id
            ];

            System.assertEquals(0, cis.size());
        }
    }

    /**
     * Test Business Contact triggers - upsert ssv records
     * @author Zi Zhang, Traction on Demand
     * @date   2016-03-09
     */
    public static testMethod void testBusinessContactTrigger() {
        User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;
        
        System.runAs(u) {
            System.assertEquals(true, String.isNotEmpty(companyAccountRecTypeId), 'Company Account Record Type not found.');
            createCompanyAccountFieldMappingSettings();
            createBusinessContactFieldMappingSettings();

            // Insert new company account
            testAccount = new Account(Name = 'Test Company Account', RecordTypeId = companyAccountRecTypeId);
            insert testAccount;

            System.assertNotEquals(null, testAccount.Id, 'Error inserting account.');

            List<Source_System_View__c> resultCompanySSVs = [SELECT Id, Name, Account__c, Company_Name__c, Contact__c, First_Name__c, Last_Name__c 
                                                        FROM Source_System_View__c 
                                                        WHERE Account__c = :testAccount.Id];

            System.assertEquals(1, resultCompanySSVs.size(), 'Related Account SSV record does not exist.');

            testContact = new Contact(FirstName = 'Test Contact FName', LastName = 'Test Contact LName', AccountId = testAccount.Id, MailingStreet='123 Fake St.');
            insert testContact;

            List<Source_System_View__c> resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c, Contact__c, First_Name__c, Last_Name__c, Source_System_View_CW_Company__c 
                                                        FROM Source_System_View__c 
                                                        WHERE Contact__c = :testContact.Id];
            System.assertEquals(1, resultSSVs.size(), 'SSV record does not exist.');
            System.assertEquals('SFDC-' + testContact.Id, resultSSVs[0].Name, 'Name field not mapped.');
            System.assertEquals(testContact.Id, resultSSVs[0].Contact__c, 'Contact__c field not mapped.');
            System.assertEquals(testAccount.Name, resultSSVs[0].Company_Name__c, 'Company_Name__c field not mapped.');
            System.assertEquals(testContact.FirstName, resultSSVs[0].First_Name__c, 'First_Name__c field not mapped.');
            System.assertEquals(testContact.LastName, resultSSVs[0].Last_Name__c, 'Last_Name__c field not mapped.');
            System.assertEquals(testAccount.Id, resultSSVs[0].Account__c, 'Account__c field not mapped.');
            System.assertEquals(resultCompanySSVs[0].Id, resultSSVs[0].Source_System_View_CW_Company__c, 'SSV record not linked to Company SSV record.');

            // Update key fields on company account
            testContact.FirstName = 'Test FName modified';
            update testContact;

            resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c, Contact__c, First_Name__c, Last_Name__c FROM Source_System_View__c WHERE Contact__c = :testContact.Id];

            System.assertEquals(1, resultSSVs.size(), 'SSV record does not exist.');
            System.assertEquals(testContact.FirstName, resultSSVs[0].First_Name__c, 'First_Name__c field not mapped.');

            delete testContact;

            resultSSVs = [SELECT Id FROM Source_System_View__c WHERE Contact__c = :testContact.Id];

            System.assertEquals(0, resultSSVs.size(), 'SSV record was not deleted.');
        }
    }

    /**
     * Test Business Contact triggers and Account triggers on lead convert
     * @author Zi Zhang, Traction on Demand
     * @date   2016-03-09
     */
    public static testMethod void testBusinessContactTriggerOnLeadConvert() {
        User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;

        System.runAs(u) {
            createCompanyAccountFieldMappingSettings();
            createBusinessContactFieldMappingSettings();
			createApplicationSettings();			

            // Create test lead to convert
            Lead testLead = new Lead();
            testLead.FirstName = 'Test First';
            testLead.LastName = 'Test Last';
            testLead.Company = 'Test Co';
            insert testLead;

            Test.StartTest();
            Database.LeadConvert lc = new database.LeadConvert();
            lc.setLeadId(testLead.id);

            LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
            lc.setConvertedStatus(convertStatus.MasterLabel);

            Database.LeadConvertResult lcr = Database.convertLead(lc);
            System.assert(lcr.isSuccess());

            Test.StopTest();

            List<Contact> contactResult = [Select Id, FirstName, LastName, AccountId, Account.IsPersonAccount FROM Contact];
            List<Account> accountResult = [Select Id, Name, X12_Digit_Member__c FROM Account];

            System.assertEquals(1, accountResult.size(), 'Lead Convert did not create an Account');
            System.assertNotEquals(NULL, accountResult[0].X12_Digit_Member__c, 'Lead Convert did not create a trade-id for the account');
            System.assertEquals(1, contactResult.size(), 'Lead Convert did not create a Contact');
            System.assertEquals(accountResult[0].Id, contactResult[0].AccountId, 'Lead Convert did not link Contact and Account');

            List<Source_System_View__c> resultCompanySSVs = [SELECT Id, Name, Account__c, Company_Name__c, Contact__c, First_Name__c, Last_Name__c 
                                                        FROM Source_System_View__c 
                                                        WHERE Source_Table__c = 'Salesforce Account'];

            System.assertEquals(1, resultCompanySSVs.size(), 'Account SSV record does not exist.');

            List<Source_System_View__c> resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c, Contact__c, First_Name__c, Last_Name__c, Source_System_View_CW_Company__c 
                                                        FROM Source_System_View__c 
                                                        WHERE Contact__c = :contactResult[0].Id];
            System.assertEquals(1, resultSSVs.size(), 'SSV record does not exist.');
            System.assertEquals('SFDC-' + contactResult[0].Id, resultSSVs[0].Name, 'Name field not mapped.');
            System.assertEquals(contactResult[0].Id, resultSSVs[0].Contact__c, 'Contact__c field not mapped.');
            System.assertEquals(accountResult[0].Name, resultSSVs[0].Company_Name__c, 'Company_Name__c field not mapped.');
            System.assertEquals(contactResult[0].FirstName, resultSSVs[0].First_Name__c, 'First_Name__c field not mapped.');
            System.assertEquals(contactResult[0].LastName, resultSSVs[0].Last_Name__c, 'Last_Name__c field not mapped.');
            System.assertEquals(accountResult[0].Id, resultSSVs[0].Account__c, 'Account__c field not mapped.');
            System.assertEquals(resultCompanySSVs[0].Id, resultSSVs[0].Source_System_View_CW_Company__c, 'SSV record not linked to Company SSV record.');
        }
    }

    /*********************** Test data custom settings field mapping ****************************/
    private static void createBusinessContactFieldMappingSettings() {
        List<Contact_SSV_Field_Mapping__c> settings = new List<Contact_SSV_Field_Mapping__c>();
        settings.add(new Contact_SSV_Field_Mapping__c(Name = 'FM1', Source_Field__c = 'ID', Target_Field__c = 'Name'));
        settings.add(new Contact_SSV_Field_Mapping__c(Name = 'FM3', Source_Field__c = 'ID', Target_Field__c = 'Contact__c'));
        settings.add(new Contact_SSV_Field_Mapping__c(Name = 'FM4', Source_Field__c = 'FirstName', Target_Field__c = 'First_Name__c'));
        settings.add(new Contact_SSV_Field_Mapping__c(Name = 'FM5', Source_Field__c = 'LastName', Target_Field__c = 'Last_Name__c'));
        settings.add(new Contact_SSV_Field_Mapping__c(Name = 'FM6', Source_Field__c = 'ID', Target_Field__c = 'EXT_Source_System_Customer_ID__c'));
        settings.add(new Contact_SSV_Field_Mapping__c(Name = 'FM7', Source_Field__c = 'AccountId', Target_Field__c = 'Account__c'));

        insert settings;
    } 

    private static void createCompanyAccountFieldMappingSettings() {
        List<Company_Account_SSV_Field_Mapping__c> settings = new List<Company_Account_SSV_Field_Mapping__c>();
        settings.add(new Company_Account_SSV_Field_Mapping__c(Name = 'FM1', Source_Field__c = 'ID', Target_Field__c = 'Name'));
        settings.add(new Company_Account_SSV_Field_Mapping__c(Name = 'FM2', Source_Field__c = 'ID', Target_Field__c = 'Account__c'));
        settings.add(new Company_Account_SSV_Field_Mapping__c(Name = 'FM3', Source_Field__c = 'Name', Target_Field__c = 'Company_Name__c'));

        insert settings;
    } 
    
    private static void createApplicationSettings() {
    	List<Application_Settings__c> settings = new LIst<Application_Settings__c>();
    	settings.add(new Application_Settings__c(Name = 'QuoteCloneStatusToCreatePortalUser', Value_Text__c = 'Quote finalized - Payment Link Sent'));
    	insert settings;
    }
}