objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <fields>
        <fullName>Value_Text__c</fullName>
        <label>Value - Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

objects/FieldIdLookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>lookup values for custom Field API names and field Id&apos;s. Used for creating pre-populated values for buttons</description>
    <fields>
        <fullName>FieldId__c</fullName>
        <description>Salesforce Field Id</description>
        <label>FieldId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>Name of the field</description>
        <label>FieldName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the object the field resides on</description>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Field Id Lookup</label>
</CustomObject>

objects/Gallery_Furniture__c.object
<CustomObject>
    <description>Represents furniture located in a Gallery.</description>
    <fields>
        <fullName>Gallery_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gallery Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Name</field>
                <operation>startsWith</operation>
                <value>Gallery</value>
            </filterItems>
            <filterItems>
                <field>Account.Name</field>
                <operation>contains</operation>
                <value>0,1,2,3,4,5,6,7,8,9</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Gallery Furniture</relationshipLabel>
        <relationshipName>Gallery_Furniture</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gallery_Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gallery Associate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Gallery_Furniture</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HDL_Checklist__c</fullName>
        <label>HDL Checklist #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Piece__c</fullName>
        <label>Piece #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Gallery Furniture</relationshipLabel>
        <relationshipName>Gallery_Furniture</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Register__c</fullName>
        <label>Register #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Date__c</fullName>
        <label>Sold Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Alternate_Phone__c</fullName>
        <label>Sold To Alternate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_To_City__c</fullName>
        <label>Sold To City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Email__c</fullName>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_To_First_Name__c</fullName>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Last_Name__c</fullName>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Phone__c</fullName>
        <label>Sold To Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_To_Postal_Code__c</fullName>
        <label>Sold To Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_State_Province__c</fullName>
        <label>Sold To State/Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Pieces__c</fullName>
        <label>Total Pieces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Gallery Furniture</label>
    <nameField>
        <displayFormat>GF-{00000000}</displayFormat>
        <label>Gallery Furniture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gallery Furniture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Actual_Product_Name__c</fullName>
        <description>to house the text product name for use in quotes</description>
        <label>Actual Product Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CW_External_Id__c</fullName>
        <description>Commercial Ware External Id</description>
        <externalId>true</externalId>
        <label>CW External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMMSSku__c</fullName>
        <description>ipim field map: CWLINK, where field is concatenation of fields Item#,  Color Code, Size Code.  032111LALO</description>
        <externalId>true</externalId>
        <label>DMMSSku</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direct_Current_Price__c</fullName>
        <description>ipim field map: Direct Current Price 032110LALO</description>
        <label>Direct Current Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ELC__c</fullName>
        <description>Added per Trade Planning Manager to assist in calculating margin. 051809LALO.   ipim field map: Direct Landed Cost. 032111LALO</description>
        <inlineHelpText>Use Estimated Landed Cost (ELC)</inlineHelpText>
        <label>ELC</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SKU_Ship_Via__c</fullName>
        <label>Product Ship Via</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC__c</fullName>
        <label>UPC</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/testGalleryFurnitureCtlExt.cls
@isTest
private class testGalleryFurnitureCtlExt {
	
	/*
	 *	Test methods for testing GalleryFurnitureCtlExt.cls.
	 *
	 */
	
	static testMethod void gfTest1() {
		
		// Create test data - User, Accounts, Product, FieldIdLookUp
		String galleryName = 'Gallery 006 - Corte Madera';
		User testUser = [select Id, Gallery__c from User where Id = :UserInfo.getUserId()];
		testUser.Gallery__c = galleryName;
		update testUser;
		
		Map<String,Schema.RecordTypeInfo> rtAccMap = Schema.SObjectType.Account.getRecordTypeInfosByName();
		List<Account> accList = new List<Account>();
		accList.add(new Account(
			Name = 'Gallery 006 - Corte Madera',
			RecordTypeId = rtAccMap.get('Internal'). getRecordTypeId(),
			Type = 'Internal',
			Gallery__c = '6')
		);
		accList.add(new Account(
			Name = 'RH DC 97 (SoCal)',
			RecordTypeId = rtAccMap.get('Internal'). getRecordTypeId(),
			Type = 'Contract',
			HDL_Code__c = '97')
		);
		insert accList;
		accList[0].Furniture_Return_DC__c = accList[1].Id;
		update accList[0];
		
		Product2 prd = new Product2(Actual_Product_Name__c = '59140061BMCO', Direct_Current_Price__c = 4645.00, DMMSSku__c = '59140061BMCO', CW_External_Id__c = '59140061BMCO', ELC__c = 1901.79, IsActive = true, Name = '59140061BMCO', UPC__c = '461102030003', SKU_Ship_Via__c = 'Ship');
        insert prd;
		
		List<FieldIdLookup__c> fieldIdList = new List<FieldIdLookup__c>();
		fieldIdList.add(new FieldIdLookup__c(
			Name = 'Gallery_Furniture.Gallery_Account',
			FieldId__c = '00N2C000000G2uy',
			FieldName__c = 'Gallery_Account',
			ObjectName__c = 'Gallery_Furniture')
		);
		fieldIdList.add(new FieldIdLookup__c(
			Name = 'Gallery_Furniture.Gallery_Associate',
			FieldId__c = '00N2C000000G2vS',
			FieldName__c = 'Gallery_Associate',
			ObjectName__c = 'Gallery_Furniture')
		);
		
		fieldIdList.add(new FieldIdLookup__c(
			Name = 'Gallery_Furniture.Product',
			FieldId__c = '00N2C000000G2v8',
			FieldName__c = 'Product',
			ObjectName__c = 'Gallery_Furniture')
		);
		fieldIdList.add(new FieldIdLookup__c(
			Name = 'Gallery_Furniture.UPC',
			FieldId__c = '00N2C000000G4np',
			FieldName__c = 'UPC',
			ObjectName__c = 'Gallery_Furniture')
		);
		insert fieldIdList;
		
		Application_Settings__c appSetting = new Application_Settings__c(
			Name = 'ProductImageNotAvailableURL',
			Value_Text__c = 'http://media.restorationhardware.com/is/image/rhis/noimage?wid=500&hei=500&fmt=gif&qlt=85,1&op_sharpen=0&quantize=adaptive,diffuse,255,&resMode=bilin&op_usm=0,0,0,0&iccEmbed=1'
		);
		insert appSetting;
		
		// Start the test
		Gallery_Furniture__c galFurn = new Gallery_Furniture__c();
		ApexPages.StandardController std = new ApexPages.StandardController(galFurn);
		ApexPages.currentPage().getParameters().put('productId', prd.Id);
		GalleryFurnitureCtlExt ctl = new GalleryFurnitureCtlExt(std);
		
		ctl.initGalleryFurniture();
		system.assert(!ctl.fatalError);
		
		galFurn = new Gallery_Furniture__c(
			Gallery_Account__c = accList[0].Id,
			Gallery_Associate__c = UserInfo.getUserId(),
			Product__c = prd.Id,
			UPC__c = '459336340005',
			Sold__c = true,
			Sold_Date__c = system.today(),
			Register__c = '7',
			Transaction__c = '123-6B',
			HDL_Checklist__c = '56ABC',
			Piece__c = 1,
			Total_Pieces__c = 1,
			Sold_To_First_Name__c = 'Billy',
			Sold_To_Last_Name__c = 'Bob',
			Sold_To_Address_1__c = '123 Main Street',
			Sold_To_City__c = 'San Francisco',
			Sold_To_State_Province__c = 'CA',
			Sold_To_Postal_Code__c = '94107',
			Sold_To_Phone__c = '555-555-5555',
			Sold_To_Alternate_Phone__c = '123-456-7890',
			Sold_To_Email__c = 'billybob@rh.com'
		);
		insert galFurn;
		
		ApexPages.StandardController std1 = new ApexPages.StandardController(galFurn);
		ApexPages.currentPage().getParameters().put('galleryFurnitureId', galFurn.Id);
		GalleryFurnitureCtlExt ctl1 = new GalleryFurnitureCtlExt(std1);
		
		ctl1.initFurnitureStatusForm();
		system.assert(!ctl1.fatalError);
	}
}