objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key_Hash__c</fullName>
        <externalId>true</externalId>
        <label>Address Match Key Hash</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key__c</fullName>
        <label>Address Match Key</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <inlineHelpText>For United States, enter US. 
For Canada, enter CA. 
Leave blank for all other countries.</inlineHelpText>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Principal_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AddressesTest.cls
@isTest
private class AddressesTest {
	
    static String STREET = 'test street';
    static String CITY = 'Vancouver';
    static String COUNTRY_CODE = 'CA';
    static String STATE = 'BC';
    static String POSTAL_CODE = 'test zip';

    static String STREET_2 = 'test street2';
    static String CITY_2 = 'Vancouver2';
    static String COUNTRY_CODE_2 = 'US';
    static String STATE_2 = 'DC';
    static String POSTAL_CODE_2 = 'test zip2';

    @testSetup
    static void setup() {
    	TestDataFactory.turnMdmFeatureFlagsOn();
        TestDataFactoryHelper.COUNTER = -10;
        User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;
        System.runAs(u) {
            Contact c = TestDataFactory.createContact(true);
            Address__c a = TestDataFactory.createAddress(false);
            a.Address_1__c = STREET;
            a.City__c = CITY;
            a.Country_Code__c = COUNTRY_CODE;
            a.State__c = STATE;
            a.Zip__c = POSTAL_CODE;
            insert a;

            // Relate contact to address
            Customer_Address__c ca = TestDataFactory.createCustomerAddress(false, false);
            ca.Is_Principal_Address__c = true;
            ca.Address__c = a.Id;
            ca.Contact__c = c.Id;
            insert ca;
        }
    }
    
    @isTest
    public static void testAmericanZipFormattingInMatchKey() {
    	
    	List<Address__c> addresses = new List<Address__c>(); 
    	addresses.add(new Address__c(
    		Zip__c = '123456789',
    		Country_Code__c = 'MEX'
    	));
    	addresses.add(new Address__c(
    		Zip__c = '123456789',
    		Country_Code__c = 'USA'
    	));    	
    	addresses.add(new Address__c(
    		Zip__c = '123456789'
    	));  
    	    	
    	addresses[0].Address_Match_Key__c = SSVCleaner.buildAddressMatchKey(addresses[0]);
    	addresses[1].Address_Match_Key__c = SSVCleaner.buildAddressMatchKey(addresses[1]);
    	addresses[2].Address_Match_Key__c = SSVCleaner.buildAddressMatchKey(addresses[2]);
    	
    	System.assertEquals('123456789', addresses[0].Address_Match_Key__c);
    	System.assertEquals('12345', addresses[1].Address_Match_Key__c);
    	System.assertEquals('123456789', addresses[2].Address_Match_Key__c);
    }
    
    // Test updating related contacts on update of an address
    @isTest
    static void test_updateContacts() {
        Contact c = [SELECT Id FROM Contact];
        Address__c a = [SELECT Id FROM Address__c];
        update_2(a);
        assertUpdated(c);
    }

    // Test setting the match key and hash on insert of an address
    @isTest
    static void test_setMatchKey_insert() {
        Address__c a = [SELECT Address_Match_Key__c, Address_Match_Key_Hash__c FROM Address__c];
        System.assertNotEquals(null, a.Address_Match_Key__c);
        System.assertNotEquals(null, a.Address_Match_Key_Hash__c);
    }

    // Test setting the match key and hash on update of an address
    @isTest
    static void test_setMatchKey_update() {
        Address__c a = [SELECT Address_Match_Key__c, Address_Match_Key_Hash__c FROM Address__c];
        System.assertNotEquals(null, a.Address_Match_Key__c);
        System.assertNotEquals(null, a.Address_Match_Key_Hash__c);
        update_2(a);
        Address__c a2 = [SELECT Address_Match_Key__c, Address_Match_Key_Hash__c FROM Address__c];
        System.assertNotEquals(a2.Address_Match_Key__c, a.Address_Match_Key__c);
        System.assertNotEquals(a2.Address_Match_Key_Hash__c, a.Address_Match_Key_Hash__c);
    }

    static void update_2(Address__c a) {
        a.Address_1__c = STREET_2;
        a.City__c = CITY_2;
        a.Country_Code__c = COUNTRY_CODE_2;
        a.State__c = STATE_2;
        a.Zip__c = POSTAL_CODE_2;
        update a;
    }

    static void assertUpdated(Contact c) {
        c = [SELECT MailingStreet,
                MailingCity,
                MailingCountry,
                MailingState,
                MailingPostalCode
            FROM Contact
            WHERE Id = :c.Id
        ];
        System.assertEquals(STREET_2, c.MailingStreet);
        System.assertEquals(CITY_2, c.MailingCity);
        System.assertEquals(COUNTRY_CODE_2, c.MailingCountry);
        System.assertEquals(STATE_2, c.MailingState);
        System.assertEquals(POSTAL_CODE_2, c.MailingPostalCode);
    }

    static void assertNotUpdated(Contact c) {
        c = [SELECT MailingStreet,
                MailingCity,
                MailingCountry,
                MailingState,
                MailingPostalCode
            FROM Contact
            WHERE Id = :c.Id
        ];
        System.assertNotEquals(STREET_2, c.MailingStreet);
        System.assertNotEquals(CITY_2, c.MailingCity);
        System.assertNotEquals(COUNTRY_CODE_2, c.MailingCountry);
        System.assertNotEquals(STATE_2, c.MailingState);
        System.assertNotEquals(POSTAL_CODE_2, c.MailingPostalCode);
    }
}