objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <inlineHelpText>For United States, enter US. 
For Canada, enter CA. 
Leave blank for all other countries.</inlineHelpText>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Principal_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerManager__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>runMDMTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>runMDMTriggers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>runTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>runTriggers</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerManager</label>
</CustomObject>

classes/CustomerAddressesTest.cls
@isTest
private class CustomerAddressesTest {
	
	static {
		TestDataFactory.turnMdmFeatureFlagsOn();
	}	

    static String STREET = 'test street';
    static String CITY = 'Vancouver';
    static String COUNTRY_CODE = 'CA';
    static String STATE = 'BC';
    static String POSTAL_CODE = '1234567';
    
    static User nonIntegrationUser {
	    get {
	            if (nonIntegrationUser == null) {
	                nonIntegrationUser = TestDataFactory.createUser();
	                nonIntegrationUser.Single_View_of_Customer_Process_User__c = false;
	                
					TriggerManager__c triggerManager = new TriggerManager__c(SetupOwnerId = nonIntegrationUser.Id, runTriggers__c=true, runMDMTriggers__c=true);
					insert triggerManager;                
	            }
	            return nonIntegrationUser;
	    } set; 
	}

    @testSetup
    static void setup() {
        Contact c = TestDataFactory.createContact(true);
        Address__c a = TestDataFactory.createAddress(false);
        a.Address_1__c = STREET;
        a.City__c = CITY;
        a.Country_Code__c = COUNTRY_CODE;
        a.State__c = STATE;
        a.Zip__c = POSTAL_CODE;
        
        System.runAs(nonIntegrationUser) {  
        	insert a;
        }
    }

    // Test updating related contacts on insert of a principle address
    @isTest
    static void test_updateContacts_insert() {
        Address__c a = [SELECT Id FROM Address__c];
        Contact c = [SELECT Id FROM Contact];
        Customer_Address__c ca = TestDataFactory.createCustomerAddress(false, false);
        ca.Is_Principal_Address__c = true;
        ca.Address__c = a.Id;
        ca.Contact__c = c.Id;

		System.runAs(nonIntegrationUser) {  
        	insert ca;
		}
		
        assertUpdated(c);
	}

    // Test updating related contacts on update of a customer address to a principle address
    @isTest
    static void test_updateContacts_update() {
        Address__c a = [SELECT Id FROM Address__c];
        Contact c = [SELECT Id FROM Contact];
        Customer_Address__c ca = TestDataFactory.createCustomerAddress(false, false);
        ca.Is_Principal_Address__c = false;
        ca.Address__c = a.Id;
        ca.Contact__c = c.Id;
        insert ca;
        assertNotUpdated(c);

        ca.Is_Principal_Address__c = true;
        System.runAs(nonIntegrationUser) {  
        	update ca;
        }
        assertUpdated(c);
    }

    static void assertUpdated(Contact c) {
        c = [SELECT MailingStreet,
                MailingCity,
                MailingCountry,
                MailingState,
                MailingPostalCode
            FROM Contact
            WHERE Id = :c.Id
        ];
        System.assertEquals(STREET, c.MailingStreet);
        System.assertEquals(CITY, c.MailingCity);
        System.assertEquals(COUNTRY_CODE, c.MailingCountry);
        System.assertEquals(STATE, c.MailingState);
        System.assertEquals(POSTAL_CODE, c.MailingPostalCode);
    }

    static void assertNotUpdated(Contact c) {
        c = [SELECT MailingStreet,
                MailingCity,
                MailingCountry,
                MailingState,
                MailingPostalCode
            FROM Contact
            WHERE Id = :c.Id
        ];
        System.assertNotEquals(STREET, c.MailingStreet);
        System.assertNotEquals(CITY, c.MailingCity);
        System.assertNotEquals(COUNTRY_CODE, c.MailingCountry);
        System.assertNotEquals(STATE, c.MailingState);
        System.assertNotEquals(POSTAL_CODE, c.MailingPostalCode);
    }
}