objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact_Information__c.object
<CustomObject>
    <description>This table contains one record per contact point. A contact point is defined as a method for contacting the customer (examples include: Email, Phone, Social Handles).</description>
    <fields>
        <fullName>Contact_Information_Type__c</fullName>
        <label>Contact Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Business Phone</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Personal Email</fullName>
                </value>
                <value>
                    <fullName>Work Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipName>Contact_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <label>Contact Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <description>For phone contact information</description>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ChildHierarchyGroupTests.cls
@isTest
private class ChildHierarchyGroupTests {

    static List<ChildHierarchyGroupTest> testGroups = new  List<ChildHierarchyGroupTest> {
        new ContactInformationEmailGroupTest(),
        new ContactInformationPhoneGroupTest(),
        new ContactInformationFaxGroupTest(),
        new CustomerAddressHierarchyGroupTest()
    };
    	
    @testSetup
    static void setup() {
    	TestDataFactory.turnMdmFeatureFlagsOn(); 
    }	    

    @isTest
    static void test_bulk_0() {
        testGroups[0].test_bulk();
    }

    @isTest
    static void test_bulk_1() {
        testGroups[1].test_bulk();
    }

    @isTest
    static void test_bulk_2() {
        testGroups[2].test_bulk();
    }

    @isTest
    static void test_bulk_3() {
        testGroups[3].test_bulk();
    }

    @isTest
    static void test_new_primary_insert() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_new_primary_insert();
        }
    }

    @isTest
    static void test_new_primary_update() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_new_primary_update();
        }
    }

    @isTest
    static void test_two_primary_insert() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_two_primary_insert();
        }
    }

    @isTest
    static void test_two_primary_update() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_two_primary_update();
        }
    }

    @isTest
    static void test_unflag_old_primary_insert() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_unflag_old_primary_insert();
        }
    }

    @isTest
    static void test_unflag_old_primary_update() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_unflag_old_primary_update();
        }
    }

    @isTest
    static void test_remove_primary_update() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_remove_primary_update();
        }
    }

    @isTest
    static void test_remove_primary_delete() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_remove_primary_delete();
        }
    }

    @isTest
    static void test_primary_change_group() {
        for (ChildHierarchyGroupTest testGroup : testGroups) {
            testGroup.test_primary_change_group();
        }
    }

	public class ContactInformationEmailGroupTest extends ChildHierarchyGroupTest {
        public ContactInformationEmailGroupTest() {
            testGroup = new ContactInformationEmailGroup();
            numChildren = 5;
        }

        public override List<SObject> getChildren(Integer num) {
            List<Contact_Information__c> children = TestDataFactory.createContactInformations(num, false);
            for (Contact_Information__c child : children) {
                child.RecordTypeId = ContactInformations.EMAIL_RECORD_TYPE_ID;
            }
            return children;
        }

        public override SObject getParent() {
            Contact c = (Contact) getParents(1)[0];
            insert c;
            return c;
        }

        public override List<SObject> getParents(Integer num) {
            List<Contact> parents = TestDataFactory.createContacts(num, false);
            return parents;
        }
	}

    public class ContactInformationPhoneGroupTest extends ChildHierarchyGroupTest {
        public ContactInformationPhoneGroupTest() {
            testGroup = new ContactInformationPhoneGroup();
            numChildren = 5;
        }

        public override List<SObject> getChildren(Integer num) {
            List<Contact_Information__c> children = TestDataFactory.createContactInformations(num, false);
            for (Contact_Information__c child : children) {
                child.Contact_Information_Type__c = 'Home Phone';
                child.RecordTypeId = ContactInformations.PHONE_RECORD_TYPE_ID;
            }
            return children;
        }

        public override SObject getParent() {
            Contact c = (Contact) getParents(1)[0];
            insert c;
            return c;
        }

        public override List<SObject> getParents(Integer num) {
            List<Contact> parents = TestDataFactory.createContacts(num, false);
            return parents;
        }
    }

    public class ContactInformationFaxGroupTest extends ChildHierarchyGroupTest {
        public ContactInformationFaxGroupTest() {
            testGroup = new ContactInformationFaxGroup();
            numChildren = 5;
        }

        public override List<SObject> getChildren(Integer num) {
            List<Contact_Information__c> children = TestDataFactory.createContactInformations(num, false);
            for (Contact_Information__c child : children) {
                child.RecordTypeId = ContactInformations.FAX_RECORD_TYPE_ID;
            }
            return children;
        }

        public override SObject getParent() {
            List<Contact> parents = [SELECT Id FROM Contact];
            if (parents.isEmpty()) {
                Contact c = (Contact) getParents(1)[0];
                insert c;
                return c;
            } else {
                return parents[0];
            }
        }

        public override List<SObject> getParents(Integer num) {
            List<Contact> parents = TestDataFactory.createContacts(num, false);
            return parents;
        }
    }

    public class CustomerAddressHierarchyGroupTest extends ChildHierarchyGroupTest {
        private Address__c addr;

        public CustomerAddressHierarchyGroupTest() {
            testGroup = new CustomerAddressHierarchyGroup();
            numChildren = 5;
            addr = TestDataFactory.createAddress(true);
        }

        public override List<SObject> getChildren(Integer num) {
            List<Customer_Address__c> children = TestDataFactory.createCustomerAddresses(num, false, false);
            for (Customer_Address__c ca : children) {
                ca.Address__c = addr.Id;
            }
            return children;
        }

        public override SObject getParent() {
            Contact c = (Contact) getParents(1)[0];
            insert c;
            return c;
        }

        public override List<SObject> getParents(Integer num) {
            List<Contact> parents = TestDataFactory.createContacts(num, false);
            return parents;
        }
    }
}