objects/Address__c.object
<CustomObject>
    <description>This table contains one record per address. Generally addresses are consolidated from various CW customer records, after the address validation step</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key_Hash__c</fullName>
        <externalId>true</externalId>
        <label>Address Match Key Hash</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key__c</fullName>
        <label>Address Match Key</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <inlineHelpText>For United States, enter US. 
For Canada, enter CA. 
Leave blank for all other countries.</inlineHelpText>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company_Account_SSV_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field mapping for account to ssv records. (Non person accounts)</description>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>Source Field mapping to SSV Field</description>
        <inlineHelpText>This contains the API field name of the relevant field from Account object</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SSV field that will be mapped to Account field</description>
        <inlineHelpText>This contains the API field name of the relevant field from Source System View object.</inlineHelpText>
        <label>Target Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company Account SSV Field Mapping</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand.

This field will be used as a primary match for Demand Tools duplicate matching/ stewardship review</description>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Address__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Person_Account_SSV_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field mapping for account to ssv records. (Person Accounts)</description>
    <fields>
        <fullName>Source_Field__c</fullName>
        <inlineHelpText>This contains the API field name of the relevant field from Account object</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Person Account SSV Field Mapping</label>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key_Hash__c</fullName>
        <description>SHA-512 Base64 Encoded version of Address Match Key for indexing and comparison purposes.</description>
        <externalId>true</externalId>
        <label>Address Match Key Hash</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key__c</fullName>
        <description>Consolidation of address1, address2, city, state,country for matching purposes (some additional analysis required). Punctuation &amp; space removal, upper case</description>
        <label>Address Match Key</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternative_Phone__c</fullName>
        <label>Alternative Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_First_Name__c</fullName>
        <label>Cleansed First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Last_Name__c</fullName>
        <label>Cleansed Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Phone_Match_Key__c</fullName>
        <description>Phone for matching purposes -- removes bad phone etc</description>
        <label>Day Phone Match Key</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email_Match_Key__c</fullName>
        <label>Email Match Key</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Ready_For_Duplicate_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Ready For Duplicate Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Record_Score__c</fullName>
        <description>This score is a key part of the matching process. 
When multiple candidate records can be consolidated into one record, this score determines which record will be the Master (the name, address, phone etc for the spawned customer is taken from the Master record). 
The score is designed to ensure:
1. Define the order of entry of new Candidate records into the process
- There is a final addition for match type = company to ensure company records are processed prior to any associated contact records
2. Ensure Salesforce records always outscore other external system records</description>
        <formula>/* This section determines the highest value Salesforce record as Salesforce records always end up as the master over external system records */
If(Source_System__c=&quot;Salesforce&quot;,100000000,0) +
If(Contact__r.Tier_Name__c=&quot;Top Tier&quot;,100000,0) +
If(Contact__r.Tier_Name__c =&quot;Tier 2&quot;,50000,0) +
If(Contact__r.Tier_Name__c =&quot;Tier 3&quot;,25000,0) +
(Date(1970,01,01)-BLANKVALUE(DateValue(If(Match_Type__c = &quot;Company&quot;, Account__r.CreatedDate,  
                                                Contact__r.CreatedDate)),Date(1970,01,01)))/10000 +

/* This section calculates the master record score for non Salesforce records */
If( DateValue(Source_System_Last_Modified_Date__c) &gt; Today()-730,10000,0) +
If( Originating_Source_System__c = &quot;ATG&quot;,5000,0) +
(BLANKVALUE(DateValue(Source_System_Last_Modified_Date__c),Date(1970,01,01)) - Date(1970,01,01))/10000 +

/* this next line ensures company records are always processed prior to any associated contacts */
/* Because company records are only ever consolidated to the same match type, the score does not impact &quot;within company match&quot; selections */
If(Match_Type__c = &quot;Company&quot;,200000,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Record Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <description>This field specifies the match type to be processed by Salesforce duplicate match</description>
        <label>Match Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Number__c</fullName>
        <label>Membership Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Ready_Time__c</fullName>
        <label>Processing Ready Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting to Start</fullName>
                    <default>true</default>
                    <label>Waiting to Start</label>
                </value>
                <value>
                    <fullName>Ready for Match Step</fullName>
                </value>
                <value>
                    <fullName>Ready for Order Linking</fullName>
                </value>
                <value>
                    <fullName>Processing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_View_CW_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System View CW Company</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Add field history tracking</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Add field history tracking</description>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountsTest.cls
/**
 * Test class for account triggers (Upsert SSV records)
 * @author Zi Zhang, Traction on Demand
 * @date   2016-03-08
 */
@isTest
public class AccountsTest {
	
	private static Account testAccount;
	// If record type names change, modify the names below
	private static Id companyAccountRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contract').getRecordTypeId();
	private static Id personAccountRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('RH End Customer').getRecordTypeId();
	private static final Id UNCLASSIFIED_RECORD_TYPE_ID = Accounts.ACCOUNT_RECORD_TYPES.get('Unclassified Business Account').getRecordTypeId();

    @testSetup
    static void setup() {
    	TestDataFactory.turnMdmFeatureFlagsOn(); 
    }
    
	public static testMethod void testCompanyAccountTrigger() {
		User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;

        System.runAs(u) {
			System.assertEquals(true, String.isNotEmpty(companyAccountRecTypeId), 'Company Account Record Type not found.');
			createCompanyAccountFieldMappingSettings();

			// Insert new company account
			testAccount = new Account(Name = 'Test Company Account', RecordTypeId = companyAccountRecTypeId);
			insert testAccount;

			System.assertNotEquals(null, testAccount.Id, 'Error inserting account.');

			List<Source_System_View__c> resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c FROM Source_System_View__c];

			System.assertEquals(1, resultSSVs.size(), 'SSV record does not exist.');
			System.assertEquals('SFDC-' + testAccount.Id, resultSSVs[0].Name, 'Name field not mapped.');
			System.assertEquals(testAccount.Id, resultSSVs[0].Account__c, 'Account__c field not mapped.');
			System.assertEquals(testAccount.Name, resultSSVs[0].Company_Name__c, 'Company_Name__c field not mapped.');

			// Update key fields on company account
			testAccount.Name = 'Test Company Account modified';
			update testAccount;

			resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c FROM Source_System_View__c];

			System.assertEquals(1, resultSSVs.size(), 'SSV record does not exist.');
			System.assertEquals(testAccount.Name, resultSSVs[0].Company_Name__c, 'Company_Name__c field not mapped.');

			delete testAccount;

			resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c FROM Source_System_View__c];

			System.assertEquals(0, resultSSVs.size(), 'SSV record was not deleted.');
		}
	}

	public static testMethod void testPersonAccountTrigger() {
		User u = TestDataFactory.createUser();
        u.Single_View_of_Customer_Process_User__c = false;

        System.runAs(u) {
			System.assertEquals(true, String.isNotEmpty(personAccountRecTypeId), 'Person Account Record Type not found.');
			createPersonAccountFieldMappingSettings();

			// Insert new company account
			testAccount = new Account(RecordTypeId = personAccountRecTypeId,
									  FirstName='Test FName',
									  LastName='Test LName',
									  PersonMailingStreet='123 Fake St.',
									  PersonMailingPostalCode='12345',
									  PersonMailingCity='Burnaby',
									  PersonEmail='test@tractionondemand.com');
			insert testAccount;

			List<Account> personAccount = [SELECT Id, PersonContactId FROM Account WHERE Id = :testAccount.Id];
			System.assertEquals(1, personAccount.size(), 'Person Account was not created.');
			System.assertNotEquals(null, testAccount.Id, 'Error inserting account.');

			List<Source_System_View__c> resultSSVs = [
				SELECT 
					Id,
					Name,
					Duplicate_Set_ID__c,
					Is_Ready_For_Duplicate_Check__c,
					Processing_Status__c,
					Processing_Ready_Time__c,
					EXT_Source_System_Customer_ID__c,
					Source_System_View_CW_Company__c,
					Account__c,
					Contact__c,
					Customer_Address__c,
					Company_Name__c,
					First_Name__c,
					Last_Name__c,
					Email__c,
					Day_Phone__c,
					Alternative_Phone__c,
					Address_1__c,
					Address_2__c,
					City__c,
					State__c,
					Zip__c,
					Country__c,
					Country_Code__c,
					Cleansed_First_Name__c,
					Cleansed_Last_Name__c,
					Cleansed_Company_Name__c,
					Email_Match_Key__c,
					Day_Phone_Match_Key__c,
					Address_Match_Key__c,
					Address_Match_Key_Hash__c,
					Match_Type__c,
					Master_Record_Score__c,
					Trade_ID__c,
					Membership_Number__c,
					Source_System_View_CW_Company__r.Duplicate_Set_ID__c,
					Source_System_View_CW_Company__r.Account__c
				FROM Source_System_View__c
			];														
			List<Contact> resultContacts = [SELECT Id, FirstName, LastName FROM Contact];

			System.assertEquals(1, resultSSVs.size(), 'SSV record does not exist.');
			System.assertNotEquals(null, resultSSVs[0].Account__c, 'Spawned SSV is not linked to the source account.');
			System.assertNotEquals(null, resultSSVs[0].Contact__c, 'Spawned SSV is not linked to the source contact.');
			
			System.assertEquals(1, resultContacts.size(), 'Contact record does not exist.');
			
			System.assertEquals('SFDC PA-' + testAccount.Id, resultSSVs[0].Name, 'Name field not mapped.');
			System.assertEquals(testAccount.Id, resultSSVs[0].Account__c, 'Account__c field not mapped.');
			System.assertEquals(personAccount[0].PersonContactId, resultContacts[0].Id, 'Contact__c field not mapped.');
			System.assertEquals(testAccount.Name, resultSSVs[0].Company_Name__c, 'Company_Name__c field not mapped.');
			System.assertEquals(resultContacts[0].FirstName, resultSSVs[0].First_Name__c, 'First_Name__c field not mapped.');
			System.assertEquals(resultContacts[0].LastName, resultSSVs[0].Last_Name__c, 'Last_Name__c field not mapped.');
			
			
			
			
			
			// run the consolidate / spawnx
			new SSVCreator(resultSSVs).syncToCustomers().spawnData();
			
			// ensure no duplicate account or contact is created
			List<Contact> newContactList = [SELECT Id, FirstName, LastName FROM Contact];
			// System.assertEquals(1, newContactList.size(), 'Additional Contact record created.');
			
			// ensure the customer address related to existing contact was created
			List<Customer_Address__c> newCustomerAddressList = [SELECT Id, Address__c, Contact__c FROM Customer_Address__c WHERE Contact__c IN :resultContacts];
						
			System.assertEquals(1, newCustomerAddressList.size(), 'Customer Address not created.');
			System.assertNotEquals(null, newCustomerAddressList[0].Address__c, 'Address was not created for contact.');
			
			
			
			

			// Update key fields on company account
			testAccount.FirstName = 'Test FName updated';
			update testAccount;

			resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c, Contact__c, First_Name__c, Last_Name__c 
														FROM Source_System_View__c];

			System.assertEquals(1, resultSSVs.size(), 'SSV record does not exist.');
			System.assertEquals(testAccount.FirstName, resultSSVs[0].First_Name__c, 'Company_Name__c field not mapped.');

			delete testAccount;

			resultSSVs = [SELECT Id, Name, Account__c, Company_Name__c, Contact__c, First_Name__c, Last_Name__c 
														FROM Source_System_View__c];

			System.assertEquals(0, resultSSVs.size(), 'SSV record was not deleted.');
		}
	}

	// Test setting membership numbers on insert
	private static testmethod void test_setMembership_insert() {
		Account a = TestDataFactory.createAccount(false);
		a.RecordTypeId = Accounts.CONTRACT_RECORD_TYPE_ID;
		insert a;

		Account a2 = TestDataFactory.createAccount(false);
		a2.RecordTypeId = Accounts.CONTRACT_RECORD_TYPE_ID;
		insert a2;

		Map<Id, Account> accs = new Map<Id, Account> ([SELECT X12_Digit_Member__c FROM Account WHERE Id = :a.Id OR Id = :a2.Id]);
		a = accs.get(a.Id);
		a2 = accs.get(a2.Id);

		System.assertNotEquals(null, a.X12_Digit_Member__c);
		System.assertNotEquals(null, a2.X12_Digit_Member__c);
		System.assert(a2.X12_Digit_Member__c > a.X12_Digit_Member__c);
	}

	// Test setting membership numbers on update
	private static testmethod void test_setMembership_update() {
		Account a = TestDataFactory.createAccount(false);
		a.RecordTypeId = UNCLASSIFIED_RECORD_TYPE_ID;
		insert a;
		a.RecordTypeId = Accounts.CONTRACT_RECORD_TYPE_ID;
		update a;

		Account a2 = TestDataFactory.createAccount(false);
		a2.RecordTypeId = UNCLASSIFIED_RECORD_TYPE_ID;
		insert a2;
		a2.RecordTypeId = Accounts.CONTRACT_RECORD_TYPE_ID;
		update a2;

		Map<Id, Account> accs = new Map<Id, Account> ([SELECT X12_Digit_Member__c FROM Account WHERE Id = :a.Id OR Id = :a2.Id]);
		a = accs.get(a.Id);
		a2 = accs.get(a2.Id);

		System.assertNotEquals(null, a.X12_Digit_Member__c);
		System.assertNotEquals(null, a2.X12_Digit_Member__c);
		System.assert(a2.X12_Digit_Member__c > a.X12_Digit_Member__c);
	}

	/*********************** Test data custom settings field mapping ****************************/
	private static void createCompanyAccountFieldMappingSettings() {
		List<Company_Account_SSV_Field_Mapping__c> settings = new List<Company_Account_SSV_Field_Mapping__c>();
		settings.add(new Company_Account_SSV_Field_Mapping__c(Name = 'FM1', Source_Field__c = 'ID', Target_Field__c = 'Name'));
		settings.add(new Company_Account_SSV_Field_Mapping__c(Name = 'FM2', Source_Field__c = 'ID', Target_Field__c = 'Account__c'));
		settings.add(new Company_Account_SSV_Field_Mapping__c(Name = 'FM3', Source_Field__c = 'Name', Target_Field__c = 'Company_Name__c'));

		insert settings;
	} 

	private static void createPersonAccountFieldMappingSettings() {
		List<Person_Account_SSV_Field_Mapping__c> settings = new List<Person_Account_SSV_Field_Mapping__c>();
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM1', Source_Field__c = 'ID', Target_Field__c = 'Name'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM2', Source_Field__c = 'ID', Target_Field__c = 'Account__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM3', Source_Field__c = 'PersonContactID', Target_Field__c = 'Contact__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM4', Source_Field__c = 'FirstName', Target_Field__c = 'First_Name__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM5', Source_Field__c = 'LastName', Target_Field__c = 'Last_Name__c'));
		
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM6', Source_Field__c = 'PersonMailingCountry', Target_Field__c = 'Country__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM7', Source_Field__c = 'PersonMailingState', Target_Field__c = 'State__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM8', Source_Field__c = 'Phone', Target_Field__c = 'Day_Phone__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM9', Source_Field__c = 'PersonMailingCity', Target_Field__c = 'City__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM10', Source_Field__c = 'PersonEmail', Target_Field__c = 'Email__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM11', Source_Field__c = 'PersonMailingPostalCode', Target_Field__c = 'Zip__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM12', Source_Field__c = 'Mailing_Country_Code__pc', Target_Field__c = 'Country_Code__c'));
		settings.add(new Person_Account_SSV_Field_Mapping__c(Name = 'FM13', Source_Field__c = 'ID', Target_Field__c = 'EXT_Source_System_Customer_ID__c'));
		

		insert settings;
	} 
}