objects/agf__ADM_Sprint__c.object
<CustomObject>
</CustomObject>

src/objects/Commit_History__c.object
<CustomObject>
    <label>Commit History</label>
    <nameField>
        <label>Revision Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commit Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Commit_History__c.object
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Commit_History__c.object
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Commit_History__c.object
    <fields>
        <fullName>Target_Repository__c</fullName>
        <label>Target Repository</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Commit_History__c.object
    <fields>
        <fullName>Work_Story__c</fullName>
        <label>Work Story</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/CommitFetch__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manageble_State__c</fullName>
        <label>Manageble State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <label>Members</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modified_Date__c</fullName>
        <label>Modified Date</label>
        <type>DateTime</type>
    </fields>
    <label>CommitFetch</label>
    <nameField>
        <displayFormat>CF -{0000}</displayFormat>
        <label>CommitFetch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CommitFetch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Security_Token__c</fullName>
        <label>Security Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/setup_vcs__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repo_Username__c</fullName>
        <label>Repo_Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repository_Name__c</fullName>
        <label>Repository Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCMType__c</fullName>
        <label>SCMType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GIT</fullName>
                </value>
                <value>
                    <fullName>SVN</fullName>
                </value>
                <value>
                    <fullName>TFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SF_Setup__c</fullName>
        <label>SF_Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>setup_vcs</relationshipLabel>
        <relationshipName>setup_vcs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>remoteurl__c</fullName>
        <label>remoteurl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>setup_vcs</label>
    <nameField>
        <displayFormat>VCS-{000000}</displayFormat>
        <label>setup_vcs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>setup_vcs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup_VCS_branch__c.object
<CustomObject>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>setup_vcs__c</fullName>
        <label>setup_vcs</label>
        <referenceTo>setup_vcs__c</referenceTo>
        <relationshipLabel>Setup_VCS_branch</relationshipLabel>
        <relationshipName>Setup_VCS_branch</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Setup_VCS_branch</label>
    <nameField>
        <displayFormat>SVB-{00000}</displayFormat>
        <label>Setup_VCS_branch#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup_VCS_branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CommitController.cls
public with sharing class CommitController {
    @AuraEnabled
    public static List<Setup_VCS_branch__c> getRepoDetails(){
        List<Setup_VCS_branch__c> repoDetails = [select Branch_Name__c, setup_vcs__r.Repository_Name__c, setup_vcs__r.remoteurl__c, setup_vcs__r.Repo_Username__c, setup_vcs__r.Password__c, setup_vcs__r.SCMType__c  from Setup_VCS_branch__c]; 
        return repoDetails;   
        
    }
    
    @AuraEnabled
    public static List<CommitFetch__c> getUserChanges(){
        List<CommitFetch__c> userChanges = [select Action__c, Component__c, Manageble_State__c, Members__c, Modified_Date__c from CommitFetch__c]; 
        return userChanges;   
        
    }
    
    @AuraEnabled
    public static List<agf__ADM_Sprint__c> getAlmDetails(){
        return [select id, Name, (select agf__Subject__c from agf__Work__r where agf__Type__c = 'User Story' and agf__Scrum_Team_Name__c != 'Sample') from agf__ADM_Sprint__c];   
    }
    
    @AuraEnabled
    public static Object getSprintUserStories(String sprintId){
        return ([select id, Name, (select agf__Subject__c from agf__Work__r where agf__Type__c = 'User Story' and agf__Scrum_Team_Name__c != 'Sample') from agf__ADM_Sprint__c where id =: sprintId ]);
    }
    
    @AuraEnabled
    public static void upsertCommitHistoryAp(){
        Commit_History__c obj = new Commit_History__c();
        obj.Sprint__c = '2016.10bcde';
        obj.Name = 'f9fb186';
        obj.Work_Story__c = 'Version Control Enhancement';
        obj.Target_Repository__c = 'ACE';
        obj.Branch__c = 'UAT';
        insert obj;
    }
    
    @AuraEnabled
    public static String fetchUserChangesReq(){
        HttpRequest req = RabitUtils.buildWebServiceRequest();
        String orgName = 'lightning.com';
        String userName = '0054B000000pAeTQAU';
        String sfEle = EncodingUtil.base64Encode(Blob.valueOf('<sforg id="abcdef123456" userid="0054B000000pAeTQAU" authtype = "Standard" url="https://test.salesforce.com" username="naresh@autorabit.com.lightning" password = "Euphoria@7" stoken="qXRv9Q72ivNWdKkTWUlQPfaS0"></sforg>'));
        String repoEle = EncodingUtil.base64Encode(Blob.valueOf('<repository id="repoid"><branch id="123456788994322" createdby="0054B000000pAeTQAU" repourl="abcddefghij13435235r23" branchurl="http://github.com/abc.git" name="dev" password="hyd@345" username="naresh.a" scmtype="git"/></repository>'));
        String reqBody = '<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ws=\"http://ws.service.rabit.com/\"><soapenv:Header/><soapenv:Body>'
            +'<ws:fetchSfUserChangesLightningWrapper>'
            +'<orgname>'+orgName+'</orgname>'
            +'<userslist>'+userName+'</userslist>'
            +'<sfele>'+sfEle+'</sfele>'
            +'<repoele>'+repoEle+'</repoele>'
            +'</ws:fetchSfUserChangesLightningWrapper>'
            +'</soapenv:Body></soapenv:Envelope>';
        System.debug(reqBody);
        req.setBody(reqBody);
        Http http = new Http();
        String response = RabitUtils.invokeWebService(http,req).getBody();
        System.debug(response);
        /* response = response.replace('"metadata":{', '"metadata":[{');
response = response.replace('},"name"', '}],"name"');
String regex = '\"metadata\":\\[(\"\\d{2,}\",|\"\\d{2,}\")*\\],';
Pattern regexPattern = Pattern.compile(regex); 
Matcher regexMatcher = regexPattern.matcher(response);
if(regexMatcher.find()) {
System.debug(loggingLevel.Error, '*** Regex match found');
response = response.replaceAll(regex, '');
}

JSONParser parser = JSON.createParser(response);
// Get question data from quiz_data
while (parser.nextToken() != null) {
if (parser.getText() == 'quiz_data') {
while (parser.nextToken() != null) {
// Advance to the start object marker to
//  find next quiz submission object.
if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
// Read entire quiz_data object, including its array of event data.
sub = (List<changes>)parser.readValueAs(List<changes>.class);

// Skip the child start array and start object markers.
parser.skipChildren();
}
}
}
}*/
        return response;
    }
    @AuraEnabled
    public static String tempFetchUserChangesReq(String branchName){
        HttpRequest req = RabitUtils.buildWebServiceRequest();
        String orgName = 'lightning.com';
        String userName = 'testuser@lightning.com';
        String sfEle = getSFElement();
        System.debug('sfEle' + sfEle);
        String repoEle = getRepoElement(branchName);
        System.debug('repoEle' + repoEle);
        String reqBody = '<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ws=\"http://ws.service.rabit.com/\"><soapenv:Header/><soapenv:Body>'
            +'<ws:fetchSfUserChangesLightningWrapper>'
            +'<orgname>'+orgName+'</orgname>'
            +'<userslist>'+userName+'</userslist>'
            +'<sfele>'+sfEle+'</sfele>'
            +'<repoele>'+repoEle+'</repoele>'
            +'</ws:fetchSfUserChangesLightningWrapper>'
            +'</soapenv:Body></soapenv:Envelope>';
        System.debug('reqBody' + reqBody);
        req.setBody(reqBody);
        Http http = new Http();
        HttpResponse res = RabitUtils.invokeWebService(http, req);
        System.debug(res.getBody());
        return res.getBody();
    }
    
    public static String getSFElement(){
        Setup__c setupObject = [select id, Name, LastModifiedBy.Id, Username__c, Security_Token__c, Password__c from setup__c];
        String sfElementString = '<sforg id= "' + setupObject.Id +'"userid="' + UserInfo.getUserId() + '" authtype = "Standard" url="' + System.URL.getSalesforceBaseUrl() + '" username="' + setupObject.Username__c + '" password = "' + setupObject.Password__c + '" stoken="' + setupObject.Security_Token__c + '"></sforg>';
        return EncodingUtil.base64Encode(Blob.valueOf(sfElementString));
    }
    
    public static String getRepoElement(String branchName){
        setup_vcs__c setupVcsObject = [select id, Repository_Name__c, password__c, remoteurl__c, Repo_Username__c from setup_vcs__c];
        String repoElementString = '<repository id="' + setupVcsObject.Id + '"><branch id="123456788994322" createdby="testuser@lightning.com" name="testbranch" repourl="abcddefghij13435235r23" branchurl="http://github.com/abc.git" name="dev" password="hyd@345" username="naresh.a" scmtype="git"/></repository>';
        
        String s = EncodingUtil.base64Encode(Blob.valueOf('as'));
        
        return '';
    }
}