objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <fields>
        <fullName>Value_Text__c</fullName>
        <label>Value - Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

objects/Manual_Reservation__c.object
<CustomObject>
    <description>Stores data from the Manual Reservation screen in CW.</description>
    <fields>
        <fullName>Early_Delivery_Date__c</fullName>
        <label>Early Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Subject_Brand__c</fullName>
        <label>Email Subject Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RH</fullName>
                </value>
                <value>
                    <fullName>RH Baby &amp; Child</fullName>
                </value>
                <value>
                    <fullName>RH Contract</fullName>
                </value>
                <value>
                    <fullName>RH Teen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_To_Address__c</fullName>
        <label>Email To Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Late_Delivery_Date__c</fullName>
        <label>Late Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Lines__c</fullName>
        <label>Order Lines</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Manual Reservations</relationshipLabel>
        <relationshipName>Manual_Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Manual Reservations</relationshipLabel>
        <relationshipName>Manual_Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Manual Reservation</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Manual Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup relationship between products and orders, so that iPIM information can go from Products to Order Lines</description>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <formula>CW_SKU_ID__r.Color__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXT_OrderShipToLine_Number__c</fullName>
        <externalId>true</externalId>
        <label>EXT OrderShipToLine Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <description>Order Quantity of Line</description>
        <label>Order Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To_Email__c</fullName>
        <formula>Ship_To__r.Ship_to_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ship To Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <description>If there is a color listed in Secondary Color, use that information, otherwise, use what is in the CW Color field.</description>
        <formula>CASE( CW_Color__c , &quot;NOT APPLICABLE&quot;,  Secondary_Color__c ,  CW_Color__c )</formula>
        <label>Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECommerce_Display_Name__c</fullName>
        <label>ECommerce Display Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Image_URL__c</fullName>
        <description>the url where the image of the product resides</description>
        <label>Product Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Web_Description__c</fullName>
        <description>ipim field map: Web Description</description>
        <label>Web Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/RH_Brand__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping table - maps the value in the Source Code field of the Order (contains the 2 character Division code) to the Restoration Hardware brand to use for things like the Billing Summary email.</description>
    <fields>
        <fullName>Brand_Home_Page_URL__c</fullName>
        <label>Brand Home Page URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Brand_Logo_Height__c</fullName>
        <label>Brand Logo Height</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Logo_URL__c</fullName>
        <label>Brand Logo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Brand_Logo_Width__c</fullName>
        <label>Brand Logo Width</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delay_Notification_Email__c</fullName>
        <label>Delay Notification Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Delay_Notification_Phone__c</fullName>
        <label>Delay Notification Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email_Subject_Brand__c</fullName>
        <label>Email Subject Brand</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>RH Brand</label>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Description__c</fullName>
        <label>Order Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_1__c</fullName>
        <label>Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_2__c</fullName>
        <label>Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Company__c</fullName>
        <label>Ship to Company</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_to_First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ManualReservation.cls
public class ManualReservation {
	
	private Manual_Reservation__c rhMR;
	private Map<String, String> subMap;
	private Map<String, String> footerMap;
	
	public class mirvOLI {
		public String description {get; set;}
		public String quantity {get; set;}
		public String image {get; set;}
		public String item {get; set;}
		public String color {get; set;}
		
		public mirvOLI(String des, String qty, String img, String itm, String clr) {
			description = des;
			quantity = qty;
			image = img;
			item = itm;
			color = clr;
		}
	}
	
	public List<mirvOLI> mirvItems {get; set;}
	
	public Id mrId {get; set;}
	
	public ManualReservation() {
		
		// The Manual Reservation record Id is either passed in as a page parameter or it comes to the page via
		// the visualforce email template (ManualReservation)
		Id mrIdParameter = ApexPages.currentPage().getParameters().get('mrId');
		if (String.isNotBlank(mrIdParameter)) {
			mrId = mrIdParameter;
		}
		
		system.debug('*****ManualReservation constructor mrId = ' + mrId + ' mrIdParameter = ' + mrIdParameter);
		
		rhMR = null;
	}
	
	// Get the data for the email template
	public Map<String, String> getsubMap() {
		
		if (rhMR == null) {
			
			system.debug('*****ManualReservation getsubMap mrId = ' + mrId);
			
			rhMR = new Manual_Reservation__c();
			rhMR = [select Id, Order_Number__c, Ship_To__c, Early_Delivery_Date__c, Late_Delivery_Date__c,  
					Email_Subject_Brand__c, Email_To_Address__c, Order_Lines__c 
					from Manual_Reservation__c where Id = :mrId];
			
			List<String> lineExtIds = new List<String>();
			lineExtIds = (List<String>)JSON.deserialize(rhMR.Order_Lines__c, List<String>.class);
			
			RH_Order__c rhOrder = new RH_Order__c();
            rhOrder = [select Id, Name, Division__c, Order_Type_Code__c, Opportunity__c, Opportunity__r.Ops_Contact__c 
                    from RH_Order__c where Id = :rhMR.Order_Number__c];
			
			List<Order_Line_Items__c> oliList = new List<Order_Line_Items__c>();
            oliList = [select Id, Name, Order_Quantity__c, EXT_OrderShipToLine_Number__c, 
                    CW_SKU_ID__c, CW_SKU_ID__r.Name, CW_SKU_ID__r.Web_Description__c, CW_SKU_ID__r.Product_Image_URL__c, 
                    CW_SKU_ID__r.ECommerce_Display_Name__c, CW_SKU_ID__r.Color__c
                    from Order_Line_Items__c where EXT_OrderShipToLine_Number__c in :lineExtIds];
            
            Ship_To__c rhShipTo = new Ship_To__c();
            rhShipTo = [select Id, Name, Order__c, Ship_to_First_Name__c, Ship_to_Last_Name__c, Ship_to_Address_1__c, 
            		Ship_to_Address_2__c, Ship_to_Company__c, Ship_to_City__c, Ship_to_State__c, Ship_to_Zip__c, 
            		Ship_to_Country__c, Ship_to_Email__c, Ship_to_Country_Code__c, Order_Description__c 
                    from Ship_To__c where Id = :rhMR.Ship_To__c];
		
			// Get the RH brand data
            String dnEmail = '';
            String dnPhone = '';
            String pmName = ' ';
            RH_Brand__c rhb = null;
            if (rhOrder.Order_Type_Code__c == 'Z') {
            	rhb = RH_Brand__c.getInstance('RH Contract');
            	if (rhOrder.Opportunity__r.Ops_Contact__c != null) {
            		User pmUser = [select Id, Name, Email, Phone from User where Id = :rhOrder.Opportunity__r.Ops_Contact__c];
            		pmName = pmUser.Name;
            		if (String.isNotBlank(pmUser.Phone)) {
            			dnPhone = Utility.formatPhone10(pmUser.Phone);
            		}
            		dnEmail = pmUser.Email;
            	}
            } else {
            	if (String.isNotBlank(rhOrder.Division__c)) {
                	rhb = RH_Brand__c.getInstance(rhOrder.Division__c);
            	} else {
            		rhb = RH_Brand__c.getInstance('999');
            	}
            }
            
            dnEmail = (String.isNotBlank(dnEmail)) ? dnEmail : rhb.Delay_Notification_Email__c;
            dnPhone = (String.isNotBlank(dnPhone)) ? dnPhone : Utility.formatPhone10(rhb.Delay_Notification_Phone__c);
            
            subMap = new Map<String, String>();
            subMap.put('%pmName%', pmName);
            subMap.put('%dnEmail%', dnEmail);
            subMap.put('%dnPhone%', dnPhone);
            subMap.put('%logoLink%', rhb.Brand_Home_Page_URL__c);
            subMap.put('%logoURL%', rhb.Brand_Logo_URL__c);
            subMap.put('%logoWidth%', rhb.Brand_Logo_Width__c);
            subMap.put('%logoHeight%', rhb.Brand_Logo_Height__c);
            
            // Customer name and addresses, order number and type code
            String shipToName = Utility.toFirstCap(rhShipTo.Ship_to_First_Name__c, 3);
            if (String.isNotBlank(shipToName)) {
                shipToName += ' ';
            }
            shipToName += Utility.toFirstCap(rhShipTo.Ship_to_Last_Name__c, 0);
            if (String.isBlank(shipToName)) {
            	shipToName = ' ';
            }
			
			subMap.put('%shipToName%', shipToName);
			
			String addr = (String.isNotBlank(rhShipTo.Ship_To_Company__c)) ? Utility.toFirstCap(rhShipTo.Ship_To_Company__c, 2) : ' ';
			subMap.put('%shipToCompany%', addr);
            addr = (String.isNotBlank(rhShipTo.Ship_To_Address_1__c)) ? Utility.toFirstCap(rhShipTo.Ship_To_Address_1__c, 2) : ' ';
			subMap.put('%shipToAddr1%', addr);
			addr = (String.isNotBlank(rhShipTo.Ship_To_Address_2__c)) ? Utility.toFirstCap(rhShipTo.Ship_To_Address_2__c, 2) : ' ';
			subMap.put('%shipToAddr2%', addr);
			addr = (String.isNotBlank(rhShipTo.Ship_To_City__c)) ? Utility.toFirstCap(rhShipTo.Ship_To_City__c, 2) : '';
			if (String.isNotBlank(addr)) {
				addr += (String.isNotBlank(rhShipTo.Ship_To_State__c)) ? ', ' + Utility.toFirstCap(rhShipTo.Ship_To_State__c, 3) : '';
			} else {
				addr += (String.isNotBlank(rhShipTo.Ship_To_State__c)) ? Utility.toFirstCap(rhShipTo.Ship_To_State__c, 3) : '';
			}
			if (String.isNotBlank(addr)) {
				addr += (String.isNotBlank(rhShipTo.Ship_To_Zip__c)) ? ' ' + rhShipTo.Ship_To_Zip__c : '';
			} else {
				addr += (String.isNotBlank(rhShipTo.Ship_To_Zip__c)) ? rhShipTo.Ship_To_Zip__c : '';
			}
			addr = (String.isNotBlank(addr)) ? addr : ' ';
			subMap.put('%shipToCityStatePostalCode%', addr);
			addr = (String.isNotBlank(rhShipTo.Ship_To_Country_Code__c)) ? rhShipTo.Ship_To_Country_Code__c : ' ';
			subMap.put('%shipToCountryCode%', addr);
            
            subMap.put('%orderNumber%', rhOrder.Name);
            subMap.put('%orderTypeCode%', rhOrder.Order_Type_Code__c);
            
            // Delivery dates and order description
            String subStr = Utility.usDate(rhMR.Early_Delivery_Date__c, '/');
            subStr = (String.isBlank(subStr)) ? ' ' : subStr;
            subMap.put('%earlyDeliveryDate%', subStr);
            subStr = Utility.usDate(rhMR.Late_Delivery_Date__c, '/');
            subStr = (String.isBlank(subStr)) ? ' ' : subStr;
            subMap.put('%lateDeliveryDate%', subStr);
            
            if (String.isBlank(rhShipTo.Order_Description__c)) {
            	subMap.put('%orderDescriptionHeader%', ' ');
            	subMap.put('%orderDescription%', ' ');
            } else {
            	subMap.put('%orderDescriptionHeader%', 'ORDER DESCRIPTION');
            	subMap.put('%orderDescription%', rhShipTo.Order_Description__c);
            }
            
            // Get the data for the MIRV order lines table
            mirvItems = new List<mirvOLI>();
            String description;
            String quantity;
            String color;
            String imageURL;
            Application_Settings__c noImgURL = Application_Settings__c.getInstance('ProductImageNotAvailableURL');
            for (Order_Line_Items__c oli :oliList) {
				
				description = ' ';
				if (String.isNotBlank(oli.CW_SKU_ID__r.ECommerce_Display_Name__c)) {
					description = oli.CW_SKU_ID__r.ECommerce_Display_Name__c;
				} else {
					if (String.isNotBlank(oli.CW_SKU_ID__r.Web_Description__c)) {
						description = oli.CW_SKU_ID__r.Web_Description__c;
					}
				}
				
				quantity = (oli.Order_Quantity__c != null) ? String.valueOf(oli.Order_Quantity__c) : ' ';
				color = (String.isNotBlank(oli.CW_SKU_ID__r.Color__c)) ? Utility.toFirstCap(oli.CW_SKU_ID__r.Color__c, 0) : ' ';
				imageURL = (String.isNotBlank(oli.CW_SKU_ID__r.Product_Image_URL__c)) ? oli.CW_SKU_ID__r.Product_Image_URL__c : noImgURL.Value_Text__c;
				
				mirvItems.add(new mirvOLI(description, quantity, imageURL, oli.CW_SKU_ID__r.Name, color));
            }
		}
		
		return subMap;
	}
	
	public Map<String, String> getfooterMap() {
		
		String phone1 = subMap.get('%dnPhone%');
		String phone2 = '1' + phone1.replaceAll('\\D',''); // strip out all non-digits
		
		footerMap = new Map<String, String>();
		footerMap.put('%phoneContact1%', phone1);
		footerMap.put('%phoneContact2%', phone2);
		footerMap.put('%emailContact%', subMap.get('%dnEmail%'));
		
		system.debug('*****ManualReservation footerMap = ' + footerMap);
		
		return footerMap;
	}
}