objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <fields>
        <fullName>Value_Text__c</fullName>
        <label>Value - Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

objects/FieldIdLookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>lookup values for custom Field API names and field Id&apos;s. Used for creating pre-populated values for buttons</description>
    <fields>
        <fullName>FieldId__c</fullName>
        <description>Salesforce Field Id</description>
        <label>FieldId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Field Id Lookup</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Attribution__c.object
<CustomObject>
    <fields>
        <fullName>Associate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associate Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Attributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attribution_ID__c</fullName>
        <label>Associate User ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribution_Percent__c</fullName>
        <label>Attribution Percent</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Sales Attributions</relationshipLabel>
        <relationshipName>Sales_Attributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Associate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Attribution</label>
    <nameField>
        <displayFormat>SA-{0000000000}</displayFormat>
        <label>Sales Attribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Attributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Order_SalesAttributionIntCtrlExt_Test.cls
@isTest
public with sharing class Order_SalesAttributionIntCtrlExt_Test {
 
    static testMethod void Order_SalesAttributionIntCtrlExt_UnitTest() {       
        List<Sales_Attribution__c> saList = new List<Sales_Attribution__c>();

        // Create test Order and insert
        RH_Order__c testOrder = PrepareData.createOrder('741741741');
        insert testOrder;
        
        // Create test Sales Attribution and insert
        List<Sales_Attribution__c> testSAList = new List<Sales_Attribution__c>();
        
        insert new Application_Settings__c(Name='CCD System Hold Codes', Value_Text__c='AT,AU,AV,AW,UT,UU,UV,UW');
        
        Sales_Attribution__c testSA1 = new Sales_Attribution__c(Order__c = testOrder.Id, Attribution_ID__c = 'wsxnji', Associate_Name__c = userInfo.getUserId(), Primary_Associate__c = true, Attribution_Percent__c = 100.00); 
        Sales_Attribution__c testSA2 = new Sales_Attribution__c(Order__c = testOrder.Id, Attribution_ID__c = 'wsxnji', Associate_Name__c = userInfo.getUserId(), Primary_Associate__c = false, Attribution_Percent__c = 10.00);
        Sales_Attribution__c testSA3 = new Sales_Attribution__c(Order__c = testOrder.Id, Attribution_ID__c = 'wsxnji', Primary_Associate__c = false, Attribution_Percent__c = 1);
        Sales_Attribution__c testSA4 = new Sales_Attribution__c(Order__c = testOrder.Id, Attribution_ID__c = 'wsxnji', Associate_Name__c = userInfo.getUserId(), Primary_Associate__c = true, Attribution_Percent__c = 0);
        
        testSAList.add(testSA1);
        testSAList.add(testSA2);
        testSAList.add(testSA3);
        testSAList.add(testSA4);
        
        insert testSAList;
        
        // Create a new instance of standard controller
        Test.StartTest();
        
        PageReference saPageRef = Page.Order_SalesAttribution;
        saPageRef.getParameters().put('id',testOrder.id);
        Test.setCurrentPage(saPageRef);
      
        ApexPages.StandardController sc = new ApexPages.standardController(testOrder);
        Order_SalesAttributionIntCtrlExt controller = new Order_SalesAttributionIntCtrlExt(sc);
        
        saList = controller.getSalesAttributions();
        
        insert new FieldIdLookup__c(Name='Sales Attribution Order Number', FieldId__c='Nibbler');
        
        // Assertions
        System.assertEquals(4,saList.size());
        System.assertEquals(null,controller.edit());
        System.assertEquals(null,controller.Save());
        System.assertEquals(null,controller.edit());
        System.assertEquals(null,controller.Cancel());
        System.assertEquals(null,controller.addRow());
        System.assertEquals(null,controller.deleteRow());
        System.assertEquals('Nibbler', controller.getSalesAttributionOrderNumberFieldId());
        
        Test.StopTest();
    }  
}