objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains general application settings used throughout the application.</description>
    <fields>
        <fullName>Value_Text__c</fullName>
        <label>Value - Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ECommerce_Display_Name__c</fullName>
        <label>ECommerce Display Name</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Attribution__c.object
<CustomObject>
    <label>Sales Attribution</label>
    <nameField>
        <displayFormat>SA-{0000000000}</displayFormat>
        <label>Sales Attribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Attributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClientOrderSearchController_Test.cls
@isTest
public with sharing class ClientOrderSearchController_Test{
 
    static testMethod void ClientOrderSearchController_UnitTest() {       
        List<Sales_Attribution__c> saList = new List<Sales_Attribution__c>();

        // Create test Order and insert
        RH_Order__c testOrder = PrepareData.createOrder('741741741');
        insert testOrder;
        
        System.debug('Test Order: ' + testOrder);
      
        // Create custom setting and insert
        insert new Application_Settings__c(Name='CCD System Hold Codes', Value_Text__c='AT,AU,AV,AW,UT,UU,UV,UW');
        
        // Create test Ship To and insert
        Ship_To__c testShipTo = PrepareData.createShipTo(testOrder.Id, '2');
        
        System.debug('Test Ship To: ' + testShipTo);
   
        insert testShipTo;
        
        // Create test Product and insert
        PrepareData.productClass testPC = PrepareData.createProduct('TESTPRODUCT', 100, 'TestProd', 200);
        Product2 testProduct = testPC.p;
        testProduct.Ecommerce_Display_Name__c = 'Nibbler';
        
        // Create test Order Lines and insert
        Order_Line_Items__c testOrderLine = PrepareData.createOrderLine(testOrder.Id, testShipTo.Id, '1', testProduct.Id);
        
        // Create a new instance of standard controller
        Test.StartTest();
        
        PageReference cosPageRef = Page.ClientOrderSearch;
        
        cosPageRef.getParameters().put('fullname',testOrder.Sold_to_Last_Name__c + ', ' + testOrder.Sold_to_First_Name__c);
        cosPageRef.getParameters().put('cwskuid',testProduct.Name);
        cosPageRef.getParameters().put('ecommdisplayname',testProduct.Ecommerce_Display_Name__c);
        
        Test.setCurrentPage(cosPageRef);
      
        ClientOrderSearchController controller = new ClientOrderSearchController();
       
        // Prep SOSL test data
       	Id [] fixedSearchResults= new Id[1];
       	fixedSearchResults[0] = testOrder.Id;
       	Test.setFixedSearchResults(fixedSearchResults);
     
        controller.runSearch();
        
        cosPageRef.getParameters().put('fullname',testOrder.Sold_to_Last_Name__c + ' ' + testOrder.Sold_to_First_Name__c);
        
        controller.runSearch();
        
        cosPageRef.getParameters().put('fullname', 'Nibbles, Nibbler');
        
        controller.runSearch();
       
        Test.StopTest();
    }  
}