objects/Case.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Dev_Name__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Dev Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Delay_Notifications</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Delay Notifications</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Delay_Feed__c.object
<CustomObject>
    <description>This object provides temporary storage for delayed order date changes on new orders. This handles the situation where we may get new delayed order data before the new Order/Order Line has been created in Salesforce.</description>
    <fields>
        <fullName>Delay_Feed__c</fullName>
        <label>Delay Feed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXT_OrderShipToLine_Number__c</fullName>
        <externalId>true</externalId>
        <label>EXT OrderShipToLine Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Delay Feed</label>
    <nameField>
        <displayFormat>DF-{00000}</displayFormat>
        <label>Delay Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delay Feeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delayed_Order_Rule__c.object
<CustomObject>
    <label>Delayed Order Rule</label>
    <nameField>
        <displayFormat>DOR-{0}</displayFormat>
        <label>Delayed Order Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delayed Order Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Available_Date__c</fullName>
        <inlineHelpText>Most recent date the Client was contacted with a changed promise date</inlineHelpText>
        <label>Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Backorder_Quantity__c</fullName>
        <description>Quantity that is back-ordered for this line item</description>
        <label>Backorder Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup relationship between products and orders, so that iPIM information can go from Products to Order Lines</description>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coordinate_Group__c</fullName>
        <description>Group items to be shipped together</description>
        <label>Coordinate Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Available_Date__c</fullName>
        <inlineHelpText>Most recent available date that has been communicated to the Client</inlineHelpText>
        <label>Current Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Delay_Date__c</fullName>
        <inlineHelpText>Most recent delivery date calculated in CW. This may not have been communicated to the Client</inlineHelpText>
        <label>Current Delay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Since_Original_Available_Date__c</fullName>
        <formula>Current_Delay_Date__c - Original_Available_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of days between Current Delay Date and Original Available Date.</inlineHelpText>
        <label>Days Since Original Available Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DelayFeed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if this Order Line requires new backorder date processing.</inlineHelpText>
        <label>DelayFeed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delay_Feed_History__c</fullName>
        <label>Delay Feed History</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delay_Feed__c</fullName>
        <label>Delay Feed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXT_OrderShipToLine_Number__c</fullName>
        <externalId>true</externalId>
        <label>EXT OrderShipToLine Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Warehouse_Date__c</fullName>
        <inlineHelpText>The date this Order Line is expected to arrive in the warehouse.</inlineHelpText>
        <label>In Warehouse Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_Status_Description__c</fullName>
        <description>Blank = Open
C = Canceled
X = Closed</description>
        <label>Line Status Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Available_Date__c</fullName>
        <inlineHelpText>Original date promised to the Client</inlineHelpText>
        <label>Original Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StaleDate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if this Order Line requires stale date processing (expected date is or was in the past).</inlineHelpText>
        <label>StaleDate</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testOrderLine_DelayOrderFeedCtlExt.cls
/*
 *  Methods to test OrderLine_DelayOrderFeedCtlExt.cls
 *
 */

@isTest(SeeAllData=true)
private class testOrderLine_DelayOrderFeedCtlExt {
    
    static testMethod void ol_dofceTest1() {
        
        // Create the test data
        Delayed_Order_Rule__c dor = PrepareData.rcDelayedOrderRule('Standard');
        
        List<RH_Order__c> orderList = new List<RH_Order__c>();
        String orderNumber = 'ol_dofO1';
        RH_Order__c order = PrepareData.createOrder(orderNumber);
        orderList.add(order);
        orderNumber = 'ol_dofO2';
        order = PrepareData.createOrder(orderNumber);
        orderList.add(order);
        insert orderList;
        
        List<Ship_To__c> shipToList = new List<Ship_To__c>();
        Ship_To__c shipTo = PrepareData.createShipTo(orderList[0].Id, '1');
        shipToList.add(shipTo);
        shipTo = PrepareData.createShipTo(orderList[1].Id, '1');
        shipToList.add(shipTo);
        insert shipToList;
        
        List<Id> oIds = new List<Id>();
        for (RH_Order__c o :orderList) {
            oIds.add(o.Id);
        }
        
        List<Product2> pList = new List<Product2>();
        pList = [select Id from Product2 where IsActive = true and Name like '%ABRS' limit 5];
        system.assertEquals(5, pList.size());
        
        
        List<Order_Line_Items__c> oliList = new List<Order_Line_Items__c>();
        Order_Line_Items__c oli;
        for (Integer i=0; i<pList.size(); i++) {
            oli = PrepareData.createOrderLine(orderList[0].Id, shipToList[0].Id, String.valueOf(i+1), pList[i].Id);
            oli.EXT_OrderShipToLine_Number__c = orderList[0].Name + '-1-' + String.valueOf(i+1);
            oliList.add(oli);
            
            oli = PrepareData.createOrderLine(orderList[1].Id, shipToList[1].Id, String.valueOf(i+1), pList[i].Id);
            oli.EXT_OrderShipToLine_Number__c = orderList[1].Name + '-1-' + String.valueOf(i+1);
            oliList.add(oli);
        }
        oliList[0].Backorder_Quantity__c = 1;
        oliList[0].In_Warehouse_Date__c = system.today() + 30;
        oliList[0].Available_Date__c = system.today() + 30 + 14;
        oliList[0].Coordinate_Group__c = '0';
        
        oliList[1].Backorder_Quantity__c = 1;
        oliList[1].In_Warehouse_Date__c = system.today() + 30;
        oliList[1].Available_Date__c = system.today() + 30 + 14;
        oliList[1].Coordinate_Group__c = '0';
        
        insert oliList;
        
        String tDate = String.valueOf(system.today());
        String dfDate = String.valueOf(oliList[0].Available_Date__c + 8);
        oliList[0].Delay_Feed__c = '{"CD":"' + dfDate + '","ND":"' + tDate + '"}';
        dfDate = String.valueOf(oliList[1].Available_Date__c + 8);
        oliList[1].Delay_Feed__c = '{"CD":"' + dfDate + '","ND":"' + tDate + '"}';
        update oliList;
        
        List<Order_Line_Items__c> orderLines = new List<Order_Line_Items__c>();
        orderLines = [select Id, Delay_Feed_History__c, Backorder_Quantity__c, Coordinate_Group__c, Current_Available_Date__c, 
                        Current_Delay_Date__c, Available_Date__c, Original_Available_Date__c, In_Warehouse_Date__c, 
                        Days_Since_Original_Available_Date__c, DelayFeed__c, StaleDate__c, CW_SKU_ID__c, Line_Total__c, Line_Status_Description__c, 
                        RH_Order_Number__c, RH_Order_Number__r.Order_Type_Code__c 
                        from Order_Line_Items__c where Id = :oliList[0].Id or Id = :oliList[1].Id];
        
        DelayedOrderActions.takeAction(orderLines);
        
        List<Case> cList = new List<Case>();
        cList = [select Id, CaseNumber, Record_Type_Dev_Name__c, Request_Category__c, RH_Order_Number__c 
                from Case where RH_Order_Number__c in :oIds 
                and Record_Type_Dev_Name__c = 'Delay_Notifications' and IsClosed = false];
        
        system.debug('*****testOrderLine_DelayOrderFeedCtlExt cList = ' + clist);
        
        for (Case c :cList) {
        	system.assertEquals('Automatic Email', c.Request_Category__c);
        }
        
        system.assertEquals(2, cList.size());
        
        Test.startTest();
        
        // Test the Order Line Delay Order Feed controller
        ApexPages.StandardController std = new ApexPages.StandardController(oliList[0]);
        OrderLine_DelayOrderFeedCtlExt ctl = new OrderLine_DelayOrderFeedCtlExt(std);
        List<OrderLine_DelayOrderFeedCtlExt.DelayedOrderDataWrapper> dodwList = ctl.getDelayOrderFeedData();
        OrderLine_DelayOrderFeedCtlExt.DelayedOrderDataWrapper dodw = new OrderLine_DelayOrderFeedCtlExt.DelayedOrderDataWrapper();
        system.assertEquals(1, dodwList.size());
        
        // Execute the DelayedOrderFeed methods
        DelayedOrderFeed dof = new DelayedOrderFeed();
        DelayedOrderFeed.DelayedOrderFeedHistory dofh = new DelayedOrderFeed.DelayedOrderFeedHistory();
        DelayedOrderFeed.DelayedOrderFeedDateChange dofdc = new DelayedOrderFeed.DelayedOrderFeedDateChange('2015-10-09', '2015-10-09');
        
        Test.stopTest();
    }
}