objects/Case.object
<CustomObject>
    <fields>
        <fullName>Accommodation_Reason__c</fullName>
        <label>Accommodation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Balance Transfer</fullName>
                </value>
                <value>
                    <fullName>Carrier Caused - HDL</fullName>
                </value>
                <value>
                    <fullName>Carrier Caused - UPS</fullName>
                </value>
                <value>
                    <fullName>Damaged/Defective Product</fullName>
                </value>
                <value>
                    <fullName>Delay - Backorder</fullName>
                </value>
                <value>
                    <fullName>Delay - DC</fullName>
                </value>
                <value>
                    <fullName>Delay - Vendor</fullName>
                </value>
                <value>
                    <fullName>Delight Shipping</fullName>
                </value>
                <value>
                    <fullName>Freight - Canadian Adjustment/Refund</fullName>
                </value>
                <value>
                    <fullName>Freight - Flat Rate Delivery Fee Refund</fullName>
                </value>
                <value>
                    <fullName>Freight Refund</fullName>
                </value>
                <value>
                    <fullName>Freight - US Adjustment/Refund</fullName>
                </value>
                <value>
                    <fullName>Gift Box Fee Refund</fullName>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                </value>
                <value>
                    <fullName>Mailed in Gift Card</fullName>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                </value>
                <value>
                    <fullName>Out Of Policy Return</fullName>
                </value>
                <value>
                    <fullName>Personalization Fee Refund</fullName>
                </value>
                <value>
                    <fullName>Pre-Bill Refund</fullName>
                </value>
                <value>
                    <fullName>Price Match – Sale/Promo</fullName>
                </value>
                <value>
                    <fullName>Refund for GC/SC/Reward MOP</fullName>
                </value>
                <value>
                    <fullName>Reissue System Refund – Incorrect/Cancelled/Did Not Generate</fullName>
                </value>
                <value>
                    <fullName>Tax Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Actual_Gift_Card_Amount__c</fullName>
        <inlineHelpText>The actual value of the Gift Card due to a delayed order that will be communicated to the client via Delay Notification email. This does not have to be the same value as the Calculated Gift Card Amount.</inlineHelpText>
        <label>Actual Gift Card Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Flat_Rate_Accommodation_Amount__c</fullName>
        <inlineHelpText>Typical Accommodation amount is 10% of the line item not the total</inlineHelpText>
        <label>Requested Flat Rate Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Requested_Percentage__c</fullName>
        <inlineHelpText>Enter the percentage that you are giving for an accommodation.</inlineHelpText>
        <label>Requested Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Queue_Type__c</fullName>
        <label>Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accommodations</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Delivering on Delight</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
                <value>
                    <fullName>Final Mile Delivery Notification</fullName>
                </value>
                <value>
                    <fullName>Order Inquiries</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Reorders</fullName>
                </value>
                <value>
                    <fullName>Replacement Parts</fullName>
                </value>
                <value>
                    <fullName>Delight HQ</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_to_City__c</fullName>
        <label>Alternate City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Country__c</fullName>
        <label>Alternate Country</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Day_Phone__c</fullName>
        <label>Alternate Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Send_to_First_Name__c</fullName>
        <label>Alternate First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Last_Name__c</fullName>
        <label>Alternate Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_State__c</fullName>
        <label>Alternate State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Zip__c</fullName>
        <label>Alternate Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Accommodations</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Accommodations</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CaseAssignmentClass_Test.cls
/**
    *   Class: CaseAssignmentClass
    *   Test Class: CaseAssignmentClass_Test
    *   Commented out portions of code relating Skill Set and updating the case ownership - RC, 05/05/2016
**/


@isTest(SeeAllData=true)
private class CaseAssignmentClass_Test 
{
    testMethod static void myUnitTest() {
        
        User u = new User();
        u.Id = UserInfo.getUserId();
        
        //create skill set
     /*   Skill_Set__c s1=new Skill_Set__c();
        s1.Queue_Type__c='Accommodations';
        s1.Request_Category__c = 'Gift Card';
        s1.User__c=UserInfo.getUserId();
        s1.Active__c=true;
        insert s1;*/
          String strRecordTypeId;
        
         List<RecordType> RecordTypeList = [Select Id From RecordType Where SobjectType = 'Case' and Name='Credit Card Declines'];
        
		if(RecordTypeList.size()>0){
			strRecordTypeId=RecordTypeList[0].Id;
			
		}        
        //create cases
        
        List<Case> cList = new List<Case>();
        cList.add(new Case(
            OwnerId = u.Id,
            //Status='Transfer',
            Request_Category__c = 'Gift Card',
            RecordTypeId=strRecordTypeId,
          //  Queue_Type__c = 'Accommodations',
            Send_to_First_Name__c = 'Bob',
            Send_to_Last_Name__c = 'Jones',
            Send_to_City__c = 'Santa Cruz',
            Send_to_State__c = 'CA',
            Send_to_Zip__c = '94500',
            Send_to_Country__c = 'USA',
            //Flat_Rate_Accommodation_Amount__c = 1,
            //Actual_Gift_Card_Amount__c=100,
            Original_Requested_Percentage__c=.95,
            Send_to_Day_Phone__c = '555-555-5555')
        );
        cList.add(new Case(
            OwnerId = u.Id,
            //Status='Transfer',
            Request_Category__c = 'Gift Card',
            RecordTypeId=strRecordTypeId,
            //Queue_Type__c = 'Accommodations',
            Send_to_First_Name__c = 'Bob',
            Send_to_Last_Name__c = 'Jones',
            Send_to_City__c = 'Santa Cruz',
            Send_to_State__c = 'CA',
            Send_to_Zip__c = '94500',
            Send_to_Country__c = 'USA',
            //Flat_Rate_Accommodation_Amount__c = 1,
            //Actual_Gift_Card_Amount__c=100,
            Original_Requested_Percentage__c=.95,
            Send_to_Day_Phone__c = '555-555-5555')
        );
        insert cList;
        
        for (Case c :cList) {
            //c.Flat_Rate_Accommodation_Amount__c = 1;
            c.Accommodation_Reason__c = 'Because';
            c.Send_to_First_Name__c = 'Bob';
            c.Send_to_Last_Name__c = 'Jones';
            c.Send_to_Day_Phone__c = '555-555-5555';
            /*c.Status = 'Transfer';*/
        }
        update cList;
        
        //When cases are present
        List<Case> lstOfCases=[SELECT Id FROM Case WHERE OwnerId=:u.Id];
        CaseAssignmentClass cac=new CaseAssignmentClass(new ApexPages.StandardSetController(lstOfCases));
        cac.listViewName='My Open Cases';
        cac.cherryPicking();
        cac.findCase();
        
        //No Cases
        lstOfCases.clear();
        CaseAssignmentClass cac2=new CaseAssignmentClass(new ApexPages.StandardSetController(lstOfCases));
        cac2.findCase();
        
     }
}