objects/Case.object
<CustomObject>
    <fields>
        <fullName>Actual_Gift_Card_Amount__c</fullName>
        <inlineHelpText>The actual value of the Gift Card due to a delayed order that will be communicated to the client via Delay Notification email. This does not have to be the same value as the Calculated Gift Card Amount.</inlineHelpText>
        <label>Actual Gift Card Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email_Alert_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked means an email alert will be sent via workflow. Used by Credit Card Declines and Delay Notifications.</inlineHelpText>
        <label>Email Alert Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gift_Card_Status__c</fullName>
        <label>Gift Card Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card Declines - 1st Notice</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines - 2nd Notice</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines - Final Notice</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases10</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <label>Sold to First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <label>Sold to Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Email_Address__c</fullName>
        <label>Email To Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>WasReopened__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this case has been re-opened.</inlineHelpText>
        <label>WasReopened</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <businessProcess>Contract</businessProcess>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Email_Address__c</fullName>
        <inlineHelpText>The email will be sent to this email address.</inlineHelpText>
        <label>To Email Address</label>
        <type>Email</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Case_DNPreviewCtlExt.cls
public with sharing class Case_DNPreviewCtlExt {
	
	/*
	 *	Preview and manual send of delayed order notifications.
	 *
	 */
	
	ApexPages.StandardController stdController;
	
	public Case rhCase {get; set;}
	public Id caseId {get; set;}
	public String retURL {get; set;}
	public Boolean isError {get; set;}
	public Boolean noSend {get; set;}
	
	public Case_DNPreviewCtlExt(ApexPages.StandardController stdController) {
		
		isError = true;
		noSend = false;
		caseId = ApexPages.currentPage().getParameters().get('caseId');
		retURL = ApexPages.currentPage().getParameters().get('retURL');
		
		rhCase = new Case();
		
		// Validate page parameters and get the data needed for the notification
		if (String.isNotBlank(caseId) && String.isNotBlank(retURL)) {
			rhCase = [select Id, CaseNumber, IsClosed, RecordTypeId, Status, Gift_Card_Status__c, Request_Category__c, 
						Email_Alert_Trigger__c, Notification_Type__c, To_Email_Address__c, Actual_Gift_Card_Amount__c, 
						Order_Type_Code__c, Opportunity_PM__c, WasReopened__c, RH_Order_Number__c, 
						RH_Order_Number__r.Name, RH_Order_Number__r.Sold_to_Email__c, 
						RH_Order_Number__r.Sold_to_First_Name__c, RH_Order_Number__r.Sold_to_Last_Name__c 
						from Case where Id = :caseId];
		
			// Validate data
			Map<Id,Schema.RecordTypeInfo> rtMapById = Schema.SObjectType.Case.getRecordTypeInfosById();
			if (String.isNotBlank(rhCase.Notification_Type__c) && rhCase.Notification_Type__c == 'Delay Notifications' && rtMapById.containsKey(rhCase.RecordTypeId) && rtMapById.get(rhCase.RecordTypeId).getName() == 'Delay Notifications') {
				if (rhCase.RH_Order_Number__c != null && rhCase.isClosed != true && rhCase.Gift_Card_Status__c != 'Pending' && rhCase.WasReopened__c != true) {
					
					// If contract order/case, verify there is an Opportunity PM
					if (rhCase.Order_Type_Code__c != 'Z' || (rhCase.Order_Type_Code__c == 'Z' && rhCase.Opportunity_PM__c != null && !(rhCase.Actual_Gift_Card_Amount__c > 0))) {
						isError = false;
						
						if (Utility.isValidDomain(rhCase.RH_Order_Number__r.Sold_to_Email__c)) {
							rhCase.To_Email_Address__c = rhCase.RH_Order_Number__r.Sold_to_Email__c;
						} else {
							rhCase.To_Email_Address__c = null;
						}
					} else {
						ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'The Opportunity PM field on the Case must not be blank and Actual Gift Card must not be greater than zero for Delay Notifications for Contract Orders.'));
					}
				} else {
					ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Case must not be closed, must not have been re-opened, must not have Gift Card Status pending, and must be associated with an Order.'));
				}
			} else {
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Invalid notification type for case record type.'));
			}
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Invalid page parameters.'));
		}
	}
	
	public PageReference cancelDNPreview() {
		PageReference pr;
		if (String.isNotBlank(retURL)) {
			pr = new PageReference(retURL);
		} else {
			pr = new PageReference('/');
		}
		return pr;
	}
	
	// Send the notification email
	public PageReference sendNotification() {
		PageReference pr = null;
		
		// Make sure the email address is in the appropriate domain for our environment
		if (Utility.isValidDomain(rhCase.To_Email_Address__c)) {
			update rhCase;
			DelayedOrderNotification.sendSingleDelayNotification(rhCase.Id);
			pr = new PageReference(retURL);
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'To Email Address must be in domain "rh.com" or "restorationhardware.com".'));
		}
		
		return pr;
	}
}