objects/Case.object
<CustomObject>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card Declines - 1st Notice</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines - 2nd Notice</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines - Final Notice</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <label>Sold to Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_2__c</fullName>
        <label>Sold to Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_City__c</fullName>
        <label>Sold to City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <label>Sold to Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <label>Sold to Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <label>Sold to First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <label>Sold to Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <label>Sold to State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <label>Sold to Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <description>CW Sold to Address Line 1</description>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address_2__c</fullName>
        <description>CW Sold to Address Line 2</description>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_City__c</fullName>
        <description>CW Sold to City</description>
        <label>Sold To City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <description>CW Sold to Country</description>
        <label>Sold To Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <description>CW Sold to Daytime Phone</description>
        <label>Sold To Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <description>CW Sold to State</description>
        <label>Sold To State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <description>CW Sold to Zip</description>
        <label>Sold To Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testCase_CCDPreviewCtlExt.cls
@isTest
private class testCase_CCDPreviewCtlExt {
	
	/*
	 *	Test methods for Case_CCDPreviewCtlExt.cls
	 *
	 */
	 
	static testMethod void ccdPreviewTest1() {
		
		// create our test data
		PrepareData.populateCustomSettings();
		
		List<RH_Order__c> orderList = new List<RH_Order__c>();
		orderList.add(new RH_Order__c(
    		Name = 'ccdOrderW',
    		Order_Type_Code__c = 'W',
    		Sold_to_First_Name__c = 'Jerry',
    		Sold_to_Last_Name__c = 'Garcia',
    		Sold_to_Day_Phone__c = '777-123-4567',
    		Sold_to_Address_1__c = '710 Ashbury Street',
			Sold_to_Address_2__c = '',
			Sold_to_City__c = 'San Francisco',
			Sold_to_State__c = 'CA',
			Sold_to_Zip__c = '94117',
			Sold_to_Country__c = 'USA',
			Sold_to_Email__c = 'jerrygarcia@rh.com')
    	);
    	insert orderList;
    	
    	// Create case for our test - first insert case as record type Standard and then change 
    	// change it to record type Credit Card Declines - avoids sending email automatically upon 
    	// insert via @future job.
    	Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
    	Case ccdCase = new Case(RecordTypeId = rtMap.get('Standard').getRecordTypeId());
    	insert ccdCase;
    	ccdCase.RecordTypeId = rtMap.get('Credit Card Declines').getRecordTypeId();
    	ccdCase.Notification_Type__c = '';
    	ccdCase.Status = 'In Progress';
    	update ccdCase;
    	
    	// Now test the controller extension - test bad page parameters
    	ApexPages.StandardController std = new ApexPages.StandardController(ccdCase);
		Case_CCDPreviewCtlExt ctl = new Case_CCDPreviewCtlExt(std);
		
		// Test controller with good page parameters but bad notification type
		std = new ApexPages.StandardController(ccdCase);
		ApexPages.currentPage().getParameters().put('caseId', ccdCase.Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + ccdCase.Id);
		ctl = new Case_CCDPreviewCtlExt(std);
		
		// Test controller with good page parameters, good notification type, but no order
		ccdCase.Notification_Type__c = 'Credit Card Declines - 1st Notice';
		update ccdCase;
		std = new ApexPages.StandardController(ccdCase);
		ApexPages.currentPage().getParameters().put('caseId', ccdCase.Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + ccdCase.Id);
		ctl = new Case_CCDPreviewCtlExt(std);
		
		// Test controller with valid data
		ccdCase.RH_Order_Number__c = orderList[0].Id;
		update ccdCase;
		std = new ApexPages.StandardController(ccdCase);
		ApexPages.currentPage().getParameters().put('caseId', ccdCase.Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + ccdCase.Id);
		ctl = new Case_CCDPreviewCtlExt(std);
		
		ctl.sendNotification();
		ctl.cancelCCDPreview();
		
	}
}