objects/Case.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Dev_Name__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Dev Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <businessProcess>Contract</businessProcess>
        <label>Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>Delay_Notifications</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Delay Notifications</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Delay_Feed__c.object
<CustomObject>
    <description>This object provides temporary storage for delayed order date changes on new orders. This handles the situation where we may get new delayed order data before the new Order/Order Line has been created in Salesforce.</description>
    <fields>
        <fullName>Delay_Feed__c</fullName>
        <label>Delay Feed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delay Feed</label>
    <nameField>
        <displayFormat>DF-{00000}</displayFormat>
        <label>Delay Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delay Feeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Available_Date__c</fullName>
        <inlineHelpText>Most recent date the Client was contacted with a changed promise date</inlineHelpText>
        <label>Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Backorder_Quantity__c</fullName>
        <description>Quantity that is back-ordered for this line item</description>
        <label>Backorder Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup relationship between products and orders, so that iPIM information can go from Products to Order Lines</description>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coordinate_Group__c</fullName>
        <description>Group items to be shipped together</description>
        <label>Coordinate Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Available_Date__c</fullName>
        <inlineHelpText>Most recent available date that has been communicated to the Client</inlineHelpText>
        <label>Current Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Delay_Date__c</fullName>
        <inlineHelpText>Most recent delivery date calculated in CW. This may not have been communicated to the Client</inlineHelpText>
        <label>Current Delay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Since_Original_Available_Date__c</fullName>
        <formula>Current_Delay_Date__c - Original_Available_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of days between Current Delay Date and Original Available Date.</inlineHelpText>
        <label>Days Since Original Available Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DelayFeed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if this Order Line requires new backorder date processing.</inlineHelpText>
        <label>DelayFeed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delay_Feed_History__c</fullName>
        <label>Delay Feed History</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delay_Feed__c</fullName>
        <label>Delay Feed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Warehouse_Date__c</fullName>
        <inlineHelpText>The date this Order Line is expected to arrive in the warehouse.</inlineHelpText>
        <label>In Warehouse Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_Status_Description__c</fullName>
        <description>Blank = Open
C = Canceled
X = Closed</description>
        <label>Line Status Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Available_Date__c</fullName>
        <inlineHelpText>Original date promised to the Client</inlineHelpText>
        <label>Original Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StaleDate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if this Order Line requires stale date processing (expected date is or was in the past).</inlineHelpText>
        <label>StaleDate</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CW_External_Id__c</fullName>
        <description>Commercial Ware External Id</description>
        <externalId>true</externalId>
        <label>CW External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMMSSku__c</fullName>
        <description>ipim field map: CWLINK, where field is concatenation of fields Item#,  Color Code, Size Code.  032111LALO</description>
        <externalId>true</externalId>
        <label>DMMSSku</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STSSku__c</fullName>
        <description>ipim field map; RH Retail SKU. 032111LALO</description>
        <label>STSSku</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sku_Status__c</fullName>
        <description>ipim field map: Sku Status, where A=Active, D=Discontinued, 
N - Non-selling; P – Part ; Q –  Quality Hold;  S – Swatch.  032111LALO</description>
        <label>Sku Status</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testCase_DNPreviewCtlExt.cls
@isTest
private class testCase_DNPreviewCtlExt {
	
	/*
	 *	Test methods for Case_DNPreviewCtlExt.cls and DelayNotification.cls
	 */
	
	// Create Delay Notification test data
	@testSetup static void dnTestData() {
		
		PrepareData.populateCustomSettings();
		
		Account acc = PrepareData.createAccount();
		insert acc;
		
		Contact con = PrepareData.createContact(acc.Id);
		insert con;
		
		Opportunity opp = PrepareData.createOpportunity(acc.Id);
		opp.Ops_Contact__c = UserInfo.getUserId();
		insert opp;
		
        Delayed_Order_Rule__c dor = PrepareData.rcDelayedOrderRule('Standard');
		
		List<RH_Order__c> orderList = new List<RH_Order__c>();
		orderList.add(PrepareData.createOrder('dnOrderW'));
		orderList[0].Order_Type_Code__c = 'W';
		
		orderList.add(PrepareData.createOrder('dnOrderE'));
		orderList[1].Order_Type_Code__c = 'W';
		orderList[1].Sold_to_Email__c = '';
		
		orderList.add(PrepareData.createOrder('dnOrderZ'));
		orderList[2].Order_Type_Code__c = 'Z';
		orderList[2].Opportunity__c = opp.Id;
		insert orderList;
    	
    	List<Ship_To__c> shipToList = new List<Ship_To__c>();
    	for (Integer i=0; i<orderList.size(); i++) {
    		shipToList.add(PrepareData.createShipTo(orderList[i].Id, '1'));
    	}
        insert shipToList;
        
        Product2 product = new Product2(
        	Name = '23580079PN',
        	CW_External_Id__c = '23580079PN',
        	Sku_Status__c = 'A',
        	STSSku__c = '23580080',
        	DMMSSku__c = '23580079PN'
        );
        insert product;
		
		List<Order_Line_Items__c> oliList = new List<Order_Line_Items__c>();
		oliList.add(PrepareData.createOrderLine(orderList[0].Id, shipToList[0].Id, '001', product.Id));
		oliList[0].Backorder_Quantity__c = 1;
        oliList[0].In_Warehouse_Date__c = system.today() + 30;
        oliList[0].Available_Date__c = system.today() + 30 + 14;
        oliList[0].Coordinate_Group__c = '0';
        
		oliList.add(PrepareData.createOrderLine(orderList[1].Id, shipToList[1].Id, '001', product.Id));
		oliList[1].Backorder_Quantity__c = 1;
        oliList[1].In_Warehouse_Date__c = system.today() + 30;
        oliList[1].Available_Date__c = system.today() + 30 + 14;
        oliList[1].Coordinate_Group__c = '0';
        
		oliList.add(PrepareData.createOrderLine(orderList[2].Id, shipToList[2].Id, '001', product.Id));
		oliList[2].Backorder_Quantity__c = 1;
        oliList[2].In_Warehouse_Date__c = system.today() + 30;
        oliList[2].Available_Date__c = system.today() + 30 + 14;
        oliList[2].Coordinate_Group__c = '0';
        insert oliList;
        
        String tDate = String.valueOf(system.today());
        String dfDate = String.valueOf(oliList[0].Available_Date__c + 8);
        oliList[0].Delay_Feed__c = '{"CD":"' + dfDate + '","ND":"' + tDate + '"}';
        dfDate = String.valueOf(oliList[1].Available_Date__c + 8);
        oliList[1].Delay_Feed__c = '{"CD":"' + dfDate + '","ND":"' + tDate + '"}';
        dfDate = String.valueOf(oliList[2].Available_Date__c + 8);
        oliList[2].Delay_Feed__c = '{"CD":"' + dfDate + '","ND":"' + tDate + '"}';
        update oliList;
        
        List<Order_Line_Items__c> orderLines = new List<Order_Line_Items__c>();
        orderLines = [select Id, Delay_Feed_History__c, Backorder_Quantity__c, Coordinate_Group__c, Current_Available_Date__c, 
                        Current_Delay_Date__c, Available_Date__c, Original_Available_Date__c, In_Warehouse_Date__c, 
                        Days_Since_Original_Available_Date__c, DelayFeed__c, StaleDate__c, CW_SKU_ID__c, Line_Total__c, Line_Status_Description__c, 
                        RH_Order_Number__c, RH_Order_Number__r.Order_Type_Code__c 
                        from Order_Line_Items__c where Id = :oliList[0].Id or Id = :oliList[1].Id or Id = :oliList[2].Id];
        DelayedOrderActions.takeAction(orderLines);
	}
	
	// Test with valid parameters and a non-Contract case/order
	static testMethod void dnPreviewTest1() {
		
		List<Case> cList = new List<Case>();
        cList = [select Id, CaseNumber, Record_Type_Dev_Name__c, Request_Category__c, RH_Order_Number__c 
                from Case where Record_Type_Dev_Name__c = 'Delay_Notifications' and IsClosed = false and RH_Order_Number__r.Name = 'dnOrderW'];
        
        system.assertEquals(1, cList.size());
        
        // Now test the controller extension
    	ApexPages.StandardController std = new ApexPages.StandardController(cList[0]);
    	ApexPages.currentPage().getParameters().put('caseId', cList[0].Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + cList[0].Id);
		Case_DNPreviewCtlExt ctl = new Case_DNPreviewCtlExt(std);
		
		Test.startTest();
		ctl.sendNotification();
		Test.stopTest();
		
		cList = [select Id, CaseNumber, Record_Type_Dev_Name__c, Request_Category__c, RH_Order_Number__c 
                from Case where Record_Type_Dev_Name__c = 'Delay_Notifications' and IsClosed = true and RH_Order_Number__r.Name = 'dnOrderW'];
        
        system.assertEquals(1, cList.size());
	}
	
	// Test with valid parameters and a Contract case/order
	static testMethod void dnPreviewTest2() {
		
		List<Case> cList = new List<Case>();
        cList = [select Id, CaseNumber, Record_Type_Dev_Name__c, Request_Category__c, RH_Order_Number__c 
                from Case where Record_Type_Dev_Name__c = 'Delay_Notifications' and IsClosed = false and RH_Order_Number__r.Name = 'dnOrderZ'];
        
        system.assertEquals(1, cList.size());
        
        // Now test the controller extension
    	ApexPages.StandardController std = new ApexPages.StandardController(cList[0]);
    	ApexPages.currentPage().getParameters().put('caseId', cList[0].Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + cList[0].Id);
		Case_DNPreviewCtlExt ctl = new Case_DNPreviewCtlExt(std);
		
		Test.startTest();
		ctl.sendNotification();
		Test.stopTest();
		
		cList = [select Id, CaseNumber, Record_Type_Dev_Name__c, Request_Category__c, RH_Order_Number__c 
                from Case where Record_Type_Dev_Name__c = 'Delay_Notifications' and IsClosed = true and RH_Order_Number__r.Name = 'dnOrderZ'];
        
        system.assertEquals(1, cList.size());
	}
	
	// Test with bad data
	static testMethod void dnPreviewTest3() {
		
		List<Case> cList = new List<Case>();
        cList = [select Id, CaseNumber, Record_Type_Dev_Name__c, Request_Category__c, RH_Order_Number__c 
                from Case where Record_Type_Dev_Name__c = 'Delay_Notifications' and IsClosed = false and RH_Order_Number__r.Name = 'dnOrderE'];
        
        system.assertEquals(1, cList.size());
        
        // Now test the controller extension with incomplete or bad data
        ApexPages.StandardController std = new ApexPages.StandardController(cList[0]);
		Case_DNPreviewCtlExt ctl = new Case_DNPreviewCtlExt(std);
        
    	std = new ApexPages.StandardController(cList[0]);
    	ApexPages.currentPage().getParameters().put('caseId', cList[0].Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + cList[0].Id);
		ctl = new Case_DNPreviewCtlExt(std);
		
		ctl.sendNotification();
		ctl.cancelDNPreview();
		
		cList = [select Id, CaseNumber, Record_Type_Dev_Name__c, Request_Category__c, RH_Order_Number__c, Opportunity_PM__c, Gift_Card_Status__c, Notification_Type__c 
                from Case where Record_Type_Dev_Name__c = 'Delay_Notifications' and IsClosed = false and RH_Order_Number__r.Name = 'dnOrderZ'];
        cList[0].Opportunity_PM__c = null;
        update cList;
		std = new ApexPages.StandardController(cList[0]);
		ApexPages.currentPage().getParameters().put('caseId', cList[0].Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + cList[0].Id);
		ctl = new Case_DNPreviewCtlExt(std);
		
		cList[0].Gift_Card_Status__c = 'Pending';
		update cList;
		std = new ApexPages.StandardController(cList[0]);
		ApexPages.currentPage().getParameters().put('caseId', cList[0].Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + cList[0].Id);
		ctl = new Case_DNPreviewCtlExt(std);
		
		cList[0].Notification_Type__c = '';
		update cList;
		std = new ApexPages.StandardController(cList[0]);
		ApexPages.currentPage().getParameters().put('caseId', cList[0].Id);
		ApexPages.currentPage().getParameters().put('retURL', '/' + cList[0].Id);
		ctl = new Case_DNPreviewCtlExt(std);
	}
}