objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Requested_Percentage__c</fullName>
        <inlineHelpText>Enter the percentage that you are giving for an accommodation.</inlineHelpText>
        <label>Requested Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateNewCaseLineController_Test.cls
/* This is a test class for CreateNewCaseLineController */
@isTest
private class CreateNewCaseLineController_Test {
/*
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        PrepareData.populateCustomSettings();
        //Creating a RH Order
        RH_Order__c rhOrder=new RH_Order__c();
        rhOrder.Name='ORDER 123';
        insert rhOrder;
        
        Case c=new Case();
        c.Original_Requested_Percentage__c=.95;
        c.Order_Number__c=rhOrder.Id;
        insert c;
        
        Case_Line_Items__c cli=new Case_Line_Items__c();
        cli.Case_Number__c=c.Id;
        insert cli;
        
        PageReference pr=new PageReference('/apex/CreateNewCaseLine');
        Test.setCurrentPage(pr);
        ApexPages.currentPage().getParameters().put('caseId', c.Id);
        ApexPages.currentPage().getParameters().put('orderId', rhOrder.Id);
        ApexPages.currentPage().getParameters().put('retURL', '/' + rhOrder.Id);
        ApexPages.currentPage().getParameters().put('retURL', '/' + rhOrder.Name);
        
        CreateNewCaseLineController cn=new CreateNewCaseLineController();
        cn.navigateToURL();
        
    }
*/
}