objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <inlineHelpText>Order Total sums all ship tos</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Delay_Notifications</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Delay Notifications</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Delay_Feed__c.object
<CustomObject>
    <description>This object provides temporary storage for delayed order date changes on new orders. This handles the situation where we may get new delayed order data before the new Order/Order Line has been created in Salesforce.</description>
    <fields>
        <fullName>EXT_OrderShipToLine_Number__c</fullName>
        <externalId>true</externalId>
        <label>EXT OrderShipToLine Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Delay Feed</label>
    <nameField>
        <displayFormat>DF-{00000}</displayFormat>
        <label>Delay Feed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delay Feeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Delay_Notifications_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked this record will be used to schedule the batch job to process automatic email Delay Notifications cases. Only one Delay Notifications Schedule record should be active at a time.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Catch_Up_Run_Time__c</fullName>
        <inlineHelpText>Time of day to schedule the catch up run of the batch job to process Delay Notifications cases. All cases not processed via other runs will be processed at this time. Make sure Catch Up Run Time is BETWEEN Start Time and End Time.</inlineHelpText>
        <label>Catch Up Run Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12:00 AM</fullName>
                </value>
                <value>
                    <fullName>1:00 AM</fullName>
                </value>
                <value>
                    <fullName>2:00 AM</fullName>
                </value>
                <value>
                    <fullName>3:00 AM</fullName>
                </value>
                <value>
                    <fullName>4:00 AM</fullName>
                </value>
                <value>
                    <fullName>5:00 AM</fullName>
                </value>
                <value>
                    <fullName>6:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>8:00 AM</fullName>
                </value>
                <value>
                    <fullName>9:00 AM</fullName>
                </value>
                <value>
                    <fullName>10:00 AM</fullName>
                </value>
                <value>
                    <fullName>11:00 AM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM</fullName>
                </value>
                <value>
                    <fullName>1:00 PM</fullName>
                </value>
                <value>
                    <fullName>2:00 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM</fullName>
                </value>
                <value>
                    <fullName>4:00 PM</fullName>
                </value>
                <value>
                    <fullName>5:00 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM</fullName>
                </value>
                <value>
                    <fullName>7:00 PM</fullName>
                </value>
                <value>
                    <fullName>8:00 PM</fullName>
                </value>
                <value>
                    <fullName>9:00 PM</fullName>
                </value>
                <value>
                    <fullName>10:00 PM</fullName>
                </value>
                <value>
                    <fullName>11:00 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <inlineHelpText>The last scheduled run of the day of the batch job to process automatic email Delay Notifications cases will be at or before this time. Make sure End Time is AFTER Start Time.</inlineHelpText>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12:00 AM</fullName>
                </value>
                <value>
                    <fullName>1:00 AM</fullName>
                </value>
                <value>
                    <fullName>2:00 AM</fullName>
                </value>
                <value>
                    <fullName>3:00 AM</fullName>
                </value>
                <value>
                    <fullName>4:00 AM</fullName>
                </value>
                <value>
                    <fullName>5:00 AM</fullName>
                </value>
                <value>
                    <fullName>6:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>8:00 AM</fullName>
                </value>
                <value>
                    <fullName>9:00 AM</fullName>
                </value>
                <value>
                    <fullName>10:00 AM</fullName>
                </value>
                <value>
                    <fullName>11:00 AM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM</fullName>
                </value>
                <value>
                    <fullName>1:00 PM</fullName>
                </value>
                <value>
                    <fullName>2:00 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM</fullName>
                </value>
                <value>
                    <fullName>4:00 PM</fullName>
                </value>
                <value>
                    <fullName>5:00 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM</fullName>
                </value>
                <value>
                    <fullName>7:00 PM</fullName>
                </value>
                <value>
                    <fullName>8:00 PM</fullName>
                </value>
                <value>
                    <fullName>9:00 PM</fullName>
                </value>
                <value>
                    <fullName>10:00 PM</fullName>
                </value>
                <value>
                    <fullName>11:00 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interval_Minutes__c</fullName>
        <inlineHelpText>Number of minutes between each scheduled run of the batch job to process automatic email Delay Notifications cases.</inlineHelpText>
        <label>Interval Minutes</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Cases__c</fullName>
        <inlineHelpText>Maximum number of Delay Notifications cases to process during each batch job run (other than the catch up run).</inlineHelpText>
        <label>Max Cases</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <inlineHelpText>Time of day to schedule the first batch job to process automatic email Delay Notifications cases.  Make sure Start Time is BEFORE End Time.</inlineHelpText>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12:00 AM</fullName>
                </value>
                <value>
                    <fullName>1:00 AM</fullName>
                </value>
                <value>
                    <fullName>2:00 AM</fullName>
                </value>
                <value>
                    <fullName>3:00 AM</fullName>
                </value>
                <value>
                    <fullName>4:00 AM</fullName>
                </value>
                <value>
                    <fullName>5:00 AM</fullName>
                </value>
                <value>
                    <fullName>6:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>8:00 AM</fullName>
                </value>
                <value>
                    <fullName>9:00 AM</fullName>
                </value>
                <value>
                    <fullName>10:00 AM</fullName>
                </value>
                <value>
                    <fullName>11:00 AM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM</fullName>
                </value>
                <value>
                    <fullName>1:00 PM</fullName>
                </value>
                <value>
                    <fullName>2:00 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM</fullName>
                </value>
                <value>
                    <fullName>4:00 PM</fullName>
                </value>
                <value>
                    <fullName>5:00 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM</fullName>
                </value>
                <value>
                    <fullName>7:00 PM</fullName>
                </value>
                <value>
                    <fullName>8:00 PM</fullName>
                </value>
                <value>
                    <fullName>9:00 PM</fullName>
                </value>
                <value>
                    <fullName>10:00 PM</fullName>
                </value>
                <value>
                    <fullName>11:00 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Delay Notifications Schedule</label>
    <nameField>
        <label>Delay Notifications Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delay Notifications Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Backorder_Quantity__c</fullName>
        <description>Quantity that is back-ordered for this line item</description>
        <label>Backorder Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EXT_OrderShipToLine_Number__c</fullName>
        <externalId>true</externalId>
        <label>EXT OrderShipToLine Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Status_Description__c</fullName>
        <description>Blank = Open
C = Canceled
X = Closed</description>
        <label>Line Status Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <description>Including shipping, handling, and tax</description>
        <inlineHelpText>Order total sums all ship tos.</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testBatchProcessDelayNotifications.cls
/*
 *  Methods to test BatchProcessDelayNotifications.cls
 *
 */

@isTest(SeeAllData=true)
private class testBatchProcessDelayNotifications {
    
public static String bpdn_CRON_EXP = '0 0 0 15 3 ? 2022';
    
    static testMethod void bpdnTest1() {
    String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name ='Delay Notifications'].Id;
        
        
        // Create the test data
        // Create a test Delay Notifications Schedule
        Delay_Notifications_Schedule__c DNS = new Delay_Notifications_Schedule__c(
                Name = 'bpdnTest1 Schedule',
                Active__c = false,
                Start_Time__c = '9:00 AM',
                End_Time__c = '3:00 PM',
                Interval_Minutes__c = 30,
                Max_Cases__c = 15,
                Catch_Up_Run_Time__c = '1:00 PM',
                Sunday__c = true,
                Monday__c = true,
                Tuesday__c = true,
                Wednesday__c = true,
                Thursday__c = true,
                Friday__c = true,
                Saturday__c = true
        );
        insert DNS;
        
        // Create the test data
        Delayed_Order_Rule__c dor = PrepareData.rcDelayedOrderRule('Standard');
        
        List<RH_Order__c> orderList = new List<RH_Order__c>();
        String orderNumber = 'bpdnT1O1';
        RH_Order__c order = PrepareData.createOrder(orderNumber);
        order.Sold_to_Email__c = 'billybob-example123456789012345678901234567890@rh.com';
        orderList.add(order);
        orderNumber = 'bpdnT1O2';
        order = PrepareData.createOrder(orderNumber);
        order.Total_Order_Amount__c = 95;
        orderList.add(order);
        insert orderList;
        
        List<Ship_To__c> shipToList = new List<Ship_To__c>();
        Ship_To__c shipTo = PrepareData.createShipTo(orderList[0].Id, '1');
        shipToList.add(shipTo);
        shipTo = PrepareData.createShipTo(orderList[1].Id, '1');
        shipToList.add(shipTo);
        insert shipToList;
        
        List<Id> oIds = new List<Id>();
        for (RH_Order__c o :orderList) {
            oIds.add(o.Id);
        }
        
        List<Product2> pList = new List<Product2>();
        pList = [select Id from Product2 where IsActive = true and Name like '%ABRS' limit 5];
        system.assertEquals(5, pList.size());
        
        
        List<Order_Line_Items__c> oliList = new List<Order_Line_Items__c>();
        Order_Line_Items__c oli;
        for (Integer i=0; i<pList.size(); i++) {
            oli = PrepareData.createOrderLine(orderList[0].Id, shipToList[0].Id, String.valueOf(i+1), pList[i].Id);
            oli.EXT_OrderShipToLine_Number__c = orderList[0].Name + '-1-' + String.valueOf(i+1);
            oliList.add(oli);
            
            oli = PrepareData.createOrderLine(orderList[1].Id, shipToList[1].Id, String.valueOf(i+1), pList[i].Id);
            oli.EXT_OrderShipToLine_Number__c = orderList[1].Name + '-1-' + String.valueOf(i+1);
            oliList.add(oli);
        }
        oliList[0].Backorder_Quantity__c = 1;
        oliList[0].Line_Status_Description__c = 'Open';
        oliList[0].In_Warehouse_Date__c = system.today() + 30;
        oliList[0].Available_Date__c = system.today() + 30 + 14;
        oliList[0].Coordinate_Group__c = '0';
        oliList[0].Line_Total__c = 70;
        
        oliList[1].Backorder_Quantity__c = 1;
        oliList[1].Line_Status_Description__c = 'Open';
        oliList[1].In_Warehouse_Date__c = system.today() + 30;
        oliList[1].Available_Date__c = system.today() + 30 + 14;
        oliList[1].Coordinate_Group__c = '0';
        oliList[1].Line_Total__c = 20;
        
        insert oliList;
        
        String tDate = String.valueOf(system.today());
        String dfDate = String.valueOf(oliList[0].Available_Date__c + 8);
        oliList[0].Delay_Feed__c = '{"CD":"' + dfDate + '","ND":"' + tDate + '"}';
        dfDate = String.valueOf(oliList[1].Available_Date__c + 8);
        oliList[1].Delay_Feed__c = '{"CD":"' + dfDate + '","ND":"' + tDate + '"}';
        update oliList;
        
        List<Order_Line_Items__c> orderLines = new List<Order_Line_Items__c>();
        orderLines = [select Id, Delay_Feed_History__c, Backorder_Quantity__c, Coordinate_Group__c, Current_Available_Date__c, 
                        Current_Delay_Date__c, Available_Date__c, Original_Available_Date__c, In_Warehouse_Date__c, 
                        Days_Since_Original_Available_Date__c, DelayFeed__c, StaleDate__c, CW_SKU_ID__c, Line_Total__c, Line_Status_Description__c, 
                        RH_Order_Number__c, RH_Order_Number__r.Order_Type_Code__c 
                        from Order_Line_Items__c where Id = :oliList[0].Id or Id = :oliList[1].Id];
        
        DelayedOrderActions.takeAction(orderLines);
        
        List<Case> cList = new List<Case>();
        
        /*
        cList = [select Id, CaseNumber,  Request_Category__c, RH_Order_Number__c, IsClosed, Actual_Gift_Card_Amount__c 
                from Case where RH_Order_Number__c in :oIds 
                and Record_Type_Dev_Name__c = 'Delay Notifications' and Request_Category__c = 'Automatic Email' 
                and IsClosed = false];
        */
        
        cList = [select Id, CaseNumber,  Request_Category__c, RH_Order_Number__c, IsClosed, Actual_Gift_Card_Amount__c 
                from Case where RH_Order_Number__c in :oIds 
                and RecordTypeId=:strRecordTypeId];
        for (Case c :cList) {
            system.debug('*****TESTBATCHPROCESSDELAY c.IsClosed = ' + c.IsClosed + ' c.Request_Category = ' + c.Request_Category__c + ' c.Actual_Gift_Card_Amount = ' + c.Actual_Gift_Card_Amount__c);
        }
        
        
        system.assert(cList.size() > 0);
        //system.assertEquals(2, cList.size());
        
        // Make sure a gift card is generated
        cList[0].Actual_Gift_Card_Amount__c = 100;
        update clist[0];
        
        Test.startTest();
        
        BatchProcessDelayNotifications BA =  new BatchProcessDelayNotifications();
        String queryFields = 'Id, Sold_to_Email__c';
        String whereClause = 'RecordType.DeveloperName = \'Delay_Notifications\' AND Request_Category__c = \'Automatic Email\' AND IsClosed = false AND On_Hold__c = false AND RH_Order_Number__r.Name LIKE \'bpdnT1%\' ORDER BY CreatedDate';
        whereClause += ' LIMIT ' + DNS.Max_Cases__c;
        BA.bpdnQueryString = 'SELECT ' + queryFields + ' FROM Case WHERE ' + whereClause;
        system.debug('*****testBatchProcessDelayNotifications querystring = ' + BA.bpdnQueryString);
        Database.executeBatch(BA, 5);
         
        Test.stopTest();
        
        /*
        cList = [select Id, CaseNumber, Request_Category__c, RH_Order_Number__c, SendGrid_Result__c, Gift_Card_Status__c, IsClosed 
                from Case where RH_Order_Number__c in :oIds 
                and RecordTypeId=:strRecordTypeId and Request_Category__c = 'Automatic Email' 
                and (IsClosed = true or Gift_Card_Status__c = 'Pending')];
        
        for (Case c :cList) {
            system.debug('*****TESTBATCHPROCESSDELAY c.IsClosed = ' + c.IsClosed + ' c.Gift_Card_Status = ' + c.Gift_Card_Status__c);
        }
        */
        
        cList = [select Id, CaseNumber, Request_Category__c, RH_Order_Number__c, SendGrid_Result__c, Gift_Card_Status__c, IsClosed 
                from Case where RH_Order_Number__c in :oIds and RecordTypeId=:strRecordTypeId];
        system.debug('*****testBatchProcessDelayNotifications cList = ' + clist);
        
        for (Case c :cList) {
        	system.assertEquals('Automatic Email', c.Request_Category__c);
        	system.assert(c.IsClosed || c.Gift_Card_Status__c == 'Pending');
        }
        
        system.assert(cList.size() > 0);
        //system.assertEquals(2, cList.size());
        //for (Case c :cList) {
            //system.assert(c.SendGrid_Result__c.contains('SUCCESS'));
        //}
        
        // Test (execute the code) the schedulable class
        String jobId = System.schedule('ScheduleBatchProcessDelayNotificationsTEST', bpdn_CRON_EXP, new ScheduleBatchProcessDelayNotifications());
    }
}