objects/Case.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Designer__c</fullName>
        <label>Designer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Address__c</fullName>
        <label>New Address</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Original_Requested_Percentage__c</fullName>
        <inlineHelpText>Enter the percentage that you are giving for an accommodation.</inlineHelpText>
        <label>Requested Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_to_City__c</fullName>
        <label>Alternate City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Country__c</fullName>
        <label>Alternate Country</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Day_Phone__c</fullName>
        <label>Alternate Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Send_to_First_Name__c</fullName>
        <label>Alternate First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Last_Name__c</fullName>
        <label>Alternate Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_State__c</fullName>
        <label>Alternate State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Zip__c</fullName>
        <label>Alternate Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Address__c</fullName>
        <label>ShipTo1 Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Day_Phone__c</fullName>
        <label>ShipTo1 Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Email__c</fullName>
        <label>ShipTo1 Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Reorders</fullName>
        <active>true</active>
        <businessProcess>Standard with Call for Pick</businessProcess>
        <label>Reorders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection__c</fullName>
        <label>Collection</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The line number selected must be from the order on the case.</errorMessage>
            <filterItems>
                <field>$Source.Order__c</field>
                <operation>equals</operation>
                <valueField>Order_Line_Items__c.RH_Order_Number__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order_Line_Items__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <description>Do not use.</description>
        <formula>Line_Number__r.RH_Order_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <recordTypes>
        <fullName>Reorders</fullName>
        <active>true</active>
        <label>Reorders</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup relationship between products and orders, so that iPIM information can go from Products to Order Lines</description>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <formula>CW_SKU_ID__r.Class__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection__c</fullName>
        <formula>CW_SKU_ID__r.Collection__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Collection</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>This field is populated by information from CW. It is hidden from the page layout because the Order LIne Number (standard name field) is required on the page layout, and this would in essence duplicate information. There is a workflow rule that takes this number and populates it into the line number name field.</description>
        <label>Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <description>Order Quantity of Line</description>
        <label>Order Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Price of Line</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CW_Color__c</fullName>
        <description>ipim field map: Color Code. 032111LALO</description>
        <label>CW Color</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CW_Item_Description__c</fullName>
        <description>upload from ipim. field map: CW Item Description. 121311LALO</description>
        <label>CW Item Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection__c</fullName>
        <description>Weekly IPIM load, column BW. 011612LALO</description>
        <label>Collection</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Description__c</fullName>
        <description>ipim field map: Web Description</description>
        <label>Web Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Designer__c</fullName>
        <description>Designer assigned to order</description>
        <label>Order Classification</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Address__c</fullName>
        <label>Ship To 1 Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Day_Phone__c</fullName>
        <label>Ship To 1 Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Email__c</fullName>
        <label>Ship To 1 Email</label>
        <type>Email</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseLineItemsTrigger_Test.cls
/* Author SP- ForeFront
 * Purpose Test the Increment and decrement counts of OrderLines for CaseLines Added/Modified in Cases
 * Dates/Sections modified 8-25-14
 * V2.0- Added Test method to unit test "Case Line Item" Record type default functionality 
       - Author:  vk@ff
 */
@isTest
(SeeAllData=true)
public class CaseLineItemsTrigger_Test {
  
    
    /*****Added by vk@ff to unit test default case line record type, order line to case line and Reorder_Count update functionality*****/
  
    static testmethod void testOrderToCase()
    {
        test.startTest();
        RecordType r=[SELECT Id FROM RecordType WHERE SobjectType='Case' AND Name='Reorders'];
        
        //Create Case
        Case c=new Case();
        c.RecordTypeId=r.Id;
        c.New_Address__c = 'TestAddress';
        c.Send_to_First_Name__c = 'Bob';
        c.Send_to_Last_Name__c = 'Jones';
        c.Send_to_City__c = 'Santa Cruz';
        c.Send_to_State__c = 'CA';
        c.Send_to_Zip__c = '94500';
        c.Send_to_Country__c = 'USA';
        c.Send_to_Day_Phone__c = '555-555-5555';
        c.Original_Requested_Percentage__c=.95;
        c.Status='New';
        insert c;
        
        Case c1=[SELECT Id,CaseNumber, Owner.Name FROM Case WHERE Id=:c.Id];
        System.debug(' Case CREATED ' + c1);
        
        //Create Order 
        RH_Order__c rho=new RH_Order__c();
        rho.ShipTo1_Address__c='Test Street';
        rho.ShipTo1_Day_Phone__c='111-222-3344';
        rho.ShipTo1_Email__c='test@testrh.com';
        rho.Designer__c='Test Designer';
        insert rho;
        
        //Create Order lines
                
       List<Order_Line_Items__c> lstOfOLI=new List<Order_Line_Items__c>();
        
        for(Integer i=0;i<100;i++)
        {
            Order_Line_Items__c ol=new Order_Line_Items__c();
            ol.RH_Order_Number__c=rho.Id;
            ol.Line_Number__c='00'+(i+1);
            ol.Unit_Price__c=50.00;
            ol.Line_Total__c=100.00;
            ol.Order_Quantity__c=2;
            lstOfOLI.add(ol);
        }
        insert lstOfOLI;
        
        
        c.RH_Order_Number__c=rho.Id;
        update c;
        
       //Create Case line items
        
       List<Case_Line_Items__c> lstOfCLI=new List<Case_Line_Items__c>();
        
        RecordType clRT=[Select Id From RecordType Where SobjectType = 'Case_Line_Items__c' AND Name = 'Reorders' Limit 1];
        for(Integer j=0;j<100;j++)
        {
            Case_Line_Items__c cli=new Case_Line_Items__c();
            cli.Case_Number__c=c.Id;
            cli.Order__c=rho.Id;
            cli.Line_Number__c=lstOfOLI[j].Id;
            cli.RecordTypeId=clRT.Id;
            lstOfCLI.add(cli);
        }
        insert lstOfCLI;
        
        //Update Line numbers
        for(Integer i=99;i>49;i--)
        {
            for(Case_Line_Items__c cli:lstOfCLI)
            {
                cli.Line_Number__c=lstOfOLI[i].Id;
                
            }
        }
        update lstOfCLI;
        
        //Remove Order line number
        for(Case_Line_Items__c cli:lstOfCLI)
        {
            cli.Line_Number__c=null;
        }
        
        update lstOfCLI;
                
        //Delete Case line items
        delete lstOfCLI;
        
        //System.debug('Case LINE CREATED' + cli.Id);
        
        test.stopTest();
    }
    
    static testmethod void testProductToCaseLine()
    {
        test.startTest();
            
        //Create Case
        Case c=new Case();
        c.New_Address__c = 'TestAddress';
        c.Send_to_First_Name__c = 'Bob';
        c.Send_to_Last_Name__c = 'Jones';
        c.Send_to_City__c = 'Santa Cruz';
        c.Send_to_State__c = 'CA';
        c.Send_to_Zip__c = '94500';
        c.Send_to_Country__c = 'USA';
        c.Send_to_Day_Phone__c = '555-555-5555';
        c.Original_Requested_Percentage__c=.95;
        insert c;
        
        //Create Product
        Product2 p=new Product2();
        p.Name='Test PRODUCT';
        p.Class__c='Test CLASS';
        p.Collection__c='Test Collection';
        p.CW_Color__c='WHITE';
        p.CW_Item_Description__c='This is product description';
        p.Web_Description__c='Test Web Description';
        insert p;
        
        //Create Case Line Item
        Case_Line_Items__c cli=new Case_Line_Items__c();
        cli.Case_Number__c=c.Id;
        cli.CW_SKU_ID__c=p.Id;
        insert cli;
        
        test.stopTest();
        
    }
}