objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CW SKU</fullName>
                </value>
                <value>
                    <fullName>CW Data Entry Needed</fullName>
                </value>
                <value>
                    <fullName>Needs a Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Timer_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Break</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                </value>
                <value>
                    <fullName>Frontline</fullName>
                </value>
                <value>
                    <fullName>Idle</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Special Project</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Walk-up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Timer Entries</relationshipLabel>
        <relationshipName>Timer_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>This is the duration of the timed event in seconds</inlineHelpText>
        <label>Duration in Seconds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the timer entry</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <description>Time the entry was started</description>
        <inlineHelpText>Start of Activity</inlineHelpText>
        <label>StartTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timer_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timer Entry</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Timer Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timer Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TimerControllerTest.cls
/***************************************************************************************
    CLIENT
        Restoration Hardware
            
    PURPOSE
        Test class for TimerController        
    
    CHANGE LOG
        v0.1; 2014/10/09; Philip Koshy/Forefront; Initial Build
        v0.2; 2014/10/20; Justin Wagner/ForeFront; 94% Code Coverage Test
***************************************************************************************/


@isTest
public class TimerControllerTest
{
   /* @isTest
    static void testTimerController()
    { 
        // Insert a case for our test to use
        Case myCase = new Case();
        insert myCase;
        
        // Create a page reference to the Timer page and set the caseId parameter and saveOnLoad parameter
        PageReference pageReference = new PageReference('/apex/Timer');
        Test.setCurrentPage(pageReference);
        ApexPages.currentPage().getParameters().put('caseId', myCase.Id);
        ApexPages.currentPage().getParameters().put('actionOnLoad', 'Lunch');
        
        // Instantiate a new timer controller and specify a few default values for the 
        // underlying timerEntry. Note we do *not* explicitly initialize the Case__c 
        // field for the timerEntry; this should be done within the controller when
        // the controller's save() method is called.
		TimerController timerController = new TimerController();

        Timer_Entry__c myTimeEntry = new Timer_Entry__c();
        myTimeEntry.Source__c = 'Lunch';
        myTimeEntry.Case__c = myCase.Id;
        myTimeEntry.User__c = UserInfo.getUserId();
        myTimeEntry.StartTime__c = system.now();

        insert myTimeEntry;

        //test login
        timerController.login();
        
        // Calling the save method should insert the timer entry record
        timerController.save();
        
        Timer_Entry__c timerEntry = [SELECT Duration__c, Case__c
							 		 FROM Timer_Entry__c
                                     LIMIT 1];

        // Make sure the timer entry we've retrieved has the case id saved
        System.assertEquals(timerEntry.Case__c, myCase.Id);

        //test saveOnLoad param
        PageReference pageReference2 = new PageReference('/apex/Timer');
        Test.setCurrentPage(pageReference2);
        ApexPages.currentPage().getParameters().put('caseId', myCase.Id);
        ApexPages.currentPage().getParameters().put('saveOnLoad', 'true');

        //new timer to test onPageLoad
        TimerController timerController2 = new TimerController();

        Case myCase2 = new Case();
        insert myCase2;

        Timer_Entry__c myTimeEntry2 = new Timer_Entry__c();
        myTimeEntry2.Memo__c = 'Test Memo DEBUG2';
        myTimeEntry2.Source__c = 'Lunch';
        myTimeEntry2.Case__c = myCase2.Id;
        myTimeEntry2.User__c = UserInfo.getUserId();
        myTimeEntry2.StartTime__c = system.now();

        insert myTimeEntry2;

        timerController2.login();
        timerController2.onPageLoad();
        timerController2.save();
        timerController2.logout();

        Timer_Entry__c timerEntry2 = [SELECT Duration__c, Case__c
                                     FROM Timer_Entry__c
                                     LIMIT 1];

        System.assertEquals(timerEntry2.Case__c, myCase.Id);
 
        //new timer to test logout without login
        TimerController timerController4 = new TimerController();
        timerController4.timerEntry.Action__c ='Lunch';
        timerController4.timerEntry.Source__c ='Lunch';
        timerController4.timerEntry.User__c = UserInfo.getUserId();

        timerController4.logout();

    }*/
}