objects/Case.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Approval_Status__c</fullName>
        <label>Exchange Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Return_Location__c</fullName>
        <label>Return Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gallery 005 - Newport Beach</fullName>
                </value>
                <value>
                    <fullName>Gallery 006 - Corte Madera</fullName>
                </value>
                <value>
                    <fullName>Gallery 008 - Portland</fullName>
                </value>
                <value>
                    <fullName>Gallery 010 - Palo Alto</fullName>
                </value>
                <value>
                    <fullName>Gallery 011 - Pasadena</fullName>
                </value>
                <value>
                    <fullName>Gallery 015 - Troy</fullName>
                </value>
                <value>
                    <fullName>Gallery 017 - St Louis</fullName>
                </value>
                <value>
                    <fullName>Gallery 020 - Dallas</fullName>
                </value>
                <value>
                    <fullName>Gallery 024 - Seattle</fullName>
                </value>
                <value>
                    <fullName>Gallery 025 - King of Prussia</fullName>
                </value>
                <value>
                    <fullName>Gallery 027 - Tysons Corner</fullName>
                </value>
                <value>
                    <fullName>Gallery 031 - Metairie</fullName>
                </value>
                <value>
                    <fullName>Gallery 034 - Charlotte</fullName>
                </value>
                <value>
                    <fullName>Gallery 035 - San Antonio</fullName>
                </value>
                <value>
                    <fullName>Gallery 036 - Pittsburgh</fullName>
                </value>
                <value>
                    <fullName>Gallery 044 - Aventura</fullName>
                </value>
                <value>
                    <fullName>Gallery 045 - Birmingham</fullName>
                </value>
                <value>
                    <fullName>Gallery 048 - Short Hills</fullName>
                </value>
                <value>
                    <fullName>Gallery 051 - Edina</fullName>
                </value>
                <value>
                    <fullName>Gallery 053 - Georgetown</fullName>
                </value>
                <value>
                    <fullName>Gallery 054 - Nashville</fullName>
                </value>
                <value>
                    <fullName>Gallery 061 - Walnut Creek</fullName>
                </value>
                <value>
                    <fullName>Gallery 062 - Flatiron</fullName>
                </value>
                <value>
                    <fullName>Gallery 071 - Oak Brook</fullName>
                </value>
                <value>
                    <fullName>Gallery 072 - Red Bank</fullName>
                </value>
                <value>
                    <fullName>Gallery 073 - Winter Park</fullName>
                </value>
                <value>
                    <fullName>Gallery 074 - Thousand Oaks</fullName>
                </value>
                <value>
                    <fullName>Gallery 075 - Columbus</fullName>
                </value>
                <value>
                    <fullName>Gallery 078 - Indianapolis</fullName>
                </value>
                <value>
                    <fullName>Gallery 100 - Mission Viejo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_To__c</fullName>
        <label>Send To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Address (Contact)</fullName>
                </value>
                <value>
                    <fullName>Ship To 1</fullName>
                </value>
                <value>
                    <fullName>Sold To (Order)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>To_Email_Address__c</fullName>
        <label>Email To Address</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Returns</fullName>
        <active>true</active>
        <businessProcess>Standard with Cancelled</businessProcess>
        <label>Returns</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exchange</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Override_Amount__c</fullName>
        <label>Price Override Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Override_Reason__c</fullName>
        <label>Price Override Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>G - Price Adjustment</fullName>
                </value>
                <value>
                    <fullName>Z - Accommodation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Override_Type__c</fullName>
        <label>Price Override Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>% off</fullName>
                </value>
                <value>
                    <fullName>Amt off</fullName>
                </value>
                <value>
                    <fullName>New Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity_Returned__c</fullName>
        <label>Quantity Returned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <description>Do not use.</description>
        <formula>Line_Number__r.RH_Order_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_DC__c</fullName>
        <label>Return DC</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Reason__c</fullName>
        <label>Return Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arrived Too Late</fullName>
                </value>
                <value>
                    <fullName>Client Pref - No Qlty Issue</fullName>
                </value>
                <value>
                    <fullName>Coordinating Items Not Avail</fullName>
                </value>
                <value>
                    <fullName>Damaged</fullName>
                </value>
                <value>
                    <fullName>Damaged - MOS</fullName>
                </value>
                <value>
                    <fullName>Defective</fullName>
                </value>
                <value>
                    <fullName>Defective - MOS</fullName>
                </value>
                <value>
                    <fullName>Gift</fullName>
                </value>
                <value>
                    <fullName>Not As Shown</fullName>
                </value>
                <value>
                    <fullName>Parts/Assembly Issue</fullName>
                </value>
                <value>
                    <fullName>Personalization Qlty Issue</fullName>
                </value>
                <value>
                    <fullName>Qlty Not As Expected</fullName>
                </value>
                <value>
                    <fullName>Swatch Return</fullName>
                </value>
                <value>
                    <fullName>Wrong Item/Qty Ordered</fullName>
                </value>
                <value>
                    <fullName>Wrong Item/Qty Rec&apos;d</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <recordTypes>
        <fullName>Returns</fullName>
        <active>true</active>
        <label>Returns</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup relationship between products and orders, so that iPIM information can go from Products to Order Lines</description>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity__c</fullName>
        <description>Quantity that was shipped for this line item</description>
        <label>Shipped Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Fulfilling_Warehouse__c</fullName>
        <description>ipim field map:  Fulfilling Warehouse, where F=Furniture &amp; S=Shelf Stock.  032111LALO,</description>
        <label>Fulfilling Warehouse</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SKU_Ship_Via__c</fullName>
        <label>Product Ship Via</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Gallery__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gallery</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>GalleryOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>To_Email_Address__c</fullName>
        <inlineHelpText>The email will be sent to this email address.</inlineHelpText>
        <label>To Email Address</label>
        <type>Email</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testCase_ReturnReceiptCtlExt.cls
/*
 *	Methods to test Case_ReturnReceiptCtlExt.cls, ReturnReceipt.cls, Case_Accept.cls and related classes/methods
 *
 */

@isTest
private class testCase_ReturnReceiptCtlExt {
	
	// Create Return Receipt test data
	@testSetup static void rrTestData() {
		
		PrepareData.populateCustomSettings();
		
		Map<String, Schema.RecordTypeInfo> rtAccMap = Schema.SObjectType.Account.getRecordTypeInfosByName();
		List<Account> accList = new List<Account>();
		accList.add(new Account(Name = 'RH DC 97 (SoCal)', RecordTypeId = rtAccMap.get('Internal').getRecordTypeId(), HDL_Code__c = '97'));
		accList.add(new Account(Name = 'RH DC 89 (OH)', RecordTypeId = rtAccMap.get('Internal').getRecordTypeId(), HDL_Code__c = '89'));
		insert accList;
		
		Account galleryAcc = new Account(Name = 'Gallery 006 - Corte Madera', RecordTypeId = rtAccMap.get('Internal').getRecordTypeId(), Email__c = 'cortemadera@rh.com', Furniture_Return_DC__c = accList[0].Id, Shelf_Stock_Return_DC__c = accList[1].Id);
		insert galleryAcc;
		
		User u = [select Id, Gallery__c from User where Id = :UserInfo.getUserId()];
		u.Gallery__c = 'Gallery 006 - Corte Madera';
		update u;
		
		RH_Order__c order = PrepareData.createOrder('rroT1');
		insert order;
		
		Ship_To__c shipTo = PrepareData.createShipTo(order.Id, '1');
		insert shipTo;
		
		PrepareData.productClass p0 = PrepareData.createProduct('57360001BLPM', 1743.50, '57360001BLPM', 6395.00);
		PrepareData.productClass p1 = PrepareData.createProduct('23750121PN', 211.58, '23750121PN', 625.00);
		PrepareData.productClass p2 = PrepareData.createProduct('17050043EUCY', 4.26, '17050043EUCY', 20);
		List<Product2> pList = new List<Product2>();
		p0.p.SKU_Ship_Via__c = '5';
		pList.add(p0.p);
		p1.p.Fulfilling_Warehouse__c = 'F';
		pList.add(p1.p);
		p2.p.Fulfilling_Warehouse__c = 'S';
		pList.add(p2.p);
		update pList;
		
		List<Order_Line_Items__c> oliList = new List<Order_Line_Items__c>();
		oliList.add(PrepareData.createOrderLine(order.Id, shipTo.Id, '1', p0.p.Id));
		oliList.add(PrepareData.createOrderLine(order.Id, shipTo.Id, '2', p1.p.Id));
		oliList.add(PrepareData.createOrderLine(order.Id, shipTo.Id, '3', p2.p.Id));
		for (Order_Line_Items__c oli :oliList) {
			oli.Shipped_Quantity__c = 2;
		}
		insert oliList;
		
		Map<String, Schema.RecordTypeInfo> rtCaseMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
		Case returnCase = new Case(
			RecordTypeId = rtCaseMap.get('Returns').getRecordTypeId(),
			RH_Order_Number__c = order.Id,
			Status = 'New'
		);
		insert returnCase;
		
		
	}
	
	static testMethod void rrTest1() {
		
		Map<String, Schema.RecordTypeInfo> rtCaseMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
		Case returnCase = [select Id from Case where RecordTypeId = :rtCaseMap.get('Returns').getRecordTypeId()];
		
		Test.startTest();
		
		// Instantiate the controller extension and start testing
		ApexPages.StandardController std = new ApexPages.StandardController(returnCase);
		ApexPages.currentPage().getParameters().put('caseId', returnCase.Id);
		Case_ReturnReceiptCtlExt ctl = new Case_ReturnReceiptCtlExt(std);
		
		ctl.rhCase.Send_To__c = 'Sold To';
		ctl.saveCaseandCaseLine();
		
		returnCase = [select Id, Return_Location__c, Send_To__c, RH_Order_Number__r.Sold_to_Email__c, To_Email_Address__c from Case where Id = :returnCase.Id];
		system.assertEquals('Gallery 006 - Corte Madera', returnCase.Return_Location__c);
		system.assertEquals('Sold To', returnCase.Send_To__c);
		system.assertEquals(returnCase.RH_Order_Number__r.Sold_to_Email__c, ctl.rhCase.To_Email_Address__c);
		
		// Select a few order lines and verify that they are added as case lines
		ctl.selectOrderLines();
		List<Case_ReturnReceiptCtlExt.SelectOrderLineClass> availableOrderLines = ctl.getOrderLines();
		for (Case_ReturnReceiptCtlExt.SelectOrderLineClass oli :availableOrderLines) {
			oli.selected = true;
		}
		ctl.getSelected();
		List<Case_ReturnReceiptCtlExt.SelectOrderLineClass> selectedOrderLines = ctl.getselectedOrderLines();
		system.assertEquals(3, selectedOrderLines.size());
		for (Case_ReturnReceiptCtlExt.SelectOrderLineClass oli :selectedOrderLines) {
			oli.returnItem.rtnItem.Quantity_Returned__c = 1;
			oli.returnItem.rtnItem.Return_Reason__c = 'Arrived Too Late';
		}
		system.assertEquals(0, ctl.rhCaseLineList.size());
		selectedOrderLines[0].solcQuantityChanged();
		selectedOrderLines[0].returnItem.rtnItem.Exchange__c = true;
		selectedOrderLines[0].returnItem.toggleExchange();
		
		Product2 psearch = [select Id, Name from Product2 where Name = '57360001BLPM'];
		List<Id> pIds = new List<Id>();
		pIds.add(psearch.Id);
		Test.setFixedSearchResults(pIds);
		
		selectedOrderLines[0].returnItem.exchList[0].productSearchString = '57360001BLPM';
		selectedOrderLines[0].returnItem.exchList[0].executeProductSearch();
		system.assertEquals(1, selectedOrderLines[0].returnItem.exchList[0].searchResults.size());
		selectedOrderLines[0].returnItem.exchList[0].searchResults[0].selectedProduct();
		
		ctl.createCaseLines();
		system.assertEquals(3, ctl.rhCaseLineList.size());
		
		// Edit the Return Items and do a price override
		ctl.editReturnItems();
		ctl.rwList[0].rtns[0].rtnItem.Exchange__c = false;
		ctl.rwList[0].rtns[0].toggleExchange();
		ctl.rwList[0].rtns[0].exchList[0].clearExchItem(ctl.rwList[0].rtns[0].exchList[0]);
		ctl.rwList[0].rtns[0].quantityChanged();
		ctl.cancelEdit();
		ctl.rwList[0].rtns[0].exchList[0].displayProductSearch();
		ctl.rwList[0].rtns[0].exchList[0].cancelProductSearch();
		
		ctl.saveCaseandCaseLine();
		ctl.rwList[2].rtns[0].deleteReturnItem();
		system.assert(!ctl.approvalRequired);
		system.assertEquals(2, ctl.rwList.size());
		
		Account cmAccount = new Account();
		cmAccount = [select Id, Name, Furniture_Return_DC__c, Furniture_Return_DC__r.HDL_Code__c, Shelf_Stock_Return_DC__c, Shelf_Stock_Return_DC__r.HDL_Code__c from Account where Name = 'Gallery 006 - Corte Madera'];
		for (Case_Line_Items__c cli :ctl.rhCaseLineList) {
			system.assertEquals(true, String.isNotBlank(cli.Return_DC__c));
			if (cli.CW_SKU_ID__r.SKU_Ship_Via__c == '5' || cli.CW_SKU_ID__r.SKU_Ship_Via__c == '6') {
				system.assertEquals('HDL', cli.Return_DC__c);
			} else {
				if (cli.CW_SKU_ID__r.Fulfilling_Warehouse__c == 'F') {
					system.assertEquals(cmAccount.Furniture_Return_DC__r.HDL_Code__c, cli.Return_DC__c);
				}
				if (cli.CW_SKU_ID__r.Fulfilling_Warehouse__c == 'S') {
					system.assertEquals(cmAccount.Shelf_Stock_Return_DC__r.HDL_Code__c, cli.Return_DC__c);
				}
			}
		}
		
		// Edit and Cancel
		ctl.editReturn();
		ctl.cancelEdit();
		
		
		// Send the Return Receipt and attach as PDF
		ctl.sendReturnReceipt();
		ctl.attachPdf();
		
		// Transfer case to the gallery queue
		ctl.transferGallery();
		List<Id> caseIds = new List<Id>();
		caseIds.add(returnCase.Id);
		Case_Accept.acceptCases(caseIds);
		
		// Test the packing slip functionality
		ctl.getpackingSlipDCList();
		ctl.setselectedPackingSlipDC('HDL');
		ctl.psSelect();
		String DC = ctl.getselectedPackingSlipDC();
		
		// Run through the left over code
		ctl.misShip();
		ctl.cancelReturnReceipt();
		ctl.transferCSC();
		
		Test.stopTest();
	}
	
	// Test the Approval Process related methods
	static testMethod void rrTest2() {
		
		Map<String, Schema.RecordTypeInfo> rtCaseMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
		Case returnCase = [select Id from Case where RecordTypeId = :rtCaseMap.get('Returns').getRecordTypeId()];
		
		Test.startTest();
		
		// Instantiate the controller extension and start testing
		ApexPages.StandardController std = new ApexPages.StandardController(returnCase);
		ApexPages.currentPage().getParameters().put('caseId', returnCase.Id);
		Case_ReturnReceiptCtlExt ctl = new Case_ReturnReceiptCtlExt(std);
		
		ctl.rhCase.Send_To__c = 'Sold To';
		ctl.saveCaseandCaseLine();
		
		returnCase = [select Id, Return_Location__c, Send_To__c, RH_Order_Number__r.Sold_to_Email__c, To_Email_Address__c from Case where Id = :returnCase.Id];
		system.assertEquals('Gallery 006 - Corte Madera', returnCase.Return_Location__c);
		system.assertEquals('Sold To', returnCase.Send_To__c);
		system.assertEquals(returnCase.RH_Order_Number__r.Sold_to_Email__c, ctl.rhCase.To_Email_Address__c);
		
		// Select a few order lines and verify that they are added as case lines
		ctl.selectOrderLines();
		List<Case_ReturnReceiptCtlExt.SelectOrderLineClass> availableOrderLines = ctl.getOrderLines();
		for (Case_ReturnReceiptCtlExt.SelectOrderLineClass oli :availableOrderLines) {
			oli.selected = true;
		}
		ctl.getSelected();
		List<Case_ReturnReceiptCtlExt.SelectOrderLineClass> selectedOrderLines = ctl.getselectedOrderLines();
		system.assertEquals(3, selectedOrderLines.size());
		for (Case_ReturnReceiptCtlExt.SelectOrderLineClass oli :selectedOrderLines) {
			oli.returnItem.rtnItem.Quantity_Returned__c = 1;
			oli.returnItem.rtnItem.Return_Reason__c = 'Arrived Too Late';
		}
		system.assertEquals(0, ctl.rhCaseLineList.size());
		selectedOrderLines[0].solcQuantityChanged();
		selectedOrderLines[0].returnItem.rtnItem.Exchange__c = true;
		selectedOrderLines[0].returnItem.toggleExchange();
		
		Product2 psearch = [select Id, Name from Product2 where Name = '23750121PN'];
		List<Id> pIds = new List<Id>();
		pIds.add(psearch.Id);
		Test.setFixedSearchResults(pIds);
		
		selectedOrderLines[0].returnItem.exchList[0].productSearchString = '23750121PN';
		selectedOrderLines[0].returnItem.exchList[0].executeProductSearch();
		system.assertEquals(1, selectedOrderLines[0].returnItem.exchList[0].searchResults.size());
		selectedOrderLines[0].returnItem.exchList[0].searchResults[0].selectedProduct();
		
		ctl.createCaseLines();
		system.assertEquals(3, ctl.rhCaseLineList.size());
		
		// Edit the Return Items and do a price override
		ctl.editReturnItems();
		
		ctl.rwList[0].rtns[0].rtnItem.Price_Override_Type__c = 'New Price';
		ctl.rwList[0].rtns[0].rtnItem.Price_Override_Amount__c = 10;
		ctl.rwList[0].rtns[0].exchList[0].exchQuantityChanged();
		ctl.rwList[0].rtns[0].rtnItem.Price_Override_Type__c = 'Amt off';
		ctl.rwList[0].rtns[0].exchList[0].exchQuantityChanged();
		ctl.rwList[0].rtns[0].rtnItem.Price_Override_Type__c = '';
		ctl.rwList[0].rtns[0].exchList[0].exchQuantityChanged();
		ctl.rwList[0].rtns[0].rtnItem.Price_Override_Type__c = '% off';
		ctl.rwList[0].rtns[0].rtnItem.Price_Override_Amount__c = 10;
		ctl.rwList[0].rtns[0].rtnItem.Price_Override_Reason__c = 'G - Price Adjustment';
		
		ctl.saveCaseandCaseLine();
		system.assert(ctl.approvalRequired);
		
		// Submit for approval
		ctl.submitApproval();
		returnCase = [select Id, Exchange_Approval_Status__c, Exchange_Approval_Rejection_Reason__c from Case where Id = :returnCase.Id];
		system.assertEquals('Pending', returnCase.Exchange_Approval_Status__c);
		
		ApexPages.StandardController std1 = new ApexPages.StandardController(returnCase);
		ApexPages.currentPage().getParameters().put('caseId', returnCase.Id);
		Case_ReturnReceiptCtlExt ctl1 = new Case_ReturnReceiptCtlExt(std1);
		
		ctl1.approveReject();
		ctl1.rhCase.Exchange_Approval_Rejection_Reason__c = 'Discount Not Approved';
		ctl1.rejectExch();
		
		returnCase = [select Id, Exchange_Approval_Status__c, Exchange_Approval_Rejection_Reason__c from Case where Id = :returnCase.Id];
		system.assertEquals('Rejected', returnCase.Exchange_Approval_Status__c);
		
		Test.stopTest();
	}
}