objects/Case.object
<CustomObject>
    <fields>
        <fullName>On_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this case is on hold and is not available for processing.</inlineHelpText>
        <label>On Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Category__c</fullName>
        <label>Order Type Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Home Office</fullName>
                </value>
                <value>
                    <fullName>Specialty Group</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SendGrid_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, means there is an @future process running to send an email via SendGrid for this Case.</inlineHelpText>
        <label>SendGrid In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To 1</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address__c</fullName>
        <label>Sold to Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Hold_Code__c</fullName>
        <label>System Hold Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <inlineHelpText>If your Status is &quot;Transfer,&quot; you must select a value for &quot;To&quot; to designate who you want to transfer the case to.</inlineHelpText>
        <label>To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accommodations</fullName>
                </value>
                <value>
                    <fullName>Alternative Address</fullName>
                </value>
                <value>
                    <fullName>CSC DC/HDL</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>Gallery Returns</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
                <value>
                    <fullName>Order Processing</fullName>
                </value>
                <value>
                    <fullName>Product Specialists</fullName>
                </value>
                <value>
                    <fullName>QA</fullName>
                </value>
                <value>
                    <fullName>QA/Audit</fullName>
                </value>
                <value>
                    <fullName>RHD Returns</fullName>
                </value>
                <value>
                    <fullName>RH Ops</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <description>Do not use.</description>
        <formula>Line_Number__r.RH_Order_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CasetoOrderFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Case_Field__c</fullName>
        <label>Case Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Field__c</fullName>
        <label>Order Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CasetoOrderFieldMapping</label>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Type_Category__c</fullName>
        <label>Order Type Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Home Office</fullName>
                </value>
                <value>
                    <fullName>Specialty Group</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address__c</fullName>
        <formula>IF(
AND
(
ISBLANK(Sold_To_Address_1__c),
ISBLANK(Sold_to_Address_2__c),
ISBLANK(Sold_to_Company__c),
ISBLANK(Sold_to_City__c),
ISBLANK(Sold_to_State__c),
ISBLANK(Sold_to_Zip__c),
ISBLANK(Sold_to_Country__c)
), 
null, 
Sold_To_Address_1__c  + BR() +  Sold_to_Address_2__c + BR() + Sold_to_City__c + &quot;, &quot; +  Sold_to_State__c + &quot;, &quot; + Sold_to_Zip__c + BR() + Sold_to_Country__c
)</formula>
        <label>Sold To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Hold_Code__c</fullName>
        <description>AT</description>
        <label>System Hold Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateCase.cls
/*
    Class: UpdateCase
    Description: This case contains a method to trigger the assignment rules for a case which is not in a New Status
    Developer: vk@ff on 07/21/2014 -- Peter Alexander Mandy 03042016 purged deprecated methods.
    Test Class: CaseTrigger_Test
    Developer:- Raghu Cheruvu on 04/26/2016, added method populateOrderShipToOnCase as part of CSC Refactoring.
*/
    
public without sharing class UpdateCase
{
    //Lock Case and associated Case Line Records
    //Added by vk@ff on 09/24/2014
    public static void lockCaseRecord(List<Id> cToLock) {
    List<Case> lstOfCases=[SELECT Id,Submitted_for_Lock__c FROM Case WHERE Id IN: cToLock and Submitted_for_Lock__c = false];
    
    List<Approval.ProcessSubmitRequest> lstOfAppReqs=new List<Approval.ProcessSubmitRequest>();
    
    if (!lstOfCases.isEmpty()) {
      for (Case c: lstOfCases) {
        // Create an approval request for Case record
        Approval.ProcessSubmitRequest req =new Approval.ProcessSubmitRequest();
        req.setComments('Lock Case Record');
        req.setObjectId(c.Id);
        lstOfAppReqs.add(req);
        c.Submitted_for_Lock__c=true;
      }
      
      try {
        update lstOfCases;  
      } catch(DmlException e) {
        System.debug(e);  
      }
      
      //Submit the approval request
      List<Approval.ProcessResult> lstOfResults=Approval.process(lstOfAppReqs,false);
      
      for (Approval.ProcessResult appvResult: lstOfResults) {
      	//System.assert(appvResult.isSuccess());
        //System.assertEquals('Pending', appvResult.getInstanceStatus(), 'Instance Status'+appvResult.getInstanceStatus());
      	
      }
      
      // Lock the Case Line records
      List<Id> lockedCaseIds = new List<Id>();
      for (Case c :lstOfCases) {
        lockedCaseIds.add(c.Id);
      }
      lockCaseLinesRecord(lockedCaseIds);
    }
  }
  
  //Unlock Case Record
  //Added by vk@ff on 09/24/2014
  
  public static void unlockCaseRecord(List<Id> cToUnlock)
  {
    try
    {
      List<Case> lstCases=[SELECT Id, Submitted_for_Lock__c FROM Case WHERE Id IN: cToUnlock];
      List<Id> lstOfAppReqIds=new List<Id>();
      
          for(Case c: lstCases)
          {
        c.Submitted_for_Lock__c=false;
        lstOfAppReqIds.add(c.Id);
      }
      
      try
      {
        update lstCases;  
      }
      catch(DmlException e)
      {
        System.debug(e.getMessage());  
      }
      
       //Reject Approval Request
      if(lstOfAppReqIds.size()>0)
      {
         Id retVal = null;
       List<Approval.ProcessWorkitemRequest> lstOfAppReq=new List<Approval.ProcessWorkitemRequest>();
        
         List<ProcessInstanceWorkitem> lstWorkItems=[Select Id from ProcessInstanceWorkitem where ProcessInstanceWorkitem.ProcessInstance.TargetObjectId IN: lstOfAppReqIds];
         
        
            for(ProcessInstanceWorkitem workItem:lstWorkItems)
            {
                // Reject the submitted request
                     
                // Instantiate the new ProcessWorkitemRequest object and populate it
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments('Rejecting request.');
                req.setAction('Reject');
                                      
                //Specify the item to be worked
                req.setWorkitemId(workItem.Id);
                lstOfAppReq.add(req);            
                
            }
        
        // Submit the request for rejection
            List<Approval.ProcessResult> result2 =  Approval.process(lstOfAppReq, false);
      }
    }
      
    catch(DmlException e)
    {
      System.debug(e.getMessage());  
    }
  }
  
    //Lock Record
    //Added by vk@ff on 09/16/2014
    public static void lockCaseLinesRecord(List<Id> clinesToLock)
    {
        List<Case_Line_Items__c> lstCLItems=[SELECT Id, Case_Number__c FROM Case_Line_Items__c WHERE Case_Number__c IN: clinesToLock];
        List<Approval.ProcessSubmitRequest> lstOfAppReqs=new List<Approval.ProcessSubmitRequest>();
    
        for(Case_Line_Items__c caseLine: lstCLItems)
        {
          // Create an approval request for Case record
          Approval.ProcessSubmitRequest req =new Approval.ProcessSubmitRequest();
          req.setComments('Lock Case Line Record');
          req.setObjectId(caseLine.Id);
          lstOfAppReqs.add(req);
    }
    
    //Submit the approval request
    List<Approval.ProcessResult> lstOfResults=Approval.process(lstOfAppReqs,false);
    
    for(Approval.ProcessResult appvResult: lstOfResults)
    {
      System.assert(appvResult.isSuccess());
            System.assertEquals('Pending', appvResult.getInstanceStatus(), 'Instance Status'+appvResult.getInstanceStatus());
    }
        
    }
  
  //Unlock Case line items
  //Added by vk@ff on 09/16/2014
  
  public static void unlockCaseLinesRecord(List<Id> cLinesToUnlock)
  {
    try
    {
      List<Case_Line_Items__c> lstCLItems=[SELECT Id, Case_Number__c FROM Case_Line_Items__c WHERE Case_Number__c IN: cLinesToUnlock];
      List<Id> lstOfAppReqIds=new List<Id>();
      
          for(Case_Line_Items__c caseLine: lstCLItems)
          {
        lstOfAppReqIds.add(caseLine.Id);
      }
      
       //Reject Approval Request
      if(lstOfAppReqIds.size()>0)
      {
         Id retVal = null;
       List<Approval.ProcessWorkitemRequest> lstOfAppReq=new List<Approval.ProcessWorkitemRequest>();
        
         List<ProcessInstanceWorkitem> lstWorkItems=[Select Id from ProcessInstanceWorkitem where ProcessInstanceWorkitem.ProcessInstance.TargetObjectId IN: lstOfAppReqIds];
         
        
            for(ProcessInstanceWorkitem workItem:lstWorkItems)
            {
                // Reject the submitted request
                     
                // Instantiate the new ProcessWorkitemRequest object and populate it
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments('Rejecting request.');
                req.setAction('Reject');
                                      
                //Specify the item to be worked
                req.setWorkitemId(workItem.Id);
                lstOfAppReq.add(req);            
                
            }
        
        // Submit the request for rejection
            List<Approval.ProcessResult> result2 =  Approval.process(lstOfAppReq, false);
      }
    }
      
    catch(DmlException e)
    {
      System.debug(e.getMessage());  
    }
  }  
	
	public static void populateOrderShipToOnCase(List<Case> caseList,Set<Id> CaseOrderIds) {
		
		//Select ShipTos based on order number
		List<Ship_To__c> ShipToList = new List<Ship_To__c>([Select Order__c, Id from Ship_To__c where Order__c in :CaseOrderIds and Name = '1']);
		Map<String,String> OrderShipToMap = new Map<String,String>();
		if (!ShipToList.isEmpty()) {
			for (Ship_To__c s :ShipToList) {
				OrderShipToMap.put(s.Order__c, s.Id);
			}
		}
		
		for (Case c :caseList) {
			if (OrderShipToMap.containsKey(c.RH_Order_Number__c)) {
				c.Ship_To_1__c = OrderShipToMap.get(c.RH_Order_Number__c);
			}
		}
	}
	
    // Populate specific fields on the Cases in the provided list from the Order and update
	// other dependent Case fields. Assumes each Case in caseList has a valid Order Number lookup field
	public static void populateOrderInformation(List<Case> caseList, Boolean isInsert) {
		Set<Id> oIds = new Set<Id>();
		Map<String, CasetoOrderFieldMapping__c> fieldMap = new Map<String, CasetoOrderFieldMapping__c>();
		
		// Create the list of the Ids for the Order records we need
		for (Case c : caseList) {
			oIds.add(c.Rh_Order_Number__c);
		}
		
		// Retrieve the fields to query from the custom setting, build the Order query and get the Order records
		fieldMap = CasetoOrderFieldMapping__c.getAll();
		String orderQuery = 'SELECT Id, ';
		for (CasetoOrderFieldMapping__c cofm :fieldMap.values()) {
			orderQuery += cofm.Order_Field__c + ', ';
		}
		orderQuery = orderQuery.removeEnd(', ');
		orderQuery += ' FROM RH_Order__c WHERE Id IN: oIds';
		Map<Id, RH_Order__c> mapOfOrders = new Map<Id, RH_Order__c>((List<RH_Order__c>)Database.query(orderQuery));
		
		// Determine if we need to set/change the on hold status of Delay Notifications cases
		Map<Id, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosById();
		Boolean checkOnHold = false;
		for (Case c :caseList) {
			if (rtMap.containsKey(c.RecordTypeId) && rtMap.get(c.RecordTypeId).getName() == 'Delay Notifications') {
				checkOnHold = true;
			}
		}
		
		// Get the relevant On Hold date ranges if necessary
		Map<String, Boolean> todayHoldsMap;
		if (checkOnHold) {
			todayHoldsMap = DelayedOrderActions.getTodayHolds();
		}
		
		// Populate the Case records with the data from the Order and update dependent Case fields
		for (Case c :caseList) {
			
			for (CasetoOrderFieldMapping__c cofm :fieldMap.values()) {
				
				// For Credit Card Declines cases, only copy System_Hold_Code__c if not insert
				if (cofm.Case_Field__c == 'System_Hold_Code__c' && isInsert) {
					if (rtMap.containsKey(c.RecordTypeId) && rtMap.get(c.RecordTypeId).getName() == 'Credit Card Declines') {
						continue;
					}
				}
				
				// Verify that the user has access to the Opportunity before copying the Opportunity Id
				if (cofm.Case_Field__c == 'Opportunity_del__c') {
					String oppId = (String)(mapOfOrders.get(c.RH_Order_Number__c).get(cofm.Order_Field__c));
					if (String.isNotBlank(oppId)) {
						Boolean hasOppRead = [select RecordId, HasReadAccess from UserRecordAccess where UserId = :UserInfo.getUserId() and RecordId = :oppId].HasReadAccess;
						if (!hasOppRead) {
							c.put(cofm.Case_Field__c, null);
							continue;
						}
					}
				}
				
				c.put(cofm.Case_Field__c, mapOfOrders.get(c.RH_Order_Number__c).get(cofm.Order_Field__c));
			}
			
			// Set the Order Type Category and On Hold state for all Delay Notifications cases
			if (rtMap.get(c.RecordTypeId).getName() == 'Delay Notifications') {
				c.Order_Type_Category__c = DelayedOrderActions.getOrderTypeCategory(c.Order_Type_Code__c);
				if (String.isNotBlank(c.Order_Type_Category__c) && todayHoldsMap.containsKey(c.Order_Type_Category__c)) {
					c.On_Hold__c = todayHoldsMap.get(c.Order_Type_Category__c);
				}
			}
			
			if (String.isNotBlank(c.Sold_to_Address__c)) {
				c.Sold_to_Address__c = c.Sold_to_Address__c.replaceAll('<br>','\n');
			}
		}
	}
	
    //Set the case to Re-Open if Action Required is true and the case was closed previously.
    public static void ReopenCaseOnActionReqd(List<Id> lstOfCases)
    {
        List<Case> lstOfCasesToUpdate=[SELECT Id, Status FROM Case WHERE Id IN: lstOfCases];
        for(Case c: lstOfCasesToUpdate)
        {
            c.Status='Re-open'; 
        }
        try
        {
            update lstOfCasesToUpdate;
        }
        catch(DMLException e)
        {
            System.debug(e.getMessage());
        }
    }
    
    /*
    //Initiate Case Assignment Rules from Code
    public static void UpdateApplyAssignmentRules(List<Id> lstOfCaseIds)
    {
        List<Case> lstOfCasesToUpdate= [SELECT Id,OwnerId,Status,To__c FROM Case WHERE Id IN:lstOfCaseIds];
        
        System.debug('BEFORE' + lstOfCasesToUpdate);
        //Fetching the assignment rules on case
        List<AssignmentRule> AR = new List<AssignmentRule>();
        AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];
		System.debug(AR);
        //Creating the DMLOptions for "Assign using active assignment rules" checkbox
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        if(AR.size()>0){
        dmlOpts.assignmentRuleHeader.assignmentRuleId= AR[0].id;
        
        dmlOpts.EmailHeader.triggerUserEmail = true;
        }
        
        for(Case c: lstOfCasesToUpdate)
        {
            //Assigning the Assignment rule Id
            c.setOptions(dmlOpts);
        }
                
        try
        {
            update lstOfCasesToUpdate;
			System.debug('AFTER'+lstOfCasesToUpdate);
        }
            
        catch(DmlException e)
        {
            System.debug(e.getMessage());
        }
    }
    */
        
    // Set the SendGrid In Process flag to indicate that a future process has been launched to send
    // an email about the Cases of the Ids provided
    public static void UpdateSendGridInProcess(List<Id> caseIds) {
        
        List<Case> caseList = new List<Case>();
        for (Id cId :caseIds) {
          caseList.add(new Case(
            Id = cId,
            SendGrid_In_Process__c = true)
          );
        }
        
        if (!caseList.isEmpty()) {
      try {
        update caseList;
      } catch(DmlException e) {
        System.debug(e.getMessage());
          }
        }
  }
}