objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is checked if action is required on the case</description>
        <label>Action Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <description>This will be autopopulated via trigger from the case comments object.</description>
        <label>Call Outcome</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Comments__c.object
<CustomObject>
    <description>NOTE: The &quot;Close Case&quot; button leads to a &quot;Close Case&quot; page that simulates the standard (out of the box) Close Case Page; however, it is a custom VisualForce page.</description>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</description>
        <inlineHelpText>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</inlineHelpText>
        <label>Action Required/Re-open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <label>Call Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Could Not Reach</fullName>
                </value>
                <value>
                    <fullName>Left Voicemail</fullName>
                </value>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Talked to Client</fullName>
                </value>
                <value>
                    <fullName>Talked to Advocate</fullName>
                </value>
                <value>
                    <fullName>Future Dating</fullName>
                </value>
                <value>
                    <fullName>No Action Taken</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Comments</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CaseCommentsTrigger_Test.cls
/**
	Description: Test Class for the Apex class UpdateCaseFromCaseComments called from the CaseComments_Trigger
	Author: vk@ff on 08/26/2014
**/

@isTest(SeeAlldata=true)
private class CaseCommentsTrigger_Test 
{
	static testMethod void myUnitTest() 
	{
		//Create Case
		Case c=new Case();
		insert c;
		
		//Create Case Comments
		Case_Comments__c cc1=new Case_Comments__c();
		cc1.Case__c=c.Id;
		cc1.Comment__c='Test Comments 1';
		cc1.Action_Required__c=true;
        cc1.Call_Outcome__c='Could Not Reach';
		insert cc1;
		
		Case_Comments__c cc2=new Case_Comments__c();
		cc2.Case__c=c.Id;
		cc2.Comment__c='Test Comments 2';
		cc2.Action_Required__c=false;
		insert cc2;
		
		//Delete case comment to test the count of comments
		delete cc2;
	}
}