objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is checked if action is required on the case</description>
        <label>Action Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <description>This will be autopopulated via trigger from the case comments object.</description>
        <label>Call Outcome</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Comments__c.object
<CustomObject>
    <description>NOTE: The &quot;Close Case&quot; button leads to a &quot;Close Case&quot; page that simulates the standard (out of the box) Close Case Page; however, it is a custom VisualForce page.</description>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</description>
        <inlineHelpText>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</inlineHelpText>
        <label>Action Required/Re-open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <label>Call Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Could Not Reach</fullName>
                </value>
                <value>
                    <fullName>Left Voicemail</fullName>
                </value>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Talked to Client</fullName>
                </value>
                <value>
                    <fullName>Talked to Advocate</fullName>
                </value>
                <value>
                    <fullName>Future Dating</fullName>
                </value>
                <value>
                    <fullName>No Action Taken</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact means</description>
        <label>Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comments</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FieldIdLookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>lookup values for custom Field API names and field Id&apos;s. Used for creating pre-populated values for buttons</description>
    <fields>
        <fullName>FieldId__c</fullName>
        <description>Salesforce Field Id</description>
        <label>FieldId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>Name of the field</description>
        <label>FieldName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the object the field resides on</description>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Field Id Lookup</label>
</CustomObject>

classes/ViewCaseCommentsController.cls
/* Class: ViewCaseCommentsController
** Test Class: 
** Description: Class used to display Case_Comments__c on a case record detail page.
** Edits:   Chris Del Fattore @ ForeFront Corp 8/25/2014
**          Added standard set controller to create pagination for the page.
**          Added hideNextPre boolean to show/hide next and previous page link.
**          Other changes denoted by cd@ff 8/25/2014
**          CarlWeiss/Forefront 9/18/2014 added remote action
**          Added code to parse URL parameters for Service Console vk@ff on 12/10/2014
*/

global without sharing class ViewCaseCommentsController
{
    public Id caseId{get;set;}
    public Case ca{get;set;}
    public List<Case_Comments__c> lstOfComments{get;Set;} 
    public ApexPages.StandardSetController setOfComments {get;Set;}
    public Boolean hideNextPre {get;set;}
    public String viewAll {get;Set;}
    
    public ViewCaseCommentsController(ApexPages.StandardController controller)
    {
        //caseId is the Id of the case
        //caseId=controller.getId();
        System.debug('URL PASSED' + ApexPages.currentPage().getParameters());
        
        //Standard screen
        if(ApexPages.currentPage().getParameters().get('id')!=null)
        {
            caseId=ApexPages.currentPage().getParameters().get('id');
        }
        //For Service Console, the parameter passed as isdtp=nv?Id=500R0000004MccI. Parse the string to get the case Id
        //Added by vk@ff on 12/10/2014 
        else
        {
            String s=ApexPages.currentPage().getParameters().get('isdtp');
            List<String> lstOfStr=s.split('=');
            caseId=(Id)lstOfStr[1];
        }
            
        System.debug('CASE ID' + caseId);
        ca=new Case();
        ca=[SELECT Id, CaseNumber,Call_Outcome__c FROM Case WHERE Id=:caseId];

        //viewall is a url parameter, used when the the modal window is displayed on the viewcasecomments
        viewAll = ApexPages.currentPage().getParameters().get('ViewAll');

        if(caseId!=null)
        {
            //query for comments related to the list, store them in a list of case comments cd@ff 8/25/2014
            lstOfComments=[SELECT Id, Action_Required__c, Comment__c,Contact__c,Case__c, CreatedDate, CreatedBy.Name, Name,Call_Outcome__c FROM Case_Comments__c WHERE Case__c=: caseId ORDER BY CreatedDate DESC];
            
            //take the list of case comments and place them in a standard set controller. this will create the pagination cd@ff 8/25/2014
            setOfComments = new ApexPages.StandardSetController(lstOfComments);
            

            if(viewAll != 'true') {
                //set the pagination size to 10 records per page. cd@ff 8/25/2014
                setOfComments.setPageSize(10);
                //if less than 10 case comments are returned hide the previous and next page links cd@ff 8/25/2014
                hideNextPre = (lstOfComments.size() > 10) ? true : false;
            }
            else {
                setOfComments.setPageSize(lstOfComments.size());
                //hideNextPre is rendered on the vf page cd@ff 8/25/2014
                hideNextPre = false;
            }            
        }
        

    }
    //method used to pass the case comments to the ViewCaseComments page cd@ff 8/25/2014
    public List<Case_Comments__c> getCaseRecords(){
        return (List<Case_Comments__c>) setOfComments.getRecords();
    }
    //method for the next page link cd@ff 8/25/2014
    public void Next(){
        setOfComments.next();
    }
    //method for the previous page link cd@ff 8/25/2014
    public void Previous(){
        setOfComments.previous();
    }

    @RemoteAction
    global static String getButtonFieldValue(String objectName, String fieldName)
    {
        System.debug(objectName);
        System.debug(fieldName);
        FieldIdLookup__c  fIdL = [SELECT FieldId__c FROM FieldIdLookup__c WHERE FieldName__c =: fieldName AND ObjectName__c =: objectName LIMIT 1];
        if(String.isNotEmpty(fIdL.FieldId__c))
        {
            return fIdL.FieldId__c;
        }
        else return '';
    }
}