objects/Case.object
<CustomObject>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Available_Date__c</fullName>
        <inlineHelpText>Most recent date the Client was contacted with a changed promise date</inlineHelpText>
        <label>Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Backorder_Quantity__c</fullName>
        <description>Quantity that is back-ordered for this line item</description>
        <label>Backorder Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CW_SKU_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup relationship between products and orders, so that iPIM information can go from Products to Order Lines</description>
        <label>CW SKU ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coordinate_Group__c</fullName>
        <description>Group items to be shipped together</description>
        <label>Coordinate Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Available_Date__c</fullName>
        <inlineHelpText>Most recent available date that has been communicated to the Client</inlineHelpText>
        <label>Current Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Delay_Date__c</fullName>
        <inlineHelpText>Most recent delivery date calculated in CW. This may not have been communicated to the Client</inlineHelpText>
        <label>Current Delay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Since_Original_Available_Date__c</fullName>
        <formula>Current_Delay_Date__c - Original_Available_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of days between Current Delay Date and Original Available Date.</inlineHelpText>
        <label>Days Since Original Available Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DelayFeed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if this Order Line requires new backorder date processing.</inlineHelpText>
        <label>DelayFeed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delay_Feed_History__c</fullName>
        <label>Delay Feed History</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>In_Warehouse_Date__c</fullName>
        <inlineHelpText>The date this Order Line is expected to arrive in the warehouse.</inlineHelpText>
        <label>In Warehouse Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_Status_Description__c</fullName>
        <description>Blank = Open
C = Canceled
X = Closed</description>
        <label>Line Status Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Available_Date__c</fullName>
        <inlineHelpText>Original date promised to the Client</inlineHelpText>
        <label>Original Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StaleDate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if this Order Line requires stale date processing (expected date is or was in the past).</inlineHelpText>
        <label>StaleDate</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchStaleDate.cls
global class BatchStaleDate implements Database.Batchable<sObject> {
	
	/*
	 *	Batch job to process all order lines that have a stale date equal to yesterday (In Warehouse Date is has not
	 *	been updated and is now in the past). For each order line meeting the criteria, a case/case line will be 
	 *	created or updated.
	 *
	 *	Note - this does not catch stale dates that set to a date beyond yesterday in the past.
	 *
	 */
	
	global final String Query;
	global BatchStaleDate() {
		
		Query = 'SELECT Id, DelayFeed__c, StaleDate__c, Delay_Feed_History__c, Backorder_Quantity__c, Coordinate_Group__c, '
				+ 'Current_Available_Date__c, Current_Delay_Date__c, RH_Order_Number__c, Available_Date__c, Original_Available_Date__c, '
				+ 'In_Warehouse_Date__c, Days_Since_Original_Available_Date__c, CW_SKU_ID__c, Line_Status_Description__c, Line_Total__c '
				+ 'FROM Order_Line_Items__c '
				+ 'WHERE In_Warehouse_Date__c = YESTERDAY AND Backorder_Quantity__c > 0';
	}
	
	global BatchStaleDate(String q) {
		Query = q;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		Database.QueryLocator ql = Database.getQueryLocator(Query);
		system.debug('*****BatchStaleDate Query locator: ' + ql);
		return ql;
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		
		List<Order_Line_Items__c> staleList = new List<Order_Line_Items__c>();
		for (sObject s :scope) {
			Order_Line_Items__c oli = (Order_Line_Items__c)s;
			if (oli.Line_Status_Description__c == 'Open' || oli.Line_Status_Description__c == 'Held') {
				oli.StaleDate__c = true;
				staleList.add(oli);
			}
		}
		
		if (!staleList.isEmpty()) {
			DelayedOrderActions.takeAction(staleList);
		}
		
		for (Order_Line_Items__c oli :staleList) {
			oli.StaleDate__c = false;
		}
		
		if (!staleList.isEmpty()) {
			update staleList;
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		
		// Get the status of the batch job just completed
		AsyncApexJob a = [select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =: BC.getJobId()];
		
		// Send an email to notify of job completion. 
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		List<String> toAddresses = new List<String>();
		toAddresses.add('salesforce@restorationhardware.com');
		mail.setToAddresses(toAddresses);
		mail.setSubject('BatchStaleDate Status: ' + a.Status);
		mail.setPlainTextBody('The batch Apex job BatchStaleDate processed ' + a.TotalJobItems + ' batches with ' + a.NumberOfErrors + ' failures.');
		if (!Test.isRunningTest()) {
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		}
	}
}