objects/Case.object
<CustomObject>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Available_Date__c</fullName>
        <inlineHelpText>Current availability date at the time the case line was created.</inlineHelpText>
        <label>Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delay_Notice_Number__c</fullName>
        <inlineHelpText>The availability date change notice number associated with this Case Line Item/Case - see the associated Order Line Item.</inlineHelpText>
        <label>Delay Notice Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The line number selected must be from the order on the case.</errorMessage>
            <filterItems>
                <field>$Source.Order__c</field>
                <operation>equals</operation>
                <valueField>Order_Line_Items__c.RH_Order_Number__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order_Line_Items__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Available_Date__c</fullName>
        <label>Original Available Date</label>
        <type>Date</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Current_Available_Date__c</fullName>
        <inlineHelpText>Most recent available date that has been communicated to the Client</inlineHelpText>
        <label>Current Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delay_Feed_History__c</fullName>
        <label>Delay Feed History</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>This field is populated by information from CW. It is hidden from the page layout because the Order LIne Number (standard name field) is required on the page layout, and this would in essence duplicate information. There is a workflow rule that takes this number and populates it into the line number name field.</description>
        <label>Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Available_Date__c</fullName>
        <inlineHelpText>Original date promised to the Client</inlineHelpText>
        <label>Original Available Date</label>
        <type>Date</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderLine_DelayOrderFeedCtlExt.cls
public with sharing class OrderLine_DelayOrderFeedCtlExt {
	
	/*
	 * Order Line controller extension methods for display and editing of delayed order data.
	 *
	 */
	
	ApexPages.StandardController stdController;
	private final Order_Line_Items__c orderLineItem;
	Order_Line_Items__c orderLine;
	List<Case_Line_Items__c> cliList;
	Map<String, Case_Line_Items__c> nnToCaseLineMap;
	
    // Constructor - read in the delayed order JSON data
    public OrderLine_DelayOrderFeedCtlExt(ApexPages.StandardController stdController) {
		
		this.orderLineItem = (Order_Line_Items__c)stdController.getRecord();
		
		orderLine = new Order_Line_Items__c();
		orderLine = [select Id, Delay_Feed_History__c, Current_Available_Date__c, Original_Available_Date__c from Order_Line_Items__c where Id = :this.orderLineItem.Id];
		
		cliList = new List<Case_Line_Items__c>();
		cliList = [select Id, Delay_Notice_Number__c, Case_Number__c, Case_Number__r.CaseNumber, Case_Number__r.Request_Category__c, Line_Number__c 
					from Case_Line_Items__c where Line_Number__c = :orderLine.Id];
		nnToCaseLineMap = new Map<String, Case_Line_Items__c>();
		for (Case_Line_Items__c cli :cliList) {
			if (cli.Delay_Notice_Number__c != null) {
				nnToCaseLineMap.put(String.valueOf(cli.Delay_Notice_Number__c), cli);
			}
		}
    }
	
	// Get the current delay order feed history data
    public List<DelayedOrderDataWrapper> getDelayOrderFeedData() {
		
		List<DelayedOrderFeed.DelayedOrderFeedHistory> dofhList = new List<DelayedOrderFeed.DelayedOrderFeedHistory>();
		if (String.isNotBlank(orderLine.Delay_Feed_History__c)) {
			dofhList = (List<DelayedOrderFeed.DelayedOrderFeedHistory>)JSON.deserialize(orderLine.Delay_Feed_History__c, List<DelayedOrderFeed.DelayedOrderFeedHistory>.class);
		}
		
		List<DelayedOrderDataWrapper> dodwList = new List<DelayedOrderDataWrapper>();
		String daysMoved = '-';
		for (Integer i=0; i<dofhList.size(); i++) {
			if (dofhList[i].NN == '1') {
				if (orderLine.Original_Available_Date__c == null) {
					daysMoved = '0';
				} else {
					daysMoved = String.valueOf(orderLine.Original_Available_Date__c.daysBetween(date.valueOf(dofhList[i].CD + ' 00:00:00')));
				}
			} else {
				if (i+1 < dofhList.size()) {
					daysMoved = String.valueOf(date.valueOf(dofhList[i+1].CD + ' 00:00:00').daysBetween(date.valueOf(dofhList[i].CD + ' 00:00:00')));
				}
			}
			
			if (nnToCaseLineMap.containsKey(dofhList[i].NN)) {
				dodwList.add(new DelayedOrderDataWrapper(dofhList[i], daysMoved, nnToCaseLineMap.get(dofhList[i].NN).Case_Number__r.Request_Category__c, nnToCaseLineMap.get(dofhList[i].NN).Case_Number__c, nnToCaseLineMap.get(dofhList[i].NN).Case_Number__r.CaseNumber));
			} else {
				dodwList.add(new DelayedOrderDataWrapper(dofhList[i], daysMoved, null, null, null));
			}
		}
		
		return dodwList;
	}
	
	public class DelayedOrderDataWrapper {
		public DelayedOrderFeed.DelayedOrderFeedHistory dofhData {get; set;}
		public String daysMoved {get; set;}
		public String actionType {get; set;}
		public Id caseId {get; set;}
		public String caseNumber {get; set;}
		
		public DelayedOrderDataWrapper() {
			dofhData = new DelayedOrderFeed.DelayedOrderFeedHistory();
			daysMoved = '0';
			actionType = null;
			caseId = null;
			caseNumber = null;
		}
		
		public DelayedOrderDataWrapper(DelayedOrderFeed.DelayedOrderFeedHistory dofh, String dm, String at, Id cId, String cn) {
			dofhData = dofh;
			daysMoved = dm;
			actionType = at;
			caseId = cId;
			caseNumber = cn;
		}
	}
}