objects/Case.object
<CustomObject>
    <fields>
        <fullName>Attempted_Contact__c</fullName>
        <description>This field is used to count the amount of attempted contacts. It is incremented both by trigger and workflow count.</description>
        <label>Attempted Contact</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCD_Auto_Email_Sent__c</fullName>
        <label>CCD Auto Email Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCD_Status__c</fullName>
        <label>CCD Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <label>Sold to Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_2__c</fullName>
        <label>Sold to Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_City__c</fullName>
        <label>Sold to City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <label>Sold to Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <label>Sold to Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <label>Sold to First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <label>Sold to Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <label>Sold to State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <label>Sold to Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <businessProcess>Contract</businessProcess>
        <label>Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>For use when specific case type does not exist yet</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <description>CW Sold to Address Line 1</description>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address_2__c</fullName>
        <description>CW Sold to Address Line 2</description>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_City__c</fullName>
        <description>CW Sold to City</description>
        <label>Sold To City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <description>CW Sold to Country</description>
        <label>Sold To Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <description>CW Sold to Daytime Phone</description>
        <label>Sold To Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <description>CW Sold to State</description>
        <label>Sold To State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <description>CW Sold to Zip</description>
        <label>Sold To Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testCreditCardDecline.cls
@isTest
private class testCreditCardDecline {
	
	/*
	 *	Test methods for CreditCardDeclineNotifications.cls and CreditCardDecline.cls
	 *
	 */
	
	// Create Credit Card Decline test data
	@testSetup static void ccdTestData() {
		
		PrepareData.populateCustomSettings();
		
		List<RH_Order__c> orderList = new List<RH_Order__c>();
		orderList.add(new RH_Order__c(
    		Name = 'ccdOrderW',
    		Order_Type_Code__c = 'W',
    		Sold_to_First_Name__c = 'Jerry',
    		Sold_to_Last_Name__c = 'Garcia',
    		Sold_to_Day_Phone__c = '777-123-4567', 
			Sold_to_Address_1__c = '710 Ashbury Street',
			Sold_to_Address_2__c = '',
			Sold_to_City__c = 'San Francisco',
			Sold_to_State__c = 'CA',
			Sold_to_Zip__c = '94117',
			Sold_to_Country__c = 'USA',
			Sold_to_Email__c = 'jerrygarcia@rh.com')
    	);
    	orderList.add(new RH_Order__c(
    		Name = 'ccdOrderE',
    		Order_Type_Code__c = 'W',
    		Sold_to_First_Name__c = 'Jerry',
    		Sold_to_Last_Name__c = 'Garcia',
    		Sold_to_Day_Phone__c = '777-123-4567', 
			Sold_to_Address_1__c = '710 Ashbury Street',
			Sold_to_Address_2__c = '',
			Sold_to_City__c = 'San Francisco',
			Sold_to_State__c = 'CA',
			Sold_to_Zip__c = '94117',
			Sold_to_Country__c = 'USA',
			Sold_to_Email__c = '')
    	);
    	orderList.add(new RH_Order__c(
    		Name = 'ccdOrderZ',
    		Order_Type_Code__c = 'Z',
    		Sold_to_First_Name__c = 'Jerry',
    		Sold_to_Last_Name__c = 'Garcia',
    		Sold_to_Day_Phone__c = '777-123-4567', 
			Sold_to_Address_1__c = '710 Ashbury Street',
			Sold_to_Address_2__c = '',
			Sold_to_City__c = 'San Francisco',
			Sold_to_State__c = 'CA',
			Sold_to_Zip__c = '94117',
			Sold_to_Country__c = 'USA',
			Sold_to_Email__c = 'jerrygarcia@rh.com')
    	);
    	insert orderList;
    	
    	List<Ship_To__c> stList = new List<Ship_To__c>();
    	stList.add(PrepareData.createShipTo(orderList[0].Id, '1'));
    	stList.add(PrepareData.createShipTo(orderList[1].Id, '1'));
    	stList.add(PrepareData.createShipTo(orderList[2].Id, '1'));
    	insert stList;
    	
    	List<PrepareData.productClass> pcList = new List<PrepareData.productClass>();
    	pcList.add(PrepareData.createProduct('91020008RH1Y', 0, '91020008RH1Y', 100));
    	pcList.add(PrepareData.createProduct('68010201DBN', 120.12, '68010201DBN', 379.00));
    	
    	List<Order_Line_Items__c> oliList = new List<Order_Line_Items__c>();
    	oliList.add(PrepareData.createOrderLine(orderList[0].Id, stList[0].Id, '1', pcList[0].p.Id));
    	oliList.add(PrepareData.createOrderLine(orderList[1].Id, stList[1].Id, '1', pcList[1].p.Id));
    	oliList.add(PrepareData.createOrderLine(orderList[2].Id, stList[2].Id, '1', pcList[1].p.Id));
    	insert oliList;
	}
	
	// Credit Card Decline on Contract Order
	static testMethod void ccdTest1() {
		
		RH_Order__c order = [select Id, Name, Order_Type_Code__c from RH_Order__c where Name = 'ccdOrderZ'];
		Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
    	Case ccdCase = new Case(
    		RecordTypeId = rtMap.get('Credit Card Declines').getRecordTypeId(),
    		RH_Order_Number__c = order.Id
    	);
    	
    	Test.startTest();
    	insert ccdCase;
    	Test.stopTest();
    	
    	Group caseQueue = [select Id, Name from Group where Name = 'Contract Case Queue' and Type = 'Queue'];
    	ccdCase = [select Id, OwnerId, RH_Order_Number__c, CCD_Status__c, CCD_Auto_Email_Sent__c, Attempted_Contact__c, Request_Category__c from Case where RH_Order_Number__c = :order.Id limit 1];
    	system.assertEquals('In Progress', ccdCase.CCD_Status__c);
    	system.assertEquals(0, ccdCase.CCD_Auto_Email_Sent__c);
    	system.assertEquals(0, ccdCase.Attempted_Contact__c);
    	system.assertEquals('Callout', ccdCase.Request_Category__c);
    	system.assertEquals(caseQueue.Id, ccdCase.OwnerId);
	}
	
	// Verify that a Credit Card Decline on non-Contract Order with no email is Callout
	static testMethod void ccdTest2() {
		
		RH_Order__c order = [select Id, Name, Order_Type_Code__c from RH_Order__c where Name = 'ccdOrderE'];
		Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
    	Case ccdCase = new Case(
    		RecordTypeId = rtMap.get('Credit Card Declines').getRecordTypeId(),
    		RH_Order_Number__c = order.Id
    	);
    	
    	Test.startTest();
    	insert ccdCase;
    	Test.stopTest();
    	
    	Group caseQueue = [select Id, Name from Group where Name = 'Order Processing Queue' and Type = 'Queue'];
    	ccdCase = [select Id, OwnerId, RH_Order_Number__c, CCD_Status__c, CCD_Auto_Email_Sent__c, Attempted_Contact__c, Request_Category__c from Case where RH_Order_Number__c = :order.Id limit 1];
    	system.assertEquals('In Progress', ccdCase.CCD_Status__c);
    	system.assertEquals(0, ccdCase.CCD_Auto_Email_Sent__c);
    	system.assertEquals(0, ccdCase.Attempted_Contact__c);
    	system.assertEquals('Callout', ccdCase.Request_Category__c);
    	system.assertEquals(caseQueue.Id, ccdCase.OwnerId);
	}
	
	// Verify that a Credit Card Decline on non-Contract Order with email is Automatic Email
	static testMethod void ccdTest3() {
		
		RH_Order__c order = [select Id, Name, Order_Type_Code__c from RH_Order__c where Name = 'ccdOrderW'];
		Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
    	Case ccdCase = new Case(
    		RecordTypeId = rtMap.get('Credit Card Declines').getRecordTypeId(),
    		RH_Order_Number__c = order.Id
    	);
    	
    	Test.startTest();
    	insert ccdCase;
    	Test.stopTest();

    	Group caseQueue = [select Id, Name from Group where Name = 'Order Processing Queue' and Type = 'Queue'];
    	List<Case> ccdCaseList = new List<Case>();
    	ccdCaseList = [select Id, IsClosed, OwnerId, RH_Order_Number__c, CCD_Status__c, CCD_Auto_Email_Sent__c, Attempted_Contact__c, Request_Category__c from Case where RH_Order_Number__c = :order.Id];
    	
    	system.assertEquals(1, ccdCaseList.size());
    	system.assert(!ccdCaseList[0].IsClosed);
    	system.assertEquals(ccdCase.Id, ccdCaseList[0].Id);
    	system.assertEquals('In Progress', ccdCaseList[0].CCD_Status__c);
    	system.assertEquals(1, ccdCaseList[0].CCD_Auto_Email_Sent__c);
    	system.assertEquals(1, ccdCaseList[0].Attempted_Contact__c);
    	system.assertEquals('Automatic Email', ccdCaseList[0].Request_Category__c);
    	system.assertEquals(caseQueue.Id, ccdCaseList[0].OwnerId);
	}
	
	// Verify that multiple open Credit Card Decline cases for a single order are dealt with appropriately
	static testMethod void ccdTest4() {
		
		RH_Order__c order = [select Id, Name, Order_Type_Code__c from RH_Order__c where Name = 'ccdOrderW'];
		Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
    	
    	Case ccdCase = new Case(
    		RecordTypeId = rtMap.get('Standard').getRecordTypeId(),
    		RH_Order_Number__c = order.Id
    	);
    	insert ccdCase;
    	ccdCase.RecordTypeId = rtMap.get('Credit Card Declines').getRecordTypeId();
    	update ccdCase;
    	
    	List<Case> ccdCaseList = new List<Case>();
    	ccdCaseList.add(new Case(
    		RecordTypeId = rtMap.get('Credit Card Declines').getRecordTypeId(),
    		RH_Order_Number__c = order.Id)
    	);
    	ccdCaseList.add(new Case(
    		RecordTypeId = rtMap.get('Credit Card Declines').getRecordTypeId(),
    		RH_Order_Number__c = order.Id)
    	);
    	
    	Test.startTest();
    	insert ccdCaseList;
    	Test.stopTest();

    	ccdCaseList = [select Id, IsClosed, OwnerId, RH_Order_Number__c, CCD_Status__c, CCD_Auto_Email_Sent__c, Attempted_Contact__c, Request_Category__c from Case where RH_Order_Number__c = :order.Id];
    	system.assertEquals(1, ccdCaseList.size());
    	system.assert(!ccdCaseList[0].IsClosed);
	}
}