objects/Case.object
<CustomObject>
    <fields>
        <fullName>Designer__c</fullName>
        <label>Designer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gallery_Number__c</fullName>
        <label>Gallery Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Type__c</fullName>
        <label>Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accommodations</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Delivering on Delight</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
                <value>
                    <fullName>Final Mile Delivery Notification</fullName>
                </value>
                <value>
                    <fullName>Order Inquiries</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Reorders</fullName>
                </value>
                <value>
                    <fullName>Replacement Parts</fullName>
                </value>
                <value>
                    <fullName>Delight HQ</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <label>Sold to Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_2__c</fullName>
        <label>Sold to Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <inlineHelpText>Order Total sums all ship tos</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Accommodations</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Accommodations</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Designer__c</fullName>
        <description>Designer assigned to order</description>
        <label>Order Classification</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gallery_Number__c</fullName>
        <description>Store Number</description>
        <label>Gallery Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <description>CW Sold to Address Line 1</description>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address_2__c</fullName>
        <description>CW Sold to Address Line 2</description>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <description>Including shipping, handling, and tax</description>
        <inlineHelpText>Order total sums all ship tos.</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCaseFromRHOrder_Test.cls
@isTest(SeeAllData=true)
private class UpdateCaseFromRHOrder_Test 
{
    public static testMethod void myUnitTest() 
    {
        Test.startTest();
        RH_Order__c rho=new RH_Order__c();
        rho.Name='ORDER 123';
        rho.Designer__c='Designer A';
        rho.Sold_To_Address_1__c='123 Test Street';
        rho.Sold_To_Address_2__c='456 Test Street';
        rho.Gallery_Number__c='5';
        rho.Total_Order_Amount__c=1500.00;
        insert rho;
        
        System.debug(rho);
         Case c=new Case();
        
        
        List<RecordType> caseRecordType = [SELECT Id, Name, Description FROM RecordType WHERE SobjectType='Case' AND Name = 'Accommodations - Order Header' LIMIT 1]; 

        if(caseRecordType.size()>0){
        	c.RecordTypeId=caseRecordType[0].Id;
        	
        }
        c.RH_Order_Number__c=rho.Id;
        c.Status='New';
       // c.Queue_Type__c='Accommodations';
        insert c;
        
        System.debug(c);
        
        //Update RHOrder
                
        rho.Name='ORDER 123';
        rho.Designer__c='Designer B';
        rho.Sold_To_Address_1__c='1234 Test Street';
        rho.Sold_To_Address_2__c='4567 Test Street';
        rho.Gallery_Number__c='5';
        rho.Total_Order_Amount__c=2500.00;
        update rho;
        
        System.debug(rho);
        Test.stopTest();
    }
}