objects/Case.object
<CustomObject>
    <fields>
        <fullName>Attempted_Contact__c</fullName>
        <description>This field is used to count the amount of attempted contacts. It is incremented both by trigger and workflow count.</description>
        <label>Attempted Contact</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCD_Auto_Email_Sent__c</fullName>
        <label>CCD Auto Email Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCD_Final_Notice_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CCD Final Notice Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCD_Status__c</fullName>
        <label>CCD Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <description>This will be autopopulated via trigger from the case comments object.</description>
        <label>Call Outcome</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Auto_Renewal_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the related Order on this Credit Card Decline case only has Membership Auto Renewal SKU Order Lines.</description>
        <inlineHelpText>If checked, the related Order on this Credit Card Decline case only has Membership Auto Renewal SKU Order Lines.</inlineHelpText>
        <label>Membership Auto Renewal Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Order_Lines__c</fullName>
        <label>Number of Order Lines</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>System_Hold_Code__c</fullName>
        <label>System Hold Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WasReopened__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this case has been re-opened.</inlineHelpText>
        <label>WasReopened</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <businessProcess>Contract</businessProcess>
        <label>Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>Returns</fullName>
        <active>true</active>
        <businessProcess>Standard with Cancelled</businessProcess>
        <label>Returns</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>AutoRenew_CCD_Order_Number__c</fullName>
        <label>AutoRenew CCD Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Cancellation_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fraud</fullName>
                </value>
                <value>
                    <fullName>Credit card decline</fullName>
                </value>
                <value>
                    <fullName>Created in error</fullName>
                </value>
                <value>
                    <fullName>Does not use it</fullName>
                </value>
                <value>
                    <fullName>Duplicate membership</fullName>
                </value>
                <value>
                    <fullName>Unhappy with membership</fullName>
                </value>
                <value>
                    <fullName>None given by customer</fullName>
                </value>
                <value>
                    <fullName>Customer does not want it</fullName>
                </value>
                <value>
                    <fullName>Renewal failed</fullName>
                </value>
                <value>
                    <fullName>Quebec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Type__c</fullName>
        <inlineHelpText>RH Terminated = RH determined that the membership needs to be terminated.
Member Terminated = Member requested and was granted a refund for membership.
Member Cancelled = Member cancelled the membership in My Account.</inlineHelpText>
        <label>Cancellation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RH Terminated</fullName>
                </value>
                <value>
                    <fullName>Member Terminated</fullName>
                </value>
                <value>
                    <fullName>Member Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Member ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Alternate_Order_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>In CW, this is equal to the ATG Order Number or the Contract Order Number</inlineHelpText>
        <label>Alternate Order Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Membership_Auto_Renewal_Order__c</fullName>
        <formula>IF(Number_of_Order_Lines__c  &gt; 0 &amp;&amp; Number_of_Order_Lines__c = Number_of_MembershipAutoRenewalSKUs__c, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Will be checked if all order lines on this order are one of the Membership Auto Renewal SKUs.</inlineHelpText>
        <label>Membership Auto Renewal Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_ID_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Membership ID</label>
        <referenceTo>Membership__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Order_Lines__c</fullName>
        <label>Number of Order Lines</label>
        <summaryForeignKey>Order_Line_Items__c.RH_Order_Number__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>System_Hold_Code__c</fullName>
        <description>AT</description>
        <label>System Hold Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreditCardDeclineNotifications.cls
public class CreditCardDeclineNotifications {
    
    /*
     *  Methods for automatic Credit Card Decline email notifications.
     *
     */
	
	// Return the auto-processing state
	public static Boolean isCCDAutoProcess(Case c) {
		Boolean autoProcess;
		
		if ( c.RH_Order_Number__c == null || 
			 c.CCD_Final_Notice_Sent__c || 
			 c.WasReopened__c || 
			 c.RH_Order_Number__r.Order_Type_Code__c == 'Z' || 
			 String.isBlank(c.RH_Order_Number__r.Sold_to_Email__c) || 
			 c.Request_Category__c == 'Callout' ||
			 c.RH_Order_Number__r.Number_of_Order_Lines__c == 0  ) {
			autoProcess = false;
		} else {
			if (c.CCD_Auto_Email_Sent__c > 0) {
				autoProcess = false;
				if (c.System_Hold_Code__c != 'AT' && c.Attempted_Contact__c == 3) {
					autoProcess = true;
				}
				if (c.System_Hold_Code__c == 'AT' && String.isNotBlank(c.Call_Outcome__c) && c.Call_Outcome__c == 'Sent Email') {
					autoProcess = true;
				}
			} else {
				autoProcess = true;
			}
		}
		
		return autoProcess;
	}
	
	// Returns the updated membership record based on case CCD_Status__c.
	public static Membership__c ccdMembership(Case c, String ccdStatus, Map<Id, Membership__c> mMap) {
		Membership__c mem = null;
		
		if ((String.isBlank(c.CCD_Status__c) || c.CCD_Status__c == 'Pending') && ccdStatus == 'In Progress') {
			if (c.Membership_Auto_Renewal_Order__c && mMap.containsKey(c.RH_Order_Number__r.Membership_ID_Lookup__c)) {
				mem = mMap.get(c.RH_Order_Number__r.Membership_ID_Lookup__c);
				mem.AutoRenew_CCD_Order_Number__c = c.RH_Order_Number__r.Alternate_Order_Number__c;
				mem.Cancellation_Reason__c = 'Credit card decline';
				mem.Cancellation_Type__c = 'Pending';
			}
		}
		
		return mem;
	}
	
	// Processes the list of CCD notifications - @future because of trigger and getContent
    @future (callout=true)
    public static void ccDeclineNotifications(Set<Id> caseIds) {
    	sendCCDNotifications(caseIds);
    }
	
	// Send the CCD notification emails
    public static void sendCCDNotifications(Set<Id> caseIds) {
        
        if (!caseIds.isEmpty()) {
            
           // Get the case data for the supplied case Ids - all must be open cases
            List<Case> caselist = new List<Case>();
			caseList = [select Id, CaseNumber, Status, Email_Alert_Trigger__c, CCD_Auto_Email_Sent__c, 
					Notification_Type__c, Future_Processing_Date__c, To_Email_Address__c, Call_Outcome__c, 
					Attempted_Contact__c, Request_Category__c, WasReopened__c, CCD_Status__c, CreatedDate, 
					CCD_Final_Notice_Sent__c, System_Hold_Code__c, Membership_Auto_Renewal_Order__c, 
					RH_Order_Number__c, RH_Order_Number__r.Name, RH_Order_Number__r.Order_Type_Code__c, 
					RH_Order_Number__r.Sold_to_Email__c, RH_Order_Number__r.Sold_to_First_Name__c, 
					RH_Order_Number__r.Sold_to_Last_Name__c, RH_Order_Number__r.Number_of_Order_Lines__c, 
					RH_Order_Number__r.Membership_ID_Lookup__c, RH_Order_Number__r.Alternate_Order_Number__c 
					from Case where Id in :caseIds and IsClosed = false and WasReopened__c = false];
			
            // Guard against the possiblity of duplicate Credit Card Declines cases
            Set<Id> oIds = new Set<Id>();
            for (Case c :caseList) {
                oIds.add(c.RH_Order_Number__c);
            }
            
            Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
            List<Case> existingCases = new List<Case>();
            existingCases = [select Id, CaseNumber, Status, Email_Alert_Trigger__c, CCD_Auto_Email_Sent__c, 
					Notification_Type__c, Future_Processing_Date__c, To_Email_Address__c, Call_Outcome__c, 
					Attempted_Contact__c, Request_Category__c, WasReopened__c, CCD_Status__c, CreatedDate, 
					CCD_Final_Notice_Sent__c, System_Hold_Code__c, Membership_Auto_Renewal_Order__c, 
					RH_Order_Number__c, RH_Order_Number__r.Name, RH_Order_Number__r.Order_Type_Code__c, 
					RH_Order_Number__r.Sold_to_Email__c, RH_Order_Number__r.Sold_to_First_Name__c, 
					RH_Order_Number__r.Sold_to_Last_Name__c, RH_Order_Number__r.Number_of_Order_Lines__c, 
					RH_Order_Number__r.Membership_ID_Lookup__c, RH_Order_Number__r.Alternate_Order_Number__c 
					from Case where RH_Order_Number__c in :oIds and Id not in :caseIds 
					and RecordTypeId = :rtMap.get('Credit Card Declines').getRecordTypeId() and IsClosed = false and WasReOpened__c = false];
            
            List<Case> deleteCases = new List<Case>();
            Map<Id, Case> oCaseMap = new Map<Id, Case>();
            for (Case c :caseList) {
                if (!oCaseMap.containsKey(c.RH_Order_Number__c)) {
                    oCaseMap.put(c.RH_Order_Number__c, c);
                } else {
                    if (c.CreatedDate < oCaseMap.get(c.RH_Order_Number__c).CreatedDate) {
                        deleteCases.add(oCaseMap.get(c.RH_Order_Number__c));
                        oCaseMap.put(c.RH_Order_Number__c, c);
                    } else {
                        deleteCases.add(c);
                    }
                }
            }
            
            for (Case c :existingCases) {
                if (oCaseMap.containsKey(c.RH_Order_Number__c)) {
                    if (c.CreatedDate <= oCaseMap.get(c.RH_Order_Number__c).CreatedDate) {
                        deleteCases.add(oCaseMap.get(c.RH_Order_Number__c));
                        oCaseMap.remove(c.RH_Order_Number__c);
                    }
                }
            }
            
            // Build map of membership records
            Set<Id> mIds = new Set<Id>();
            for (Case c :oCaseMap.values()) {
            	if (c.RH_Order_Number__r.Membership_ID_Lookup__c != null) {
            		mIds.add(c.RH_Order_Number__r.Membership_ID_Lookup__c);
            	}
            }
            Map<Id, Membership__c> membershipMap = new Map<Id, Membership__c>([select Id, Name, AutoRenew_CCD_Order_Number__c, Cancellation_Reason__c, Cancellation_Type__c from Membership__c where Id in :mIds]);
            
        
            // Send out credit card decline notification for each case that meets the automatic email criteria
			Set<Id> ccdAutoIds = new Set<Id>();
			List<Membership__c> membershipUpList = new List<Membership__c>();
			String ccdStatus;
			Membership__c mem;
            for (Case c :oCaseMap.values()) {
				
				if (c.Attempted_Contact__c == null) {
					c.Attempted_Contact__c = 0;
				}
				
                if (c.CCD_Auto_Email_Sent__c == null) {
                	c.CCD_Auto_Email_Sent__c = 0;
                }
				
				if (isCCDAutoProcess(c) && Utility.isValidDomain(c.RH_Order_Number__r.Sold_to_Email__c)) {
					
					// Notify customer via automatic email
					ccdStatus = 'In Progress';
					mem = ccdMembership(c, ccdStatus, membershipMap);
					if (mem != null) {
						membershipUpList.add(mem);
					}
					c.CCD_Status__c = ccdStatus;
					c.Request_Category__c = 'Automatic Email';
					c.To_Email_Address__c = c.RH_Order_Number__r.Sold_to_Email__c;
					c.Attempted_Contact__c++;
					c.Call_Outcome__c = 'Sent Email';
					c.CCD_Auto_Email_Sent__c++;
					c.Email_Alert_Trigger__c = true;
					
					// Determine which notification to send
					c.Notification_Type__c = 'Credit Card Declines - 1st Notice';
					if (c.CCD_Auto_Email_Sent__c == 2) {
						if (c.System_Hold_Code__c != 'AT') {
							c.Notification_Type__c = 'Credit Card Declines - Final Notice';
						} else {
							c.Notification_Type__c = 'Credit Card Declines - 2nd Notice';
						}
					} else {
						if (c.CCD_Auto_Email_Sent__c > 2) {
							c.Notification_Type__c = 'Credit Card Declines - Final Notice';
						}
					}
					
					if (c.Notification_Type__c == 'Credit Card Declines - Final Notice') {
						c.CCD_Final_Notice_Sent__c = true;
					}
					
					// Set subject line of CCD email
					Map<String, CreditCardDeclineEmail__c> ccdEmailMap = CreditCardDeclineEmail__c.getAll();
					String noticeType = c.Notification_Type__c.substringAfter('Credit Card Declines - ');
					if (c.RH_Order_Number__r.Order_Type_Code__c == 'Z') {
						noticeType += ' - Contract';
					} else {
						if (c.Membership_Auto_Renewal_Order__c) {
							noticeType += ' - Membership';
						} else {
							noticeType += ' - Regular';
						}
					}
					c.CCD_Email_Subject__c = ccdEmailMap.get(noticeType).Subject__c;
					if (ccdEmailMap.get(noticeType).Include_Order_Number__c) {
						c.CCD_Email_Subject__c += c.RH_Order_Number__r.Name;
					}
					
					ccdAutoIds.add(c.Id);
					
				} else {
					
					// We are not ready to process CCD case automatically, determine next steps
					if (c.RH_Order_Number__r.Number_of_Order_Lines__c == 0 && String.isBlank(c.CCD_Status__c)) {
						ccdStatus = 'Pending';
						mem = ccdMembership(c, ccdStatus, membershipMap);
						if (mem != null) {
							membershipUpList.add(mem);
						}
						c.CCD_Status__c = ccdStatus;
						c.Request_Category__c = 'Automatic Email';
						c.Future_Processing_Date__c = system.today().addDays(2);
					} else {
						if (c.RH_Order_Number__r.Number_of_Order_Lines__c > 0) {
							ccdStatus = 'In Progress';
							mem = ccdMembership(c, ccdStatus, membershipMap);
							if (mem != null) {
								membershipUpList.add(mem);
							}
							c.CCD_Status__c = ccdStatus;
						}
						
						// Customer must be contacted by phone
						c.Request_Category__c = 'Callout';
					}
					
					c.Email_Alert_Trigger__c = false;
				}
			}
			
			// Cause all automatic notifications to be sent (via workflow/email alert)
			update oCaseMap.values();
            
            // Verify that automatic notifications were successfully sent and attach copy of email to case
            if (!ccdAutoIds.isEmpty()) {
				Blob pageContent;
				List<Attachment> attList = new List<Attachment>();
				List<Case> ccdFailList = new List<Case>();
				List<Case> ccdAutoList = new List<Case>();
				ccdAutoList = [select Id, CaseNumber, Email_Alert_Trigger__c, Request_Category__c, Call_Outcome__c, Notification_Type__c, To_Email_Address__c from Case where Id in :ccdAutoIds];
				
				for (Case c :ccdAutoList) {
					
					if (c.Email_Alert_Trigger__c) {
						
						// Email failed to send
						c.Email_Alert_Trigger__c = false;
						c.Call_Outcome__c = 'Failed To Send Email';
						c.Request_Category__c = 'Callout';
						ccdFailList.add(c);
						
					} else {
						
						system.debug('*****CreditCardDeclineNotifications notificationType = ' + c.Notification_Type__c);
						
						// Email sent, prepare copy as an attachment
						if (!Test.isRunningTest()) {
							pageContent = new PageReference('/apex/CreditCardDeclineHTML?caseId=' + c.Id + '&notificationType=' + c.Notification_Type__c).getContent();
						} else {
							pageContent = Blob.valueOf('Test Class');
						}
						
						attList.add(new Attachment(
							ParentId = c.Id,
							Name = c.Notification_Type__c + ': automatic.html',
							ContentType = 'html',
							Body = pageContent,
							Description = 'System Generated Attachment'
								+ '\nNotification sent automatically: ' + c.Notification_Type__c 
								+ '\nToAddress = ' + c.To_Email_Address__c
								+ '\nSend Date/Time = ' + String.valueOf(system.now()))
						);
					}
				}
				
				if (!attList.isEmpty()) {
					insert attList;
				}
				
				if (!ccdFailList.isEmpty()) {
					update ccdFailList;
				}
            }
            
            // Update membership records to reflect CCD state
            if (!membershipUpList.isEmpty()) {
            	update membershipUpList;
            }
            
			// Delete any duplicate CCD cases
			if (!deleteCases.isEmpty()) {
				delete deleteCases;
			}
		}
	}
}