objects/Case.object
<CustomObject>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                    <default>true</default>
                    <label>Client</label>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Gallery</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>VIP/BOD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HTTP_POST_In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HTTP POST In Progress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Original_Requested_Percentage__c</fullName>
        <inlineHelpText>Enter the percentage that you are giving for an accommodation.</inlineHelpText>
        <label>Requested Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Queue_Type__c</fullName>
        <label>Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accommodations</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Delivering on Delight</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
                <value>
                    <fullName>Final Mile Delivery Notification</fullName>
                </value>
                <value>
                    <fullName>Order Inquiries</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Reorders</fullName>
                </value>
                <value>
                    <fullName>Replacement Parts</fullName>
                </value>
                <value>
                    <fullName>Delight HQ</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_to_Address_1__c</fullName>
        <label>Alternate Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_City__c</fullName>
        <label>Alternate City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Country__c</fullName>
        <label>Alternate Country</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Day_Phone__c</fullName>
        <label>Alternate Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Send_to_First_Name__c</fullName>
        <label>Alternate First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Last_Name__c</fullName>
        <label>Alternate Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_State__c</fullName>
        <label>Alternate State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Zip__c</fullName>
        <label>Alternate Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Reorders</fullName>
        <active>true</active>
        <businessProcess>Standard with Call for Pick</businessProcess>
        <label>Reorders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <description>Do not use.</description>
        <formula>Line_Number__r.RH_Order_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reorder_Reason__c</fullName>
        <label>Reorder Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bugs</fullName>
                </value>
                <value>
                    <fullName>Customer Preference</fullName>
                </value>
                <value>
                    <fullName>Damage</fullName>
                </value>
                <value>
                    <fullName>Defective</fullName>
                </value>
                <value>
                    <fullName>Item Number/Labeling Issue</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <recordTypes>
        <fullName>Reorders</fullName>
        <active>true</active>
        <label>Reorders</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <label>Master</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestReleaseOrderHoldWebServiceCallout.cls
@isTest(SeeAllData=true)
private class TestReleaseOrderHoldWebServiceCallout {
    
    /*
     *	Test methods for ReleaseOrderHoldWebServiceCallOut.cls and ReleaseOrderHoldCalloutTrigger.trigger
     *
     */
	
    
    /*
    static testmethod void test_Notification(){
    releaseOrderHoldWebServiceCallout rel = new releaseOrderHoldWebServiceCallout();
    
    String retVal = rel.testNotification();
    
    String expectedResult = 'Successful Notification Test';
    System.assertEquals(retVal, expectedResult);
    }
    */
    
    static testmethod void test_Notification() {
    	
    	List<Id> caseIds = new List<Id>();
    	//Create the test data
    	RH_Order__c o = new RH_Order__c();
        o.RecordTypeId = [select Id from RecordType where Name = 'Master' and SobjectType = 'RH_Order__c' limit 1].Id;
        o.Name = '7777777';
        insert o;
        
        Order_Line_Items__c ol = new Order_Line_Items__c();
        ol.Name = '77';
        ol.RH_Order_Number__c = o.Id;
        insert ol;
        
        Case c = new Case();
        c.RecordTypeId = [Select Id from RecordType where Name = 'Reorders' and SobjectType = 'Case' limit 1].Id;     
        c.RH_Order_Number__c = o.Id;
       // c.Queue_Type__c = 'Reorders';
        c.Client_Type__c = 'Customer';
        c.Send_to_First_Name__c = 'John';
        c.Send_to_Last_Name__c = 'Doe';
        c.Send_to_Address_1__c = '1234 Main Street';
        c.Send_to_City__c = 'San Francisco';
        c.Send_to_State__c = 'CA';
        c.Send_to_Country__c = 'USA';
        c.Send_to_Zip__c = '94107';
        c.Send_to_Day_Phone__c = '777-777-7777';       
        c.Original_Requested_Percentage__c=.95;
        // c.HTTP_POST_In_Progress__c=True;    
        insert c;
        
        Case_Line_Items__c cl= new Case_Line_Items__c();
        cl.RecordTypeId = [Select Id, SobjectType, Name From RecordType Where Name = 'Reorders' and SobjectType = 'Case_Line_Items__c' limit 1].id;
        cl.Order__c = o.Id;
        cl.Case_Number__c = c.Id;
        cl.Reorder_Reason__c = 'Customer Preference'; 
        insert cl;
        
        // Run the test
    	//Test.StartTest();
    	Test.setMock(HttpCalloutMock.class, new MockROHCResponseGenerator());
        c.Status = 'Call for Pick'; 
        try{
        update c;
        }
        catch(DmlException e){
        System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION' , e.getDmlStatusCode(0));
        }
        //Test.StopTest();
        
        // Verify results
        c = [select Id, HTTP_POST_In_Progress__c from Case where Id = :c.Id];
        caseIds.add(c.Id);
        ReleaseOrderHoldWebServiceCallout.sendNotification(caseIds);
        system.assertEquals(true, c.HTTP_POST_In_Progress__c);
    }
}