objects/Case.object
<CustomObject>
    <fields>
        <fullName>CCD_Email_Subject__c</fullName>
        <label>CCD Email Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Auto_Renewal_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the related Order on this Credit Card Decline case only has Membership Auto Renewal SKU Order Lines.</description>
        <inlineHelpText>If checked, the related Order on this Credit Card Decline case only has Membership Auto Renewal SKU Order Lines.</inlineHelpText>
        <label>Membership Auto Renewal Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card Declines - 1st Notice</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines - 2nd Notice</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines - Final Notice</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <businessProcess>Contract</businessProcess>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CreditCardDeclineEmail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Include_Order_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked - include order number at the end of the email subject.</description>
        <inlineHelpText>If checked - include order number at the end of the email subject.</inlineHelpText>
        <label>Include Order Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CreditCardDeclineEmail</label>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Membership_Auto_Renewal_Order__c</fullName>
        <formula>IF(Number_of_Order_Lines__c  &gt; 0 &amp;&amp; Number_of_Order_Lines__c = Number_of_MembershipAutoRenewalSKUs__c, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Will be checked if all order lines on this order are one of the Membership Auto Renewal SKUs.</inlineHelpText>
        <label>Membership Auto Renewal Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Case_NotificationsCtlExt.cls
public with sharing class Case_NotificationsCtlExt {
	
	/*
	 *	Case controller extension to support Case based email notifications. Allows the user to 
	 *	select the notification type to preview and/or send. The user can only select those notifications
	 *	supported by the Case record type.
	 *
	 */
	
	ApexPages.StandardController stdController;
	
	private List<SelectOption> emailTypes;
	private String emailSelected;
	
	public Case rhCase {get; set;}
	public Boolean isError {get; set;}
	
	public Case_NotificationsCtlExt(ApexPages.StandardController stdController) {
		
		isError = false;
		emailTypes = new List<SelectOption>();
		emailSelected = '--None--';
		
		rhCase = new Case();
		this.rhCase = (Case)stdController.getRecord();
		rhCase = [select Id, CaseNumber, RecordTypeId, Notification_Type__c, Membership_Auto_Renewal_Order__c, 
				RH_Order_Number__c, RH_Order_Number__r.Name, RH_Order_Number__r.Order_Type_Code__c 
				from Case where Id = :this.rhCase.Id];
	}
	
	// Take the user immediately to the preview page if there is only one notification type for the Case record type
	public PageReference previewOne() {
		PageReference pr = null;
		Map<Id,Schema.RecordTypeInfo> rtMapById = Schema.SObjectType.Case.getRecordTypeInfosById();
		
		if (!rtMapById.containsKey(rhCase.RecordTypeId) || (rtMapById.get(rhCase.RecordTypeId).getName() != 'Credit Card Declines' && rtMapById.get(rhCase.RecordTypeId).getName() != 'Delay Notifications')) {
			isError = true;
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Invalid case record type.'));
		}
		
		// Verify that the user has permissions to update the case record
		UserRecordAccess ura = [select RecordId, HasEditAccess from UserRecordAccess where UserId = :UserInfo.getUserId() and RecordId = :rhCase.Id];
		Profile sysAdmin = [select Id from Profile where Name = 'System Administrator'];
		if (!ura.HasEditAccess || (Approval.isLocked(rhCase.Id) && UserInfo.getProfileId() != sysAdmin.Id)) {
			isError = true;
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Insufficient privileges. The case cannot be locked and you must be able to edit the case.'));
		}
		
		if (!isError) {
			if (rtMapById.containsKey(rhCase.RecordTypeId) && rtMapById.get(rhCase.RecordTypeId).getName() == 'Delay Notifications') {
				// Go to Delay Notifications preview page
				pr = new PageReference('/apex/Case_DNPreview?caseId=' + rhCase.Id + '&retURL=/' + rhCase.Id);
			}
		}
		
		return pr;
	}
    
	// Get the list of notifications for the current case record type
	public List<SelectOption> notificationTypes {
		get {
			// Get all of the possible notification types
			Schema.DescribeFieldResult fieldResult = Case.Notification_Type__c.getDescribe();
			List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
			
			// Set our possible selections based upon case record type
			emailTypes.clear();
			emailTypes.add(new SelectOption('--None--', '--None--'));
			Map<Id,Schema.RecordTypeInfo> rtMapById = Schema.SObjectType.Case.getRecordTypeInfosById();
			if (rtMapById.containsKey(rhCase.RecordTypeId)) {
				String rtName = rtMapById.get(rhCase.RecordTypeId).getName();
				for (Schema.PicklistEntry f :ple) {
					if (f.getLabel().startsWith(rtName)) {
						emailTypes.add(new SelectOption(f.getLabel(), f.getLabel()));
					}
				}
			}
			
			return emailTypes;
		}
		set;        
	}
	
	public String getnotificationSelected() {
		return emailSelected;
	}
	
	public void setnotificationSelected(String ns) {
		emailSelected = ns;
	}
	
	// Take the user to the preview page based upon the selected notification type
	public PageReference notificationPreview() {
		PageReference pr = null;
		
		if (String.isBlank(emailSelected) || emailSelected == '--None--') {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Please select notification type.'));
		} else {
			if (emailSelected.startsWith('Credit Card Declines')) {
				rhCase.Notification_Type__c = emailSelected;
				
				// Set subject line of CCD email
				Map<String, CreditCardDeclineEmail__c> ccdEmailMap = CreditCardDeclineEmail__c.getAll();
				String noticeType = rhCase.Notification_Type__c.substringAfter('Credit Card Declines - ');
				if (rhCase.RH_Order_Number__r.Order_Type_Code__c == 'Z') {
					noticeType += ' - Contract';
				} else {
					if (rhCase.Membership_Auto_Renewal_Order__c) {
						noticeType += ' - Membership';
					} else {
						noticeType += ' - Regular';
					}
				}
				rhCase.CCD_Email_Subject__c = ccdEmailMap.get(noticeType).Subject__c;
				if (ccdEmailMap.get(noticeType).Include_Order_Number__c) {
					rhCase.CCD_Email_Subject__c += rhCase.RH_Order_Number__r.Name;
				}
				
				update rhCase;
				pr = new PageReference('/apex/Case_CCDPreview?caseId=' + rhCase.Id + '&retURL=/' + rhCase.Id);
			} else {
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Notification type ' + emailSelected + ' is not supported at this time.'));
			}
		}
		return pr;
	}
}