objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is checked if action is required on the case</description>
        <label>Action Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Address__c</fullName>
        <label>New Address</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Comments__c.object
<CustomObject>
    <description>NOTE: The &quot;Close Case&quot; button leads to a &quot;Close Case&quot; page that simulates the standard (out of the box) Close Case Page; however, it is a custom VisualForce page.</description>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</description>
        <inlineHelpText>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</inlineHelpText>
        <label>Action Required/Re-open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Comments</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CloseCaseController_Test.cls
@isTest(SeeAllData=true)
private class CloseCaseController_Test 
{
	static testMethod void myUnitTest() 
	{
		
		//Create Case
		Case c=new Case();
		c.New_Address__c='Test Address';
		insert c;
		
		//Create Case Comments
		Case_Comments__c cc1=new Case_Comments__c();
		cc1.Case__c=c.Id;
		cc1.Comment__c='Test Comments 1';
		cc1.Action_Required__c=true;
		insert cc1;
		
		ApexPages.currentPage().getParameters().put('caseId',c.Id);
		ApexPages.currentPage().getParameters().put('id',cc1.Id);
		ApexPages.StandardController con=new ApexPages.StandardController(c);
        CloseCaseController ccon=new CloseCaseController(con);
        CloseCaseController.getStatusValues();
        ccon.closeCase();
		
		//Create Case: Case for DML Error: Catch Block
		Case c2=new Case();
		insert c2;
		
		//Create Case Comments
		Case_Comments__c cc2=new Case_Comments__c();
		//cc2.Case__c=c.Id;
		cc2.Comment__c='Test Comments 1';
		cc2.Action_Required__c=true;
		insert cc2;
		
		ApexPages.currentPage().getParameters().put('caseId',c2.Id);
		ApexPages.currentPage().getParameters().put('id',cc2.Id);
		ApexPages.StandardController con2=new ApexPages.StandardController(c2);
        CloseCaseController ccon2=new CloseCaseController(con2);
        CloseCaseController.getStatusValues();
        ccon2.closeCase();
        ccon2.cancelClose();
		
	}
}