objects/Case.object
<CustomObject>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The line number selected must be from the order on the case.</errorMessage>
            <filterItems>
                <field>$Source.Order__c</field>
                <operation>equals</operation>
                <valueField>Order_Line_Items__c.RH_Order_Number__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order_Line_Items__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <description>Do not use.</description>
        <formula>Line_Number__r.RH_Order_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CaseLineToOrderLineMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting contains field mappings for Case Line Item and Order Line Item</description>
    <fields>
        <fullName>Case_Line_Item_field__c</fullName>
        <label>Case Line Item field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item_field__c</fullName>
        <label>Order Line Item field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseLineToOrderLineMapping</label>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>This field is populated by information from CW. It is hidden from the page layout because the Order LIne Number (standard name field) is required on the page layout, and this would in essence duplicate information. There is a workflow rule that takes this number and populates it into the line number name field.</description>
        <label>Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateCaseLineFromOrderLine.cls
/**
    * Description: Class to update the fields on Case Line Item when an RH Order line Item is Updated
    * Test Class: 
    * Apex Trigger: OrderLineItem Trigger
**/

public without sharing class UpdateCaseLineFromOrderLine 
{
	public static void UpdateCaseLineItem(Map<Id,Order_Line_Items__c> triggerNewMap, Map<Id,Order_Line_Items__c> triggeroldMap)
	{
		Set<Id> OrderLineIdList = new Set<Id>();
        List<CaseLineToOrderLineMapping__c> cLineToOrderLineMapping = [SELECT Case_Line_Item_field__c, Order_Line_Item_field__c FROM CaseLineToOrderLineMapping__c];
        
        String caseLineQuery = 'SELECT Id, RH_Order_Number__c, ';
        
        for(CaseLineToOrderLineMapping__c cofm: cLineToOrderLineMapping){
            caseLineQuery += cofm.Case_Line_Item_field__c + ', ';
        }
        
        caseLineQuery = caseLineQuery.removeEnd(', ');
        
        for(Order_Line_Items__c ol: triggerNewMap.values())
		{
            for(CaseLineToOrderLineMapping__c colm: cLineToOrderLineMapping)
			{
                if(ol.get(colm.Order_Line_Item_field__c) != triggeroldMap.get(ol.Id).get(colm.Order_Line_Item_field__c))
				{
                    OrderLineIdList.add(ol.Id);
                    break;
                }
            }
        }
        System.debug(OrderLineIdList);
        caseLineQuery += ' FROM Case_Line_Items__c WHERE Line_Number__c IN: OrderLineIdList';
        List<Case_Line_Items__c> caseLineList = Database.query(caseLineQuery);
        
        for(Case_Line_Items__c c: caseLineList)
		{
            for(CaseLineToOrderLineMapping__c colm: cLineToOrderLineMapping)
			{
                 c.put(colm.Case_Line_Item_field__c, triggerNewMap.get(c.Line_Number__c).get(colm.Order_Line_Item_field__c));
            }
        }
        
        try
		{
            update caseLineList;
        }
		catch(DMLException de)
		{
            System.debug(de.getDMLMessage(0));
        } 
	}
}