objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>This field is populated by information from CW. It is hidden from the page layout because the Order LIne Number (standard name field) is required on the page layout, and this would in essence duplicate information. There is a workflow rule that takes this number and populates it into the line number name field.</description>
        <label>Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_Number__c</fullName>
        <formula>Ship_To__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ship to Number</label>
        <type>Text</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Number__c</fullName>
        <description>This field is populated by information from CW. It is hidden from the page layout because the Ship to Number (standard name field) is required on the page layout, and this would in essence should duplicate information.</description>
        <label>Ship to Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AddNewCaseLineItemsClass_Test.cls
@isTest(SeeAlldata=true)
private class AddNewCaseLineItemsClass_Test 
{
    static testMethod void myUnitTest() 
    {
        //Creating a RH Order
        RH_Order__c rhOrder=new RH_Order__c();
        rhOrder.Name='ORDER 123';
        insert rhOrder;
        
        //Creating a Ship To
        Ship_To__c shipTo=new Ship_To__c();
        shipTo.Order__c=rhOrder.Id;
        shipTo.Ship_to_Number__c='1';
        insert shipTo;
        
        //Creating RH Order Lines
        Order_Line_Items__c oli1=new Order_Line_Items__c();
        oli1.RH_Order_Number__c=rhOrder.Id;
        oli1.Line_Number__c='1';
        oli1.Ship_To__c=shipTo.Id;  
        insert oli1;
        
        Order_Line_Items__c oli2=new Order_Line_Items__c();
        oli2.RH_Order_Number__c=rhOrder.Id;
        oli2.Line_Number__c='2';
        oli2.Ship_To__c=shipTo.Id;  
        insert oli2;
        
        //Creating Case
        Case c=new Case();
        c.Order_Number__c=rhOrder.Id;
        insert c;
        
        //Instantiating a PageReference
        
        PageReference pr=Page.AddNewCaseLineItems;
        Test.setCurrentPage(pr);
        ApexPages.currentPage().getParameters().put('caseId',c.Id);
        ApexPages.currentPage().getParameters().put('OrderId',rhOrder.Id);
        AddNewCaseLineItemsClass con=new AddNewCaseLineItemsClass();
        con.getSelectedOrderLineList();
        con.save();
        con.gethasNext();
        con.next();
        con.saveandSelectMore();
        con.filter();
        con.gettotalPages();
        con.gethasPrevious();
        con.previous();
        con.gethasLast();
        con.last();
        con.gethasFirst();
        con.first();
        con.sortLineNumber();
        String sortColumn = con.getsortColumn();
        system.assertEquals('LineNumber', sortColumn);
        con.sortItemNumber();
        con.sortItemDescription();
        con.sortDC();
        con.sortOrderQuantity();
        con.sortReturnQuantity();
        con.sortShipDate();
        con.sortLineTotal();
        con.sortShiptoNum();
        con.sortCollection();
        con.sortMonogram_able();
        con.sortSPO();
        con.sortSPO();
        con.cancel();
        
    }
}