objects/Case.object
<CustomObject>
    <fields>
        <fullName>Attempted_Contact__c</fullName>
        <description>This field is used to count the amount of attempted contacts. It is incremented both by trigger and workflow count.</description>
        <label>Attempted Contact</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <description>This will be autopopulated via trigger from the case comments object.</description>
        <label>Call Outcome</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SendGrid_Result__c</fullName>
        <inlineHelpText>Automatically set to SUCCESS or FAILURE with a brief error description based upon the result of the attempt to send an email via SendGrid.</inlineHelpText>
        <label>SendGrid Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <label>Sold to Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_2__c</fullName>
        <label>Sold to Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_City__c</fullName>
        <label>Sold to City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <label>Sold to Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <label>Sold to Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <label>Sold to Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <label>Sold to First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <label>Sold to Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <label>Sold to State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <label>Sold to Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To_Day_Phone__c</fullName>
        <formula>Ship_To__r.Ship_to_Day_Phone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ship To Day Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Email__c</fullName>
        <formula>Ship_To__r.Ship_to_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ship To Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>SendGrid_Result__c</fullName>
        <label>SendGrid Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <description>CW Sold to Address Line 1</description>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address_2__c</fullName>
        <description>CW Sold to Address Line 2</description>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_City__c</fullName>
        <description>CW Sold to City</description>
        <label>Sold To City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <description>CW Sold to Country</description>
        <label>Sold To Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <description>CW Sold to Daytime Phone</description>
        <label>Sold To Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <description>CW Sold to State</description>
        <label>Sold To State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <description>CW Sold to Zip</description>
        <label>Sold To Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_1__c</fullName>
        <label>Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_2__c</fullName>
        <label>Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_to_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_to_First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestBatchCreditCardDeclineEmail.cls
@isTest(SeeAllData=true)
public with sharing class TestBatchCreditCardDeclineEmail {

    /*
    static Case initCCDecline() {
		 	
    	// Create the test data - Order, Ship To, and Case
    	List<RecordType> rtList = new List<RecordType>();
    	Id caseRtId = [select Id, SobjectType from RecordType where Name = 'Credit Card Declines' and SobjectType = 'Case' limit 1].Id;
    	
    	RH_Order__c order = new RH_Order__c(
    		Name = 'TestOrder1',
    		Sold_to_First_Name__c = 'Jerry',
    		Sold_to_Last_Name__c = 'Garcia',
    		Sold_to_Day_Phone__c = '777-123-4567', 
			Sold_to_Address_1__c = '710 Ashbury Street',
			Sold_to_Address_2__c = '',
			Sold_to_City__c = 'San Francisco',
			Sold_to_State__c = 'CA',
			Sold_to_Zip__c = '94117',
			Sold_to_Country__c = 'USA',
			Sold_to_Email__c = 'jerrygarcia@gmail.com'
    	);
    	insert order;
    	
    	Ship_To__c shipTo = new Ship_To__c(
    		Name = '1',
    		Order__c = order.Id,
    		Ship_to_First_Name__c = 'Jerry',
    		Ship_to_Last_Name__c = 'Garcia',
    		Ship_to_Day_Phone__c = '777-123-4567', 
			Ship_to_Address_1__c = '710 Ashbury Street',
			Ship_to_Address_2__c = '',
			Ship_to_City__c = 'San Francisco',
			Ship_to_State__c = 'CA',
			Ship_to_Zip__c = '94117',
			Ship_to_Country__c = 'USA',
			Ship_to_Email__c = 'jerrygarcia@rh.com'
    	);
    	insert shipTo;
    	
    	Order_Line_Items__c orderLine = new Order_Line_Items__c(
    		Name = '1',
    		RH_Order_Number__c = order.Id,
    		Ship_To__c = shipTo.Id
    	);
    	insert orderLine;
    	
    	// Create a Case
    	List<Case> ccCase = new List<Case>();
    	ccCase.add(new Case(
    		RecordTypeId = caseRtId,
    		RH_Order_Number__c = order.Id
    		)
    	);
    	//insert ccCase;
    	
    	return ccCase[0];
    }
    
    static testmethod void testBatchNotification() {
		
        Case ccdCase = new Case();
		
		ccdCase = initCCDecline();
		
		Test.StartTest();
		insert ccdCase;
		//BatchCreditCardDeclineEmail sync = new BatchCreditCardDeclineEmail();
		//ID batchprocessid = Database.executeBatch(sync, 100);
		Test.StopTest();
		
		// Verify results
		ccdCase = [select Id, SendGrid_Result__c, Call_Outcome__c, Attempted_Contact__c from Case where Id = :ccdCase.Id];
		system.assertEquals(true, ccdCase.SendGrid_Result__c.contains('SUCCESS'));
		system.assertEquals('Sent Email', ccdCase.Call_Outcome__c);
		system.assertEquals(1, ccdCase.Attempted_Contact__c);
    }
    
    static testmethod void testFinalNotification() {
		
		Case ccdCase = new Case();
		
		ccdCase = initCCDecline();
		
		Test.StartTest();
		insert ccdCase;
		ccdCase.Attempted_Contact__c = 3;
		ccdCase.Call_Outcome__c = 'Could Not Reach';
		update ccdCase;
		Test.StopTest();
		
		// Verify results
		ccdCase = [select Id, SendGrid_Result__c, Call_Outcome__c, Attempted_Contact__c from Case where Id = :ccdCase.Id];
		system.assertEquals(true, ccdCase.SendGrid_Result__c.contains('SUCCESS'));
		system.assertEquals('Sent Email', ccdCase.Call_Outcome__c);
		system.assertEquals(4, ccdCase.Attempted_Contact__c);
	}
	*/
}