objects/Case.object
<CustomObject>
    <fields>
        <fullName>Designer__c</fullName>
        <label>Designer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gallery_Number__c</fullName>
        <label>Gallery Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Type__c</fullName>
        <label>Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accommodations</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Delivering on Delight</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
                <value>
                    <fullName>Final Mile Delivery Notification</fullName>
                </value>
                <value>
                    <fullName>Order Inquiries</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Reorders</fullName>
                </value>
                <value>
                    <fullName>Replacement Parts</fullName>
                </value>
                <value>
                    <fullName>Delight HQ</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <label>Sold to Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_2__c</fullName>
        <label>Sold to Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <inlineHelpText>Order Total sums all ship tos</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Accommodations</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Accommodations</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The line number selected must be from the order on the case.</errorMessage>
            <filterItems>
                <field>$Source.Order__c</field>
                <operation>equals</operation>
                <valueField>Order_Line_Items__c.RH_Order_Number__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order_Line_Items__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <description>Do not use.</description>
        <formula>Line_Number__r.RH_Order_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <recordTypes>
        <fullName>Accommodations</fullName>
        <active>true</active>
        <label>Accommodations</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>This field is populated by information from CW. It is hidden from the page layout because the Order LIne Number (standard name field) is required on the page layout, and this would in essence duplicate information. There is a workflow rule that takes this number and populates it into the line number name field.</description>
        <label>Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Quantity__c</fullName>
        <description>Order Quantity of Line</description>
        <label>Order Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Price of Line</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Designer__c</fullName>
        <description>Designer assigned to order</description>
        <label>Order Classification</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gallery_Number__c</fullName>
        <description>Store Number</description>
        <label>Gallery Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <description>CW Sold to Address Line 1</description>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address_2__c</fullName>
        <description>CW Sold to Address Line 2</description>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Order_Amount__c</fullName>
        <description>Including shipping, handling, and tax</description>
        <inlineHelpText>Order total sums all ship tos.</inlineHelpText>
        <label>Total Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCaseLineFromOrderLine_Test.cls
@isTest(SeeAllData=true)
private class UpdateCaseLineFromOrderLine_Test 
{
    static testMethod void myUnitTest() 
    {
        Test.startTest();
        
        //Create RH Order
        RH_Order__c rho=new RH_Order__c();
        rho.Name='ORDER 123';
        rho.Designer__c='Designer A';
        rho.Sold_To_Address_1__c='123 Test Street';
        rho.Sold_To_Address_2__c='456 Test Street';
        rho.Gallery_Number__c='5';
        rho.Total_Order_Amount__c=1500.00;
        insert rho;
        
        System.debug(rho);
        
        //Create Order line items
        Order_Line_Items__c oli1=new Order_Line_Items__c();
        oli1.RH_Order_Number__c=rho.Id;
        oli1.Order_Quantity__c=2;
        oli1.Unit_Price__c=10.0;
        oli1.Line_Total__c=20.0;
        insert oli1;
        
        Order_Line_Items__c oli2=new Order_Line_Items__c();
        oli2.RH_Order_Number__c=rho.Id;
        oli2.Order_Quantity__c=3;
        oli2.Unit_Price__c=15.0;
        oli2.Line_Total__c=45.0;
        insert oli2;
        
        
        //Create Case
        Case c=new Case();
        List<RecordType> caseRecordType = [SELECT Id, Name, Description FROM RecordType WHERE SobjectType='Case' LIMIT 1]; 
        if(caseRecordType.size()>0){
            c.RecordTypeId=caseRecordType[0].Id;
        	}
        
        c.RH_Order_Number__c=rho.Id;
        c.Status='New';
        //c.Queue_Type__c='Accommodations';
        insert c;
        
        System.debug(c);
        
        //Create Case line items
        Case_Line_Items__c cli1=new Case_Line_Items__c();
        cli1.Case_Number__c=c.Id;
        cli1.Line_Number__c=oli1.Id;
        cli1.Order__c=rho.Id;
        insert cli1;
        
        //Create Case line items
        Case_Line_Items__c cli2=new Case_Line_Items__c();
        cli2.Case_Number__c=c.Id;
        cli2.Line_Number__c=oli2.Id;
        cli2.Order__c=rho.Id;
        insert cli2;
        
        //Update RHOrder
        rho.Name='ORDER 123';
        rho.Designer__c='Designer B';
        rho.Sold_To_Address_1__c='1234 Test Street';
        rho.Sold_To_Address_2__c='4567 Test Street';
        rho.Gallery_Number__c='5';
        rho.Total_Order_Amount__c=2500.00;
        update rho;
        
        System.debug(rho);
        
        //Update Order Line Items
        oli1.Order_Quantity__c=2;
        oli1.Unit_Price__c=15.0;
        oli1.Line_Total__c=30.0;
        update oli1;
        
        oli2.Order_Quantity__c=1;
        oli2.Unit_Price__c=25.0;
        oli2.Line_Total__c=25.0;
        update oli2;
        
        Test.stopTest();
    }
}