objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is checked if action is required on the case</description>
        <label>Action Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attempted_Contact__c</fullName>
        <description>This field is used to count the amount of attempted contacts. It is incremented both by trigger and workflow count.</description>
        <label>Attempted Contact</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <description>This will be autopopulated via trigger from the case comments object.</description>
        <label>Call Outcome</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Callout_Contacts__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Set automatically by trigger.  Records the number of times the customer was actually reached via phone.</inlineHelpText>
        <label>Callout Contacts per Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Contacts__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Set automatically. Records the number of times an email was sent to the customer.</inlineHelpText>
        <label>Email Contacts per Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>no_of_case_comments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Case comments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Comments__c.object
<CustomObject>
    <description>NOTE: The &quot;Close Case&quot; button leads to a &quot;Close Case&quot; page that simulates the standard (out of the box) Close Case Page; however, it is a custom VisualForce page.</description>
    <fields>
        <fullName>Action_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</description>
        <inlineHelpText>Check this box if an action is required on this case. If the case is open, a flag will notify the case owner that an action is required. If the case is closed, it will re-open and be sent back to the original queue to be worked.</inlineHelpText>
        <label>Action Required/Re-open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <label>Call Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Could Not Reach</fullName>
                </value>
                <value>
                    <fullName>Left Voicemail</fullName>
                </value>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Talked to Client</fullName>
                </value>
                <value>
                    <fullName>Talked to Advocate</fullName>
                </value>
                <value>
                    <fullName>Future Dating</fullName>
                </value>
                <value>
                    <fullName>No Action Taken</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comments</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Available_Date__c</fullName>
        <inlineHelpText>Current availability date at the time the case line was created.</inlineHelpText>
        <label>Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line Number</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The line number selected must be from the order on the case.</errorMessage>
            <filterItems>
                <field>$Source.Order__c</field>
                <operation>equals</operation>
                <valueField>Order_Line_Items__c.RH_Order_Number__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order_Line_Items__c</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <description>Do not use.</description>
        <formula>Line_Number__r.RH_Order_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Current_Available_Date__c</fullName>
        <inlineHelpText>Most recent available date that has been communicated to the Client</inlineHelpText>
        <label>Current Available Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Delay_Date__c</fullName>
        <inlineHelpText>Most recent delivery date calculated in CW. This may not have been communicated to the Client</inlineHelpText>
        <label>Current Delay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>This field is populated by information from CW. It is hidden from the page layout because the Order LIne Number (standard name field) is required on the page layout, and this would in essence duplicate information. There is a workflow rule that takes this number and populates it into the line number name field.</description>
        <label>Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Callout_Contacts__c</fullName>
        <inlineHelpText>Number of times the customer has been contacted by phone via a case.</inlineHelpText>
        <label>Callout Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Contacts__c</fullName>
        <inlineHelpText>Number of times the customer has been contacted by email via a case.</inlineHelpText>
        <label>Email Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCaseFromCaseComments.cls
/*
    Class: UpdateCaseFromCaseComments
    Description: This case contains a method to update the Case field "Action Required" and also number of case comments related to a Case
    Developer: vk@ff on 08/26/2014
    Test Class: CaseCommentsTrigger_Test
*/

public without sharing class UpdateCaseFromCaseComments
{
	/*
	 *	Entire class file is commented out because the CaseCommentsTrigger has been rewritten to no longer use this class file.
	 *	This class file should probably be deleted at some point in the future when we are sure we will not want to go back to it.
	 *
	
	//Method sets the Action Required field on a Case
	public static void UpdateCase(List<Id> lstOfCIds)
	{
		List<Case> lstOfCases=new List<Case>();
		lstOfCases=[SELECT Id, Action_Required__c FROM Case WHERE Id IN: lstOfCIds];
		if(!lstOfCases.isEmpty())
		{
			for(Case c: lstOfCases)
			{
				c.Action_Required__c=true;
			}
		}
		
		try
		{
			update lstOfCases;	
		}
		catch(DmlException e)
		{
			System.debug(e.getMessage());	
		}
	}
	
	//Updates the number of Case Comments on a Case
	public static void UpdateNoOfComments(Map<Id,Boolean> mOfCids)
	{
		List<Case> lstOfCases=new List<Case>();
		System.debug('CASE IDS'+ mOfCids.keySet());
		List<Id> lstOfCids=new List<Id>();
		lstOfCids.addAll(mOfCids.keySet());
		
		lstOfCases=[SELECT Id, no_of_case_comments__c FROM Case WHERE Id IN:mOfCids.keySet()];
		System.debug('IN CLASS' + lstOfCases);
		if(!lstOfCases.isEmpty())
		{
			for(Case c: lstOfCases)
			{
				if(mOfCids.containsKey(c.Id))
				{
					if(mOfCids.get(c.Id)==true && c.no_of_case_comments__c!=null)
					{
						c.no_of_case_comments__c=c.no_of_case_comments__c+1;
						System.debug('INCREMENTING' + c.no_of_case_comments__c);
					}
					else
					{
						if(c.no_of_case_comments__c!=null)
						{
							c.no_of_case_comments__c=c.no_of_case_comments__c-1;
							System.debug('DECREMENTING' + c.no_of_case_comments__c);
						}
					}	
				}	
			}	
		}
		
		try
		{
			update lstOfCases;
		}
		catch(DmlException e)
		{
			System.debug(e.getMessage());	
		}
	}
	
	//Updates the accepted count field on Case
	public static void UpdateAttemptedCount(List<Id> lstOfCIds)
	{
		List<Case> lstOfCases=[SELECT Id,Attempted_Contact__c FROM Case WHERE Id IN: lstOfCIds];
		
		for(Case c: lstOfCases)
		{
			if(c.Attempted_Contact__c!=null)
			{
				c.Attempted_Contact__c++;
			}
			else
			{
				c.Attempted_Contact__c=1;
			}
		}
		
		try
		{
			update lstOfCases;
		}
		catch(DmlException e)
		{
			System.debug(e.getMessage());	
		}
		
	}
	
	// Update the case field Call Outcome from the case comment.  Also update the related order and order line information as appropriate
	public static void UpdateCaseCallOutcome(Map<Id,Id> mapCCToCase)
	{
		List<Id> oIds = new List<Id>();
		List<Id> cDNIds = new List<Id>();
		Map<Id, RH_Order__c> oMap;
		Boolean upOrder;
		List<RH_Order__c> oUpList = new List<RH_Order__c>();
		Id caseDNRecordTypeId = '012500000009tdy';
		
		List<Case> lstOfCases = [SELECT Id, Call_Outcome__c, RecordTypeId, RH_Order_Number__c FROM Case WHERE Id IN: mapCCToCase.values()];
		for (Case c :lstOfCases) {
			oIds.add(c.RH_Order_Number__c);
			if (c.RecordTypeId == caseDNRecordTypeId) {
				cDNIds.add(c.Id);
			}
		}
		
		oMap = new Map<Id, RH_Order__c>([select Id, Callout_Contacts__c, Email_Contacts__c from RH_Order__c where Id in :oIds]);
		
		//Retrieve all the call outcomes from Case Comments
		Map<Id,Case_Comments__c> mapOfcc = new Map<Id,Case_Comments__c>([SELECT Id, Call_Outcome__c FROM Case_Comments__c WHERE Id IN: mapCCToCase.keySet()]);
		
		for (Case c :lstOfCases) {
			for (Id ccId :mapCCToCase.keySet()) {
				if (mapCCToCase.get(ccId) == c.Id && mapOfcc.get(ccId) != null && mapOfcc.get(ccId).Call_Outcome__c != null) {
					c.Call_Outcome__c=mapOfcc.get(ccId).Call_Outcome__c;
					
					// update the related order customer contact fields
					if (oMap.containsKey(c.RH_Order_Number__c)) {
						upOrder = false;
						if (c.Call_Outcome__c == 'Talked to Customer') {
							if (oMap.get(c.RH_Order_Number__c).Callout_Contacts__c == null) {
								oMap.get(c.RH_Order_Number__c).Callout_Contacts__c = 0;
							}
							oMap.get(c.RH_Order_Number__c).Callout_Contacts__c++;
							upOrder = true;
						}
						if (c.Call_Outcome__c == 'Sent Email') {
							if (oMap.get(c.RH_Order_Number__c).Email_Contacts__c == null) {
								oMap.get(c.RH_Order_Number__c).Email_Contacts__c = 0;
							}
							oMap.get(c.RH_Order_Number__c).Email_Contacts__c++;
							upOrder = true;
						}
						if (upOrder) {
							oUpList.add(oMap.get(c.RH_Order_Number__c));
						}
					}
				}
			}
		}
		
		// Update the order line availability date communicated to customer for all Delay Notifications cases
		Map<Id, Order_Line_Items__c> oliMap = new Map<Id, Order_Line_Items__c>();
		if (!oUpList.isEmpty() && !cDNIds.isEmpty()) {
			List<Case_Line_Items__c> cliList = new List<Case_Line_Items__c>();
			cliList = [select Id, Case_Number__c, Line_Number__c, Current_Available_Date__c from Case_Line_Items__c where Case_Number__c in :cDNIds];
			List<Id> oliIds = new List<Id>();
			for (Case_Line_Items__c cli :cliList) {
				oliIds.add(cli.Line_Number__c);
			}
			oliMap = new Map<Id, Order_Line_Items__c>([select Id, Current_Available_Date__c, Current_Delay_Date__c from Order_Line_Items__c where Id in :oliIds]);
			for (Case_Line_Items__c cli :cliList) {
				if (cli.Current_Available_Date__c != null) {
					oliMap.get(cli.Line_Number__c).Current_Available_Date__c = cli.Current_Available_Date__c;
				} else {
					if (oliMap.get(cli.Line_Number__c).Current_Delay_Date__c != null) {
						oliMap.get(cli.Line_Number__c).Current_Available_Date__c = oliMap.get(cli.Line_Number__c).Current_Delay_Date__c;
					}
				}
			}
		}
		
		try {
			if (!oUpList.isEmpty()) {
				update oUpList;
			}
			if (!oliMap.isEmpty()) {
				update oliMap.values();
			}
			if (!lstOfCases.isEmpty()) {
				update lstOfCases;
			}
		} catch(DmlException e) {
			System.debug('*****UpdateCaseCallOutcome exception = ' + e.getMessage());	
		}
	}
	*/
}