objects/Case_Comments__c.object
<CustomObject>
    <description>NOTE: The &quot;Close Case&quot; button leads to a &quot;Close Case&quot; page that simulates the standard (out of the box) Close Case Page; however, it is a custom VisualForce page.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Comments</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ViewCaseCommentsController_Test.cls
@isTest(SeeAlldata=true)
public class ViewCaseCommentsController_Test {
    static testMethod void ViewCaseCommentsControllerTest() {
        Case c = new Case();
        insert c;
        
        Case_Comments__c cc = new Case_Comments__c(Case__c = c.Id, Comment__c = 'Test Case Comments');
        insert cc;
                
        //Apex.PageReference='/apex/ViewCaseComments?Id='+ c.Id+ '&ViewAll=true';
        ApexPages.StandardController csc = new ApexPages.StandardController(c);
        PageReference pageRef = Page.ViewCaseComments;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id', c.Id);
        ApexPages.currentPage().getParameters().put('ViewAll','true');
        
        String objName='Case_Comments';
        String FieldName='Case';
        ViewCaseCommentsController.getButtonFieldValue(objName,FieldName);
        ViewCaseCommentsController caseComments = new ViewCaseCommentsController(csc);
       
             
        caseComments.Next();
        caseComments.Previous();
        caseComments.getCaseRecords(); 
    }

}