objects/Case.object
<CustomObject>
    <fields>
        <fullName>Callout_Contacts__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Set automatically by trigger.  Records the number of times the customer was actually reached via phone.</inlineHelpText>
        <label>Callout Contacts per Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Contacts__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Set automatically. Records the number of times an email was sent to the customer.</inlineHelpText>
        <label>Email Contacts per Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Membership_Auto_Renewal_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the related Order on this Credit Card Decline case only has Membership Auto Renewal SKU Order Lines.</description>
        <inlineHelpText>If checked, the related Order on this Credit Card Decline case only has Membership Auto Renewal SKU Order Lines.</inlineHelpText>
        <label>Membership Auto Renewal Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Order_Lines__c</fullName>
        <label>Number of Order Lines</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Notification_Visibility__c</fullName>
        <inlineHelpText>Automatically copied from the Order - an RH email address to be copied on various customer Order notifications (like Delay Notifications, etc.).</inlineHelpText>
        <label>Order Notification Visibility</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address__c</fullName>
        <label>Sold to Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>System_Hold_Code__c</fullName>
        <label>System Hold Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CasetoOrderFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Case_Field__c</fullName>
        <label>Case Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Field__c</fullName>
        <label>Order Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CasetoOrderFieldMapping</label>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Callout_Contacts__c</fullName>
        <inlineHelpText>Number of times the customer has been contacted by phone via a case.</inlineHelpText>
        <label>Callout Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Contacts__c</fullName>
        <inlineHelpText>Number of times the customer has been contacted by email via a case.</inlineHelpText>
        <label>Email Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Membership_Auto_Renewal_Order__c</fullName>
        <formula>IF(Number_of_Order_Lines__c  &gt; 0 &amp;&amp; Number_of_Order_Lines__c = Number_of_MembershipAutoRenewalSKUs__c, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Will be checked if all order lines on this order are one of the Membership Auto Renewal SKUs.</inlineHelpText>
        <label>Membership Auto Renewal Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Order_Lines__c</fullName>
        <label>Number of Order Lines</label>
        <summaryForeignKey>Order_Line_Items__c.RH_Order_Number__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Notification_Visibility__c</fullName>
        <inlineHelpText>Enter an RH email address to be copied on various customer Order notifications (like Delay Notifications, etc.).</inlineHelpText>
        <label>Order Notification Visibility</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address__c</fullName>
        <formula>IF(
AND
(
ISBLANK(Sold_To_Address_1__c),
ISBLANK(Sold_to_Address_2__c),
ISBLANK(Sold_to_Company__c),
ISBLANK(Sold_to_City__c),
ISBLANK(Sold_to_State__c),
ISBLANK(Sold_to_Zip__c),
ISBLANK(Sold_to_Country__c)
), 
null, 
Sold_To_Address_1__c  + BR() +  Sold_to_Address_2__c + BR() + Sold_to_City__c + &quot;, &quot; +  Sold_to_State__c + &quot;, &quot; + Sold_to_Zip__c + BR() + Sold_to_Country__c
)</formula>
        <label>Sold To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Hold_Code__c</fullName>
        <description>AT</description>
        <label>System Hold Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Hold_Description__c</fullName>
        <description>Decline Credit Card</description>
        <label>System Hold</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCaseFromRHOrder.cls
/**
    * Description: Class to update the fields on Case when an RH Order is Updated
    * Test Class: UpdateCaseFromRHOrder_Test
    * Apex Trigger: RHOrderTrigger
**/

public without sharing class UpdateCaseFromRHOrder
{
    public static void updateCase(List<SObject> recordsToupdate, Map<Id, RH_Order__c> triggerNewMap, Map<Id, RH_Order__c> triggeroldMap){
        Set<Id> rhIdList = new Set<Id>();
        List<CasetoOrderFieldMapping__c> caseToRHOMapping = [SELECT Case_Field__c, Order_Field__c FROM CasetoOrderFieldMapping__c];
        Id muleAPIUserId = '00550000003kjUn';
        
        Map<String, Schema.RecordTypeInfo> rtNameMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
        Id caseCWIntegrationErrRT = rtNameMap.get('CW Integration Errors').getRecordTypeId();
        Id caseCCDRecordTypeId = rtNameMap.get('Credit Card Declines').getRecordTypeId();
        
        String caseQuery = 'SELECT Id, RH_Order_Number__c, RecordTypeId, LastModifiedById, ';
        
        for(CasetoOrderFieldMapping__c cofm: caseToRHOMapping){
            caseQuery += cofm.Case_Field__c + ', ';
        }
        
        caseQuery = caseQuery.removeEnd(', ');
        
        for(RH_Order__c rh: triggerNewMap.values()){
            for(CasetoOrderFieldMapping__c cofm: caseToRHOMapping){
                if(rh.get(cofm.Order_Field__c) != triggeroldMap.get(rh.Id).get(cofm.Order_Field__c)){
                    rhIdList.add(rh.Id);
                    break;
                }
            }
        }
        
        caseQuery += ' FROM Case WHERE RH_Order_Number__c IN: rhIdList AND IsClosed = FALSE AND RecordTypeId != \'' + caseCWIntegrationErrRT + '\'';
        List<Case> caseList=new List<Case>();
        if (rhIdList.size() > 0) {
			caseList = Database.query(caseQuery);
			
        	for (Case c :caseList) {
            		
				for (CasetoOrderFieldMapping__c cofm :caseToRHOMapping) {
					
					// Verify that the user has access to the Opportunity before copying the Opportunity Id
					if (cofm.Order_Field__c == 'Opportunity__c') {
						String oppId = (String)(triggerNewMap.get(c.RH_Order_Number__c).get(cofm.Order_Field__c));
						if (String.isNotBlank(oppId)) {
							Boolean hasOppRead = [select RecordId, HasReadAccess from UserRecordAccess where UserId = :UserInfo.getUserId() and RecordId = :oppId].HasReadAccess;
							if (!hasOppRead) {
								c.put(cofm.Case_Field__c, null);
								continue;
							}
						}
					}
					
					// We only copy all updated order information to Credit Card Decline cases where the LastModifiedById 
					// is the Mule API User - means the case has not been picked up yet by any user.
					if (c.RecordTypeId != caseCCDRecordTypeId || (c.RecordTypeId == caseCCDRecordTypeId && c.LastModifiedById == muleAPIUserId)) {
						
						// If case field is Sold to address, remove BR tags and replace with New line
						if (cofm.Order_Field__c == 'Sold_to_Address__c') {
							String str = String.valueOf(triggerNewMap.get(c.RH_Order_Number__c).get(cofm.Order_Field__c));
							if (String.isNotBlank(str)) {
								str = str.replaceAll('_BR_ENCODED_','\n');
							}
							c.put(cofm.Case_Field__c, str);
						} else {
							c.put(cofm.Case_Field__c, triggerNewMap.get(c.RH_Order_Number__c).get(cofm.Order_Field__c));
						}
					
					} else {
						
						// Credit Card Declines case - only copy select information
						if ( cofm.Order_Field__c == 'Callout_Contacts__c' || 
							 cofm.Order_Field__c == 'Email_Contacts__c' || 
							 cofm.Order_Field__c == 'Opportunity__c' || 
							 cofm.Order_Field__c == 'System_Hold_Description__c' || 
							 cofm.Order_Field__c == 'System_Hold_Code__c' || 
							 cofm.Order_Field__c == 'Membership_Auto_Renewal_Order__c' || 
							 cofm.Order_Field__c == 'Number_of_Order_Lines__c' || 
							 cofm.Order_Field__c == 'Order_Notification_Visibility__c' || 
							 cofm.Order_Field__c == 'Order_Type_Code__c') {
							c.put(cofm.Case_Field__c, triggerNewMap.get(c.RH_Order_Number__c).get(cofm.Order_Field__c));
						}
					}
            	}
        	}
        	
        	try {
            	// update caseList;
            	recordsToUpdate.addAll((List<SObject>)caseList);
            	System.debug(caseList);
        	} catch(DMLException de) {
            	System.debug('*****UpdateCaseFromRHOrder exception = ' + de.getDMLMessage(0));
        	}
    	}   
    }
}