objects/Case.object
<CustomObject>
    <fields>
        <fullName>Future_Processing_Date__c</fullName>
        <label>Future Processing Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Timer_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Timer Entries</relationshipLabel>
        <relationshipName>Timer_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <description>when the event was stopped</description>
        <inlineHelpText>End of Activity</inlineHelpText>
        <label>EndTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the timer entry</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Timer Entry</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Timer Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timer Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CaseTimerEntries.cls
/***************************************************************************************
    CLIENT
        Restoration Hardware
            
    PURPOSE
        Create a timer entry to track cases that are Transfered back to the queue.

    TEST CLASS
        CaseTimerEntries_TEST
         
    ENTRY POINTS
        CaseTrigger              
    
    CHANGE LOG
        [[Version; Date; Author; Description]]
        v0.1; 2014/11/03; Carl Weiss/Forefront; Initial Build
        Peter Alexander Mandy 03.02.2016 17:06:22.84 - refactored code, removed SOQL FROM for Loop and combined all sources into single collection.
***************************************************************************************/
public with sharing class CaseTimerEntries {

  /*  public static void CreateTransferTimerEntry(Map<String, Map<Id, Case>> sourceCases)
    {
        Set<Id> setCaseIds = new Set<Id>();
        for(String source:sourceCases.keySet()){
           setCaseIds.addAll(sourceCases.get(source).keySet());
        }    
        List<Timer_Entry__c> relatedCaseTimers = new List<Timer_Entry__c>();
        List<Timer_Entry__c> te = [SELECT id, CreatedById, Case__c 
                                     FROM Timer_Entry__c
                                    WHERE Case__c in :setCaseIds  
                                      AND EndTime__c = null];
        Set<Id> timerIds = new Set<Id>();                            
        for(String source:sourceCases.keySet()){    
           for (Timer_Entry__c t : te){    
              if(sourceCases.get(source).containsKey(t.Case__c)
                 && t.CreatedById == sourceCases.get(source).get(t.Case__c).LastModifiedById
                 ){
                     if(sourceCases.get(source).get(t.Case__c).Future_Processing_Date__c != null 
                        && source == 'Transfer Back'){
                        t.Source__c = 'Future Process';
                     }else{
                        t.Source__c = source;
                     }
                     if(!timerIds.Contains(t.Id)){
                        relatedCaseTimers.add(t);              
                        timerIds.add(t.Id);
                     }
                  }
            }      
         }
        
        if (!relatedCaseTimers.isEmpty()){
            update relatedCaseTimers;
        }
    }*/
}