objects/Case.object
<CustomObject>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                    <default>true</default>
                    <label>Client</label>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Gallery</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>VIP/BOD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Requested_Percentage__c</fullName>
        <inlineHelpText>Enter the percentage that you are giving for an accommodation.</inlineHelpText>
        <label>Requested Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Queue_Type__c</fullName>
        <label>Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accommodations</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Delivering on Delight</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Credit Card Declines</fullName>
                </value>
                <value>
                    <fullName>Delay Notifications</fullName>
                </value>
                <value>
                    <fullName>Final Mile Delivery Notification</fullName>
                </value>
                <value>
                    <fullName>Order Inquiries</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Reorders</fullName>
                </value>
                <value>
                    <fullName>Replacement Parts</fullName>
                </value>
                <value>
                    <fullName>Delight HQ</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>​Address Change</fullName>
                    <color>#0B6FCE</color>
                    <label>​Address Change</label>
                </value>
                <value>
                    <fullName>All</fullName>
                    <color>#78C953</color>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Assembly/Parts</fullName>
                    <color>#E27001</color>
                    <label>Assembly/Parts</label>
                </value>
                <value>
                    <fullName>Automatic Email</fullName>
                    <color>#A845DC</color>
                    <label>Automatic Email</label>
                </value>
                <value>
                    <fullName>B&amp;C Registry Cards</fullName>
                    <color>#F3D904</color>
                    <label>B&amp;C Registry Cards</label>
                </value>
                <value>
                    <fullName>Billing/Order Inquiry</fullName>
                    <color>#A53711</color>
                    <label>Billing/Order Inquiry</label>
                </value>
                <value>
                    <fullName>Callout</fullName>
                    <color>#0B6FCE</color>
                    <label>Callout</label>
                </value>
                <value>
                    <fullName>Canadian Freight Fee</fullName>
                    <color>#0B24BE</color>
                    <label>Canadian Freight Fee</label>
                </value>
                <value>
                    <fullName>Cancelled Delivery</fullName>
                    <color>#419249</color>
                    <label>Cancelled Delivery</label>
                </value>
                <value>
                    <fullName>Cancelled Return</fullName>
                    <color>#B6E32E</color>
                    <label>Cancelled Return</label>
                </value>
                <value>
                    <fullName>Cash Accommodation</fullName>
                    <color>#641CCF</color>
                    <label>Cash Accommodation</label>
                </value>
                <value>
                    <fullName>CDN Not in PODirect</fullName>
                    <color>#F96FB7</color>
                    <label>CDN Not in PODirect</label>
                </value>
                <value>
                    <fullName>Change of Address</fullName>
                    <color>#2F5D85</color>
                    <label>Change of Address</label>
                </value>
                <value>
                    <fullName>Checklist Needed</fullName>
                    <color>#AFCADF</color>
                    <label>Checklist Needed</label>
                </value>
                <value>
                    <fullName>Complimentary Credit</fullName>
                    <color>#8F6429</color>
                    <label>Complimentary Credit</label>
                </value>
                <value>
                    <fullName>Conditional Delivery</fullName>
                    <color>#EFAE73</color>
                    <label>Conditional Delivery</label>
                </value>
                <value>
                    <fullName>Contact Issue</fullName>
                    <color>#57F17C</color>
                    <label>Contact Issue</label>
                </value>
                <value>
                    <fullName>Days Moved In</fullName>
                    <color>#0B6FCE</color>
                    <label>Days Moved In</label>
                </value>
                <value>
                    <fullName>Delivery Refusal</fullName>
                    <color>#78C953</color>
                    <label>Delivery Refusal</label>
                </value>
                <value>
                    <fullName>ETA Request</fullName>
                    <color>#E27001</color>
                    <label>ETA Request</label>
                </value>
                <value>
                    <fullName>Failed Deluxe</fullName>
                    <color>#A845DC</color>
                    <label>Failed Deluxe</label>
                </value>
                <value>
                    <fullName>Gift Boxes</fullName>
                    <color>#F3D904</color>
                    <label>Gift Boxes</label>
                </value>
                <value>
                    <fullName>Gift Card Refund</fullName>
                    <color>#A53711</color>
                    <label>Gift Card Refund</label>
                </value>
                <value>
                    <fullName>Gift Return</fullName>
                    <color>#66E9BD</color>
                    <label>Gift Return</label>
                </value>
                <value>
                    <fullName>HDL Escalations</fullName>
                    <color>#0B24BE</color>
                    <label>HDL Escalations</label>
                </value>
                <value>
                    <fullName>Mailed in Request</fullName>
                    <color>#419249</color>
                    <label>Mailed in Request</label>
                </value>
                <value>
                    <fullName>Manual Billing Summary</fullName>
                    <color>#B6E32E</color>
                    <label>Manual Billing Summary</label>
                </value>
                <value>
                    <fullName>Manual Charge</fullName>
                    <color>#641CCF</color>
                    <label>Manual Charge</label>
                </value>
                <value>
                    <fullName>Manual Charge - Unpaid Items</fullName>
                    <color>#F96FB7</color>
                    <label>Manual Charge - Unpaid Items</label>
                </value>
                <value>
                    <fullName>Manual Email</fullName>
                    <color>#FF0000</color>
                    <label>Manual Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_to_City__c</fullName>
        <label>Alternate City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Country__c</fullName>
        <label>Alternate Country</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Day_Phone__c</fullName>
        <label>Alternate Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Send_to_First_Name__c</fullName>
        <label>Alternate First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Last_Name__c</fullName>
        <label>Alternate Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_State__c</fullName>
        <label>Alternate State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_to_Zip__c</fullName>
        <label>Alternate Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Accommodations</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Accommodations</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Line Items</relationshipLabel>
        <relationshipName>Case_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <label>Item Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Total__c</fullName>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Line Item</label>
    <nameField>
        <label>Case Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <recordTypes>
        <fullName>Accommodations</fullName>
        <active>true</active>
        <label>Accommodations</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CloneCaseWithCaseLinesController_Test.cls
@isTest
private class CloneCaseWithCaseLinesController_Test 
{
	static testMethod void myUnitTest() 
	{	PrepareData.populateCustomSettings();
		
		//Create Case
		Case c=new Case();
		//c.Queue_Type__c='Accommodations';
		c.Request_Category__c='Gift Card';
		c.Client_Type__c='Customer';
		c.Send_to_First_Name__c = 'Bob';
		c.Send_to_Last_Name__c = 'Jones';
		c.Send_to_City__c = 'Santa Cruz';
		c.Send_to_State__c = 'CA';
		c.Send_to_Zip__c = '94500';
		c.Send_to_Country__c = 'USA';
		c.Send_to_Day_Phone__c = '555-555-5555';
		c.Original_Requested_Percentage__c=.95;
		insert c;
		
		//Create Case Lines
		Case_Line_Items__c cl1=new Case_Line_Items__c();
		cl1.Item_Number__c='1213';
		cl1.Color__c='Green';
		cl1.Line_Total__c=100.00;
		cl1.Case_Number__c=c.Id;
		insert cl1;
		
		Case_Line_Items__c cl2=new Case_Line_Items__c();
		cl2.Item_Number__c='3232';
		cl2.Color__c='Yellow';
		cl2.Line_Total__c=200.00;
		cl2.Case_Number__c=c.Id;
		insert cl2;
		
		PageReference pageRef = new PageReference('apex/CloneCaseWithCaseLines' + 'id=' + c.Id);
        
        //Set the current test page to the Clone with related list visualforce page
        Test.setCurrentPage(pageRef);       
        
        //Instantiate the Controllers
        ApexPages.StandardController sc = new ApexPages.StandardController(c);
        CloneCaseWithCaseLineController cClone = new CloneCaseWithCaseLineController(sc);
        
        Test.startTest();
        cClone.cloneRecord();
        Test.stopTest();

	}
}