objects/Contact_Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CITY__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Addresses</relationshipLabel>
        <relationshipName>Contact_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Address</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Contact Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RHOppAddressSelectionControllerTest.cls
@isTest
public class RHOppAddressSelectionControllerTest {       
    
    static testMethod void myTest() {
        PrepareData.createGenericRHData();
        
        Contact_Address__c con = new Contact_Address__c();
        con.Contact__c=[SELECT id FROM Contact][0].id;
        con.Address_1__c='s';
        con.Address_2__c='d';
        con.State__c='d';
        con.CITY__c='ds';
        con.Zip__c='g';
        insert con;
        system.assertNotEquals(con.id, null);
        
        List<Contact_Address__c> conList= new  List<Contact_Address__c>();
        conList.add(con);
        
        RHOpportunityAddressSelectionController selectController= new RHOpportunityAddressSelectionController();
        PageReference pr= new PageReference('/apex/OpportunityAddressSelectionPage');                
        selectController.selectedRecordType= 'Design Atelier';
        selectController.selectedContactId=con.id;
        selectController.contactAdressList=conList;
        selectController.doCancel();
        selectController.getcontactAdressList();
        selectController.fillUrlParamters(pr,'a','b','c','d','e','k',conList,'f');
        selectController.generateUrl();
        selectController.getSelectedContactAddress();
       
    }
}