objects/Contact_Information__c.object
<CustomObject>
    <description>This table contains one record per contact point. A contact point is defined as a method for contacting the customer (examples include: Email, Phone, Social Handles).</description>
    <fields>
        <fullName>Contact_Information_Type__c</fullName>
        <label>Contact Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Business Phone</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Personal Email</fullName>
                </value>
                <value>
                    <fullName>Work Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Information</relationshipLabel>
        <relationshipName>Contact_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Information</label>
    <nameField>
        <label>Contact Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <recordTypes>
        <fullName>Fax</fullName>
        <active>true</active>
        <description>For fax contact information</description>
        <label>Fax</label>
    </recordTypes>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <description>For phone contact information</description>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactInformationFaxGroup.cls
/**
 * @description A child hierarchy group containing contact information records of 'Fax' record type
 */
public class ContactInformationFaxGroup extends ChildHierarchyGroupType {
    public static SObjectField PRIMARY_FLAG = Contact_Information__c.Is_Primary__c;
    public static SObjectField LOOKUP_FIELD = Contact_Information__c.Contact__c;
    public static String MULTIPLE_NEW_PRIMARIES_ERROR = 'There can only be one fax contact information record marked as primary';
    public static String REMOVE_ONLY_PRIMARY_ERROR = 'You cannot remove the only fax phone contact information record';
    public static List<String> ADDITIONAL_REQUIRED_FIELDS = new List<String> {
        Contact_Information__c.RecordTypeId.getDescribe().getName(), 
        Contact_Information__c.Contact_Information_Type__c.getDescribe().getName()
    };

    public ContactInformationFaxGroup() {
        primaryFlag = PRIMARY_FLAG;
        lookupField = LOOKUP_FIELD;
        multipleNewPrimariesError = MULTIPLE_NEW_PRIMARIES_ERROR;
        removeOnlyPrimaryError = REMOVE_ONLY_PRIMARY_ERROR;
        groupTypeId = ContactInformations.FAX_RECORD_TYPE_ID;
        additionalRequiredFields = ADDITIONAL_REQUIRED_FIELDS;
    }
    
    /**
     * @author John Rogers, Traction on Demand
     * @date        2016-02-23
     * @param       record : The record to check
     * @return True if the record can be a part of this group type, false otherwise.
     */
    public override Boolean belongsToGroupType(SObject record) {
        return record.get(Contact_Information__c.RecordTypeId) == ContactInformations.FAX_RECORD_TYPE_ID;
    }
}