objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Fraud_Warning__c</fullName>
        <formula>Account.Fraud_Warning__c = TRUE</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fraud Warning</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Address__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fraud_Warning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fraud Warning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sold_to_Company__c</fullName>
        <label>Sold To Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Customer_Number__c</fullName>
        <description>CW Sold to Cust Number</description>
        <label>Sold To Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <formula>Order__r.Account_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_1__c</fullName>
        <label>Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_2__c</fullName>
        <label>Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Company__c</fullName>
        <label>Ship to Company</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer_Number__c</fullName>
        <label>Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_to_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_to_First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Night_Phone__c</fullName>
        <label>Night Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>ATG_Profile_ID__c</fullName>
        <label>ATG Profile ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternative_Phone__c</fullName>
        <label>Alternative Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Apartment__c</fullName>
        <label>Apartment</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fraud_Warning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fraud Warning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Ready_For_Duplicate_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Ready For Duplicate Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <description>This field specifies the match type to be processed by Salesforce duplicate match</description>
        <label>Match Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type_Code__c</fullName>
        <label>Order Type Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Originating_Source_System__c</fullName>
        <label>Originating Source System</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Create_Date__c</fullName>
        <label>CW Customer Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Source_System_Last_Modified_Date__c</fullName>
        <label>CW Customer Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Source_System_View_CW_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System View CW Company</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Table_ID__c</fullName>
        <description>The ID of the table that spawned the record. This is for auditing trail</description>
        <label>Source_Table_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Table__c</fullName>
        <label>Source Table</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Add field history tracking</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Add field history tracking</description>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SSVLoader.cls
public with sharing class SSVLoader {
	private static final String SALESFORCE = 'Salesforce';
	private static final String SALESFORCE_ACCOUNT = 'Salesforce Account';
	private static final String SALESFORCE_PERSON_ACCOUNT = 'Salesforce Person Account';
	private static final String SALESFORCE_CONTACT = 'Salesforce Contact';
	private static final String COMPANY_ACCOUNT_PREFIX = 'SFDC-';
	private static final String BUSINESS_CONTACT_PREFIX = 'SFDC-';
	private static final String PERSON_ACCOUNT_PREFIX = 'SFDC PA-';
	private static final String CLIENT_TYPE = 'Employee';
	private static final String PROCESSING_STATUS = 'Waiting to Start';
	private static final Boolean IS_RDY_FOR_DUPE_CHECK = false;

	private @testVisible List<Source_System_View__c> records;

	private @testVisible Map<Integer, Source_System_View__c> companyRecordsMap {
		get {
			if (companyRecordsMap == null) companyRecordsMap = new Map<Integer, Source_System_View__c>();
			return companyRecordsMap;	
		}
		set;
	}

	public SSVLoader(List<Source_System_View__c> records) {
		this.records = records;
	}

	public SSVLoader createCompanyRecordsForCustomers() {

		Integer currentIndex = 0;
		for (Source_System_View__c ssv : records) {

			if (shouldCreateCompanyMatch(ssv)) {
				companyRecordsMap.put(currentIndex, createCompanyMatchSSV(ssv));
			}

			currentIndex++;
		}
		return this;
	}

	public SSVLoader linkCustomerRecordsToCompanyRecords() {

		for (Integer currentIndex : companyRecordsMap.keySet()) {
			records[currentIndex].Source_System_View_CW_Company__c = companyRecordsMap.get(currentIndex).Id;
		}
		return this;
	}

	public List<Source_System_View__c> getCompanyRecords() {
		return companyRecordsMap.values();
	}

	public static Boolean shouldCreateCompanyMatch(Source_System_View__c customerRecord) {

		return 
			(String.isNotEmpty(customerRecord.Cleansed_Company_Name__c) || String.isNotEmpty(customerRecord.Trade_ID__c)) 
			&&
			customerRecord.Match_Type__c == 'Contact' 
			&&
			customerRecord.Source_Table__c != 'Salesforce Contact';
	}

	public static Source_System_View__c createCompanyMatchSSV(Source_System_View__c customerRecord) {

		return new Source_System_View__c(
			Source_Table__c = 'CW Replicated Company',
			Match_Type__c = 'Company',
			EXT_Source_System_Customer_ID__c = customerRecord.EXT_Source_System_Customer_ID__c + 'C',
			Is_Ready_For_Duplicate_Check__c = false,
			Name = customerRecord.EXT_Source_System_Customer_ID__c + 'C',
			Source_System_Last_Modified_Date__c = customerRecord.Source_System_Last_Modified_Date__c,
			Originating_Source_System__c = customerRecord.Originating_Source_System__c,
			Company_Name__c = customerRecord.Company_Name__c, 
			Day_Phone__c = customerRecord.Day_Phone__c,
			Email__c = customerRecord.Email__c,
			Address_1__c = customerRecord.Address_1__c,
			Address_2__c =  customerRecord.Address_2__c,
			City__c = customerRecord.City__c,
			State__c = customerRecord.State__c,
			Zip__c = customerRecord.Zip__c,
			Country__c = customerRecord.Country__c,
			Source_System_Create_Date__c = DateTime.now(),
			Trade_ID__c = customerRecord.Trade_ID__c,
			Source_Table_ID__c = customerRecord.ID,
			Order_Type_Code__c = customerRecord.Order_Type_Code__c,
			Account__c = customerRecord.Account__c,
			Country_Code__c = customerRecord.Country_Code__c,
			Fraud_Warning__c = customerRecord.Fraud_Warning__c
		);
	}
	
	/**
	 * Create Source System View record given ship_to record
	 * @param  orderRecord Order record
	 * @param  mapSetting  Custom Setting of field mapping
	 * @return             new Source System View record
	 */
	 
	public static Source_System_View__c createSSV(Ship_To__c shipToRecord, 
											 	  List<SObject> mapSettings) {
											 	  	
		Source_System_View__c newSSV = new Source_System_View__c();
		FieldMapper.mapObject((SObject) shipToRecord, newSSV, mapSettings); 
		
		// Inline mapping (until I build the map settings)
		// TODO :: put all these mappings into Order_SSV_Field_Mapping__c
		
	   newSSV.Name = shipToRecord.Ship_to_Customer_Number__c;
	   newSSV.EXT_Source_System_Customer_ID__c = shipToRecord.Ship_to_Customer_Number__c;	
	  newSSV.Source_Table__c = 'CW Customer Ship To';				
	  newSSV.Account__c = NULL;									
	  newSSV.Contact__c = NULL;									
	  newSSV.First_Name__c = shipToRecord.Ship_to_First_Name__c;				
	  newSSV.Last_Name__c = shipToRecord.Ship_to_Last_Name__c;														
	  newSSV.Company_Name__c = shipToRecord.Ship_to_Company__c;				
	  newSSV.Apartment__c = NULL;
	  newSSV.Address_1__c = shipToRecord.Ship_To_Address_1__c;					
	  newSSV.Address_2__c = shipToRecord.Ship_to_Address_2__c;					
	  newSSV.City__c = shipToRecord.Ship_to_City__c;							
	  newSSV.State__c = shipToRecord.Ship_to_State__c;							
	  newSSV.Zip__c = shipToRecord.Ship_to_Zip__c;
	  newSSV.Country__c = shipToRecord.Ship_to_Country__c;								
	  newSSV.Country_Code__c = Utility.substring(shipToRecord.Ship_to_Country_Code__c, 0, 2); // or Ship_to_Country_Code__c 	         
	  newSSV.Email__c = shipToRecord.Ship_to_Email__c;							
	  newSSV.Day_Phone__c = shipToRecord.Ship_to_Day_Phone__c;					
	  newSSV.Alternative_Phone__c = shipToRecord.Ship_to_Night_Phone__c;								    
	  newSSV.ATG_Profile_ID__c = NULL;		
	  newSSV.Originating_Source_System__c = (shipToRecord.order__r.Order_Type_Code__c == 'W' || shipToRecord.order__r.Order_Type_Code__c == 'O') ? 'ATG' : 'CW'; 
	  newSSV.Source_Table_ID__c = shipToRecord.ID;	
	  newSSV.Source_System_Create_Date__c = DateTime.now();						

		return newSSV;													 	  	
	}	
	
	/**
	 * Create Source System View record given order record
	 * @param  orderRecord Order record
	 * @param  mapSetting  Custom Setting of field mapping
	 * @return             new Source System View record
	 */
	 
	public static Source_System_View__c createSSV(RH_Order__c orderRecord, 
											 	  List<SObject> mapSettings) {
														
		Source_System_View__c newSSV = new Source_System_View__c();
		FieldMapper.mapObject((SObject) orderRecord, newSSV, mapSettings); 
		
		// Inline mapping (until I build the map settings)
		// TODO :: put all these mappings into Order_SSV_Field_Mapping__c
		
		newSSV.Name = orderRecord.Sold_to_Customer_Number__c;
	  	newSSV.EXT_Source_System_Customer_ID__c = orderRecord.Sold_To_Customer_Number__c;	
	  	newSSV.Source_Table__c = 'CW Customer';
	  	newSSV.Account__c = orderRecord.Account_Sold_To__c;								
	  	newSSV.Contact__c = orderRecord.Contact_Sold_To__c;
      	newSSV.First_Name__c = orderRecord.Sold_to_First_Name__c;			
      	newSSV.Last_Name__c = orderRecord.Sold_to_Last_Name__c;
		newSSV.Company_Name__c = orderRecord.Sold_to_Company__c;       					
       	newSSV.Apartment__c = NULL;
      	newSSV.Address_1__c = orderRecord.Sold_To_Address_1__c;	
      	newSSV.Address_2__c = orderRecord.Sold_to_Address_2__c;	
      	newSSV.City__c = orderRecord.Sold_to_City__c;						
      	newSSV.State__c = orderRecord.Sold_to_State__c;						
      	newSSV.Zip__c = orderRecord.Sold_to_Zip__c;
      	newSSV.Country__c = orderRecord.Sold_to_Country__c;
      	newSSV.Country_Code__c = Utility.substring(orderRecord.Sold_to_Country_Code__c, 0, 2); // or Sold_to_Country_Code__c  							
	  	newSSV.Email__c = orderRecord.Sold_to_Email__c;						
      	newSSV.Day_Phone__c = Utility.stripNonAlphanumericCharacters(orderRecord.Sold_to_Day_Phone__c); // clean all phone numbers coming in so stored 				
      	newSSV.Alternative_Phone__c = Utility.stripNonAlphanumericCharacters(orderRecord.Sold_to_Night_Phone__c); // clean all phone numbers coming in			
       	newSSV.Source_System_Last_Modified_Date__c = orderRecord.Order_Date__c;				
	  	newSSV.ATG_Profile_ID__c = orderRecord.ATG_Account_ID__c;
		// newSSV.Is_RH_Employee__c = orderRecord.Order_Type_Code__c == 'E' ? true : false;
	  	newSSV.Membership_Number__c = orderRecord.Membership_ID__c;
	  	newSSV.Originating_Source_System__c = (orderRecord.Order_Type_Code__c == 'W' || orderRecord.Order_Type_Code__c == 'O') ? 'ATG' : 'CW';
	  	// newSSV.Last_Order_Number = orderRecord.EXT_Order_Number__c;
	  	newSSV.Source_Table_ID__c = orderRecord.ID;
	  	newSSV.Trade_ID__c = orderRecord.Trade_ID__c;
	  	newSSV.Order_Type_Code__c = orderRecord.Order_Type_Code__c;
	  	newSSV.Fraud_Warning__c = orderRecord.Fraud_Warning__c;
	  	newSSV.Source_System_Create_Date__c = DateTime.now();
	  	 				
		// Mapping not handled by field mapper (done inline, no reason to split out)
		
		return newSSV;
	}	

	/**
	 * Create Source System View record given parent record
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-27
	 * @param  accountRecord Company/Person Account record
	 * @param  mapSetting    Custom Setting of field mapping
	 * @return               new Source System View record
	 */
	public static Source_System_View__c createSSV(Contact contactRecord, 
													List<SObject> mapSettings, 
													Customer_Address__c relatedContactCustomerAddress, 
													Account relatedAccount,
													Source_System_View__c relatedAccountSSV) {
														
		Source_System_View__c newSSV = new Source_System_View__c();
		newSSV.Source_Table_ID__c = contactRecord.ID;
		newSSV.Source_System_Create_Date__c = DateTime.now();
		newSSV.Membership_Number__c = contactRecord.Membership_ID__c;
		newSSV.Trade_ID__c = (relatedAccount == null) ? null : relatedAccount.X12_Digit_Member__c;
		
		FieldMapper.mapObject((SObject) contactRecord, newSSV, mapSettings); 

		// Mapping not handled by field mapper
		businessContactMapping(contactRecord, newSSV, relatedContactCustomerAddress, relatedAccount, relatedAccountSSV);

		return newSSV;
	}

	/**
	 * Update existing Source System View record given parent record
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-27
	 * @param  accountRecord Company/Person Account record
	 * @param  mapSetting    Custom Setting of field mapping
	 * @return               new Source System View record
	 */
	public static void updateSSV(Contact contactRecord, 
								Source_System_View__c ssv, 
								List<SObject> mapSettings, 
								Customer_Address__c relatedContactCustomerAddress, 
								Account relatedAccount,
								Source_System_View__c relatedAccountSSV) {
									
		FieldMapper.mapObject((SObject) contactRecord, ssv, mapSettings); 

		// Mapping not handled by field mapper
		businessContactMapping(contactRecord, ssv, relatedContactCustomerAddress, relatedAccount, relatedAccountSSV);
	}

	/**
	 * Create Source System View record given parent record
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-27
	 * @param  accountRecord Company/Person Account record
	 * @param  mapSetting    Custom Setting of field mapping
	 * @return               new Source System View record
	 */
	public static Source_System_View__c createSSV(Account accountRecord, List<SObject> mapSettings, Customer_Address__c relatedContactCustomerAddress) {
		
		Source_System_View__c newSSV = new Source_System_View__c();
		newSSV.Source_Table_ID__c = accountRecord.ID;
		newSSV.Source_System_Create_Date__c = DateTime.now();
		newSSV.Membership_Number__c = accountRecord.Membership_ID__pc;
		newSSV.Trade_ID__c = accountRecord.X12_Digit_Member__c;
				
		FieldMapper.mapObject((SObject) accountRecord, newSSV, mapSettings); 

		if(accountRecord.IsPersonAccount) {
			personAccountMapping(accountRecord, newSSV, relatedContactCustomerAddress);
		} else {
			companyAccountMapping(accountRecord, newSSV);
		}
		return newSSV;
	}

	/**
	 * Update existing Source System View record given parent record
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-27
	 * @param  accountRecord Company/Person Account record
	 * @param  mapSetting    Custom Setting of field mapping
	 * @return               new Source System View record
	 */
	public static void updateSSV(Account accountRecord, Source_System_View__c ssv, List<SObject> mapSettings, Customer_Address__c relatedContactCustomerAddress) {
		
		FieldMapper.mapObject((SObject) accountRecord, ssv, mapSettings); 

		if(accountRecord.IsPersonAccount) {
			personAccountMapping(accountRecord, ssv, relatedContactCustomerAddress);
		} else {
			companyAccountMapping(accountRecord, ssv);
		}
	}

	/**
	 * Specific field mapping that field mapper doesn't handle
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-29
	 * @param  companyRecord Company Account
	 * @param  ssvRecord     SSV
	 */
	private static void businessContactMapping(Contact contactRecord, 
												Source_System_View__c ssvRecord, 
												Customer_Address__c relatedContactCustomerAddress, 
												Account relatedAccount,
												Source_System_View__c relatedAccountSSV) {
		if (ssvRecord == null) return;

		ssvRecord.Name = BUSINESS_CONTACT_PREFIX + ssvRecord.Name;
		ssvRecord.EXT_Source_System_Customer_ID__c = BUSINESS_CONTACT_PREFIX + ssvRecord.EXT_Source_System_Customer_ID__c;
		ssvRecord.Source_Table__c = SALESFORCE_CONTACT;
		ssvRecord.Originating_Source_System__c = SALESFORCE;
		// ssvRecord.Is_Ready_For_Duplicate_Check__c = IS_RDY_FOR_DUPE_CHECK;
		// ssvRecord.Processing_Status__c = PROCESSING_STATUS;
		ssvRecord.Company_Name__c = (relatedAccount != null) ? relatedAccount.Name : null;
		ssvRecord.Source_System_Last_Modified_Date__c = contactRecord.LastModifiedDate;
		ssvRecord.Customer_Address__c = (relatedContactCustomerAddress != null) ? relatedContactCustomerAddress.Id : null;
		ssvRecord.Source_System_View_CW_Company__c = (relatedAccountSSV != null) ? relatedAccountSSV.Id : null;
		
		if (contactRecord != null) parseAddress(contactRecord.MailingStreet, ssvRecord);
	}

	/**
	 * Specific field mapping that field mapper doesn't handle
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-29
	 * @param  companyRecord Company Account
	 * @param  ssvRecord     SSV
	 */
	private static void companyAccountMapping(Account companyRecord, Source_System_View__c ssvRecord) {
		if (ssvRecord == null) return;

		ssvRecord.Name = COMPANY_ACCOUNT_PREFIX + ssvRecord.Name;
		ssvRecord.EXT_Source_System_Customer_ID__c = COMPANY_ACCOUNT_PREFIX + ssvRecord.EXT_Source_System_Customer_ID__c;
		ssvRecord.Source_Table__c = SALESFORCE_ACCOUNT;
		ssvRecord.Originating_Source_System__c = SALESFORCE;
		// ssvRecord.Is_Ready_For_Duplicate_Check__c = IS_RDY_FOR_DUPE_CHECK;
		// ssvRecord.Processing_Status__c = PROCESSING_STATUS;
		ssvRecord.Source_System_Last_Modified_Date__c = companyRecord.LastModifiedDate;

		if (companyRecord != null) parseAddress(companyRecord.BillingStreet, ssvRecord);
	}

	/**
	 * Specific field mapping that field mapper doesn't handle
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-29
	 * @param  personRecord Person Account
	 * @param  ssvRecord     SSV
	 */
	private static void personAccountMapping(Account personRecord, Source_System_View__c ssvRecord, Customer_Address__c relatedCustomerAddress) {

		if (ssvRecord == null) return;

		ssvRecord.Name = PERSON_ACCOUNT_PREFIX + ssvRecord.Name;
		ssvRecord.EXT_Source_System_Customer_ID__c = PERSON_ACCOUNT_PREFIX + ssvRecord.EXT_Source_System_Customer_ID__c;
		ssvRecord.Source_Table__c = SALESFORCE_PERSON_ACCOUNT;
		ssvRecord.Originating_Source_System__c = SALESFORCE;
		// ssvRecord.Is_Ready_For_Duplicate_Check__c = IS_RDY_FOR_DUPE_CHECK;
		// ssvRecord.Processing_Status__c = PROCESSING_STATUS;
		ssvRecord.Customer_Address__c = (relatedCustomerAddress != null) ? relatedCustomerAddress.Id : null;
		ssvRecord.Source_System_Last_Modified_Date__c = personRecord.LastModifiedDate;

		if (personRecord != null) parseAddress(personRecord.PersonMailingStreet, ssvRecord);
	}

	/**
	 * Parse address field on first line break, assign to 2 Address fields on SSV record
	 * @author Zi Zhang, Traction on Demand
	 * @date   2016-02-29
	 * @param  streetAddress String of street addres with line breaks
	 * @param  ssvRecord     SSV record
	 */
	private static void parseAddress(String streetAddress, Source_System_View__c ssvRecord) {
		if(String.isNotEmpty(streetAddress)) {
			String[] result = streetAddress.split('\r\n', 2);
			ssvRecord.Address_1__c = result[0];
			if(result.size() == 2) {
				ssvRecord.Address_2__c = result[1];
			}
		}
	}
}