objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Order.</description>
        <label>Customer Address Sold To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System_View_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV process has run to determine whether this Order should be linked to an existing SSV or if a new SSV needs to be created.</description>
        <label>Source System View Sold To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Ship To should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Ship Tos are linked to the incorrect Business or Person Account record.</description>
        <label>Account Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <formula>Order__r.Account_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CW_Customer_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CW Customer Ship To</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Ship Tos (CW Customer Ship To)</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the Account record has been completed. For Person Accounts, this field will be updated with the Customer Address record associated to this Ship To.</description>
        <label>Customer Address Ship To</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Customer_Number__c</fullName>
        <label>Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Ship_Tos.cls
/**
 * @description Domain class for Ship_To__c object. 
 *  Handles all functionality for its respective object,
 *  deferring complex implementations to helper classes.
 * @author John Rogers, Traction on Demand
 * @date 17-02-2016
 */
public class Ship_Tos extends SObjectDomain {

    public Ship_Tos() {
        super();
    }

    /**
     *  @description Constructor, casts given records to appropiate type
     *  @author      Ernesto Valdes, Traction on Demand.
     *  @date        2015-11-03
     *  @param       records       List of sObjects (should be of type Ship_To__c)
     */
    public Ship_Tos(List<Ship_To__c> records) {
        super();
        this.records = records;
    }

    public override void handleBeforeInsert() {
    	if (!UserHelper.isIntegrationUser()) {
        	setLookups(records);
    	}
    }

    public override void handleBeforeUpdate(Map<Id, SObject> oldRecordMap) {
    	if (!UserHelper.isIntegrationUser()) {
	        List<Ship_To__c> updateLookups = new List<Ship_To__c>();
	        for (Ship_To__c shipTo : (List<Ship_To__c>) records) {
	            Ship_To__c oldShipTo = (Ship_To__c) oldRecordMap.get(shipTo.Id);
	            // If Ship_To_Customer_Number__c changes
	            if (oldShipTo.Ship_To_Customer_Number__c != shipTo.Ship_To_Customer_Number__c) {
	                // Update lookups
	                updateLookups.add(shipTo);
	            }
	        }
	        setLookups(updateLookups);
    	}
    }   

    /**
     * @description Given a list of ship to records set the SSV lookup and related lookup values
     * @author John Rogers, Traction on Demand
     * @date 2016-02-18
     * @param shipTos : The ship to records to update the lookups for 
     */
    private void setLookups(List<Ship_To__c> shipTos) {
        // If Ship_To_Customer_Number__c is zero set CW_Customer_Ship_To__c to parent order lookup (ship to = sold to)
        List<Ship_To__c> shipToOrder = new List<Ship_To__c>();

        /* 
           If Ship_To_Customer_Number__c is non-zero set lookups by Ship_To_Customer_Number__c
           If Ship_To_Customer_Number__c is null AND the CW_Customer_Ship_To__c is non null set lookups by CW_Customer_Ship_To__c
           (ship to != sold to)
        */
        List<Ship_To__c> shipToSsv = new List<Ship_To__c>();

        // Sort the shipTo records
        for (Ship_To__c shipTo : (List<Ship_To__c>) shipTos) {
            if (shipTo.Ship_To_Customer_Number__c == '0') {
                shipToOrder.add(shipTo);
            } else if (shipTo.Ship_To_Customer_Number__c != '0' && shipTo.Ship_To_Customer_Number__c != null) {
                shipToSsv.add(shipTo);
            }
        }

        // Set the CW_Customer_Ship_To__c and other lookups appropriately
        setLookupsByOrder(shipToOrder);
        setLookupsBySSV(shipToSsv);
    }

    /**
     * @description Given a list of shipTos, sets the lookups to the parent
     *              order's lookup values
     * @author John Rogers, Traction on Demand
     * @date        2016-02-18
     * @param       shipTos : shipTo records to set the lookups on
     */
    private void setLookupsByOrder(List<Ship_To__c> shipTos) {
        if (shipTos.isEmpty()) {
            return;
        }

        Set<Id> orderIds = ListUtils.collectIds(shipTos, Ship_To__c.Order__c);

        if (orderIds.isEmpty()) {
            return;
        }

        Map<Id, RH_Order__c> orders = new Map<Id, RH_Order__c>([
            SELECT Source_System_View_Sold_To__c,
                Account_Sold_To__c,
                Contact_Sold_To__c,
                Customer_Address_Sold_To__c
            FROM RH_Order__c
            WHERE Id IN :orderIds
        ]);

        for (Ship_To__c shipTo : shipTos) {
            RH_Order__c parent = orders.get(shipTo.Order__c);
            if (parent != null) {
                shipTo.CW_Customer_Ship_To__c = parent.Source_System_View_Sold_To__c;
                shipTo.Account_Ship_To__c = parent.Account_Sold_To__c;
                shipTo.Contact_Ship_To__c = parent.Contact_Sold_To__c;
                shipTo.Customer_Address_Ship_To__c = parent.Customer_Address_Sold_To__c;
            }
        }
    }

    /**
     * @description Given a list of shipTos, sets lookups by the SSV record 
     *              SSV.EXT_Source_System_Customer_ID__c = shipTo.Ship_To_Customer_Number__c or
     *              if Ship_To_Customer_Number__c is null, sets lookups by the SSV record
     *              SSV.Id = shipTo.CW_Customer_Ship_To__c
     * @author John Rogers, Traction on Demand
     * @date        2016-02-18
     * @param       shipTos : shipTo records to set the lookups on
     */
    private void setLookupsBySSV(List<Ship_To__c> shipTos) {
        // Collect Ship_To_Customer_Number__c values
        Set<String> custNums = new Set<String>();
        for (Ship_To__c shipTo : shipTos) {
            if (!String.isBlank(shipTo.Ship_To_Customer_Number__c)) {
                custNums.add(shipTo.Ship_To_Customer_Number__c);
            }
        }

        if (custNums.isEmpty()) {
            return;
        }

        // Get related SSV records
        List<Source_System_View__c> ssvs = [
            SELECT EXT_Source_System_Customer_ID__c,
                Account__c,
                Contact__c,
                Customer_Address__c
            FROM Source_System_View__c
            WHERE EXT_Source_System_Customer_ID__c IN :custNums
        ];

        setShipToLookupsFromSSV(shipTos, ssvs);
    }

    public static void setShipToLookupsFromSSV(List<Ship_To__c> shipTos,
                                                List<Source_System_View__c> ssvs) {

        Map<String, Source_System_View__c> custNumToSSV = new Map<String, Source_System_View__c>();
        MapUtils.mapByField(custNumToSSV, ssvs, Source_System_View__c.EXT_Source_System_Customer_ID__c);

        for (Ship_To__c shipTo : shipTos) {
            Source_System_View__c ssv = custNumToSSV.get(shipTo.Ship_To_Customer_Number__c);

            if (ssv != null) {
                shipTo.CW_Customer_Ship_To__c = ssv.Id;
                shipTo.Account_Ship_To__c = ssv.Account__c;
                shipTo.Contact_Ship_To__c = ssv.Contact__c;
                shipTo.Customer_Address_Ship_To__c = ssv.Customer_Address__c;
            }
        }
    }
}