objects/Customer_Address__c.object
<CustomObject>
    <description>This table links customers (accounts or people) with their relevant addresses</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Addresses</relationshipLabel>
        <relationshipName>Customer_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Address__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Customer Address</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key_Hash__c</fullName>
        <description>SHA-512 Base64 Encoded version of Address Match Key for indexing and comparison purposes.</description>
        <externalId>true</externalId>
        <label>Address Match Key Hash</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Match_Key__c</fullName>
        <description>Consolidation of address1, address2, city, state,country for matching purposes (some additional analysis required). Punctuation &amp; space removal, upper case</description>
        <label>Address Match Key</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternative_Phone__c</fullName>
        <label>Alternative Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_First_Name__c</fullName>
        <label>Cleansed First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Last_Name__c</fullName>
        <label>Cleansed Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Address</label>
        <referenceTo>Customer_Address__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Phone_Match_Key__c</fullName>
        <description>Phone for matching purposes -- removes bad phone etc</description>
        <label>Day Phone Match Key</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXT_Source_System_Customer_ID__c</fullName>
        <description>External Key Unique -- key used by integration</description>
        <externalId>true</externalId>
        <label>EXT Source System Customer ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email_Match_Key__c</fullName>
        <label>Email Match Key</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fraud_Warning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fraud Warning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Ready_For_Duplicate_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Ready For Duplicate Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Record_Score__c</fullName>
        <description>This score is a key part of the matching process. 
When multiple candidate records can be consolidated into one record, this score determines which record will be the Master (the name, address, phone etc for the spawned customer is taken from the Master record). 
The score is designed to ensure:
1. Define the order of entry of new Candidate records into the process
- There is a final addition for match type = company to ensure company records are processed prior to any associated contact records
2. Ensure Salesforce records always outscore other external system records</description>
        <formula>/* This section determines the highest value Salesforce record as Salesforce records always end up as the master over external system records */
If(Source_System__c=&quot;Salesforce&quot;,100000000,0) +
If(Contact__r.Tier_Name__c=&quot;Top Tier&quot;,100000,0) +
If(Contact__r.Tier_Name__c =&quot;Tier 2&quot;,50000,0) +
If(Contact__r.Tier_Name__c =&quot;Tier 3&quot;,25000,0) +
(Date(1970,01,01)-BLANKVALUE(DateValue(If(Match_Type__c = &quot;Company&quot;, Account__r.CreatedDate,  
                                                Contact__r.CreatedDate)),Date(1970,01,01)))/10000 +

/* This section calculates the master record score for non Salesforce records */
If( DateValue(Source_System_Last_Modified_Date__c) &gt; Today()-730,10000,0) +
If( Originating_Source_System__c = &quot;ATG&quot;,5000,0) +
(BLANKVALUE(DateValue(Source_System_Last_Modified_Date__c),Date(1970,01,01)) - Date(1970,01,01))/10000 +

/* this next line ensures company records are always processed prior to any associated contacts */
/* Because company records are only ever consolidated to the same match type, the score does not impact &quot;within company match&quot; selections */
If(Match_Type__c = &quot;Company&quot;,200000,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Record Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <description>This field specifies the match type to be processed by Salesforce duplicate match</description>
        <label>Match Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Number__c</fullName>
        <label>Membership Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Ready_Time__c</fullName>
        <label>Processing Ready Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting to Start</fullName>
                    <default>true</default>
                    <label>Waiting to Start</label>
                </value>
                <value>
                    <fullName>Ready for Match Step</fullName>
                </value>
                <value>
                    <fullName>Ready for Order Linking</fullName>
                </value>
                <value>
                    <fullName>Processing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System_View_CW_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source System View CW Company</label>
        <referenceTo>Source_System_View__c</referenceTo>
        <relationshipLabel>Source System Views</relationshipLabel>
        <relationshipName>Source_System_Views</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Add field history tracking</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Add field history tracking</description>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SSVSelector.cls
/**
 *  SSVSelector.cls
 *  @description Selector class for Source System View
 *               Provides the ability to centralize and reuse queries
 *  @author Ernesto Valdes, Traction On Demand
 */
public with sharing class SSVSelector {

	public static String PROCESSING_STATUS_READY = 'Ready for Match Step';
	public static String PROCESSING_ORDER_LINK_READY = 'Ready for Order Linking';
	public static String PROCESSING_STATUS_COMPLETE = 'Processing Complete';

	private static Set<Schema.SObjectField> fields = new Set<Schema.SObjectField>{
		Source_System_View__c.Id,
		Source_System_View__c.Duplicate_Set_ID__c,
		Source_System_View__c.Is_Ready_For_Duplicate_Check__c,
		Source_System_View__c.Processing_Status__c,
		Source_System_View__c.Processing_Ready_Time__c,
		Source_System_View__c.EXT_Source_System_Customer_ID__c,
		Source_System_View__c.Source_System_View_CW_Company__c,
		Source_System_View__c.Account__c,
		Source_System_View__c.Contact__c,
		Source_System_View__c.Customer_Address__c,
		Source_System_View__c.Company_Name__c,
		Source_System_View__c.First_Name__c,
		Source_System_View__c.Last_Name__c,
		Source_System_View__c.Email__c,
		Source_System_View__c.Day_Phone__c,
		Source_System_View__c.Alternative_Phone__c,
		Source_System_View__c.Address_1__c,
		Source_System_View__c.Address_2__c,
		Source_System_View__c.City__c,
		Source_System_View__c.State__c,
		Source_System_View__c.Zip__c,
		Source_System_View__c.Country__c,
		Source_System_View__c.Country_Code__c,
		Source_System_View__c.Cleansed_First_Name__c,
		Source_System_View__c.Cleansed_Last_Name__c,
		Source_System_View__c.Cleansed_Company_Name__c,
		Source_System_View__c.Email_Match_Key__c,
		Source_System_View__c.Day_Phone_Match_Key__c,
		Source_System_View__c.Address_Match_Key__c,
		Source_System_View__c.Address_Match_Key_Hash__c,
		Source_System_View__c.Match_Type__c,
		Source_System_View__c.Master_Record_Score__c,
		Source_System_View__c.Trade_ID__c,
		Source_System_View__c.Membership_Number__c,
		Source_System_View__c.Fraud_Warning__c		
	};
	
	public static List<String> getFields() {
		List<String> fieldList = new List<String>();
		for (Schema.SObjectField field : fields) {
			fieldList.add(String.valueOf(field));
		}
		return fieldList;		
	}

	public static List<String> getFieldList() {
		List<String> fieldList = getFields();
		fieldList.add('Source_System_View_CW_Company__r.Duplicate_Set_ID__c');
		fieldList.add('Source_System_View_CW_Company__r.Account__c');
		fieldList.add('Account__r.RecordTypeId');
		return fieldList;
	}
	
    public static String getBatchSyncQuery(Integer batchLimit, Datetime processingReadyTime) {

        String query = String.format('SELECT {0} ' 
                                    + 'FROM Source_System_View__c '
                                    + 'WHERE Processing_Ready_Time__c < {1} '
                                    + 'AND Is_Ready_For_Duplicate_Check__c = true '                                    
                                    + 'AND Processing_Status__c = :PROCESSING_STATUS_READY '
                                    + 'ORDER BY Master_Record_Score__c DESC '
                                    + ((batchLimit != null) ? ('LIMIT ' + batchLimit) : '')
                                , new List<String> {
                                    String.join(getFieldList(), ', '),
                                    processingReadyTime.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                                });

        return query;
    }

	public static List<Source_System_View__c> getExistingSSVByDuplicateSetId(Set<String> duplicateSetIds) {

		String query = String.format('SELECT {0} ' 
									+ ' FROM Source_System_View__c '
									+ ' WHERE Duplicate_Set_ID__c IN :duplicateSetIds '
									+ ' AND (Processing_Status__c = :PROCESSING_STATUS_COMPLETE '
									+ '		OR Processing_Status__c = :PROCESSING_ORDER_LINK_READY) '
									+ ' AND Is_Ready_For_Duplicate_Check__c = true '
									+ ' ORDER BY Master_Record_Score__c DESC'
								, new List<String> {String.join(getFieldList(), ', ')});

		return Database.query(query);

	}

	public static List<Source_System_View__c> getSSVsByDuplicateSetIdAndExcludeRecordIds(
		Set<String> duplicateSetIds,
		Set<Id> excludedRecordIds) {

		// exclude following to improve performance
		// + ' AND (Account__c != null OR Contact__c != null)'
		
		String query = String.format('SELECT {0} ' 
									+ ' FROM Source_System_View__c '
									+ ' WHERE Duplicate_Set_ID__c IN :duplicateSetIds '
									+ ' AND (Processing_Status__c = :PROCESSING_STATUS_COMPLETE '
									+ '		OR Processing_Status__c = :PROCESSING_ORDER_LINK_READY) '
									+ ' AND Is_Ready_For_Duplicate_Check__c = true '
									+ ' AND Id NOT IN :excludedRecordIds'									
									+ ' ORDER BY Master_Record_Score__c DESC'
								, new List<String> {String.join(getFieldList(), ', ')});

		return Database.query(query);

	}

	public static List<Source_System_View__c> getSSVsById(Set<Id> recordIds) {

		String query = String.format('SELECT {0} ' 
									+ 'FROM Source_System_View__c '
									+ 'WHERE Id IN :recordIds'
								, new List<String> {String.join(getFieldList(), ', ')});

		return Database.query(query);
	}


	public static List<Source_System_View__c> getSSVsByConsolidationKey(Set<String> keys, Set<Id> excludedRecordIds) {

		String query = String.format('SELECT {0} ' 
									+ 'FROM Source_System_View__c '
									+ 'WHERE Duplicate_Set_ID__c IN :keys'
									+ 'AND Id NOT IN :excludedRecordIds'
								, new List<String> {String.join(getFieldList(), ', ')});

		return Database.query(query);
	}
}