objects/CW_Invoice__x.object
<CustomObject>
    <description>CW Invoice</description>
    <externalDataSource>CWConnection</externalDataSource>
    <externalName>CW Invoice</externalName>
    <fields>
        <fullName>Additional_Charge_Amount_IST__c</fullName>
        <description>Additional Charge Amount (IST)</description>
        <externalDeveloperName>Additional Charge Amount (IST)</externalDeveloperName>
        <label>Additional Charge Amount (IST)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Additional_Freight_Amount_IST__c</fullName>
        <description>Additional Freight Amount (IST)</description>
        <externalDeveloperName>Additional Freight Amount (IST)</externalDeveloperName>
        <label>Additional Freight Amount (IST)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOM_Component_Sequence__c</fullName>
        <description>BOM Component Sequence</description>
        <externalDeveloperName>BOM Component Sequence</externalDeveloperName>
        <label>BOM Component Sequence</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOM_Header_Flag__c</fullName>
        <description>BOM Header Flag</description>
        <externalDeveloperName>BOM Header Flag</externalDeveloperName>
        <label>BOM Header Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Code__c</fullName>
        <description>Color Code</description>
        <externalDeveloperName>Color Code</externalDeveloperName>
        <label>Color Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <description>Company</description>
        <externalDeveloperName>Company</externalDeveloperName>
        <label>Company</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <description>Credit Card Number</description>
        <externalDeveloperName>Credit Card Number</externalDeveloperName>
        <label>Credit Card Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Shipped__c</fullName>
        <description>Date Shipped</description>
        <externalDeveloperName>Date Shipped</externalDeveloperName>
        <label>Date Shipped</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Amount_IL__c</fullName>
        <description>Freight Amount (IL)</description>
        <externalDeveloperName>Freight Amount (IL)</externalDeveloperName>
        <label>Freight Amount (IL)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Freight_Amount_IST__c</fullName>
        <description>Freight Amount (IST)</description>
        <externalDeveloperName>Freight Amount (IST)</externalDeveloperName>
        <label>Freight Amount (IST)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GST_Amount_IL__c</fullName>
        <description>GST Amount (IL)</description>
        <externalDeveloperName>GST Amount (IL)</externalDeveloperName>
        <label>GST Amount (IL)</label>
        <precision>10</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GST_Amount_IST__c</fullName>
        <description>GST Amount (IST)</description>
        <externalDeveloperName>GST Amount (IST)</externalDeveloperName>
        <label>GST Amount (IST)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Handling_Amount_IL__c</fullName>
        <description>Handling Amount (IL)</description>
        <externalDeveloperName>Handling Amount (IL)</externalDeveloperName>
        <label>Handling Amount (IL)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Handling_Amount_IST__c</fullName>
        <description>Handling Amount (IST)</description>
        <externalDeveloperName>Handling Amount (IST)</externalDeveloperName>
        <label>Handling Amount (IST)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <description>Invoice Date</description>
        <externalDeveloperName>Invoice Date</externalDeveloperName>
        <label>Invoice Date</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Number__c</fullName>
        <description>Invoice Line Number</description>
        <externalDeveloperName>Invoice Line Number</externalDeveloperName>
        <label>Invoice Line Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <description>Invoice Number</description>
        <externalDeveloperName>Invoice Number</externalDeveloperName>
        <label>Invoice Number</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Order_Line_Sequence_Number__c</fullName>
        <description>Invoice Order Line Sequence Number</description>
        <externalDeveloperName>Invoice Order Line Sequence Number</externalDeveloperName>
        <label>Invoice Order Line Sequence Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <description>Invoice Type</description>
        <externalDeveloperName>Invoice Type</externalDeveloperName>
        <label>Invoice Type</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <description>Item Number</description>
        <externalDeveloperName>Item Number</externalDeveloperName>
        <label>Item Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchandise_Amount_IST__c</fullName>
        <description>Merchandise Amount (IST)</description>
        <externalDeveloperName>Merchandise Amount (IST)</externalDeveloperName>
        <label>Merchandise Amount (IST)</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Merchandise_Unit_Price_IL__c</fullName>
        <description>Merchandise Unit Price (IL)</description>
        <externalDeveloperName>Merchandise Unit Price (IL)</externalDeveloperName>
        <label>Merchandise Unit Price (IL)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Level_Freight_Tax__c</fullName>
        <description>Order Level Freight Tax</description>
        <externalDeveloperName>Order Level Freight Tax</externalDeveloperName>
        <label>Order Level Freight Tax</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Number</description>
        <externalDeveloperName>Order Number</externalDeveloperName>
        <label>Order Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Payment_Sequence_Number__c</fullName>
        <description>Order Payment Sequence Number</description>
        <externalDeveloperName>Order Payment Sequence Number</externalDeveloperName>
        <label>Order Payment Sequence Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PST_Amount_IL__c</fullName>
        <description>PST Amount (IL)</description>
        <externalDeveloperName>PST Amount (IL)</externalDeveloperName>
        <label>PST Amount (IL)</label>
        <precision>10</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PST_Amount_IST__c</fullName>
        <description>PST Amount (IST)</description>
        <externalDeveloperName>PST Amount (IST)</externalDeveloperName>
        <label>PST Amount (IST)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Additional_Charge_Amount__c</fullName>
        <description>Payment Additional Charge Amount</description>
        <externalDeveloperName>Payment Additional Charge Amount</externalDeveloperName>
        <label>Payment Additional Charge Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Additional_Freight_Amount__c</fullName>
        <description>Payment Additional Freight Amount</description>
        <externalDeveloperName>Payment Additional Freight Amount</externalDeveloperName>
        <label>Payment Additional Freight Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Category_Description__c</fullName>
        <description>Payment Category Description</description>
        <externalDeveloperName>Payment Category Description</externalDeveloperName>
        <label>Payment Category Description</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Category__c</fullName>
        <description>Payment Category</description>
        <externalDeveloperName>Payment Category</externalDeveloperName>
        <label>Payment Category</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Freight_Amount__c</fullName>
        <description>Payment Freight Amount</description>
        <externalDeveloperName>Payment Freight Amount</externalDeveloperName>
        <label>Payment Freight Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_GST_Amount__c</fullName>
        <description>Payment GST Amount</description>
        <externalDeveloperName>Payment GST Amount</externalDeveloperName>
        <label>Payment GST Amount</label>
        <precision>10</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Handling_Amount__c</fullName>
        <description>Payment Handling Amount</description>
        <externalDeveloperName>Payment Handling Amount</externalDeveloperName>
        <label>Payment Handling Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Merchandise_Amount__c</fullName>
        <description>Payment Merchandise Amount</description>
        <externalDeveloperName>Payment Merchandise Amount</externalDeveloperName>
        <label>Payment Merchandise Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_PST_Amount__c</fullName>
        <description>Payment PST Amount</description>
        <externalDeveloperName>Payment PST Amount</externalDeveloperName>
        <label>Payment PST Amount</label>
        <precision>10</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Tax_Amount__c</fullName>
        <description>Payment Tax Amount</description>
        <externalDeveloperName>Payment Tax Amount</externalDeveloperName>
        <label>Payment Tax Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Type_Description__c</fullName>
        <description>Payment Type Description</description>
        <externalDeveloperName>Payment Type Description</externalDeveloperName>
        <label>Payment Type Description</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type</description>
        <externalDeveloperName>Payment Type</externalDeveloperName>
        <label>Payment Type</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pre_Bill_Color_Code__c</fullName>
        <description>Pre Bill Color Code</description>
        <externalDeveloperName>Pre Bill Color Code</externalDeveloperName>
        <label>Pre Bill Color Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Bill_Item_Number__c</fullName>
        <description>Pre Bill Item Number</description>
        <externalDeveloperName>Pre Bill Item Number</externalDeveloperName>
        <label>Pre Bill Item Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>CW Invoice</label>
    <pluralLabel>CW Invoice</pluralLabel>
</CustomObject>

objects/CW_Order_Note__x.object
<CustomObject>
    <description>CW Order Note</description>
    <externalDataSource>CWConnection</externalDataSource>
    <externalName>CW Order Note</externalName>
    <fields>
        <fullName>Company__c</fullName>
        <description>Company</description>
        <externalDeveloperName>Company</externalDeveloperName>
        <label>Company</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date</description>
        <externalDeveloperName>Date</externalDeveloperName>
        <label>Date</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Number</description>
        <externalDeveloperName>Order Number</externalDeveloperName>
        <label>Order Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Sequence Number</description>
        <externalDeveloperName>Sequence Number</externalDeveloperName>
        <label>Sequence Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CW Order Note</label>
    <pluralLabel>CW Order Note</pluralLabel>
</CustomObject>

classes/CWConnection.cls
public with sharing class CWConnection {
    
    /*
     *  Methods to work with the CWConnection external data source.
     *
     */
    
    // Return a List of all Invoices for a given Order Number.  
    // Each Invoice row will contain all fields of the external object.
    public static List<CW_Invoice__x> getCWInvoiceAllFields(String orderNumber) {
        // Get all the object field names and build the query
        String query = 'SELECT';
        Map<String,Schema.SObjectField> FieldMap = Schema.SObjectType.CW_Invoice__x.fields.getMap();
        
        //system.debug('***** number of fields = ' + FieldMap.size());
        
        for (Schema.SObjectField f : FieldMap.values()) {
            //Schema.DescribeFieldResult DescField = f.getDescribe();
            //system.debug('Name: ' +  DescField.getName());
            //system.debug('Type: ' +  DescField.getType());
            query += ' ' + f.getDescribe().getName() + ',';
        }
        query = query.removeEnd(',');
        query += ' FROM CW_Invoice__x WHERE Order_Number__c = \'' + orderNumber + '\'';
        
        //system.debug('***** query string = ' + query); 
        
        List<CW_Invoice__x> cwInvoices = new List<CW_Invoice__x>();
        
        if (Test.isRunningTest()) {
            cwInvoices = getInvoiceTestData(orderNumber);
        } else {
            cwInvoices = Database.query(query);
        }
        
        return cwInvoices;
    }
    
    // Return dummy test data for the Order number provided
    public static List<CW_Invoice__x> getInvoiceTestData(String orderNumber) {
        List<CW_Invoice__x> cwInvoices = new List<CW_Invoice__x>();
        
        if (orderNumber == '298356' || orderNumber != '298356') {
            cwInvoices.add(new CW_Invoice__x(
                Id = 'x004B0000008OOrQAM',
                ExternalId = 'IP-0-61377-2-1-1-1',
                DisplayUrl = null,
                Additional_Charge_Amount_IST__c = 0.00,
                Additional_Freight_Amount_IST__c = 0.00,
                BOM_Component_Sequence__c = '0',
                BOM_Header_Flag__c = 'N',
                Color_Code__c = 'G1',
                Company__c = null,
                Credit_Card_Number__c = '************4113',
                Date_Shipped__c = '11/13/2015',
                Freight_Amount_IL__c = 0.00,
                Freight_Amount_IST__c = 0.00,
                GST_Amount_IL__c = 0.00000,
                GST_Amount_IST__c = 0.00,
                Handling_Amount_IL__c = 0.00,
                Handling_Amount_IST__c = 0.00,
                Invoice_Date__c = '11/13/2015',
                Invoice_Line_Number__c = 1,
                Invoice_Number__c = 61377,
                Invoice_Order_Line_Sequence_Number__c = 1,
                Invoice_Type__c = 'Credit',
                Item_Number__c = 'CASHACGW',
                Merchandise_Amount_IST__c = -5.95,
                Merchandise_Unit_Price_IL__c = 5.95,
                Order_Level_Freight_Tax__c = null,
                Order_Number__c = '0',
                Order_Payment_Sequence_Number__c = 1,
                PST_Amount_IL__c = 0.00000,
                PST_Amount_IST__c = 0.00,
                Payment_Additional_Charge_Amount__c = 0.00,
                Payment_Additional_Freight_Amount__c = 0.00,
                Payment_Category_Description__c = 'Credit Card',
                Payment_Category__c = '2',
                Payment_Freight_Amount__c = 0.00,
                Payment_GST_Amount__c = 0.00000,
                Payment_Handling_Amount__c = 0.00,
                Payment_Merchandise_Amount__c = -5.95,
                Payment_PST_Amount__c = 0.00000,
                Payment_Tax_Amount__c = -0.54,
                Payment_Type_Description__c = 'VISA',
                Payment_Type__c = 4,
                Pre_Bill_Color_Code__c = null,
                Pre_Bill_Item_Number__c = null,
                Pre_Bill_Size_Code__c = null,
                Quantity_Shipped__c = -1,
                Ship_To_Number_IST__c = 2,
                Size_Code__c = '10',
                Tax_Amount_IL__c = -0.54000,
                Tax_Amount_IST__c = -0.54
            ));
            cwInvoices.add(new CW_Invoice__x(
                Id = 'x004B0000008OOsQAM',
                ExternalId = 'IP-0-61384-1-1-1-1',
                DisplayUrl = null,
                Additional_Charge_Amount_IST__c = 5.95,
                Additional_Freight_Amount_IST__c = 0.00,
                BOM_Component_Sequence__c = '0',
                BOM_Header_Flag__c = 'N',
                Color_Code__c = 'AZUR',
                Company__c = null,
                Credit_Card_Number__c = '************4113',
                Date_Shipped__c = '11/13/2015',
                Freight_Amount_IL__c = 0.00,
                Freight_Amount_IST__c = 7.00,
                GST_Amount_IL__c = 0.00000,
                GST_Amount_IST__c = 0.00,
                Handling_Amount_IL__c = 0.00,
                Handling_Amount_IST__c = 0.00,
                Invoice_Date__c = '11/13/2015',
                Invoice_Line_Number__c = 1,
                Invoice_Number__c = 61384,
                Invoice_Order_Line_Sequence_Number__c = 1,
                Invoice_Type__c = 'Sale',
                Item_Number__c = '17050043',
                Merchandise_Amount_IST__c = 19.00,
                Merchandise_Unit_Price_IL__c = 19.00,
                Order_Level_Freight_Tax__c = null,
                Order_Number__c = '0',
                Order_Payment_Sequence_Number__c = 1,
                PST_Amount_IL__c = 0.00000,
                PST_Amount_IST__c = 0.00,
                Payment_Additional_Charge_Amount__c = 5.95,
                Payment_Additional_Freight_Amount__c = 0.00,
                Payment_Category_Description__c = 'Credit Card',
                Payment_Category__c = '2',
                Payment_Freight_Amount__c = 7.00,
                Payment_GST_Amount__c = 0.00000,
                Payment_Handling_Amount__c = 0.00,
                Payment_Merchandise_Amount__c = 19.00,
                Payment_PST_Amount__c = 0.00000,
                Payment_Tax_Amount__c = 1.71,
                Payment_Type_Description__c = 'VISA',
                Payment_Type__c = 4,
                Pre_Bill_Color_Code__c = null,
                Pre_Bill_Item_Number__c = null,
                Pre_Bill_Size_Code__c = null,
                Quantity_Shipped__c = 1,
                Ship_To_Number_IST__c = 1,
                Size_Code__c = null,
                Tax_Amount_IL__c = 1.71000,
                Tax_Amount_IST__c = 1.71
            ));
            cwInvoices.add(new CW_Invoice__x(
                Id = 'x004B0000008OOtQAM',
                ExternalId = 'IP-0-61385-1-0-0-1',
                DisplayUrl = null,
                Additional_Charge_Amount_IST__c = -5.95,
                Additional_Freight_Amount_IST__c = 0.00,
                BOM_Component_Sequence__c = '0',
                BOM_Header_Flag__c = null,
                Color_Code__c = null,
                Company__c = null,
                Credit_Card_Number__c = '************4113',
                Date_Shipped__c = null,
                Freight_Amount_IL__c = 0.00,
                Freight_Amount_IST__c = 0.00,
                GST_Amount_IL__c = 0.00000,
                GST_Amount_IST__c = 0.00,
                Handling_Amount_IL__c = 0.00,
                Handling_Amount_IST__c = 0.00,
                Invoice_Date__c = '11/13/2015',
                Invoice_Line_Number__c = 0,
                Invoice_Number__c = 61385,
                Invoice_Order_Line_Sequence_Number__c = 0,
                Invoice_Type__c = 'Credit',
                Item_Number__c = null,
                Merchandise_Amount_IST__c = 0.00,
                Merchandise_Unit_Price_IL__c = 0.00,
                Order_Level_Freight_Tax__c = null,
                Order_Number__c = '0',
                Order_Payment_Sequence_Number__c = 1,
                PST_Amount_IL__c = 0.00000,
                PST_Amount_IST__c = 0.00,
                Payment_Additional_Charge_Amount__c = -5.95,
                Payment_Additional_Freight_Amount__c = 0.00,
                Payment_Category_Description__c = 'Credit Card',
                Payment_Category__c = '2',
                Payment_Freight_Amount__c = 0.00,
                Payment_GST_Amount__c = 0.00000,
                Payment_Handling_Amount__c = 0.00,
                Payment_Merchandise_Amount__c = 0.00,
                Payment_PST_Amount__c = 0.00000,
                Payment_Tax_Amount__c = 0.00,
                Payment_Type_Description__c = 'VISA',
                Payment_Type__c = 4,
                Pre_Bill_Color_Code__c = null,
                Pre_Bill_Item_Number__c = null,
                Pre_Bill_Size_Code__c = null,
                Quantity_Shipped__c = 0,
                Ship_To_Number_IST__c = 1,
                Size_Code__c = null,
                Tax_Amount_IL__c = 0.00000,
                Tax_Amount_IST__c = 0.00
            ));
        }
        
        return cwInvoices;
    }
    
    public static List<CW_Order_Note__x> getCWOrderNotesAllFields(String orderNumber) {
        // Get all the object field names and build the query
        String query = 'SELECT';
        Map<String,Schema.SObjectField> FieldMap = Schema.SObjectType.CW_Order_Note__x.fields.getMap();
        
        //system.debug('***** number of fields = ' + FieldMap.size());
        
        for (Schema.SObjectField f : FieldMap.values()) {
            //Schema.DescribeFieldResult DescField = f.getDescribe();
            //system.debug('Name: ' +  DescField.getName());
            //system.debug('Type: ' +  DescField.getType());
            query += ' ' + f.getDescribe().getName() + ',';
        }
        query = query.removeEnd(',');
        query += ' FROM CW_Order_Note__x WHERE Order_Number__c = \'' + orderNumber + '\'';
        
        //system.debug('***** query string = ' + query); 
        
        List<CW_Order_Note__x> cwOrderNotes = new List<CW_Order_Note__x>();
        
        if (Test.isRunningTest()) {
            cwOrderNotes = getOrderNoteTestData(orderNumber);
        } else {
        
            for(CW_Order_Note__x cwon : Database.query(query))
            cwOrderNotes.add(cwon);
            
        }
    
        return cwOrderNotes;
    }
    
    // Return Order Note dummy test data for the Order number provided
    public static List<CW_Order_Note__x> getOrderNoteTestData(String orderNumber) {
        List<CW_Order_Note__x> cwOrderNotes = new List<CW_Order_Note__x>();
        
        if (orderNumber == '331971' || orderNumber != '331971') {
            
            cwOrderNotes.add(new CW_Order_Note__x(
                Id = 'x004B0000008OOrQAM',
                ExternalId = '331971-1-1',
                DisplayUrl = null,
                Ship_To__c = '1',
                Sequence_Number__c = 001,
                Message__c = ' ',
                Message_Type__c = 'N',
                User__c = 'SCANNY',    
                Date__c = '03/16/1971'      
            ));
        }
        return cwOrderNotes;
    }
}