objects/CW_Order_Note__x.object
<CustomObject>
    <description>CW Order Note</description>
    <externalDataSource>CWConnection</externalDataSource>
    <externalName>CW Order Note</externalName>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date</description>
        <externalDeveloperName>Date</externalDeveloperName>
        <label>Date</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <description>Message Type</description>
        <externalDeveloperName>Message Type</externalDeveloperName>
        <label>Message Type</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message</description>
        <externalDeveloperName>Message</externalDeveloperName>
        <label>Message</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Number</description>
        <externalDeveloperName>Order Number</externalDeveloperName>
        <label>Order Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Sequence Number</description>
        <externalDeveloperName>Sequence Number</externalDeveloperName>
        <label>Sequence Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <description>Ship To</description>
        <externalDeveloperName>Ship To</externalDeveloperName>
        <label>Ship To</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>User</description>
        <externalDeveloperName>User</externalDeveloperName>
        <label>User</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>CW Order Note</label>
    <pluralLabel>CW Order Note</pluralLabel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>EXT_Order_Number__c</fullName>
        <externalId>true</externalId>
        <label>EXT Order Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Order_NotesIntCtrlExt.cls
public with sharing class Order_NotesIntCtrlExt {
	
	private final RH_Order__c rhOrder;
	RH_Order__c theRHOrder = new RH_Order__c();
	List<CW_Order_Note__x> orderNotes = new List<CW_Order_Note__x>();
                  
    public Order_NotesIntCtrlExt(ApexPages.StandardController stdController){
    
       	this.rhOrder = (RH_Order__c)stdController.getRecord();
       	theRHOrder = [Select EXT_Order_Number__c from RH_Order__c where Id =: this.rhOrder.Id];

       	System.debug('Ext Order Id: ' + theRHOrder.Ext_Order_Number__c);
    }

	public List<CW_Order_Note__x> getOrderNotesList(){
       
		if (orderNotes.size()==0) {
        	try{       
            	//orderNotesList = [SELECT Date__c, Message__c, Message_Type__c, Order_Number__c, Sequence_Number__c, Ship_To__c, User__c FROM CW_Order_Note__x where Order_Number__c = :theRHOrder.Ext_Order_Number__c];
                orderNotes = CWConnection.getCWOrderNotesAllFields(theRHOrder.Ext_Order_Number__c);  
              }
              catch(Exception e){
              	System.debug('Order Notes Error' + e);
              	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error retrieving data from external data source.'));
                return null;
              }
            }
            return orderNotes;
        }    
}