objects/Manual_Reservation__c.object
<CustomObject>
    <description>Stores data from the Manual Reservation screen in CW.</description>
    <fields>
        <fullName>Early_Delivery_Date__c</fullName>
        <label>Early Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Subject_Brand__c</fullName>
        <label>Email Subject Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RH</fullName>
                </value>
                <value>
                    <fullName>RH Baby &amp; Child</fullName>
                </value>
                <value>
                    <fullName>RH Contract</fullName>
                </value>
                <value>
                    <fullName>RH Teen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_To_Address__c</fullName>
        <label>Email To Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Late_Delivery_Date__c</fullName>
        <label>Late Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Lines__c</fullName>
        <label>Order Lines</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Number</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Manual Reservations</relationshipLabel>
        <relationshipName>Manual_Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Manual Reservations</relationshipLabel>
        <relationshipName>Manual_Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Manual Reservation</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Manual Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ManualReservation_PreviewCtlExt.cls
public with sharing class ManualReservation_PreviewCtlExt {
	
	/*
	 *	Preview and manual send of Auto MIRV email (manual reservation of back ordered 
	 *	product). Back ordered product is now available earlier than expected.
	 *
	 */
	
	ApexPages.StandardController stdController;
	
	public Manual_Reservation__c rhMR {get; set;}
	public Id mrId {get; set;}
	public String retURL {get; set;}
	public Boolean isError {get; set;}
	public Boolean noSend {get; set;}
	
	public ManualReservation_PreviewCtlExt(ApexPages.StandardController stdController) {
		
		isError = true;
		noSend = false;
		mrId = ApexPages.currentPage().getParameters().get('mrId');
		retURL = ApexPages.currentPage().getParameters().get('retURL');
		
		rhMR = new Manual_Reservation__c();
		
		// Validate page parameters and get the data needed for the notification
		if (String.isNotBlank(mrId) && String.isNotBlank(retURL)) {
			
			try {
				rhMR = [select Id, Name, Ship_To__c, Early_Delivery_Date__c, Late_Delivery_Date__c,  
						Email_Subject_Brand__c, Email_To_Address__c, Order_Lines__c, Send_Email__c, 
						Order_Number__c, Order_Number__r.Sold_to_Email__c 
						from Manual_Reservation__c where Id = :mrId];
				
				rhMR.Email_To_Address__c = rhMR.Order_Number__r.Sold_to_Email__c;
				if (!Utility.isValidDomain(rhMR.Email_To_Address__c)) {
					rhMR.Email_To_Address__c = null;
				}
				
				isError = false;
				
			} catch(Exception e) {
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Manual Reservation read exception: ' + e.getMessage()));
			}
			
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Invalid page parameters.'));
		}
	}
	
	public PageReference cancelMRPreview() {
		PageReference pr;
		if (String.isNotBlank(retURL)) {
			pr = new PageReference(retURL);
		} else {
			pr = new PageReference('/');
		}
		return pr;
	}
	
	// Send the notification email
	public PageReference sendNotification() {
		PageReference pr = null;
		
		// Make sure the email address is in the appropriate domain for our environment
		if (Utility.isValidDomain(rhMR.Email_To_Address__c)) {
			
			// Send the email
			try {
				// Send the email
				rhMR.Send_Email__c = true;
				update rhMR;
				
				// Attach a copy of the email
				Blob pageContent;
				if (!Test.isRunningTest()) {
					pageContent = new PageReference('/apex/ManualReservationHTML?mrId=' + mrId).getContent();
				} else {
					pageContent = Blob.valueOf('Test Class');
				}
				
				Attachment mrAttachment = new Attachment(
					ParentId = rhMr.Id,
					Name = 'Manual Reservation ' + rhMR.Name + ': on-demand.html',
					ContentType = 'html',
					Body = pageContent,
					Description = 'System Generated Attachment'
						+ '\nManual Reservation Notification sent on-demand: ' + rhMR.Name 
						+ '\nToAddress = ' + rhMR.Email_To_Address__c
						+ '\nSend Date/Time = ' + String.valueOf(system.now())
				);
				insert mrAttachment;
				pr = new PageReference(retURL);
			} catch(Exception e) {
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Error while processing send email request, exception: ' + e.getMessage()));
			}
			
			
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'To Email Address must be in domain "rh.com" or "restorationhardware.com".'));
		}
		
		return pr;
	}
}