objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>BC_Renewal_CC_Entity_Code__c</fullName>
        <label>BC Renewal CC Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Renewal_CC_Expiration_Date__c</fullName>
        <label>BC Renewal CC Expiration Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Renewal_CC_Final_4_Digits__c</fullName>
        <label>BC Renewal CC Final 4 Digits</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BC_Renewal_CC_Updated_DateTime__c</fullName>
        <label>BC Renewal CC Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Cancellation_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fraud</fullName>
                </value>
                <value>
                    <fullName>Credit card decline</fullName>
                </value>
                <value>
                    <fullName>Created in error</fullName>
                </value>
                <value>
                    <fullName>Does not use it</fullName>
                </value>
                <value>
                    <fullName>Duplicate membership</fullName>
                </value>
                <value>
                    <fullName>Unhappy with membership</fullName>
                </value>
                <value>
                    <fullName>None given by customer</fullName>
                </value>
                <value>
                    <fullName>Customer does not want it</fullName>
                </value>
                <value>
                    <fullName>Renewal failed</fullName>
                </value>
                <value>
                    <fullName>Quebec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Type__c</fullName>
        <inlineHelpText>RH Terminated = RH determined that the membership needs to be terminated.
Member Terminated = Member requested and was granted a refund for membership.
Member Cancelled = Member cancelled the membership in My Account.</inlineHelpText>
        <label>Cancellation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RH Terminated</fullName>
                </value>
                <value>
                    <fullName>Member Terminated</fullName>
                </value>
                <value>
                    <fullName>Member Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Create_Renewal_Order__c</fullName>
        <formula>AND(
 Is_Auto_Renew__c = TRUE,
 ISPICKVAL(Membership_Type__c , &quot;Paid&quot;),
 Expiration_Date__c = TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Create Renewal Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Created_by_Order_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Created by Order ID</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Date__c</fullName>
        <formula>DATEVALUE( Enrollment_Date_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <formula>DATEVALUE( Expiration_Date_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GetsChangedTandCs__c</fullName>
        <formula>IF(Enrollment_Date__c &gt;= DATE(2016,10,16),TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GetsChangedTandCs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Valid_CC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Valid CC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Target_Group__c</fullName>
        <formula>IF(
OR(
Member_State__c = &apos;IL&apos;,
Member_State__c = &apos;CT&apos;,
Member_State__c = &apos;HI&apos;,
Member_State__c = &apos;NC&apos;),true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>In Target Group?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Auto Renew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latest_CC_Expiration_Date__c</fullName>
        <label>Latest CC Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Country__c</fullName>
        <label>Member Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Email__c</fullName>
        <externalId>true</externalId>
        <label>Member Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Member_State__c</fullName>
        <label>Member State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Type__c</fullName>
        <label>Membership Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complimentary - PR</fullName>
                </value>
                <value>
                    <fullName>Complimentary - VIP</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Phone Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RH_Renewal_CC_Entity_Code__c</fullName>
        <label>RH Renewal CC Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Renewal_CC_Expiration_Date__c</fullName>
        <label>RH Renewal CC Expiration Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Renewal_CC_Final_4_Digits__c</fullName>
        <label>RH Renewal CC Final 4 Digits</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Renewal_CC_Updated_DateTime__c</fullName>
        <label>RH Renewal CC Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renew_Email_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renew Email Opt In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RenewalEmailSubjectLine__c</fullName>
        <description>Needed to dynamically set email subject in membership reminder template. set in batch monitor membership email.</description>
        <label>RenewalEmailSubjectLine</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Email_Notification__c</fullName>
        <label>Renewal Email Notification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>60-Day Notice</fullName>
                </value>
                <value>
                    <fullName>30-Day Notice</fullName>
                </value>
                <value>
                    <fullName>5-Day Notice</fullName>
                </value>
                <value>
                    <fullName>3-Day Notice</fullName>
                </value>
                <value>
                    <fullName>1-Day Notice</fullName>
                </value>
                <value>
                    <fullName>1-Day Post Expiration</fullName>
                </value>
                <value>
                    <fullName>1-Day Post Termination</fullName>
                </value>
                <value>
                    <fullName>5-Day Post Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Order_Entity_Code__c</fullName>
        <description>Entity code that should be passed in CreateRenewal XML message. Will be updated in Salesforce code based on certain conditions.</description>
        <label>Renewal Order Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Reminder_Email_Sent_Date__c</fullName>
        <label>Renewal Reminder Email Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renewal_Term__c</fullName>
        <label>Renewal Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Enrollee__c</fullName>
        <description>// SMR-164
// Members who enrolled between 3/12 and 3/16
// According to our T&amp;Cs during this 4 day period (3/12/16-3/16/16), we told 
// customers we would email them at 30 days by default.
// Any Member meeting all of the following conditions: Enrollment Date &lt;= 3/16/16</description>
        <formula>IF(
AND(Enrollment_Date__c &gt;=  DATE(2016,3,12),Enrollment_Date__c &lt;=  DATE(2016,3,16)),
TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Special Enrollee</label>
        <type>Checkbox</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Member ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Type__c</fullName>
        <description>Type of membership coming from BI CW and ATG</description>
        <label>Membership Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchMonitorMembershipRenewalEmails.cls
global class BatchMonitorMembershipRenewalEmails implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
                             
    global static Integer[] expirationDateList = new List<Integer>{ 60, 30, 5, 3, 1, -5, -1 };
    private Integer membershipCount = 0;  
    private Integer membershipUpdates = 0;
    private Integer jobNumber = 0;
    private Integer expirationDayCheckIndex = 0;
    private List<SObject> failedRecords = new List<SObject>();
    //private boolean disableFlag;
//test    
  /*
   * Instantiate a new batch class
   * Empty constructor is purely for backward compatibliity and should be removed after R17.01 goes live
   */
   
  global BatchMonitorMembershipRenewalEmails() {
    this.jobNumber = 0;
    this.expirationDayCheckIndex = 0;
  }  
  
  global BatchMonitorMembershipRenewalEmails(Integer job, Integer checkIndex) {
    this.jobNumber = job;
    this.expirationDayCheckIndex = checkIndex;
    //this.disableFlag = disableFlag;
  }
  
  /*
   * Get the query string
   */
        
    global String getQuery() {
      Integer expirationDay = BatchMonitorMembershipRenewalEmails.expirationDateList.get(this.expirationDayCheckIndex); 
        String dayToCheck = String.valueOf(System.Today().addDays(expirationDay)).substring(0,10);    //cadence list can be used for both expire and terminate 
        String query;
        
        System.debug('starting job -' + this.jobNumber + ' for cadence -' + expirationDay);
        
        //this query is to pull memberships based on candence for expiration date, needed to create new logic to handle cancellation date (query below)
        //if (this.jobNumber == 0 || this.jobNumber == 1 || this.jobNumber == 2)
        if (this.expirationDayCheckIndex != 6)
        {
          
          query = 'SELECT Id, Name, Enrollment_Date__c, Expiration_Date__c, Renewal_Reminder_Email_Sent_Date__c, Renewal_Term__c, Renewal_Email_Notification__c'
            + ', BC_Renewal_CC_Final_4_Digits__c, BC_Renewal_CC_Expiration_Date__c, RH_Renewal_CC_Final_4_Digits__c, RH_Renewal_CC_Expiration_Date__c, Has_Valid_CC__c'
            + ', Special_Enrollee__c, GetsChangedTandCs__c, Latest_CC_Expiration_Date__c, Created_By_Order_Id__c, Created_By_Order_Id__r.Name'
            + ', Renewal_Order_Entity_Code__c, RH_Renewal_CC_Entity_Code__c, BC_Renewal_CC_Entity_Code__c, Created_By_Order_Id__r.Division__c'
            + ', RH_Renewal_CC_Updated_DateTime__c, BC_Renewal_CC_Updated_DateTime__c, Is_Auto_Renew__c, Renew_Email_Opt_In__c, In_Target_Group__c, RenewalEmailSubjectLine__c'
            + ', Phone_Order__c, Member_State__c, Member_Country__c, Contact__c, CreatedDate'
            + ', Create_Renewal_Order__c, Contact__r.FirstName, Contact__r.LastName, Member_Email__c'
            + '  FROM Membership__c'
            + '  WHERE Cancellation_Type__c != \'Member Terminated\' AND Cancellation_Type__c != \'RH Terminated\''
            + '  AND (Membership_Type__c = NULL OR Membership_Type__c = \'Paid\')'  
            + '  AND Expiration_Date__c = ' + dayToCheck;       
        }
        //job for sending termination email notifications, query to pull memberships that were terminated +1 days ago, based on cancellation type/reason, cancellation date
        else if (this.expirationDayCheckIndex ==6)
          {
            System.debug('getting terminated memberss query results');
            
            query = 'SELECT Id, Name, Enrollment_Date__c, Expiration_Date__c, Renewal_Reminder_Email_Sent_Date__c, Renewal_Term__c, Renewal_Email_Notification__c'
            + ', BC_Renewal_CC_Final_4_Digits__c, BC_Renewal_CC_Expiration_Date__c, RH_Renewal_CC_Final_4_Digits__c, RH_Renewal_CC_Expiration_Date__c, Has_Valid_CC__c'
            + ', Special_Enrollee__c, GetsChangedTandCs__c, Latest_CC_Expiration_Date__c, Created_By_Order_Id__c, Created_By_Order_Id__r.Name'
            + ', Renewal_Order_Entity_Code__c, RH_Renewal_CC_Entity_Code__c, BC_Renewal_CC_Entity_Code__c, Created_By_Order_Id__r.Division__c'
            + ', RH_Renewal_CC_Updated_DateTime__c, BC_Renewal_CC_Updated_DateTime__c, Is_Auto_Renew__c, Renew_Email_Opt_In__c, In_Target_Group__c, RenewalEmailSubjectLine__c'
            + ', Phone_Order__c, Member_State__c, Member_Country__c, Contact__c, CreatedDate, Cancellation_Date__c '
            + ', Create_Renewal_Order__c, Contact__r.FirstName, Contact__r.LastName, Member_Email__c'
            + '  FROM Membership__c'
            + '  WHERE Cancellation_Type__c like \'RH Terminated\' AND Cancellation_Reason__c like \'Credit Card Decline\'' 
            + '  AND (Membership_Type__c = NULL OR Membership_Type__c = \'Paid\')'  
            + '  AND Cancellation_Date__c = ' + dayToCheck;           
            
            
          }
        
        
        
        return query;     
    }
    
    /*
     * Start the batch
     */
   
  global database.queryLocator start(Database.BatchableContext BC) {
    String query = this.getQuery();
    system.debug('BatchMonitorMembershipRenewalEmails -> start -> ' + this.jobNumber + ' -> ' + this.expirationDayCheckIndex + ' -> ' + query);                 
    return database.getQueryLocator(query);
  }  
  
  /*
   * Execute the batch - split into 3 batches to ensure we don't blow any SOQL limits
   * Job ONE : Assigns new expiration dates to the membership record
   * Job TWO : Assigns better expiration dates from CW if necessary
   * JOB THREE : Finds the membership records that need emails
   * JOB FOUR : Queries membership that have terminated + 1 day for email notifiation
   */
    
    global void execute(Database.BatchableContext BC, List<Membership__c> memberships) {
      
      system.debug('BatchMonitorMembershipRenewalEmails -> execute -> ' + this.jobNumber + ' -> ' + this.expirationDayCheckIndex + ' -> ' + memberships.size());
      
      if (this.jobNumber == 0) {

        system.debug('Bulk update expiration dates for membership records in batch');
        List<Membership__c> assignedMemberships = MembershipRenewalService.assignExpirationDates(memberships);
        if (!assignedMemberships.isEmpty()) {
          Utility.logUpdate(assignedMemberships);
        }
        
      } else if (this.jobNumber == 1) {
        
        system.debug('Bulk update membership records with better CW expiration dates if any available');
        MembershipRenewalService.CalloutResponse response = MembershipRenewalService.callCwForBetterCardDetails(memberships);
        Utility.logUpdate(response.updatedMemberships);
        Utility.logInsert(response.resultingErrors);
        
      } else if (this.jobNumber == 2) {
        
        membershipCount += memberships.size();  
            
        system.debug('retrieve all membership records that require renewal emails');
          List<Membership__c> updateMemberships = MembershipRenewalService.buildRenewalMembershipRecords(memberships, 'renewal');
      if (!updateMemberships.isEmpty()) {
        system.debug('update the membership records -> ' + updateMemberships);
        this.failedRecords.addAll(Utility.logUpdate(updateMemberships));        
        system.debug('Insert the attachments');
        List<Attachment> attachments = MembershipRenewalService.buildAttachments(updateMemberships, 'renewal');
            Utility.logInsert(attachments);       
            system.debug('record number updated');
        membershipUpdates += updateMemberships.size();
          }         
      }  
      
      else if (this.jobNumber == 3) {
        
        membershipCount += memberships.size();  
            
        system.debug('retrieve terminated memberships');
          List<Membership__c> updateMemberships = MembershipRenewalService.buildRenewalMembershipRecords(memberships, 'terminate');
      if (!updateMemberships.isEmpty()) {
        system.debug('update the terminated membership records -> ' + updateMemberships);
        this.failedRecords.addAll(Utility.logUpdate(updateMemberships));        
        system.debug('Insert the attachments');
        List<Attachment> attachments = MembershipRenewalService.buildAttachments(updateMemberships, 'terminate');
            Utility.logInsert(attachments);       
            system.debug('record number updated');
        membershipUpdates += updateMemberships.size();
          }         
      }         
    }
    
    /*
     * Finish batch:
     * Either move onto the next batch or send email
     * Job ONE has to be run with a smaller batch size as this potentially makes call outs to CW for every membership record 
     * String of batches together, one calling another
     */
        
    global void finish(Database.BatchableContext BC) {   
      system.debug('BatchMonitorMembershipRenewalEmails -> finish -> ' + this.jobNumber + ' -> ' + this.expirationDayCheckIndex);   
      if (this.jobNumber ==  0 && this.expirationDayCheckIndex !=6 ) {        
        Database.executeBatch(new BatchMonitorMembershipRenewalEmails(1, this.expirationDayCheckIndex), 1);
      } else if (this.jobNumber == 1 && this.expirationDayCheckIndex !=6 ) {
        Database.executeBatch(new BatchMonitorMembershipRenewalEmails(2, this.expirationDayCheckIndex), 200);
        
      } 
      //only spawn the terminated email job if the cadence is +1 which is index 5 in the date array
      //spawn terminated job with new cadence index 6 and only when flag=true, will need to disable when cadence is modified to cover gap
      //else if (this.jobNumber ==2 && this.expirationDayCheckIndex==5 && !disableFlag)  {
      //  else if (this.expirationDayCheckIndex==)
      //        Database.executeBatch(new BatchMonitorMembershipRenewalEmails(3, this.expirationDayCheckIndex+1), 200); //termination job has a new cadence now, no longer sharing with expiry which is cadence 5
              
      else {           
      AsyncApexJob aaj = [
        Select Id, Status, NumberOfErrors, JobItemsProcessed, MethodName, TotalJobItems, CreatedBy.Email, CreatedDate
              from AsyncApexJob 
              where Id = :BC.getJobId()
      ];                                                     
  
      String daysOut = String.valueOf(BatchMonitorMembershipRenewalEmails.expirationDateList.get(this.expirationDayCheckIndex));
      String[] addresses = new String[] {aaj.CreatedBy.Email};
      String subject = daysOut + ' Days Out Membership Renewal CC Warning Batch Job ' + aaj.Status;              
      String bodyText =   'Number of batches processed ' + aaj.TotalJobItems + ' with '+ aaj.NumberOfErrors + ' failures.\n' +  
                              'Triggered emails for ' + membershipUpdates + ' Memberships.\n' + 'out of ' + membershipCount + ' Memberships queried.\n' +
                               (this.failedRecords.size() < 1 ? '' : 'Full list of Failed Records ' + JSON.serialize(this.failedRecords));
  
      Utility.sendEmail(addresses, bodyText, subject);
      }
    }
        
}