objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Date__c</fullName>
        <formula>DATEVALUE( Enrollment_Date_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <formula>DATEVALUE( Expiration_Date_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Email__c</fullName>
        <externalId>true</externalId>
        <label>Member Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Member ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MembershipWelcomeEmailTemplateController.cls
public class MembershipWelcomeEmailTemplateController{
 
 public String membershipId{get;set;}

 public String dayPhone{get;set;}
 
 public Boolean isQuebec{get{ 
    return MembershipService.isQuebecois(membershipId, true);
 }set;}
 
 public MembershipWelcomeEmailTemplateController(){}
 
 public List<MembershipWelcomeEmailTemplateController.MembershipInfo> getMembershipDetails(){ 
   
   List<MembershipWelcomeEmailTemplateController.MembershipInfo> listMembershipDetails = new List<MembershipWelcomeEmailTemplateController.MembershipInfo>();
   Contact con;
   Membership__c m = [SELECT Id, Name, Contact__c, Enrollment_Date__c, Expiration_Date__c, Member_Email__c
                        from Membership__c
                       where Id = :membershipId];
   if(m.Contact__c != null){
      for(Contact c:[SELECT Id, Name, Phone from Contact where Id = :m.Contact__c]){
         con = c;
      } 
   }else{
      con = new Contact();  
   }
   listMembershipDetails.add(new MembershipInfo(m, con));
   return listMembershipDetails;
 }
 
	public class MembershipInfo {
		public Membership__c membership{get;set;}
		public Contact membershipParty{get;set;}
		public String dayPhone{get;set;} 
		public String EnrollmentDate{get;set;}
		public String ExpirationDate{get;set;}

		public MembershipInfo(Membership__c m, Contact con){
			this.membership = m;
			this.membershipParty = con;
			if (String.isNotBlank(con.Phone)) {
				this.dayPhone = Utility.formatPhone10(con.Phone);
			}
			this.EnrollmentDate = Utility.usWrittenDate(m.Enrollment_Date__c, true);
			this.ExpirationDate = Utility.usWrittenDate(m.Expiration_Date__c, true);      
		}
	}
 
 }