objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Cancellation_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Fraud</fullName>
                </value>
                <value>
                    <fullName>Credit card decline</fullName>
                </value>
                <value>
                    <fullName>Created in error</fullName>
                </value>
                <value>
                    <fullName>Does not use it</fullName>
                </value>
                <value>
                    <fullName>Duplicate membership</fullName>
                </value>
                <value>
                    <fullName>Unhappy with membership</fullName>
                </value>
                <value>
                    <fullName>None given by customer</fullName>
                </value>
                <value>
                    <fullName>Customer does not want it</fullName>
                </value>
                <value>
                    <fullName>Renewal failed</fullName>
                </value>
                <value>
                    <fullName>Quebec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Type__c</fullName>
        <inlineHelpText>RH Terminated = RH determined that the membership needs to be terminated.
Member Terminated = Member requested and was granted a refund for membership.
Member Cancelled = Member cancelled the membership in My Account.</inlineHelpText>
        <label>Cancellation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RH Terminated</fullName>
                </value>
                <value>
                    <fullName>Member Terminated</fullName>
                </value>
                <value>
                    <fullName>Member Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_Restore_Date__c</fullName>
        <label>Membership Restore Date</label>
        <type>DateTime</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Member ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MembershipCancellationTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Replicates the dependencies of the dependent picklist fields Cancellation_Type__c and Cancellation_Reason__c of the Membership__c object.</description>
    <fields>
        <fullName>Cancellation_Reasons__c</fullName>
        <inlineHelpText>The semi-colon delimited list of possible Cancellation Reasons for the Cancellation Type of this record. This should be identical to the dependent picklist configuration for the two picklist fields.</inlineHelpText>
        <label>Cancellation Reasons</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reasons_non_Admin__c</fullName>
        <inlineHelpText>Allowable Cancellation_Reason__c picklist values for non-Admin users.</inlineHelpText>
        <label>Reasons non-Admin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nonAdmin__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, Cancellation Type (as represented in the Name field) is allowed for non-admin users.</inlineHelpText>
        <label>nonAdmin</label>
        <type>Checkbox</type>
    </fields>
    <label>MembershipCancellationTypes</label>
</CustomObject>

classes/MembershipCancellationTypeCtlExt.cls
public with sharing class MembershipCancellationTypeCtlExt {
	
	/*
	 *	Membership object controller extension to control what picklist values of field Cancellation_Type__c can be
	 *	set via the UI depending on who the running user is and what the current value is.
	 */
	
	ApexPages.StandardController stdController;
	
	public Membership__c rhMembership {get; set;}
	public Boolean isReadOnly {get; set;}
	public Boolean isEditMode {get; set;}
	public Boolean isNonAdminUser {get; set;}
	
	private Map<String, Set<String>> nonAdminReasonMap;
	private Map<String, Set<String>> adminReasonMap;
	Map<String, MembershipCancellationTypes__c> memCancelMap;
	
	public MembershipCancellationTypeCtlExt(ApexPages.StandardController stdController) {
		
		isEditMode = false;
		
		this.rhMembership = (Membership__c)stdController.getRecord();
		this.rhMembership = [select Id, Name, Cancellation_Type__c, Cancellation_Reason__c, Cancellation_Date__c, Membership_Restore_Date__c from Membership__c where Id = :this.rhMembership.Id];
		
		List<User> uList = new List<User>();
		uList = [select Id, Name, UserRoleId, UserRole.Name from User where Id = :UserInfo.getUserId()];
		isNonAdminUser = (uList[0].UserRole.Name == 'Administration') ? false : true;
		
		// Create the set of allowable Cancellation Reason values for non-admin and admin users
		memCancelMap = MembershipCancellationTypes__c.getAll();
		List<String> reasons = new List<String>();
		nonAdminReasonMap = new Map<String, Set<String>>();
		adminReasonMap = new Map<String, Set<String>>();
		for (String cancelType :memCancelMap.keySet()) {
			nonAdminReasonMap.put(cancelType, new Set<String>());
			if (String.isNotBlank(memCancelMap.get(cancelType).Reasons_non_Admin__c)) {
				reasons = memCancelMap.get(cancelType).Reasons_non_Admin__c.split(';');
				nonAdminReasonMap.get(cancelType).addAll(reasons);
			}
			
			adminReasonMap.put(cancelType, new Set<String>());
			if (String.isNotBlank(memCancelMap.get(cancelType).Cancellation_Reasons__c)) {
				reasons = memCancelMap.get(cancelType).Cancellation_Reasons__c.split(';');
				adminReasonMap.get(cancelType).addAll(reasons);
			}
		}
		
		// Determine if fields are read only based upon user type and value of Cancellation Type
		isReadOnly = false;
		if (String.isNotBlank(rhMembership.Cancellation_Type__c)) {
			if (memCancelMap.containsKey(rhMembership.Cancellation_Type__c)) {
				if (isNonAdminUser && !memCancelMap.get(rhMembership.Cancellation_Type__c).nonAdmin__c) {
					isReadOnly = true;
				}
			}
		}
	}
	
	public List<SelectOption> getcancellationTypes() {
		List<SelectOption> options = new List<SelectOption>();
		
		Schema.DescribeFieldResult fieldResult = Membership__c.Cancellation_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		
		options.add(new SelectOption('', '--None--'));
		for (Schema.PicklistEntry f : ple) {
			if (memCancelMap.containsKey(f.getLabel())) {
				if (!isNonAdminUser || memCancelMap.get(f.getLabel()).nonAdmin__c) {
					options.add(new SelectOption(f.getLabel(), f.getValue()));
				}
			}
		}
		
		return options;
	}
	
	public List<SelectOption> getcancellationReasons() {
		List<SelectOption> options = new List<SelectOption>();
		
		Schema.DescribeFieldResult fieldResult = Membership__c.Cancellation_Reason__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		
		options.add(new SelectOption('', '--None--'));
		for( Schema.PicklistEntry f : ple) {
			if (isNonAdminUser) {
				if (nonAdminReasonMap.containsKey(rhMembership.Cancellation_Type__c)) {
					if (nonAdminReasonMap.get(rhMembership.Cancellation_Type__c).contains(f.getLabel())) {
						options.add(new SelectOption(f.getLabel(), f.getValue()));
					}
				}
			} else {
				if (adminReasonMap.containsKey(rhMembership.Cancellation_Type__c)) {
					if (adminReasonMap.get(rhMembership.Cancellation_Type__c).contains(f.getLabel())) {
						options.add(new SelectOption(f.getLabel(), f.getValue()));
					}
				}
			}
		}
		
		return options;
	}
	
	public PageReference cancellationTypeChanged() {
		return null;
	}
	
	public PageReference cancelCancellationType() {
		isEditMode = false;
		rhMembership = [select Id, Name, Cancellation_Type__c, Cancellation_Reason__c, Cancellation_Date__c, Membership_Restore_Date__c from Membership__c where Id = :rhMembership.Id];
		return null;
	}
	
	public PageReference editCancellationType() {
		isEditMode = true;
		return null;
	}
	
	public PageReference saveCancellationType() {
		PageReference pr = null;
		
		try {
			update rhMembership;
			rhMembership = [select Id, Name, Cancellation_Type__c, Cancellation_Reason__c, Cancellation_Date__c, Membership_Restore_Date__c from Membership__c where Id = :rhMembership.Id];
			isEditMode = false;
			
			// Determine if fields are read only based upon user type and value of Cancellation Type
			isReadOnly = false;
			if (String.isNotBlank(rhMembership.Cancellation_Type__c)) {
				if (memCancelMap.containsKey(rhMembership.Cancellation_Type__c)) {
					if (isNonAdminUser && !memCancelMap.get(rhMembership.Cancellation_Type__c).nonAdmin__c) {
						isReadOnly = true;
					}
				}
			}
			
		} catch(Exception e) {
			if (!ApexPages.hasMessages()) {
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Save exception: ' + e.getMessage()));
			}
		}
		
		return pr;
	}
}