objects/Operations_Request__c.object
<CustomObject>
    <fields>
        <fullName>DC_Location__c</fullName>
        <label>DC Location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>89 - ODC</fullName>
                </value>
                <value>
                    <fullName>95 - SFDC</fullName>
                </value>
                <value>
                    <fullName>96 - DDC</fullName>
                </value>
                <value>
                    <fullName>97 - LADC</fullName>
                </value>
                <value>
                    <fullName>98 - MDC</fullName>
                </value>
                <value>
                    <fullName>Direct to Customer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OpsNotesLineItem__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, at least one related Operations Request Line Item record has a non-blank Ops Notes field.</inlineHelpText>
        <label>OpsNotesLineItem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ops_Notes__c</fullName>
        <label>Ops Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Operations Request</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Operations Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Operations_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>DC_Location__c</fullName>
        <label>DC Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>89 - ODC</fullName>
                </value>
                <value>
                    <fullName>95 - SFDC</fullName>
                </value>
                <value>
                    <fullName>96 - DDC</fullName>
                </value>
                <value>
                    <fullName>97 - LADC</fullName>
                </value>
                <value>
                    <fullName>98 - MDC</fullName>
                </value>
                <value>
                    <fullName>Direct to Customer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operations_Request__c</fullName>
        <label>Operations Request</label>
        <referenceTo>Operations_Request__c</referenceTo>
        <relationshipName>Operations_Request_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ops_Notes__c</fullName>
        <label>Ops Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Operations Request Line Item</label>
    <nameField>
        <displayFormat>ORLI-{000000}</displayFormat>
        <label>Operations Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OperationsRequestLineItemService.cls
public with sharing class OperationsRequestLineItemService {
	
	/*
	 *	Service methods for OperationsRequestLineItemTrigger.
	 *
	 */
	
	// "Roll Up" various fields from Operations Request Line Item records to their parent Operations Request record
	// - after insert, after update
	//		- DC_Location__c - "roll up" picklist field to multi-select picklist DC_Location__c
	//		- Ops_Notes__c - if one or more is non blank, set OpsNotesLineItem__c to true
	public static void rollUp(List<Operations_Request_Line_Item__c> newList, Map<Id, Operations_Request_Line_Item__c> oldMap, Boolean isInsert) {
		Set<Id> orIds = new Set<Id>();
		
		for (Operations_Request_Line_Item__c orli :newList) {
			if (isInsert) {
				if (String.isNotBlank(orli.DC_Location__c)) {
					orIds.add(orli.Operations_Request__c);
				}
				if (String.isNotBlank(orli.Ops_Notes__c)) {
					orIds.add(orli.Operations_Request__c);
				}
			}
			
			if (!isInsert) {
				if (orli.DC_Location__c != oldMap.get(orli.Id).DC_Location__c) {
					orIds.add(orli.Operations_Request__c);
				}
				if (orli.Ops_Notes__c != oldMap.get(orli.Id).Ops_Notes__c) {
					orIds.add(orli.Operations_Request__c);
				}
			}
		}
		
		if (!orIds.isEmpty()) {
			Map<Id, Operations_Request__c> orMap = new Map<Id, Operations_Request__c>([select Id, DC_Location__c, OpsNotesLineItem__c from Operations_Request__c where Id in :orIds]);
			for (Operations_Request__c o :orMap.values()) {
				o.DC_Location__c = '';
				o.OpsNotesLineItem__c = false;
			}
			
			List<Operations_Request_Line_Item__c> orliList = new List<Operations_Request_Line_Item__c>();
			orliList = [select Id, DC_Location__c, Operations_Request__c, Ops_Notes__c from Operations_Request_Line_Item__c where Operations_Request__c in :orIds];
			for (Operations_Request_Line_Item__c orli :orliList) {
				
				if (String.isNotBlank(orli.DC_Location__c)) {
					if (orMap.containsKey(orli.Operations_Request__c)) {
						if (!orMap.get(orli.Operations_Request__c).DC_Location__c.contains(orli.DC_Location__c + ';')) {
							orMap.get(orli.Operations_Request__c).DC_Location__c += orli.DC_Location__c + ';';
						}
					}
				}
				
				if (String.isNotBlank(orli.Ops_Notes__c)) {
					if (orMap.containsKey(orli.Operations_Request__c)) {
						orMap.get(orli.Operations_Request__c).OpsNotesLineItem__c = true;
					}
				}
			}
			
			for (Operations_Request__c o :orMap.values()) {
				if (String.isNotBlank(o.DC_Location__c)) {
					o.DC_Location__c = o.DC_Location__c.removeEnd(';');
				}
			}
			
			if (!orMap.isEmpty()) {
				update orMap.values();
			}
		}
	}
}