objects/Operations_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved at &gt; 50% OH</fullName>
                </value>
                <value>
                    <fullName>Approved at &lt; 50% OH</fullName>
                </value>
                <value>
                    <fullName>Not Approved, place SPO</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Customer Accepted</fullName>
                </value>
                <value>
                    <fullName>Customer Declined</fullName>
                </value>
                <value>
                    <fullName>Logistics Operations</fullName>
                </value>
                <value>
                    <fullName>Planning Operations</fullName>
                </value>
                <value>
                    <fullName>Product Operations</fullName>
                </value>
                <value>
                    <fullName>Executive Approval</fullName>
                </value>
                <value>
                    <fullName>Kesha Weldon</fullName>
                </value>
                <value>
                    <fullName>Back to PM</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Terms__c</fullName>
        <formula>TEXT(Opportunity__r.Credit_Terms__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Decline_Reason__c</fullName>
        <inlineHelpText>Explain why the customer declined the request and not proceed with the order.</inlineHelpText>
        <label>Customer Decline Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Margin</fullName>
                </value>
                <value>
                    <fullName>Timing</fullName>
                </value>
                <value>
                    <fullName>Changed Mind</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notify_Ops__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked will trigger workflow rule to send operations an email alert.</inlineHelpText>
        <label>Notify Ops</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Opportunity/Project lookup field</description>
        <inlineHelpText>Opportunity Lookup Field</inlineHelpText>
        <label>Opportunity/Project</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations Requests</relationshipLabel>
        <relationshipName>Operations_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>RH_Order__c.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Operations Requests (Order)</relationshipLabel>
        <relationshipName>Operations_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Payment_Received__c</fullName>
        <formula>Opportunity__r.Total_Payment_Received__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Payment Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Operations Request</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Operations Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Operations_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Operations_Request__c</fullName>
        <label>Operations Request</label>
        <referenceTo>Operations_Request__c</referenceTo>
        <relationshipName>Operations_Request_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operations Request Line Item</label>
    <nameField>
        <displayFormat>ORLI-{000000}</displayFormat>
        <label>Operations Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Credit_Terms__c</fullName>
        <formula>TEXT(Opportunity.Credit_Terms__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>this is populated from the Opportunity</inlineHelpText>
        <label>Credit Terms</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OperationsRequestService.cls
public class OperationsRequestService {
	
	/*
	 *	Service methods for OperationsRequestTrigger.trigger.
	 *
	 */
	
	// Automatically sets key fields on insert - fields: Order__c
	// - before insert
	public static void setFields(List<Operations_Request__c> newList) {
		Set<Id> oppIds = new Set<Id>();
		
		for (Operations_Request__c opr :newList) {
			if (opr.Opportunity__c != null && opr.Order__c == null) {
				oppIds.add(opr.Opportunity__c);
			}
		}
		
		if (!oppIds.isEmpty()) {
			
			Map<Id, Id> oppToOrderMap = new Map<Id, Id>();
			List<RH_Order__c> orderList = new List<RH_Order__c>();
			orderList = [select Id, Opportunity__c from RH_Order__c where Opportunity__c in :oppIds];
			
			for (RH_Order__c o :orderList) {
				oppToOrderMap.put(o.Opportunity__c, o.Id);
			}
			
			for (Operations_Request__c opr :newList) {
				if (oppToOrderMap.containsKey(opr.Opportunity__c)) {
					opr.Order__c = oppToOrderMap.get(opr.Opportunity__c);
				}
			}
		}
	}
	
	// Performs various validation rules and throws errors if appropriate
	// - before insert, before update
	public static void validationRules(List<Operations_Request__c> newList, Map<Id, Operations_Request__c> oldMap, Boolean isInsert) {
		
		if (isInsert) {
			
		}
		
		if (!isInsert) {
			for (Operations_Request__c opr :newList) {
				
				// Validate field Customer Decline Reason is not blank if field Approval Status is "Customer Declined"
				if (opr.Approval_Status__c != oldMap.get(opr.Id).Approval_Status__c && opr.Approval_Status__c == 'Customer Declined') {
					if (String.isBlank(opr.Customer_Decline_Reason__c)) {
						opr.Customer_Decline_Reason__c.addError('Customer Decline Reason must not be blank.');
					}
				}
			}
		}
	}
	
	// If Approval Status is "Customer Accepted" notify operations if related Opportunity is in appropriate state
	// - before update
	public static void customerAccepted(List<Operations_Request__c> newList, Map<Id, Operations_Request__c> oldMap) {
		Set<Id> oppIds = new Set<Id>();
		List<Operations_Request__c> oprList = new List<Operations_Request__c>();
		Set<Id> rtIds = new Set<Id>();
		Map<String, Schema.RecordTypeInfo> rtByNameMap = Schema.SObjectType.Operations_Request__c.getRecordTypeInfosByName();
		
		if (rtByNameMap.containsKey('COM/COL')) {
			rtIds.add(rtByNameMap.get('COM/COL').getRecordTypeId());
		}
		if (rtByNameMap.containsKey('Custom Product')) {
			rtIds.add(rtByNameMap.get('Custom Product').getRecordTypeId());
		}
		if (rtByNameMap.containsKey('SPO Quote')) {
			rtIds.add(rtByNameMap.get('SPO Quote').getRecordTypeId());
		}
		
		for (Operations_Request__c opr :newList) {
			if (opr.Opportunity__c != null && rtIds.contains(opr.RecordTypeId)) {
				if (opr.Approval_Status__c == 'Customer Accepted' && oldMap.get(opr.Id).Approval_Status__c != 'Customer Accepted') {
					// Only if we haven't already notified operations
					if (!opr.Notify_Ops__c) {
						oppIds.add(opr.Opportunity__c);
						oprList.add(opr);
					}
				}
			}
		}
		
		if (!oppIds.isempty()) {
			Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>([select Id, Name, Amount, Total_Payment_Received__c, Credit_Terms__c 
					from Opportunity where Id in :oppIds]);
			for (Operations_Request__c opr :oprList) {
				if (oppMap.containsKey(opr.Opportunity__c)) {
					if (String.isNotBlank(oppMap.get(opr.Opportunity__c).Credit_Terms__c) && oppMap.get(opr.Opportunity__c).Credit_Terms__c != 'Pre-Pay') {
						opr.Notify_Ops__c = true;	// Notify operations
					}
					
					if (oppMap.get(opr.Opportunity__c).Amount > 0 && oppMap.get(opr.Opportunity__c).Total_Payment_Received__c > 0) {
						if (oppMap.get(opr.Opportunity__c).Total_Payment_Received__c >= oppMap.get(opr.Opportunity__c).Amount / 2) {
							opr.Notify_Ops__c = true;	// Notify operations
						}
					}
				}
			}
		}
	}
	
	// Change the related Operations Request Line Item record types to match the parent Operations Request record type
	// - after update
	public static void changeRecordType(Map<Id, Operations_Request__c> newMap, Map<Id, Operations_Request__c> oldMap) {
		Set<Id> orIds = new Set<Id>();
		
		for (Operations_Request__c opr :newMap.values()) {
			if (opr.RecordTypeId != null && opr.RecordTypeId != oldMap.get(opr.Id).RecordTypeId) {
				orIds.add(opr.Id);
			}
		}
		
		if (!orIds.isEmpty()) {
			List<Operations_Request_Line_Item__c> orliList = new List<Operations_Request_Line_Item__c>();
			orliList = [select Id, RecordTypeId, Operations_Request__c from Operations_Request_Line_Item__c where Operations_Request__c in :orIds];
			
			Map<Id, RecordTypeInfo> rtOpRecByIdMap = Schema.SObjectType.Operations_Request__c.getRecordTypeInfosById();
			Map<String, RecordTypeInfo> rtOpRecLineItemByNameMap = Schema.SObjectType.Operations_Request_Line_Item__c.getRecordTypeInfosByName();
			
			for (Operations_Request_Line_Item__c orli :orliList) {
				orli.RecordTypeId = rtOpRecLineItemByNameMap.get(rtOpRecByIdMap.get(newMap.get(orli.Operations_Request__c).RecordTypeId).getName()).getRecordTypeId();
			}
			
			if (!orliList.isEmpty()) {
				update orliList;
			}
		}
	}
}