objects/Operations_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Pricing__c</fullName>
        <label>Approved Pricing ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Attribute_Color_Finish__c</fullName>
        <inlineHelpText>Color Code or Description</inlineHelpText>
        <label>Attribute/Color/Finish</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmed_Lead_Time__c</fullName>
        <label>Confirmed Lead Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Tracking__c</fullName>
        <label>Customer Tracking #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DC_Location__c</fullName>
        <label>DC Location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>89 - ODC</fullName>
                </value>
                <value>
                    <fullName>95 - SFDC</fullName>
                </value>
                <value>
                    <fullName>96 - DDC</fullName>
                </value>
                <value>
                    <fullName>97 - LADC</fullName>
                </value>
                <value>
                    <fullName>98 - MDC</fullName>
                </value>
                <value>
                    <fullName>Direct to Customer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ELC__c</fullName>
        <label>ELC ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Type__c</fullName>
        <label>Fulfillment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dropship</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>SPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Indoor_Outdoor__c</fullName>
        <label>Indoor/Outdoor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Indoor</fullName>
                </value>
                <value>
                    <fullName>Outdoor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Opportunity/Project lookup field</description>
        <inlineHelpText>Opportunity Lookup Field</inlineHelpText>
        <label>Opportunity/Project</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations Requests</relationshipLabel>
        <relationshipName>Operations_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_in_DC_Date__c</fullName>
        <label>PO in DC Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ready_to_place_dropship__c</fullName>
        <label>Ready to place dropship?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Square_Feet__c</fullName>
        <inlineHelpText>Yardage found in IM10 additional measurements. Conversion rate 1 yard = 18 sq/ft</inlineHelpText>
        <label>Square Feet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>COI</fullName>
                </value>
                <value>
                    <fullName>COL</fullName>
                </value>
                <value>
                    <fullName>COM</fullName>
                </value>
                <value>
                    <fullName>Confirmed Quote</fullName>
                </value>
                <value>
                    <fullName>Core Inventory</fullName>
                </value>
                <value>
                    <fullName>Core Margin</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>DC Pickup</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Expedite Domestic</fullName>
                </value>
                <value>
                    <fullName>Expedite International</fullName>
                </value>
                <value>
                    <fullName>Freight Request</fullName>
                </value>
                <value>
                    <fullName>Large Qty SPO</fullName>
                </value>
                <value>
                    <fullName>Lead Time</fullName>
                </value>
                <value>
                    <fullName>Model Room Sample</fullName>
                </value>
                <value>
                    <fullName>Permission to Exceed Guidelines</fullName>
                </value>
                <value>
                    <fullName>POD</fullName>
                </value>
                <value>
                    <fullName>SM</fullName>
                </value>
                <value>
                    <fullName>Special Handling</fullName>
                </value>
                <value>
                    <fullName>Vendor Air Freight</fullName>
                </value>
                <value>
                    <fullName>Yardage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yardage__c</fullName>
        <inlineHelpText>Yardage found in IM10 additional measurements. Conversion rate 1 yard = 18 sq/ft</inlineHelpText>
        <label>Yardage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Operations Request</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Operations Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Operations_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Product_Name__c</fullName>
        <formula>IF(ISBLANK(Product__r.Actual_Product_Name__c), Product__r.Name, Product__r.Actual_Product_Name__c)</formula>
        <label>Actual Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approved_Pricing__c</fullName>
        <label>Approved Pricing ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Attribute_Color_Finish__c</fullName>
        <inlineHelpText>Color Code or Description</inlineHelpText>
        <label>Attribute/Color/Finish</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmed_Lead_Time__c</fullName>
        <label>Confirmed Lead Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Location__c</fullName>
        <label>Customer Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Spec__c</fullName>
        <label>Customer Spec #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Tracking__c</fullName>
        <label>Customer Tracking #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DC_Location__c</fullName>
        <label>DC Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>89 - ODC</fullName>
                </value>
                <value>
                    <fullName>95 - SFDC</fullName>
                </value>
                <value>
                    <fullName>96 - DDC</fullName>
                </value>
                <value>
                    <fullName>97 - LADC</fullName>
                </value>
                <value>
                    <fullName>98 - MDC</fullName>
                </value>
                <value>
                    <fullName>Direct to Customer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ELC__c</fullName>
        <label>ELC ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Type__c</fullName>
        <label>Fulfillment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dropship</fullName>
                </value>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>SPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Indoor_Outdoor__c</fullName>
        <label>Indoor/Outdoor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Indoor</fullName>
                </value>
                <value>
                    <fullName>Outdoor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New SKU</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Operations Request Line Items (New SKU)</relationshipLabel>
        <relationshipName>Operations_Request_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operations_Request__c</fullName>
        <label>Operations Request</label>
        <referenceTo>Operations_Request__c</referenceTo>
        <relationshipName>Operations_Request_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Id__c</fullName>
        <label>Opportunity Product Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_In_DC_Date__c</fullName>
        <label>PO In DC Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Operations Request Line Items</relationshipLabel>
        <relationshipName>Operations_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ready_To_Place_Dropship__c</fullName>
        <label>Ready To Place Dropship?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Square_Feet__c</fullName>
        <inlineHelpText>1 Sq Ft leather converts to .1 Yards of fabric</inlineHelpText>
        <label>Square Feet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yardage__c</fullName>
        <inlineHelpText>1 Yard of Fabric converts to 18 Sq Ft of leather</inlineHelpText>
        <label>Yardage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Operations Request Line Item</label>
    <nameField>
        <displayFormat>ORLI-{000000}</displayFormat>
        <label>Operations Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Actual_Product_Name__c</fullName>
        <description>to house the text product name for use in quotes</description>
        <label>Actual Product Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ELC__c</fullName>
        <description>Added per Trade Planning Manager to assist in calculating margin. 051809LALO.   ipim field map: Direct Landed Cost. 032111LALO</description>
        <inlineHelpText>Use Estimated Landed Cost (ELC)</inlineHelpText>
        <label>ELC</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

classes/OperationsRequestLineItem_EditAllCtlExt.cls
public with sharing class OperationsRequestLineItem_EditAllCtlExt {
	
	/*
     *  Operations Request Line Item controller extension - methods to support editing key fields of all 
     *	operations request line item records related to a single operations request record on a single page.
     *
     */
    
	ApexPages.StandardController stdController;
	
	private String orId;
	private String retURL;
	private List<Operations_Request_Line_Item__c> opReqLineList;
	private List<Operations_Request_Line_Item__c> displayOpReqLineList;
	private Integer minDisplayRows = 2;
	private Integer defaultDisplayRows = 10;
	
	public Operations_Request__c opReq {get; set;}
	public Boolean fatalError {get; set;}
	public Boolean noLines {get; set;}
	public Integer displaySet {get; set;}
    public Integer pageNumber {get; set;}
    public Integer totalPages {get; set;}
    public Integer rowsToDisplay {get; set;}
    public String recordTypeName {get; set;}
	
	// Constructor
	public OperationsRequestLineItem_EditAllCtlExt(ApexPages.StandardController stdController) {
		
		fatalError = false;
		noLines = false;
		opReq = new Operations_Request__c();
		opReqLineList = new List<Operations_Request_Line_Item__c>();
		displayOpReqLineList = new List<Operations_Request_Line_Item__c>();
		orId = ApexPages.currentPage().getParameters().get('orId');
		retURL = ApexPages.currentPage().getParameters().get('retURL');
		
		// Initialize display variables
		rowsToDisplay = defaultDisplayRows;
		displaySet = 0;
		pageNumber = 1;
		totalPages = 1;
		
		if (String.isNotBlank(orId) && String.isNotBlank(retURL)) {
			try {
				opReq = [select Id, Name, RecordTypeId, Opportunity__c from Operations_Request__c where Id = :orId];
				Map<Id, RecordTypeInfo> rtByIdMap = Schema.SObjectType.Operations_Request__c.getRecordTypeInfosById();
				recordTypeName = rtByIdMap.containsKey(opReq.RecordTypeId) ? rtByIdMap.get(opReq.RecordTypeId).getName() : '';
				initOpReqLines();
			} catch(Exception e) {
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Fatal exception: ' + e.getMessage()));
				fatalError = true;
			}
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Invalid page parameters.'));
			fatalError = true;
		}
	}
	
	// Read in the entire list of Operations Request Line Items - all fields
	private void initOpReqLines() {
		String selects;
		Map<String, Schema.SObjectField> fMap;
		List<String> selectFields;
		
		opReqLineList.clear();
		
		fMap = Schema.getGlobalDescribe().get('Operations_Request_Line_Item__c').getDescribe().Fields.getMap();
		selectFields = new List<String>();
		if (fMap != null) {
			for (Schema.SObjectField ft : fMap.values()) {
				Schema.DescribeFieldResult fd = ft.getDescribe();
				selectFields.add(fd.getName());
			}
		}
		
		selects = '';
		for (String s:selectFields) {
			selects += s + ',';
		}
		if (selects.endsWith(',')) {
			selects += 'Product__r.Name,';
			selects = selects.substring(0,selects.lastIndexOf(','));
			
			system.debug('*****initOpReqLines field list = ' + selects);
			
			opReqLineList = (List<Operations_Request_Line_Item__c>)Database.query('SELECT ' + selects + ' FROM Operations_Request_Line_Item__c WHERE Operations_Request__c = \'' + opReq.Id + '\' ORDER BY Name ASC');
		}
		
		/*
		opReqLineList = [select Id, Name, Operations_Request__c, Customer_Location__c, Customer_Spec__c, 
				DC_Location__c, Notes__c, Opportunity_Product_Id__c, Quantity__c, Actual_Product_Name__c, 
				New_SKU__c, Ready_To_Place_Dropship__c, Product__c, Product__r.Name, Indoor_Outdoor__c, 
				Attribute_Color_Finish__c, ELC__c, Approved_Pricing__c, Customer_Tracking__c, PO__c, 
				PO_In_DC_Date__c, Confirmed_Lead_Time__c, Yardage__c, Square_Feet__c, Fulfillment_Type__c,
				Dom_Int__c, Additional_Information__c, MOQ__c, Ops_Notes__c, Freight_Cost_Per_Unit__c, 
				Discount__c, MMU_Approved__c, Question__c, Product_Information__c, Foam_Fill__c,
				Vendor_Request_Date__c, Is_this_a_Custom_Item__c, Custom_Specification_Info__c, 
				Do_you_need_a_CAD__c, Vendor_Tracking__c, Arrival_Date__c, Type__c 
				from Operations_Request_Line_Item__c where Operations_Request__c = :opReq.Id order by Name asc];
		*/
		
		noLines = opReqLineList.isEmpty() ? true : false;
		
		// Initialize the first set of operations request lines to display
		PageReference pr = rowsPerPageChanged();
	}
	
	// The list of Operations Request Line Items displayed
	public List<Operations_Request_Line_Item__c> getOpReqLines() {
		return displayOpReqLineList;
	}
	
	// Operations Request Line Items pagination methods
	public PageReference firstSet() {
		displayOpReqLineList.clear();
		displaySet = 0;
		pageNumber = displaySet + 1;
		for (Integer i=displaySet * rowsToDisplay; i<opReqLineList.size() && i<((displaySet * rowsToDisplay) + rowsToDisplay); i++) {
			displayOpReqLineList.add(opReqLineList[i]);
		}
        return null;
    }
	
	public PageReference nextSet() {
        if ((displaySet + 1) * rowsToDisplay < opReqLineList.size()) {
            displayOpReqLineList.clear();
            displaySet++;
            pageNumber = displaySet + 1;
            for (Integer i=displaySet * rowsToDisplay; i<opReqLineList.size() && i<((displaySet * rowsToDisplay) + rowsToDisplay); i++) {
                displayOpReqLineList.add(opReqLineList[i]);
            }
        }
        return null;
    }
    
    public PageReference previousSet() {
        if (displaySet - 1 >= 0) {
            displayOpReqLineList.clear();
            displaySet--;
            pageNumber = displaySet + 1;
            for (Integer i=displaySet * rowsToDisplay; i<opReqLineList.size() && i<((displaySet * rowsToDisplay) + rowsToDisplay); i++) {
                displayOpReqLineList.add(opReqLineList[i]);
            }
        }
        return null;
    }
	
	public PageReference lastSet() {
		displayOpReqLineList.clear();
		displaySet = totalPages > 1 ? totalPages - 1 : 0;
		pageNumber = displaySet + 1;
		for (Integer i=displaySet * rowsToDisplay; i<opReqLineList.size() && i<((displaySet * rowsToDisplay) + rowsToDisplay); i++) {
			displayOpReqLineList.add(opReqLineList[i]);
        }
        return null;
    }
    
    public String getRowsPerPage() {
        return String.valueOf(rowsToDisplay);
    }
    
    public void setRowsPerPage(String rpp) {
        rowsToDisplay = Integer.valueOf(rpp);
        if (rowsToDisplay > opReqLineList.size()) {
            rowsToDisplay = opReqLineList.size();
        }
        if (rowsToDisplay < minDisplayRows) {
            rowsToDisplay = minDisplayRows;
        }
    }
    
    public PageReference rowsPerPageChanged() {
        displayOpReqLineList.clear();
        displaySet = 0;
        for (Integer i=displaySet * rowsToDisplay; i<opReqLineList.size() && i<((displaySet * rowsToDisplay) + rowsToDisplay); i++) {
            displayOpReqLineList.add(opReqLineList[i]);
        }
        pageNumber = displaySet + 1;
        totalPages = opReqLineList.size() / rowsToDisplay;
        if (math.mod(opReqLineList.size(), rowsToDisplay) > 0) {
            totalPages++;
        }
        return null;
    }
	
	// Save whatever changes have been made and return the user to the operations request detail page
	public PageReference save() {
		PageReference pr = null;
		
		try {
			update opReqLineList;
			pr = new PageReference('/' + opReq.Id);
			pr.setRedirect(true);
		} catch(Exception e) {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Exception saving Operations Request Line Items: ' + e.getMessage()));
		}
		
		return pr;
	}
	
	// Save whatever changes have been made and allow the user to continue editing
	public PageReference saveAndMore() {
		PageReference pr = null;
		
		try {
			update opReqLineList;
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, 'Save success.'));
		} catch(Exception e) {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Exception saving Operations Request Line Items: ' + e.getMessage()));
		}
		
		return pr;
	}
}