objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Actual_Product_Name__c</fullName>
        <formula>PricebookEntry.Product2.Actual_Product_Name__c</formula>
        <label>Actual Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Location__c</fullName>
        <label>Customer Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Spec__c</fullName>
        <label>Customer Spec #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direct_Current_Price__c</fullName>
        <formula>PricebookEntry.Product2.Direct_Current_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Direct Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <description>to be used in new visual force opportunity line item</description>
        <label>Discount Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Method__c</fullName>
        <inlineHelpText>Choose a method for each line item.</inlineHelpText>
        <label>Fulfillment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COM/COL</fullName>
                    <color>#990000</color>
                    <label>COM/COL</label>
                </value>
                <value>
                    <fullName>Contract Inventory</fullName>
                    <color>#CC0000</color>
                    <label>Contract Inventory</label>
                </value>
                <value>
                    <fullName>Contract SPO</fullName>
                    <color>#FF0000</color>
                    <label>Contract SPO</label>
                </value>
                <value>
                    <fullName>Custom</fullName>
                    <color>#993300</color>
                    <label>Custom</label>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                    <color>#FF6666</color>
                    <label>Drop Ship</label>
                </value>
                <value>
                    <fullName>Retail Inventory</fullName>
                    <color>#333333</color>
                    <default>true</default>
                    <label>Retail Inventory</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent_Discounted__c</fullName>
        <description>The percentage discount for a line item.</description>
        <formula>( ListPrice -  UnitPrice )/ ListPrice</formula>
        <label>Percent Discounted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Margin__c</fullName>
        <formula>(UnitPrice - PricebookEntry.Product2.ELC__c )/UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>IF(ISBLANK(PricebookEntry.Product2.Actual_Product_Name__c), HYPERLINK(&quot;/&quot; &amp; PricebookEntry.Product2Id, PricebookEntry.Product2.Name, &quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; PricebookEntry.Product2Id, PricebookEntry.Product2.Actual_Product_Name__c, &quot;_self&quot;))</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Actual_Product_Name__c</fullName>
        <description>to house the text product name for use in quotes</description>
        <label>Actual Product Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direct_Current_Price__c</fullName>
        <description>ipim field map: Direct Current Price 032110LALO</description>
        <label>Direct Current Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Customer_Location__c</fullName>
        <label>Customer Location</label>
        <length>51</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Spec__c</fullName>
        <label>Customer Spec #</label>
        <length>51</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <formula>( Unit_Price__c - UnitPrice) / Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Method__c</fullName>
        <label>Fulfillment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COM/COL</fullName>
                </value>
                <value>
                    <fullName>Contract Inventory</fullName>
                </value>
                <value>
                    <fullName>Contract SPO</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Drop Ship</fullName>
                </value>
                <value>
                    <fullName>Retail Inventory</fullName>
                    <default>true</default>
                    <label>Retail Inventory</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MMU__c</fullName>
        <formula>(UnitPrice- ELC__c )/ UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MMU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product2.Actual_Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LineItemRelatedListCtlExt.cls
public class LineItemRelatedListCtlExt {
	
	/*
     *  Line Item Related List controller extension - methods for displaying a custom OpportunityLineItem and
     *	QuoteLineItem related list on the parent Opportunity and Quote detail page.
     *
     */
    
	ApexPages.StandardController stdController;
	
	public Boolean fatalError {get; set;}
	public Id objId {get; set;}
	public Id deleteId {get; set;}
	
	private Boolean isOpportunity;
	private List<LineItemWrapper> lineItemList;
	
	// Constructor
	public LineItemRelatedListCtlExt(ApexPages.StandardController stdController) {
		String objName;
		
		fatalError = false;
		lineItemList = new List<LineItemWrapper>();
		objId = stdController.getRecord().Id;
		
		if (objId != null) {
			
	        // Determine if we are working with OpportunityLineItems or QuoteLineItems
	        objName = objId.getSObjectType().getDescribe().getName();
	        if (objName == 'Opportunity' || objName == 'Quote') {
	        	isOpportunity = (objName == 'Opportunity') ? true : false;
	        	
	        } else {
	        	fatalError = true;
				ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Parent record must be either an Opportunity or a Quote'));
	        }
	        
		} else {
			fatalError = true;
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Bad page parameters - missing parent record Id.'));
		}
	}
	
	public class LineItemWrapper {
		public OpportunityLineItem oli {get; set;}
		public QuoteLineItem qli {get; set;}
		
		public LineItemWrapper(OpportunityLineItem oli, QuoteLineItem qli) {
			this.oli = oli;
			this.qli = qli;
		}
	}
	
	// Return the list of line items
	public List<LineItemWrapper> getLineItems() {
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
		List<QuoteLineItem> qliList = new List<QuoteLineItem>();
		
		lineItemList.clear();
		
		if (isOpportunity) {
			
			oliList = [select Id, Name, OpportunityId, Sort_Order__c, Quantity, UnitPrice, 
					Actual_Product_Name__c, Delivery_Date__c, Fulfillment_Method__c, Notes__c, 
					Direct_Current_Price__c, Percent_Discounted__c, Product_Margin__c, Product2Id, Product2.Name 
					from OpportunityLineItem where OpportunityId = :objId order by Sort_Order__c asc nulls last];
			
			for (OpportunityLineItem oli :oliList) {
				lineItemList.add(new LineItemWrapper(oli, null));
			}
			
		} else {
			
			qliList = [select Id, LineNumber, QuoteId, Sort_Order__c, Quantity, UnitPrice, TotalPrice, 
					Discount_Percent__c, MMU__c, Product_Name__c, Delivery_Date__c, Fulfillment_Method__c, Notes__c, 
					Product2Id, Product2.Name,Customer_Location__c,Customer_Spec__c  
					from QuoteLineItem where QuoteId = :objId order by Sort_Order__c asc nulls last];
			
			for (QuoteLineItem qli :qliList) {
				lineItemList.add(new LineItemWrapper(null, qli));
			}
		}
		
		//system.debug('*****LineItemRelatedListCtlExt getLineItems lineItemList.size = ' + lineItemList.size());
		return lineItemList;
	}
	
	// Delete the line item indicated in deleteId
	public PageReference deleteLine() {
		
		//system.debug('*****LineItemRelatedListCtlExt deleteLine deleteId = ' + deleteId);
		
		try {
			for (LineItemWrapper li :lineItemList) {
				if (isOpportunity) {
					if (li.oli.Id == deleteId) {
						//system.debug('*****LineItemRelatedListCtlExt deleteLine delete oli = ' + li.oli);
						delete li.oli;
						break;
					}
				} else {
					if (li.qli.Id == deleteId) {
						//system.debug('*****LineItemRelatedListCtlExt deleteLine delete qli = ' + li.qli);
						delete li.qli;
						break;
					}
				}
			}
		} catch(Exception e) {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Delete exception: ' + e.getMessage()));
		}
		
		return null;
	}
}