objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Grey_Card_Opt_in__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member Card Opt In?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_Enrollment_Date__c</fullName>
        <label>Membership Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_Expiration_Date__c</fullName>
        <label>Membership Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_ID__c</fullName>
        <label>Membership ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Welcome_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership Welcome Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testOrder_RHMembershipCtlExt.cls
/*
 *	Methods to test Order_RHMembershipCtlExt.cls
 *
 */

@isTest(SeeAllData=true)
private class testOrder_RHMembershipCtlExt {
	
	static testMethod void membershipTest1() {
		
		String orderNumber = 'mtest01';
		RH_Order__c order = PrepareData.createOrder(orderNumber);
		insert order;
		
		// Test the Order Line Delay Order Feed controller
		ApexPages.StandardController std = new ApexPages.StandardController(order);
		Order_RHMembershipCtlExt ctl = new Order_RHMembershipCtlExt(std);
		
		ctl.requestNewMembershipCard();
		system.assertEquals(false, ctl.newCardRequested);
		
		order.Membership_ID__c = 'RH-123456';
		order.Grey_Card_Opt_in__c = true;
		order.Membership_Expiration_Date__c = system.today();
		order.Membership_Expiration_Date__c = system.today().addDays(30);
		update order;
		
		ApexPages.StandardController std1 = new ApexPages.StandardController(order);
		Order_RHMembershipCtlExt ctl1 = new Order_RHMembershipCtlExt(std1);
		
		ctl1.requestNewMembershipCard();
		system.assertEquals(true, ctl1.newCardRequested);
		
		ctl1.sendMembershipWelcomeEmail();
	}
	
	static testMethod void membershipTest2() {
		String welcomeEmailOrderNumber = 'weoT1O1';
		String rhMembershipSKU = '91020001RH';
		
		RH_Order__c weOrder = PrepareData.createOrder(welcomeEmailOrderNumber);
		insert weOrder;
		
		Ship_To__c shipTo = PrepareData.createShipTo(weOrder.Id, '1');
		insert shipTo;
		
		weOrder = [select Id, Name, Membership_ID__c, Membership_Enrollment_Date__c, Membership_Expiration_Date__c, Membership_Welcome_Email_Sent__c from RH_Order__c where Id = :weOrder.Id];
		weOrder.Membership_ID__c = 'RH-1234';
		weOrder.Membership_Enrollment_Date__c = system.today();
		update weOrder;
		
		weOrder = [select Id, Name, Membership_ID__c, Membership_Enrollment_Date__c, Membership_Expiration_Date__c, Membership_Welcome_Email_Sent__c from RH_Order__c where Id = :weOrder.Id];
		system.assertEquals(system.today().addYears(1), weOrder.Membership_Expiration_Date__c);
		system.assertEquals(false, weOrder.Membership_Welcome_Email_Sent__c);
		
		// Create Membship SKU Order Line and verify membership email was created and sent (simulated)
		Id rhMembershipSKUId = [select Id, Name from Product2 where Name = :rhMembershipSKU].Id;
		shipTo = [select Id, Name, Order__c from Ship_To__c where Order__c = :weOrder.Id];
		Order_Line_Items__c oliMembership = PrepareData.createOrderLine(weOrder.Id, shipTo.Id, '001', rhMembershipSKUId);
		
		Test.startTest();
		insert oliMembership;
		Test.stopTest();
		
		weOrder = [select Id, Name, Membership_ID__c, Membership_Enrollment_Date__c, Membership_Expiration_Date__c, Membership_Welcome_Email_Sent__c from RH_Order__c where Name = :welcomeEmailOrderNumber];
		system.assertEquals(true, weOrder.Membership_Welcome_Email_Sent__c);
		
		// Now test manual send of email
		ApexPages.StandardController std = new ApexPages.StandardController(weOrder);
		Order_RHMembershipCtlExt ctl = new Order_RHMembershipCtlExt(std);
		ctl.sendMembershipWelcomeEmail();
		system.assertEquals(false, ctl.orderDataError);
		
		weOrder.Membership_ID__c = '';
		update weOrder;
		ApexPages.StandardController std1 = new ApexPages.StandardController(weOrder);
		Order_RHMembershipCtlExt ctl1 = new Order_RHMembershipCtlExt(std1);
		ctl1.sendMembershipWelcomeEmail();
		system.assertEquals(true, ctl1.orderDataError);
	}
}