objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ship to lookup, and how you will create a relationship between the ship to and the order line.</description>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderLine_PersonalizationIntCtrlExt_Test.cls
/*Test class for controller*/

@isTest(SeeAllData=true)

public with sharing class OrderLine_PersonalizationIntCtrlExt_Test {
	
	static testMethod void OrderLine_PersonalizationIntCtrlExt_Test() {
  	// Create a new instance of RH Order
 	RH_Order__c rho = PrepareData.createOrder('olpT01');
 	insert rho;
 	Ship_To__c st = PrepareData.createShipTo(rho.id, '1');
 	insert st;
 	
 	List<Product2> prod = new List<Product2>();
 	prod.add([Select Id, Name from Product2 where Name like '%SAND' limit 1]);
 	
 	System.debug('Product Id: ' + prod);
 	
 	Order_Line_Items__c olp = PrepareData.createOrderLine(rho.Id, st.Id, '1', prod[0].Id);
 	insert olp;	
 	
 	List<CWOrderLinePersonalization> testOrderLinePersonalizationList = new List<CWOrderLinePersonalization>();
  	
  	// Test.setMock(HttpCalloutMock.class, new MockOLPHttpResponseGenerator());
  	
  	// Create a new instance of standard controller
  	test.startTest();
  	ApexPages.StandardController sc = new ApexPages.standardController(olp);
  	OrderLine_PersonalizationIntCtrlExt controller = new OrderLine_PersonalizationIntCtrlExt(sc);
  	testOrderLinePersonalizationList = controller.getOrderLinePersonalizationList();
  	test.stopTest();
    }  
}