objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Address_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Ship To</label>
        <referenceTo>Contact_Address__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact_Address__c</fullName>
        <description>Field created to display Ship To address fields and to be used for field history tracking. Field will be updated with code.</description>
        <label>Ship To Contact Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_1__c</fullName>
        <label>Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Company__c</fullName>
        <label>Ship to Company</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShipToServiceTest.cls
@isTest
public with sharing class ShipToServiceTest {

	public static testMethod void testHandleShipToUpdateChanges() {
		
		PrepareData.populateCustomSettings();
		
		// given a contact
		
		List<Contact> testContacts = new List<Contact>();
		testContacts.add(new Contact(
			FirstName = 'paul', 
			LastName = 'hemmings')
		);
		database.insert(testContacts);
				
		// given an order (pointing to contact)
		
		List<Rh_Order__c> testOrders = new List<Rh_Order__c>();
		testOrders.add(new Rh_Order__c(
			Name='test order', 
			Contact_Sold_To__c = [SELECT ID FROM CONTACT].Id)
		);
		database.insert(testOrders);
		
		// given a ship to

		List<Ship_To__c> testShipTos = new List<Ship_To__c>();
		testShipTos.add(new Ship_To__c(
			Name='test ship-to', 
			Order__c = [SELECT ID FROM RH_ORDER__C].Id, 
			Contact_Ship_To__c = [SELECT ID FROM CONTACT].Id,
	        ship_to_first_name__c = 'paul',
	        ship_to_last_name__c = 'hemmings',
	        Ship_to_Company__c = 'test-company',
	        Ship_to_Address_1__c = '112 somerset dr',
	        Ship_to_City__c  = 'novato',
	        Ship_to_State__c = 'ca',
	        Ship_to_Zip__c = '94949',
	        Ship_to_Country__c = 'US'		
		));
		database.insert(testShipTos);
		
		// when (ship-to processed)
		
		Ship_to__c[] insertedShipTos = database.query(ContactAddressBatch.buildShipToQuery(false, null));
		database.update(ContactAddressService.buildAddressForShipTos(insertedShipTos));
		
		// when (ship-to with associations retrieved)
		
		List<Ship_To__c> processedShipTos = [
			SELECT ID, Contact_Ship_To__c, Address_Ship_To__c FROM Ship_To__c
		];
		
		// then ship-to is linked to a contact-address
		
		for (Ship_To__c shipTo : processedShipTos) {
			system.assertNotEquals(null, shipTo.Address_Ship_To__c);
		}
		
		// when (the contact is changed for that order)
		
		for (Ship_To__c shipTo : processedShipTos) {
			shipTo.Contact_Ship_To__c = null;
		}
		database.update(processedShipTos);
		
		// then (the order should have no link to the contact-address) 
		
        for (Ship_To__c shipTo : [SELECT ID, Contact_Ship_To__c, Address_Ship_To__c, Ship_To_Contact_Address__c FROM Ship_To__c]) {
            system.assertEquals(null, shipTo.Address_Ship_To__c);
        }  	
        
        // when (the ship to address is changed)
        
		testShipTos.get(0).Ship_to_Country__c = 'UK';
		database.update(testShipTos);      	
		
		// then historical address updated
		
        for (Ship_To__c shipTo : [SELECT ID, Contact_Ship_To__c, Address_Ship_To__c, Ship_To_Contact_Address__c FROM Ship_To__c]) {
            system.assertNotEquals(null, shipTo.Ship_To_Contact_Address__c);
        }		
	}
		
}