objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person Account record.</description>
        <label>Account Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders Sold To this Account</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Sold To</label>
        <referenceTo>Contact_Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Order should be linked. Editable by those with the Data Stewardship Permission Set only. Other users can create Stewardship Requests if Orders are linked to the incorrect Business or Person contact record.</description>
        <label>Contact Sold To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders Sold To this Contact</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Address_1__c</fullName>
        <description>CW Sold to Address Line 1</description>
        <label>Sold To Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address_2__c</fullName>
        <description>CW Sold to Address Line 2</description>
        <label>Sold To Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_City__c</fullName>
        <description>CW Sold to City</description>
        <label>Sold To City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Country__c</fullName>
        <description>CW Sold to Country</description>
        <label>Sold To Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Customer_Number__c</fullName>
        <description>CW Sold to Cust Number</description>
        <label>Sold To Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Day_Phone__c</fullName>
        <description>CW Sold to Daytime Phone</description>
        <label>Sold To Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_First_Name__c</fullName>
        <description>CW Sold to Fname</description>
        <label>Sold To First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Last_Name__c</fullName>
        <description>CW Sold to Lname</description>
        <label>Sold To Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_State__c</fullName>
        <description>CW Sold to State</description>
        <label>Sold To State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Zip__c</fullName>
        <description>CW Sold to Zip</description>
        <label>Sold To Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Account_Sold_To__c</fullName>
        <formula>Order__r.Account_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Ship To</label>
        <referenceTo>Contact_Address__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_1__c</fullName>
        <label>Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_2__c</fullName>
        <label>Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_to_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_to_First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Night_Phone__c</fullName>
        <label>Night Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactAddressBatchTest.cls
@isTest
public with sharing class ContactAddressBatchTest {

	public static testMethod void ensureBothBatchesRun() {
		
    	PrepareData.populateCustomSettings();
    	
    	// GIVEN - an ssv user
    	
		User su = TestDataFactory.createUser();
        su.Single_View_of_Customer_Process_User__c = true;   		
		
		// GIVEN a contact
		/*
		Contact testContact = new Contact(
			FIRSTNAME = 'paul',
			LASTNAME = 'hemmings'
		);
		System.runAs(su) {
			database.insert(testContact);
		}
		*/
		
		// GIVEN an order with that contact
		
		List<Rh_Order__c> testOrders = new List<Rh_Order__c>(); 
		testOrders.add(new Rh_Order__c(
			CONTACT_SOLD_TO__C = null, // testContact.Id,
			SOLD_TO_ADDRESS_1__C = 'address 1',
			SOLD_TO_ADDRESS_2__C = 'address 2',
			SOLD_TO_CITY__C = 'city',
			SOLD_TO_STATE__C = 'CA',
			SOLD_TO_ZIP__C = '94949',	
			SOLD_TO_COUNTRY__C = 'US',	
			SOLD_TO_CUSTOMER_NUMBER__C = '1111111',
			SOLD_TO_DAY_PHONE__C = '9191231234',
			SOLD_TO_EMAIL__C = 'paul@paul.com',
			SOLD_TO_FIRST_NAME__C = 'paul',
			SOLD_TO_LAST_NAME__C = 'hemmings'		
		));
		System.runAs(su) {
			database.insert(testOrders);
		}
		
		// GIVEN a test ship-to (shipment)
		
		List<Ship_To__c> testShipments = new List<Ship_To__c>();
		testShipments.add(new Ship_To__c(
			Order__c = testOrders.get(0).Id,
			CONTACT_SHIP_TO__c = null, // testContact.Id,    
			NAME  = '',
			Ship_to_FIRST_NAME__C = 'paul',  
			Ship_to_LAST_NAME__C  = 'hemmings',
			Ship_to_ADDRESS_1__C = '4 cielo lane',
			Ship_to_ADDRESS_2__C = '',			
			Ship_to_CITY__C = 'novato',
			Ship_to_COUNTRY__C = 'US',
			Ship_to_STATE__C = 'CA',
			Ship_to_ZIP__C = '94949',
			Ship_to_DAY_PHONE__C = '1231231234',
			Ship_to_NIGHT_PHONE__C = '1231231234',
			Ship_to_EMAIL__C = 'paul@paul.com'			
		));
		System.runAs(su) {
			database.insert(testShipments);
		}					
		
		// when		
		Test.startTest();
		ContactAddressBatch.executeFullBatch(false, 200);
		Test.stopTest();
		
		// then
		system.assertNotEquals(null, [SELECT Account_Sold_To__c FROM Rh_Order__c WHERE ID = :testOrders.get(0).Id].Account_Sold_To__c);
		system.assertNotEquals(null, [SELECT Contact_Sold_To__c FROM Rh_Order__c WHERE ID = :testOrders.get(0).Id].Contact_Sold_To__c);
		system.assertNotEquals(null, [SELECT Address_Sold_To__c FROM Rh_Order__c WHERE ID = :testOrders.get(0).Id].Address_Sold_To__c);
		system.assertNotEquals(null, [SELECT Address_Ship_To__c FROM Ship_To__c WHERE ID = :testShipments.get(0).Id].Address_Ship_To__c);
			
	}    
}