objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{000}</displayFormat>
        <label>OrderName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RH_Order__c.object
<CustomObject>
    <fields>
        <fullName>New_Sold_to_Day_Phone__c</fullName>
        <label>New Sold To Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>New_Sold_to_Night_Phone__c</fullName>
        <label>New Sold To Night Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Address__c</fullName>
        <label>Ship To 1 Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Day_Phone__c</fullName>
        <label>Ship To 1 Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Email__c</fullName>
        <label>Ship To 1 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Name__c</fullName>
        <label>Ship To 1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipTo1_Night_Phone__c</fullName>
        <label>Ship To 1 Night Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_To_1_Order_Description__c</fullName>
        <label>Ship To 1 Order Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <description>Created for use with the MDM project by Traction on Demand. No known use for this field.</description>
        <formula>ShipTo1_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ship To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Address__c</fullName>
        <formula>IF(
AND
(
ISBLANK(Sold_To_Address_1__c),
ISBLANK(Sold_to_Address_2__c),
ISBLANK(Sold_to_Company__c),
ISBLANK(Sold_to_City__c),
ISBLANK(Sold_to_State__c),
ISBLANK(Sold_to_Zip__c),
ISBLANK(Sold_to_Country__c)
), 
null, 
Sold_To_Address_1__c  + BR() +  Sold_to_Address_2__c + BR() + Sold_to_City__c + &quot;, &quot; +  Sold_to_State__c + &quot;, &quot; + Sold_to_Zip__c + BR() + Sold_to_Country__c
)</formula>
        <label>Sold To Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Email__c</fullName>
        <description>CW Sold to Email</description>
        <label>Sold To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sold_to_Name__c</fullName>
        <formula>IF(
AND(ISBLANK(Sold_to_Last_Name__c),  ISBLANK(Sold_to_First_Name__c)), null, Sold_to_Last_Name__c + &quot;, &quot; + Sold_to_First_Name__c)</formula>
        <label>Sold To Name</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Ship_to_Last_Name__c + &quot;, &quot; +  Ship_to_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Description__c</fullName>
        <label>Order Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>RH_Order__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_1__c</fullName>
        <label>Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_2__c</fullName>
        <label>Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address__c</fullName>
        <formula>Ship_to_Address_1__c + BR() + Ship_to_Address_2__c + BR() + Ship_to_City__c + &quot;, &quot; +  Ship_to_State__c + &quot;, &quot; +  Ship_to_Zip__c + BR() +  Ship_to_Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Company__c</fullName>
        <label>Ship to Company</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Day_Phone__c</fullName>
        <label>Day Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_to_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_to_First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Night_Phone__c</fullName>
        <label>Night Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateOrderFromShipTo.cls
/**
    Description: UpdateOrderFromShipTo class defaults the fields on the first Ship To record on a RH Order Header Record
    Author:vk@ff
    Trigger: ShipTo_Trigger
    Test Class:
    Change Log: 
        * V0.1- Initial
        * V1.0- 
**/

public without sharing class UpdateOrderFromShipTo {
	
	public static List<Id> generateUpdatedList(List<Ship_To__c> records, Map<Id, Ship_To__c> oldMap) {		
		List<Id> shipToIds = new List<Id>();
		for (Ship_To__c record : records) {			
			if (record.Name.equals('1')) {			
				if (oldMap == null) { 
					shipToIds.add(record.Order__c);
				} else {
					Ship_To__c existing = oldMap.get(record.id);
					if (record.Ship_to_Address__c != existing.Ship_to_Address__c 
						|| record.Ship_to_Email__c != existing.Ship_to_Email__c 
						|| record.Name__c != existing.Name__c 
						|| record.Ship_to_Day_Phone__c != existing.Ship_to_Day_Phone__c 
						|| record.Ship_to_Night_Phone__c != existing.Ship_to_Night_Phone__c) {
						shipToIds.add(record.Order__c);
					}	
				}
			}			
		}
		return shipToIds;
	}
	
    public static void updateOrderHeader(List<Id> lstOfRHOIds)
    {        
    	if (lstOfRHOIds == null || lstOfRHOIds.size() < 1) {
    		return;
    	}
    	
        List<RH_Order__c> lstOfOrders = [
        	SELECT Id, Ship_To_1_Order_Description__c, Sold_to_Name__c, Sold_to_Address__c,New_Sold_to_Day_Phone__c, New_Sold_to_Night_Phone__c, Sold_to_Email__c, (
        		SELECT Id,Name, Order_Description__c, Order__c, Name__c, Ship_to_Address__c, Ship_to_Day_Phone__c, Ship_to_Night_Phone__c, Ship_to_Email__c,Ship_to_Company__c,Ship_to_Address_1__c, Ship_to_Address_2__c , Ship_to_City__c , Ship_to_State__c , Ship_to_Zip__c ,Ship_to_Country__c,Ship_to_First_Name__c,Ship_to_Last_Name__c  
        		FROM Ship_Tos__r  
        		WHERE Name='1' LIMIT 1
    		) 
			FROM RH_Order__c 
			WHERE Id IN: lstOfRHOIds
		];
        
        for(RH_Order__c rho: lstOfOrders)
        {
            for(Ship_To__c st: rho.Ship_Tos__r)
            {            
                if(st.Order_Description__c != null){
                   rho.Ship_To_1_Order_Description__c = st.Order_Description__c;
                }         
                
                // Copy Ship To Name
                
                rho.ShipTo1_Name__c = '';
                if (String.isNotBlank(st.Ship_to_Last_Name__c)) {
                    rho.ShipTo1_Name__c = st.Ship_to_Last_Name__c;
                }
                if (String.isNotBlank(st.Ship_to_First_Name__c)) {
                    if (String.isNotBlank(rho.ShipTo1_Name__c)) {
                        rho.ShipTo1_Name__c += ', ';
                    }
                    rho.ShipTo1_Name__c += st.Ship_to_First_Name__c;
                }
                
                // Copy Ship To Address
                
                rho.ShipTo1_Address__c='';

                rho.ShipTo1_Address__c+='\r\n';
                if (String.isNotBlank(st.Ship_to_Address_1__c))
                {
                    rho.ShipTo1_Address__c += st.Ship_to_Address_1__c + '\r\n';
                }
                
                if (String.isNotBlank(st.Ship_to_Address_2__c))
                {
                    rho.ShipTo1_Address__c += st.Ship_to_Address_2__c+ '\r\n';
                }
                
                if(String.isNotBlank(st.Ship_to_Company__c))
                {
                    rho.ShipTo1_Address__c += st.Ship_to_Company__c;
                }
                
                else
                {
                    rho.ShipTo1_Address__c += '';
                }
                
                
                rho.ShipTo1_Address__c += '\r\n';
                if (String.isNotBlank(st.Ship_to_City__c))
                {
                    rho.ShipTo1_Address__c += st.Ship_to_City__c;
                }
                if (String.isNotBlank(st.Ship_to_State__c))
                {
                    rho.ShipTo1_Address__c += ' ' + st.Ship_to_State__c;
                }
                if (String.isNotBlank(st.Ship_to_Zip__c))
                {
                    rho.ShipTo1_Address__c += ', ' + st.Ship_to_Zip__c;
                }
                if (String.isNotBlank(st.Ship_to_Country__c))
                {
                    rho.ShipTo1_Address__c += '\r\n' + st.Ship_to_Country__c;
                }
                
                //Copy phone and email
                rho.ShipTo1_Day_Phone__c = st.Ship_to_Day_Phone__c;
                rho.ShipTo1_Night_Phone__c = st.Ship_to_Night_Phone__c;
                rho.ShipTo1_Email__c = st.Ship_to_Email__c;
            }
        }
        
        if (!lstOfOrders.isEmpty()) {
        	update lstOfOrders;
        }

   }
}