objects/Sche__c.object
<CustomObject>
    <fields>
        <fullName>Sam__c</fullName>
        <label>Sam</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sche</label>
    <nameField>
        <label>Sche Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sche</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SchedulerClassTest.cls
global class SchedulerClassTest Implements Schedulable {
     
     static Integer i = 0;
     
     global void execute(SchedulableContext sc)
        {
            setToMiko();
        }

        public void setToMiko()
        {
            List<Sche__c> listSche = new List<Sche__c>();
            listSche = [SELECT ID,Sam__c FROM Sche__c];

            for(Sche__c she : listSche)
            {
                i++;
                she.Sam__c = 'Sample Test' + i;
            }

            update listSche;
            System.debug('Scheduler function: ' + [SELECT ID,Sam__c FROM Sche__c]);
        }

}