objects/Setup__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Security_Token__c</fullName>
        <label>Security Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/setup_vcs__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repo_Username__c</fullName>
        <label>Repo_Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repository_Name__c</fullName>
        <label>Repository Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Setup__c</fullName>
        <label>SF_Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>setup_vcs</relationshipLabel>
        <relationshipName>setup_vcs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>remoteurl__c</fullName>
        <label>remoteurl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>setup_vcs</label>
    <nameField>
        <displayFormat>VCS-{000000}</displayFormat>
        <label>setup_vcs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>setup_vcs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SetupController.cls
public with sharing class SetupController {
    
    @AuraEnabled
    public static Object getSalesForceInformation(){
        /*String[] fieldsToCheck = new String[] {
            'Id', 'Name', 'Username__c', 'Security_Token__c', 'Password__c', 'setup_vcs__r'
        };
                    
                    Map<String,Schema.SObjectField> fieldDescribeTokens = 
                    Schema.SObjectType.setup__c.fields.getMap();
        
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
                return null;
            }
        }*/
        
        System.debug('User Setup  -> ' + [select id, Name, Username__c, Security_Token__c, Password__c, (select id, Repository_Name__c, password__c, remoteurl__c, Repo_Username__c from setup_vcs__r) from setup__c]);
        System.debug('JSON Try ' + JSON.serialize([select id, Name, Username__c, Security_Token__c, Password__c, (select id, Repository_Name__c, password__c, remoteurl__c, Repo_Username__c from setup_vcs__r) from setup__c]));
        
        return JSON.serialize([select id, Name, Username__c,LastModifiedBy.Id, Security_Token__c, Password__c, (select id, Repository_Name__c, password__c, remoteurl__c, Repo_Username__c from setup_vcs__r) from setup__c]);
    }
    
    @AuraEnabled
    public static String getUserInfo(){
        return UserInfo.getUserName();
    }
    
}