objects/Ship_To__c.object
<CustomObject>
    <fields>
        <fullName>Address_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Ship To</label>
        <referenceTo>Contact_Address__c</referenceTo>
        <relationshipLabel>Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for use with the MDM project by Traction on Demand. This field gets updated automatically after the SSV record has been created and processed, and the system has determined the correct Business Contact or Person Account record to which this Ship To should be linked.</description>
        <label>Contact Ship To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Ship Tos</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Sold_To__c</fullName>
        <formula>Order__r.Contact_Sold_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Sold To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Ship_to_Last_Name__c + &quot;, &quot; +  Ship_to_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact_Address__c</fullName>
        <description>Field created to display Ship To address fields and to be used for field history tracking. Field will be updated with code.</description>
        <label>Ship To Contact Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_1__c</fullName>
        <label>Address 1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address_2__c</fullName>
        <label>Address 2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Company__c</fullName>
        <label>Ship to Company</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShipToService.cls
public with sharing class ShipToService {
    
    private static @testVisible Set<Schema.SObjectField> addressFields = new Set<Schema.SObjectField> {
        Ship_To__c.Name__c,
        Ship_To__c.Ship_to_Company__c,
        Ship_To__c.Ship_to_Address_1__c,
        Ship_To__c.Ship_to_Address_2__c,
        Ship_To__c.Ship_to_City__c,
        Ship_To__c.Ship_to_State__c,
        Ship_To__c.Ship_to_Zip__c,
        Ship_To__c.Ship_to_Country__c
    };
    
    /*
     * IF an update to an existing order changes the existing Contact to a new Contact
     * Remove all references to the contact-address objects
     */
     
    public static void handleContactChange(List<Ship_To__c> shipTos, Map<Id, Ship_To__c> oldMap) {
    	system.debug('ShipToService -> handleContactChange -> ' + shipTos);
        if (oldMap != null) {
            for (Ship_To__c shipTo : shipTos) {
                if (oldMap.get(shipTo.id).Contact_Ship_To__c != null && shipTo.Contact_Ship_To__c != oldMap.get(shipTo.id).Contact_Ship_To__c) {                	
                    system.debug('ShipToService -> handleContactChange -> Contact_Ship_To__c changed -> ' + shipTo);                    
                    shipTo.Address_Ship_To__c = null;
                } else if (oldMap.get(shipTo.id).Contact_Sold_To__c != null && shipTo.Contact_Sold_To__c != oldMap.get(shipTo.id).Contact_Sold_To__c) {
                	system.debug('ShipToService -> handleContactChange -> Contact_Sold_To__c changed -> ' + shipTo);
                	shipTo.Address_Ship_To__c = null;
                }
            }
        }
    }
    
    public static void handleAddressChange(List<Ship_To__c> shipTos, Map<Id, Ship_To__c> oldMap) {
        for (Ship_To__c shipTo : shipTos) {
            if (oldMap == null || Utility.hasChanges(shipTo, oldMap.get(shipTo.id), addressFields)) {
                shipTo.Ship_To_Contact_Address__c = Utility.aggregateFields(shipTo, addressFields, ', ');  
            }                                                       
        }   
    }
            
}