objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Ready_For_Duplicate_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Ready For Duplicate Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Record_Score__c</fullName>
        <description>This score is a key part of the matching process. 
When multiple candidate records can be consolidated into one record, this score determines which record will be the Master (the name, address, phone etc for the spawned customer is taken from the Master record). 
The score is designed to ensure:
1. Define the order of entry of new Candidate records into the process
- There is a final addition for match type = company to ensure company records are processed prior to any associated contact records
2. Ensure Salesforce records always outscore other external system records</description>
        <formula>/* This section determines the highest value Salesforce record as Salesforce records always end up as the master over external system records */
If(Source_System__c=&quot;Salesforce&quot;,100000000,0) +
If(Contact__r.Tier_Name__c=&quot;Top Tier&quot;,100000,0) +
If(Contact__r.Tier_Name__c =&quot;Tier 2&quot;,50000,0) +
If(Contact__r.Tier_Name__c =&quot;Tier 3&quot;,25000,0) +
(Date(1970,01,01)-BLANKVALUE(DateValue(If(Match_Type__c = &quot;Company&quot;, Account__r.CreatedDate,  
                                                Contact__r.CreatedDate)),Date(1970,01,01)))/10000 +

/* This section calculates the master record score for non Salesforce records */
If( DateValue(Source_System_Last_Modified_Date__c) &gt; Today()-730,10000,0) +
If( Originating_Source_System__c = &quot;ATG&quot;,5000,0) +
(BLANKVALUE(DateValue(Source_System_Last_Modified_Date__c),Date(1970,01,01)) - Date(1970,01,01))/10000 +

/* this next line ensures company records are always processed prior to any associated contacts */
/* Because company records are only ever consolidated to the same match type, the score does not impact &quot;within company match&quot; selections */
If(Match_Type__c = &quot;Company&quot;,200000,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Record Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_Ready_Time__c</fullName>
        <label>Processing Ready Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting to Start</fullName>
                    <default>true</default>
                    <label>Waiting to Start</label>
                </value>
                <value>
                    <fullName>Ready for Match Step</fullName>
                </value>
                <value>
                    <fullName>Ready for Order Linking</fullName>
                </value>
                <value>
                    <fullName>Processing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SSVBatchSelectorBuilder.cls
public with sharing class SSVBatchSelectorBuilder {
	
	private Integer batchLimit = null; 
	private Datetime processingReadyTime; 
	private Boolean includeDuplicates = null;
	private String customFilter = null;
	private String processStatus = SSVSelector.PROCESSING_STATUS_READY;
	private boolean orderByMasterRecordScore = true;
	private List<String> fieldList = SSVSelector.getFieldList();
	
    
    public static String FILTER_LAST_NAME_AM 
    								= ' AND ('
									+ 'Last_Name__c LIKE \'A%\' OR Last_Name__c LIKE \'B%\' OR Last_Name__c LIKE \'C%\' OR Last_Name__c LIKE \'D%\' OR Last_Name__c LIKE \'E%\' OR Last_Name__c LIKE \'F%\' OR '
									+ 'Last_Name__c LIKE \'G%\' OR Last_Name__c LIKE \'H%\' OR Last_Name__c LIKE \'I%\' OR Last_Name__c LIKE \'J%\' OR Last_Name__c LIKE \'K%\' OR Last_Name__c LIKE \'L%\' OR '
									+ 'Last_Name__c LIKE \'M%\' '
									+ ') ';
									  								
	public static String FILTER_LAST_NAME_NZ 
									= ' AND ('
									+ 'Last_Name__c LIKE \'N%\' OR Last_Name__c LIKE \'O%\' OR Last_Name__c LIKE \'P%\' OR Last_Name__c LIKE \'Q%\' OR Last_Name__c LIKE \'R%\' OR Last_Name__c LIKE \'S%\' OR '
									+ 'Last_Name__c LIKE \'T%\' OR Last_Name__c LIKE \'U%\' OR Last_Name__c LIKE \'V%\' OR Last_Name__c LIKE \'W%\' OR Last_Name__c LIKE \'X%\' OR Last_Name__c LIKE \'Y%\' OR '
									+ 'Last_Name__c LIKE \'Z%\' '									
									+ ') ';	
																
																		
    public static String FILTER_LAST_NAME_AG 
    								= ' AND ('
									+ 'Last_Name__c LIKE \'A%\' OR Last_Name__c LIKE \'B%\' OR Last_Name__c LIKE \'C%\' OR Last_Name__c LIKE \'D%\' OR '
									+ 'Last_Name__c LIKE \'E%\' OR Last_Name__c LIKE \'F%\' OR Last_Name__c LIKE \'G%\' '
									+ ') ';
									
    public static String FILTER_LAST_NAME_HO 
    								= ' AND ('
    								+ 'Last_Name__c LIKE \'H%\' OR '
									+ 'Last_Name__c LIKE \'I%\' OR Last_Name__c LIKE \'J%\' OR Last_Name__c LIKE \'K%\' OR Last_Name__c LIKE \'L%\' OR '
									+ 'Last_Name__c LIKE \'M%\' OR Last_Name__c LIKE \'N%\' OR Last_Name__c LIKE \'O%\' '
									+ ') ';
  								
	public static String FILTER_LAST_NAME_PZ 
									= ' AND ('
									+ 'Last_Name__c LIKE \'P%\' OR Last_Name__c LIKE \'Q%\' OR '
									+ 'Last_Name__c LIKE \'R%\' OR Last_Name__c LIKE \'S%\' OR Last_Name__c LIKE \'T%\' OR Last_Name__c LIKE \'U%\' OR '
									+ 'Last_Name__c LIKE \'V%\' OR Last_Name__c LIKE \'W%\' OR Last_Name__c LIKE \'X%\' OR Last_Name__c LIKE \'Y%\' OR '
									+ 'Last_Name__c LIKE \'Z%\' '									
									+ ') ';										
	
	public SSVBatchSelectorBuilder withBatchLimit(Integer blimit) {
		this.batchLimit = blimit;
		return this;
	}
	public SSVBatchSelectorBuilder withProcessingReadyTime(Datetime pTime) {
		this.processingReadyTime = (pTime != null) ? pTime : Datetime.now();
		return this;
	}
	public SSVBatchSelectorBuilder withIncludingDuplicates(boolean include) {
		this.includeDuplicates = include;
		return this;
	}
	public SSVBatchSelectorBuilder withCustomFilter(String filter) {
		this.customFilter = filter;
		return this;
	}
	public SSVBatchSelectorBuilder withProcessStatus(String status) {
		this.processStatus = status;
		return this;
	}
	public SSVBatchSelectorBuilder withOrderByMasterRecordScoreOn(boolean orderOn) {
		this.orderByMasterRecordScore = orderOn;
		return this;
	}
	public SSVBatchSelectorBuilder withFieldList(List<String> fList) {
		this.fieldList = fList;
		return this;
	} 
	
    public String getBaseQuery() {

        String query = String.format('SELECT {0} ' 
                                    + ' FROM Source_System_View__c '
                                    + ' WHERE Processing_Ready_Time__c < {1} '
                                    + ' AND Is_Ready_For_Duplicate_Check__c = true '
                                , new List<String> {
                                    String.join(this.fieldList, ', '),
                                    this.processingReadyTime.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
                                });

        return query;
    }	

	private String orderByMasterRecordScore() {
		return (orderByMasterRecordScore) ? ' ORDER BY Master_Record_Score__c DESC' : '';
	}    
	
	private String filterByProcessStatus() {
		return (this.processStatus != null) ? ' AND Processing_Status__c = \'' + this.processStatus +'\' ' : '';
	}
	
	private String filterByCustomFilter() {
		return (this.customFilter != null) ? this.customFilter : '';
	}
	
	private String filterByDuplicates() {
		if (this.includeDuplicates != null) {
			return (this.includeDuplicates == true) ? ' AND Duplicate_Set_ID__c != NULL ' : ' AND Duplicate_Set_ID__c = NULL ';
		}
		return '';
	}
	
	private String limitBatchSize() {
		return (this.batchLimit != null) ? ' LIMIT ' + this.batchLimit : '';		
	}
	
	public SSVBatchSelectorBuilder() {		
	}
	
	public String buildQuery() {
		String builtQuery =  this.getBaseQuery() 
								+ this.filterByProcessStatus()
								+ this.filterByCustomFilter()
								+ this.filterByDuplicates()
								+ this.orderByMasterRecordScore()
								+ this.limitBatchSize();
								
		system.debug('Query built:: ' + builtQuery);		
		return builtQuery;								
	}
	
}