objects/Source_System_View__c.object
<CustomObject>
    <description>Stores all CW customer records. Staging area for cleansing &amp; matching of data. Also used to inform reps of CW records linked to a customer.
&quot;Table populated via integration from Mule ESB
Cleansed fields populated by Triggers in SFDC&quot;</description>
    <fields>
        <fullName>Duplicate_Set_ID__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Set ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <description>This field specifies the match type to be processed by Salesforce duplicate match</description>
        <label>Match Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_ID__c</fullName>
        <label>Trade ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Source System View</label>
    <nameField>
        <label>Source System ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source System Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SSVMatcherTest.cls
@isTest
public with sharing class SSVMatcherTest {
    
    
	@isTest static void testMatchingCompanyRecords() {
		
		Source_System_View__c companyToMatch = new Source_System_View__c(
			Match_Type__c = 'Company',
			Duplicate_Set_ID__c = '123',
			Trade_ID__c = '123456'
		);
		
		Source_System_View__c companyMatchTrade = new Source_System_View__c(
			Match_Type__c = 'Company',
			Duplicate_Set_ID__c = '456',
			Trade_ID__c = '123456'
		);

		Source_System_View__c companyMatchDuplicateSetWrongTradeID = new Source_System_View__c(
			Match_Type__c = 'Company',
			Duplicate_Set_ID__c = '123',
			Trade_ID__c = '456789'
		);		

		Source_System_View__c companyMatchDuplicateSetRightTradeID = new Source_System_View__c(
			Match_Type__c = 'Company',
			Duplicate_Set_ID__c = '123',
			Trade_ID__c = '123456'
		);	
		
		Source_System_View__c companyNoTradeToMatch = new Source_System_View__c(
			Match_Type__c = 'Company',
			Duplicate_Set_ID__c = '123',
			Trade_ID__c = ''
		);	

		Source_System_View__c companyMatchWrongDuplicateSet = new Source_System_View__c(
			Match_Type__c = 'Company',
			Duplicate_Set_ID__c = '456',
			Trade_ID__c = ''
		);		
			
		SSVMatcher.CompanyMatcher matcher = new SSVMatcher.CompanyMatcher();
		// match on trade
		system.assertEquals(true, matcher.matches(new SSVCleansed(companyToMatch), new SSVCleansed(companyMatchTrade)));
		// do not match on trade
		system.assertEquals(false, matcher.matches(new SSVCleansed(companyToMatch), new SSVCleansed(companyMatchDuplicateSetWrongTradeID)));		
		// match as has no trade
		system.assertEquals(true, matcher.matches(new SSVCleansed(companyToMatch), new SSVCleansed(companyNoTradeToMatch)));
		// no match as neither has trade and wrong duplicates set
		system.assertEquals(false, matcher.matches(new SSVCleansed(companyNoTradeToMatch), new SSVCleansed(companyMatchWrongDuplicateSet)));
	}
	
	
}